### ISSUE TITLE
export the echarts to svg with htmlunit, wrong path.

### ISSUE THREAD

**Issue by endypark** [HtmlUnit/htmlunit#102]
htmlunit-2.36.0.jar

export the echarts to svg， should be <path d="M 68 340 L 132 340 L 132 305 L 68 305 L 68 340 Z" 
， but actual is <path d="M 68 340 L 132 340 L 132 340 L 68 340 L 68 340 Z"  。

the previous is generate by chrome or firefox, it is a histogram. but htmlunit generated a non-histogram svg.

<html>
    <head>
        <meta charset="utf-8">
        <title>ECharts</title>
        <script src="js/echarts.js"></script>
    </head>

    <body>
        <div id="main" style="width: 600px;height:400px;"></div>
        <script type="text/javascript">
            var myChart = echarts.init(document.getElementById('main'), null, {renderer: 'svg'});
            var option = {
                title: {
                    text: 'ECharts 入门示例'
                },
                tooltip: {},
                legend: {
                    data:['销量']
                },
                xAxis: {
                    data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                },
                yAxis: {},
                series: [{
                    name: '销量',
                    type: 'bar',
                    data: [7, 20, 36, 10, 10, 20]
                }]
            };
            myChart.setOption(option);
        </script>

    </body>
</html>

public String renderHtml(String path, String subDomName) {
		try (WebClient webClient = new WebClient();) {
			try {
				URL url = this.getClass().getClassLoader().getResource(path);
				URI uri = url.toURI();
				String links = FileUtil.getContentFromFile(new File(url.getPath()));
				HtmlPage page = webClient.getPage(uri.toString());
				webClient.waitForBackgroundJavaScript(30000);
				return page == null ? null : page.getElementById(subDomName).asXml();
			} catch (FailingHttpStatusCodeException | IOException | URISyntaxException e) {
				return null;
			}
		} catch (Exception e) {
			return null;
		}
	}

**Comment by endypark** [comment]
@rbri, thanks

**Comment by endypark** [comment]
chrome or firefox:
![图片](https://user-images.githubusercontent.com/5320122/69131051-a2e99c80-0aec-11ea-956a-f3502cd10609.png)

**Comment by endypark** [comment]
htmlunit:
![图片](https://user-images.githubusercontent.com/5320122/69131132-cc0a2d00-0aec-11ea-90d2-b1fb75df0a41.png)

**Comment by endypark** [comment]
the Y is always 340, so no histogram showed.

path d="M 68 340 L 132 340 L 132 340 L 68 340 L 68 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none">
      path d="M 148 340 L 212 340 L 212 340 L 148 340 L 148 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none"
      path d="M 228 340 L 292 340 L 292 340 L 228 340 L 228 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none"
      path d="M 308 340 L 372 340 L 372 340 L 308 340 L 308 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none"
      path d="M 388 340 L 452 340 L 452 340 L 388 340 L 388 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none"
      path d="M 468 340 L 532 340 L 532 340 L 468 340 L 468 340 Z" fill="#c23531" fill-opacity="undefined" stroke="none" clip-path="none"

**Comment by rbri** [comment]
Can you please provide echarts.js also - will try to reproduce....

**Comment by rbri** [comment]
Ok, was able to reproduce your case.
The culprit here is the animation - based on window.requestAnimationFrame(). In this case the browser triggers a js method repeatably and in the end, the chart is refreshed. 

There is only limited support in HtmlUnit for that - means you have to control this from the outside.

Sample:

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_68)) {
            HtmlPage page = webClient.getPage(uri);
            webClient.waitForBackgroundJavaScript(10000);

            Window window = page.getEnclosingWindow().getScriptableObject();
            int i = 0;
            do {
                i++;
                System.out.println("start animation " + i);
                window.animateAnimationsFrames();
                System.out.println("end animation");
            } while (i < 200);

            System.out.println("----------------");
            System.out.println(page.asXml());
            System.out.println("----------------");
        }

Every time you call window.animateAnimationsFrames(); a new animation step is performed.
With the code above i was able to get the right chart.

**Comment by rbri** [comment]
No further response - i guess this problem is solved.
