### ISSUE TITLE
Email address validation not being triggered correctly

### ISSUE THREAD

**Issue by gavintranter** [HtmlUnit/htmlunit#103]
We are attempting to log into:
[pCloud](https://partner.pcloud.com/my) 
using HtmlUnit we enter a valid email address and password and click on the login button, the resulting page display a verification error to the effect that the email address is invalid.  

We know the email address is valid as we can login with the same details from a desktop browser.

We have tried to add `waitForBackgroundJavaScript` and `waitForBackgroundJavaScriptStartingBefore` into various stages of the flow, such as after typing the email address to no avail.

In our limited testing it should be possible to cause the validation error with any valid email and a random password string.  

Using HtmlUnit 2.36.0
WebClient config:
```
        webClient = new WebClient(CHROME);
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.getOptions().setPrintContentOnFailingStatusCode(true);
        webClient.getCookieManager().setCookiesEnabled(true);
        webClient.getOptions().setTimeout(300000);
        webClient.setJavaScriptTimeout(300000);
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setRedirectEnabled(true);
        webClient.setAjaxController(new NicelyResynchronizingAjaxController());
// tried with and without NicelyResynchronizingAjaxController
        webClient.addRequestHeader("Accept-Charset", "UTF-8");
        webClient.getOptions().setCssEnabled(true);
```

Thanks

**Comment by rbri** [comment]
Can you please provide the code that fills the form - do you use type(...)?

**Comment by gavintranter** [comment]
That seems to have been the issue.  Using `.type("")` seems to have gotten me past the valid email error.

I didnt even consider setting the _value_ attribute would be different from using `type` but in hindsight they are clearly different things :)

Thanks.

**Comment by rbri** [comment]
Thanks for the feedback - enjoy using HtmlUnit.
