### ISSUE TITLE
API error, as shown below

### ISSUE THREAD

**Issue by yingyingqiqi** [HtmlUnit/htmlunit#104]
API error, as shown below
![image](https://user-images.githubusercontent.com/48437786/69697396-40f8ea80-111d-11ea-9166-9034121bec3f.png)

location:http://htmlunit.sourceforge.net/apidocs/com/gargoylesoftware/htmlunit/BrowserVersion.html

**Comment by rbri** [comment]
The javadoc is for the latest release. Please make sure you are using the latest version (this is a good idea in general ;-))

**Comment by yingyingqiqi** [comment]
I didn't make myself clear

 An error occurred in this section of the comment.So the latest project source code is shown:
  https://github.com/HtmlUnit/htmlunit/blob/97dfdd532afd7735cd1ba807958636661a46d6d9/src/main/java/com/gargoylesoftware/htmlunit/BrowserVersion.java#L46-L50

 BrowserVersionFactory.class does not exist in the latest version.

 We can not create a different browser setup by using the BrowserVersionFactory.

 We use BrowserVersionBuilder.class

<pre id='htmlUnitCode'>
 *      String applicationName = "APPNAME";
 *      String applicationVersion = "APPVERSION";
 *      String userAgent = "USERAGENT";
 *      int browserVersionNumeric = NUMERIC;
 *
 *      BrowserVersion browser = new BrowserVersion.BrowserVersionBuilder(BrowserVersion.CHROME)
 *          .setApplicationName(applicationName)
 *          .setApplicationVersion(applicationVersion)
 *          .setUserAgent(userAgent)
 *          .build();
 * </pre>

**Comment by yingyingqiqi** [comment]
I was wrong. Thank you

**Comment by rbri** [comment]
You are welcome - feel free to open new issues if you have any problem with HtmlUnit.
