### ISSUE TITLE
I have confirmed again that there is a comment error

### ISSUE THREAD

**Issue by yingyingqiqi** [HtmlUnit/htmlunit#105]
I didn't make myself clear

 An error occurred in this section of the comment.So the latest project source code is shown:
  https://github.com/HtmlUnit/htmlunit/blob/97dfdd532afd7735cd1ba807958636661a46d6d9/src/main/java/com/gargoylesoftware/htmlunit/BrowserVersion.java#L46-L50

 BrowserVersionFactory.class does not exist in the latest version.This is the previous version.

 We can not create a different browser setup by using the BrowserVersionFactory.

 We use BrowserVersionBuilder.class, In the newest warehouse:
 https://github.com/HtmlUnit/htmlunit/blob/97dfdd532afd7735cd1ba807958636661a46d6d9/src/main/java/com/gargoylesoftware/htmlunit/BrowserVersion.java#L780-L785

<pre id='htmlUnitCode'>
 *      String applicationName = "APPNAME";
 *      String applicationVersion = "APPVERSION";
 *      String userAgent = "USERAGENT";
 *      int browserVersionNumeric = NUMERIC;
 *
 *      BrowserVersion browser = new BrowserVersion.BrowserVersionBuilder(BrowserVersion.CHROME)
 *          .setApplicationName(applicationName)
 *          .setApplicationVersion(applicationVersion)
 *          .setUserAgent(userAgent)
 *          .build();
 * </pre>

Sorry to bother you again

**Comment by rbri** [comment]
Sorry, this was a misunderstanding at my side. Will fix this.
