### ISSUE TITLE
How to get Re-synchronized call to address？

### ISSUE THREAD

**Issue by NuoLanC** [HtmlUnit/htmlunit#106]
How to get Re-synchronized call to address？
Thank you！

信息: Re-synchronized call to https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAA-Bn1zYLRIMtu8izF7MgPbNP7LKGf1O0Sq4zhUDX3xK4&count=21&max_cursor=0&aid=1128&_signature=APvL6xAZXSD9o-X-tXFJ8gD7y.&dytk=f1547c6ee1f85fe810533a0f9a9

**Comment by rbri** [comment]
Sorry but i do not understand your question/problem. Can you please provide more details.

**Comment by rbri** [comment]
sorry but without further clarification i can't do anything here.
Will close this for now - please reopen if i can help
