### ISSUE TITLE
Performance issue in SimpleScriptable.isReadOnlySettable

### ISSUE THREAD

**Issue by SteveHarney** [HtmlUnit/htmlunit#107]
Hi All, 
    We have been using HtmlUnit to execute a long list of JUnit tests.  As part of our performance profiling of our code it has been identified that SimpleScriptable.isReadOnlySettable  is an issue and is accounting for ~10% of our processing.   

This particular method is calling Method.getAnnotation(JsxGetter.class) and Method.getAnnotation(CanSetReadOnly.class) potentially for each method on the subclass.   The getAnnotation method is time consuming and the results are highly unlikely to change.  It would be better if the classes could establish a cache which would eliminate the need to process the unnecessary annotations on every execution on every subclass.

**Comment by rbri** [comment]
Strange - while working on rhino yesterday i found this method and did a simple first cache impl. But with the current test suite, this method is not really called.
Will implement a meaningful testcase and then build a new snapshot.
Please check at twitter (https://twitter.com/HtmlUnit) for updates.

**Comment by rbri** [comment]
Ok, have done the impl the other way - have completely removed the annotation handling. Hope that helps.
Will make a new snapshot available if the ci build is green.

**Comment by rbri** [comment]
The snapshot is out - waiting for feedback.

**Comment by SteveHarney** [comment]
Looks good. our test suite passes and the hot spot is gone.   Thanks.

**Comment by rbri** [comment]
Thanks for the feedback...
