### ISSUE TITLE
Javascript methods like flatmap and flat are not supported

### ISSUE THREAD

**Issue by sombhattacharyya1983** [HtmlUnit/htmlunit#113]
How do we get the support for enhanced javascript functions like `flatmap` , `flat` added to html unit ?

**Comment by rbri** [comment]
This simplest way to get this is to make a pull request for rhino (https://github.com/mozilla/rhino) that adds support for this.

Second option is to motivate me to add the implementation :-); but keep in mind i'm doing all the work on HtmlUnit/Rhino in my spare time and i have a real job and a real family.

**Comment by sombhattacharyya1983** [comment]
Ok I will try and add the support in my spare time. Any guides to get started on that will be very helpful.

**Comment by rbri** [comment]
Sounds great, Rhino is a monster but adding this functions might be not that tricky.

You might start by lucking at these commits:
* https://github.com/mozilla/rhino/commit/2d89acb883576c0acc62ab4300da6c0029dc565d
* https://github.com/mozilla/rhino/commit/833133ca7df1fb6ba85b4d8e47b62e63216f183d
to get a first idea how to add new functions to a class (prototype).

And regarding the implementation of flatmap and flat you might find many hints inside the existing functions like map().

And finally you have to add testcases for your new implementations. There might be something like
* https://github.com/mozilla/rhino/commit/af30e136a93fe02ece892e92fffaf09c84b509ad a good starting point.

The rest is the usual game- provide your PR for Rhino and someone will jump in and add some comments.

**Comment by bhattacharyyasom** [comment]
Cool. I will do this work from this personal account. Thanks. If i need help where do I ask?

**Comment by rbri** [comment]
Am 31. Dezember 2019 19:16:46 MEZ schrieb Som Shankar Bhattacharyya <notifications@github.com>:
>Cool. I will do this work from this personal account. Thanks. If i need
>help where do I ask?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/HtmlUnit/htmlunit/issues/113#issuecomment-569969139

Great, please open an issue for Rhino - if you need some help we can use the issue for discussing.

**Comment by rbri** [comment]
Looks like there are already testcases for these functions (currently disabled) in rhino.

**Comment by bhattacharyyasom** [comment]
Awesome ! Thanks for checking up on that. I will get cracking the moment I return from vacation.
