### ISSUE TITLE
com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializer ignores xsl:output

### ISSUE THREAD

**Issue by manstis** [HtmlUnit/htmlunit#118]
Hi,

I notice that `com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializer` ignores any output options defined however it may simply be my understanding or my environment and others with a better understanding able to guide me to a solution or clarify my understanding.

I am running `HtmlUnit` indirectly through a Google Web Toolkit (GWT) `GWTTestCase` that uses `HtmlUnit` internally.. (so my ability to change to a different version of `HtmlUnit` is more difficult, if needed). That aside how `HtmlUnit` is instantiated should have little influence on the issue.

During my debugging I notice `com.gargoylesoftware.htmlunit.javascript.host.xml.XSLTProcessor` is looking up a Xalan `XSLTProcessor` that correctly contains the same _output_ settings defined in the XSLT after instantiation and transformation to a `Element`. However `com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializer` ignores the _output_ settings and writes the string to a single un-indented line.

**_My XLST_**
(additional settings taken from [here](https://xml.apache.org/xalan-j/usagepatterns.html#outputprops))
```
<xsl:stylesheet version="1.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" ',
    xmlns:xalan="http://xml.apache.org/xalan" >
  <xsl:output indent="yes" xalan:indent-amount="2" />
```
**_My usage from JS_**
```
var xlstProcessor = new XSLTProcessor(xslt);
var xmlResult = xlstProcessor.transformToDocument(xmlDocument);
new XMLSerializer().serializeToString(xmlResult);
```
When ran in a _real_ browser this returns a formatted (indents and multi-line) string.

Any pointers or help very much appreciated.

With kind regards,

Mike

**Comment by rbri** [comment]
Will be great if you can help with fixing this.

At first i need a complete working minimal sample to make a test case out of this.

* a html file
  * containing the js that does the transformation
  * containing a button that triggers the js and places the output in eg a textarea
  * the stylesheet

This will be a real help, and of course you can also provide pull requests....

Many thanks

**Comment by manstis** [comment]
Hi @rbri I'd love to help fix it.

I'm not overly familiar with your codebase.

Would you mind pointing me to where in your [tests](https://github.com/HtmlUnit/htmlunit/tree/master/src/test/java/com/gargoylesoftware/htmlunit) would be a good place to try submitting a test? If there's an existing one I can plagiarise it'd be super useful for me.

With kind regards,

Mike

**Comment by manstis** [comment]
On review I'm not sure there's anything we can do.

The following JavaScript returns a formatted String:-
```
var xsltProcessor = new XSLTProcessor();
xsltProcessor.importStylesheet(....);
var resultDocument = xsltProcessor.transformToDocument(xmlDocument);
var xml = new XMLSerializer().serializeToString(resultDocument);
```
Whereas with plain Java or HtmlUnit I need to do the following to get a formatted output:-
```
final TransformerFactory tFactory = javax.xml.transform.TransformerFactory.newInstance();
final Transformer transformer = tFactory.newTransformer(new StreamSource(new StringReader(xsl)));

final DOMResult result = new DOMResult();
transformer.transform(new StreamSource(new StringReader(xml)), result);

// This uses the DOMResult (like HtmlUnit) and serialises it as a formatted String
// I need to copy the XSL's output parameters manually to the serializer
final Properties transformerProperties = transformer.getOutputProperties();
final Properties serializerProperties = OutputPropertiesFactory.getDefaultMethodProperties("xml");
serializerProperties.setProperty("standalone", "no");
serializerProperties.setProperty("indent", transformerProperties.getProperty("indent"));
serializerProperties.setProperty("{http://xml.apache.org/xalan}indent-amount", transformerProperties.getProperty("{http://xml.apache.org/xalan}indent-amount"));
final Serializer serializer = SerializerFactory.getSerializer(serializerProperties);
serializer.setOutputStream(System.out);
serializer.asDOMSerializer().serialize(result.getNode());

// This writes the result direct to a formatted String
// This is applying some default format settings
final StringWriter writer = new StringWriter();
final Result streamResult = new StreamResult(writer);
transformer.transform(new StreamSource(new StringReader(xml)), streamResult);
System.out.println(writer.toString());
```
`com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSeriaizer.serializeToString(Node)` has no notion of the _output_ settings in the `XSLTProcessor`and returns an unformatted `String` since the input `Node` is a `Document` from `XSLTProcessor`... only the fallback to `return root.getDomNodeOrDie().asXml();` returns a formatted `String` (with some sensible defaults.. that I assume JavaScript's `XMLSerializer` is doing (but I could not find any source code for it).

IDK.. I've waffled on a bit, but should you have read this far I admire you!

Perhaps your `XMLSeriaizer` should just return the result of my second Java example above to better mimic JavaScript?

**Comment by manstis** [comment]
I'm happy to submit a PR changing `XMLSeriaizer.serializeToString(...)` to use:
```
final StringWriter writer = new StringWriter();
final Result streamResult = new StreamResult(writer);
transformer.transform(new StreamSource(new StringReader(xml)), streamResult);
System.out.println(writer.toString());
```
... however it unfortunately won't help me as I'm stuck with GWT2.8.2 that uses HtmlUnit 2.19
```
[INFO] +- com.google.gwt:gwt-dev:jar:2.8.2:provided
... <snip> ...
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.19:provided
```

**Comment by rbri** [comment]
Have added three test cases
* com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializerTest.outputIndent()
* com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializerTest.withoutOutputIndent()
* com.gargoylesoftware.htmlunit.javascript.host.xml.XMLSerializerTest.outputStripSpace()

When running these tests with real browsers i can see no effect of the output indent option.
Can you please check what i'm doing wrong here.

(To run the test with real browsers you can have a look at the class jdoc for WebDriverTestCase).

**Comment by manstis** [comment]
Hi @rbri I've submitted a PR showing a failing test.

https://github.com/HtmlUnit/htmlunit/pull/121

**Comment by rbri** [comment]
Great will have a look at this tomorrow

**Comment by rbri** [comment]
Have a working imp here. Still some minor issues remaining but i'm nearly done.

**Comment by rbri** [comment]
Sorry for the missing comment here, this is implemented with the latest release.
Please check and open a new issue if you still have problems with this.

Again sorry for missing this update.
