### ISSUE TITLE
Login to page not working

### ISSUE THREAD

**Issue by codebyoul** [HtmlUnit/htmlunit#119]
I have poster a question in stuckoverflow, but no response yet i have tried many configuration but also not work.
question: https://stackoverflow.com/questions/59693423/htmlunit-login-to-page-with-redirection
there is my senario:
- Request page of categories:  https://sycm.aliexpress.com/api/public/categories?lang=en_US (for information the response is a json)
- Page requested is secure, so a redirection to login page is made

here is the code:

`package com.test.report;

import com.gargoylesoftware.htmlunit.*;
import com.gargoylesoftware.htmlunit.html.*;
import org.springframework.beans.factory.annotation.Value;

import java.io.IOException;

public class TestLogin {
    static String categoriesUrl = "https://sycm.aliexpress.com/api/public/categories?lang=en_US";
    static String loginUrl="https://sycm.aliexpress.com/api/public/categories?lang=en_US";
    static String loginForm = "login-form";
    static String loginId = "fm-login-id";
    static String passwordId = "fm-login-password";
    static String btnSubmitId = "fm-login-submit";
    static String login = "mylogin";
    static String password = "mypass";

    public static void main(String[] args) throws IOException {
        WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED);
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.setAjaxController(new NicelyResynchronizingAjaxController());
        HtmlPage page1 = null;
        try {
            page1 = webClient.getPage(loginUrl);
            webClient.waitForBackgroundJavaScriptStartingBefore(10000);
            webClient.waitForBackgroundJavaScript(10000);
            String htmlBody = page1.getWebResponse().getContentAsString();
            System.out.println(htmlBody);
        } catch (IOException e) {
            e.printStackTrace();
        }
        HtmlForm form = (HtmlForm) page1.getElementById(loginForm);
        HtmlTextInput textField = (HtmlTextInput) page1.getElementById(loginId);
        textField.click();
        webClient.waitForBackgroundJavaScriptStartingBefore(10000);
        webClient.waitForBackgroundJavaScript(10000);
        textField.type(login);
        HtmlPasswordInput textField2 = (HtmlPasswordInput) page1.getElementById(passwordId);
        textField2.click();
        webClient.waitForBackgroundJavaScriptStartingBefore(10000);
        webClient.waitForBackgroundJavaScript(10000);
        textField2.type(password);
        //HtmlSubmitInput button = (HtmlSubmitInput) page1.getElementById(btnSubmitId);
        try {
            HtmlButton button = (HtmlButton) form.getButtonByName("");
            HtmlPage page2 = button.click();
            webClient.waitForBackgroundJavaScriptStartingBefore(10000);
            webClient.waitForBackgroundJavaScript(10000);
            String htmlBody = page2.getWebResponse().getContentAsString();
            System.out.println(htmlBody);
            webClient.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}`

**Comment by rbri** [comment]
can you please provide valid credentials (via private mail) to give me a chance to try out

**Comment by codebyoul** [comment]
Please check your email

**Comment by codebyoul** [comment]
also the login page is:https://login.aliexpress.com/seller.htm

**Comment by codebyoul** [comment]
@rbri :i think i found what is the problem, there is a slider but i dont know how to slide with htmlunit ?

**Comment by rbri** [comment]
Ok,i was able to input using you credentials. Looks like the slider is there to prevent automatic login.
Will have a look at the inner workings of the page and come back to you.

**Comment by codebyoul** [comment]
Hi rbri
i found a solution but with different login page url ? you still need the credentials ?

**Comment by codebyoul** [comment]
the password has changed

**Comment by rbri** [comment]
Great, will close this.
Enjoy using HtmlUnit.
