### ISSUE TITLE
htmlunit supported es6 template string?

### ISSUE THREAD

**Issue by hunannan** [HtmlUnit/htmlunit#12]
hi , Does now htmlunit supported es6 template string?

http://es6.ruanyifeng.com/#docs/string#%E6%A8%A1%E6%9D%BF%E5%AD%97%E7%AC%A6%E4%B8%B2

**Comment by rbri** [comment]
The javascript support from HtmlUnit is based on Rhino and Rhino currently does not supports templates. There is already an (old) pull request https://github.com/mozilla/rhino/pull/81. If you like you can try to help to get this in sync with the current Rhino source....
