### ISSUE TITLE
[regression in 2.37] getting text of element ignores the value of child's input

### ISSUE THREAD

**Issue by php-coder** [HtmlUnit/htmlunit#128]
Simplified example:
```
<p id="number-of-stamps-block">
    I have <input type="number" value="2"/> out of 2 stamps
</p>
```
With htmlunit 2.36 when we get the text of the paragraph, the value was `I have 2 out of 2 stamps`
With htmlunit 2.37 the value is `I have out of 2 stamps`

The value of an `<input>` is being ignored now. This is regression and it seems like a bug.

Please, let me know if you need more information.

**Comment by rbri** [comment]
Can you please add the method you are using to get the text

**Comment by php-coder** [comment]
@rbri Thank you for the quick response!

> Can you please add the method you are using to get the text

That's good question. I'm using Robot Framework keyword that seems like is executing `WebElement.getText()`:

https://github.com/MarketSquare/robotframework-seleniumlibrary-java/blob/7164c2587b00f19208e888bd924739dd052366c5/src/main/java/com/github/markusbernhardt/seleniumlibrary/keywords/Element.java#L392

Also I'm using `htmlunit-driver` and if I'm not mistaken, `getText()` is implemented in the following way:

https://github.com/SeleniumHQ/htmlunit-driver/blob/122070661e7e309a849f59c0e616aa28b0b4c512/src/main/java/org/openqa/selenium/htmlunit/HtmlUnitWebElement.java#L463-L467

And here is `getVisiableText()`:

https://github.com/HtmlUnit/htmlunit/blob/f4e710378e8fcfc58eeee33bc848f9d044ef4659/src/main/java/com/gargoylesoftware/htmlunit/html/DomNode.java#L821-L824

I'm not 100% sure that that's correct and I hope that you might know even better what has been changed as you maintain these 2 libraries. If you need more assist, let me know and I'll run it under debugger to be fully ensure.

At this moment, to me it seems like it's not htmlunit issue but rather htmlunit-driver (if that's the case, could you transfer the issue to the appropriate repo?). Also I see that `getText()` implementation has been changed twice, so I guess that one of these changes might be a cause: https://github.com/SeleniumHQ/htmlunit-driver/commit/f3cba476e9de3aa5fbcc419edefe749c05c55312 https://github.com/SeleniumHQ/htmlunit-driver/commit/dcab0f9e0ffc3a15625dfa8866997b42eb6b2e0c

**Comment by rbri** [comment]
You are right, there was some change done in 2.37 (because of https://github.com/SeleniumHQ/htmlunit-driver/issues/80)

But now the implementation is compatible to the other selenium drivers.
Have added a test case that proves, Selenium WebDriver with real browsers are producing the same result.

**Comment by php-coder** [comment]
> But now the implementation is compatible to the other selenium drivers.

@rbri Does it mean that this won't be fixed?

I can get text but there will be no input value. I can get input value but it won't have outside text and I can't just glue them together as an input value in the middle of the text. Could you give me a pointer on how to get get a text like it was before?

**Comment by rbri** [comment]
@php-coder can you verify that you will get the same result when using selenium with real browser instead of htmlunit

**Comment by php-coder** [comment]
@rbri Thanks! I'll try it this week and report back about results.

**Comment by php-coder** [comment]
> can you verify that you will get the same result when using selenium with real browser instead of htmlunit

@rbri You were right: in Chrome it returns the same result: `The text of element 'id:number-of-stamps-block' should have been 'I have 2 out of 2 stamps', but it was 'I have out of 2 stamps'.`

Thanks, I'm closing the issue then.
