### ISSUE TITLE
com.gargoylesoftware.htmlunit.ScriptException: missing formal parameter (https://www.mohavecounty.us/Scripts/app/password_reset/index.js?v=2#100)

### ISSUE THREAD

**Issue by AbdenourAchab** [HtmlUnit/htmlunit#129]
With Firefox on Ubuntu 20.04 (latest daily build), I am able to read the contents of https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502 without any problem, regardless of the existence of script errors. However, when I try to do the same with HTMLUnit, using the following Java code and the latest release of HTMLUnit (version 2.37.0, which I downloaded from https://jar-download.com/artifact-search/htmlunit along with all its dependencies).

    final WebClient webClient = new WebClient();
    webClient.getOptions().setCssEnabled(false);
    webClient.getOptions().setThrowExceptionOnScriptError(false);
    webClient.setRefreshHandler(new RefreshHandler() {
		public void handleRefresh(Page page, URL url, int arg) throws IOException {
		    System.out.println("handleRefresh");
		}
	});
	HtmlPage page = (HtmlPage) webClient.getPage("https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502");

I get the following exception:
com.gargoylesoftware.htmlunit.ScriptException: missing formal parameter (https://www.mohavecounty.us/Scripts/app/password_reset/index.js?v=2#100)

I understand that whoever has developed the website has messed up. But Firefox is able to handle that problem gracefully. I would like the next release of HTMLUnit to handle the same problem just as gracefully as Firefox. In the meantime, I would appreciate any workarounds and tips on how I can change my code to get it to open the web page without throwing the above referenced exception.

**Comment by rbri** [comment]
Sorry, but i can't reach the page at https://www.mohavecounty.us/ContentPage.aspx - got a server not found. Without being able to reproduce your problem i can't really help.

In general
webClient.getOptions().setThrowExceptionOnScriptError(false);
should make the javascript execption handling similar to the browsers. But even with this set to false the errors are visible in the logs.

**Comment by AbdenourAchab** [comment]
https://www.mohavecounty.us/ContentPage.aspx does return a "Sorry, this page is not available" in Firefox. But that's not the page I am trying to access. The page I am trying to access is:
https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502

And https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502 does NOT return a "Sorry, this page is not available" in Firefox, and does return data in Firefox.

**Comment by rbri** [comment]
Am 10. Februar 2020 22:01:41 MEZ schrieb AbdenourAchab <notifications@github.com>:
>https://www.mohavecounty.us/ContentPage.aspx does return a server not
>found. But that's not the page I am trying to access. The page I am
>trying to access is:
>https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502
>
>And
>https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502
>does NOT return a server not found, and does return data.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/HtmlUnit/htmlunit/issues/129#issuecomment-584352121

Strange, have tested it again, same result - server not found. Any idea?

**Comment by AbdenourAchab** [comment]
Are you in the United States or Canada ? ... And are you using a VPN ?
I am in the United States. I access https://www.mohavecounty.us/ContentPage.aspx?id=111&cid=869&parcel=31344502 using my laptop without a VPN, and using a virtual desktop in Canada without a VPN. But, I just tunneled to France using a VPN and, now, I cannot access the web page either.

Please make sure you are not trying to access the page from outside the United States or Canada. Whether by being physically outside the United States or Canada without a VPN, or by using a VPN to tunnel outside the US or Canada.

**Comment by rbri** [comment]
No, i'm from the good old europe. So far i have no access to any VPN - will try if i can find some spare time.

**Comment by AbdenourAchab** [comment]
The following import statement:

    import com.gargoylesoftware.htmlunit.javascript.*;

and adding the following code, suggested by rbri while helping me with issue # 127

    webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener());

did fix the problem.

Thank you very much rbri for your help. I am going to close this issue.
