### ISSUE TITLE
Failure With JavaScript Errors

### ISSUE THREAD

**Issue by michellenw** [HtmlUnit/htmlunit#13]
I have been stuck on an issue with HtmlUnit which I posted on StackOverflow [here](https://stackoverflow.com/questions/54029644/how-to-fix-htmlunit-getelementbyid-returns-null). 

It looks like the page content loaded by JavaScript throws some errors that the HtmlUnit headless browser cannot handle.

Is there a work around to this? I have not been able to make even this simple code work due to this.

**Comment by rbri** [comment]
will have a look

**Comment by rbri** [comment]
Hi Michelle,

have posted a detailed answer to your stackoverflow question. Hope that helps.
