### ISSUE TITLE
HTMLUnit sends POST request with content-type application/x-www-form-urlencoded whereas browser sets the content-type text/plain

### ISSUE THREAD

**Issue by vasucomandur** [HtmlUnit/htmlunit#130]
The URL of the portal
 https://allegis.ramcocloud.com/RVW/extui/vwrt/LaunchPanel.htm

**Comment by rbri** [comment]
There are already some test cases for this.

com.gargoylesoftware.htmlunit.javascript.host.html.HTMLFormElementTest.enctypePost()

Can you please have a look and check what is missing here.

**Comment by vasucomandur** [comment]
Hi Ronald,

   Don't you think you need add test cases for the following Content-Type
as part of POST request.
   Content-Type : text/plain, application/json, text/xml

   Correct me if I am wrong.

Regards
 Vasu

**Comment by rbri** [comment]
Yes looks like you are correct. Will require some days....

**Comment by rbri** [comment]
Have started work on this.

**Comment by rbri** [comment]
Hi Vasu,
just made a new snapshot build available.
Please verify if this solves your problem.

**Comment by vasucomandur** [comment]
Hi Ronald,

    I downloaded the latest snapshot Version 2.38 Build 531 and tested it.
    It was still sending application/x-www-form-urlencoded and not
text/plain. The issue still persists.

Regards
 Vasu

**Comment by rbri** [comment]
ok, maybe i miss something

**Comment by rbri** [comment]
ok, maybe i miss something

**Comment by rbri** [comment]
Hi Vasu,
have done some more analysis and written many more test.
But outside of a small issue (only when simulating IE) everything seems to be fine.

Can you please try with the next build (if jenkins is ready). If this still fails i need some hint from your side where the problem is.
Do you simulate IE?

**Comment by vasucomandur** [comment]
Hi Roland,

   I simulate either Firefox or Chrome. I never simulate IE.

Regards
 Vasu

**Comment by vasucomandur** [comment]
Hi Ronald,

    The portal is executing extensive Javascript through which the POST
request happens with Content-Type set to text/plain.
     In fact, I had given the URL also. The starting URL is
https://allegis.ramcocloud.com/RVW/extui/vwrt/LaunchPanel.htm
<https://www.google.com/url?q=https://allegis.ramcocloud.com/RVW/extui/vwrt/LaunchPanel.htm&sa=D&source=hangouts&ust=1581580986089000&usg=AFQjCNFRSq2h9NlsJScfypVf_qbB5a7VzQ>

 Regards
 Vasu

**Comment by rbri** [comment]
I'm aware of that already and i already had a look on the js code. But this is (as in many other cases) a nightmare.

**Comment by vasucomandur** [comment]
Hi Ronald,

   If you want me to simulate IE and validate, I can do that.

Regards
 Vasu

**Comment by rbri** [comment]
No that will not help. I need a glue how the form gets switched to text/plain mode.
Do you have a web  proxy running? If yes can you figure out if this is an ordinary post or an xml request.

**Comment by vasucomandur** [comment]
Hi Roland,

   It is an ordinary POST request and not an XML request.

regards
 Vasu

**Comment by rbri** [comment]
Ok, have another idea - maybe they use FormData based on a for. Have to write some tests.
Will inform you if i made some progress.

**Comment by vasucomandur** [comment]
Thanks Ronald for your quick response.

Regards
 Vasu

**Comment by rbri** [comment]
Tests are written an passing, At the moment i have no idea how this page builds the form and switches the form to "text/plain" mode.
Will be great if you can find any hint....

**Comment by vasucomandur** [comment]
Hi Roland,

   What if the JS is written with fetch method setting the content-type
text/plan and data sent as part of the body?
    Does that make sense?.

Regards
 Vasu

**Comment by rbri** [comment]
Hi Vasu,
can you please provide a code snippet, that
* opens the page
* fills the entry fields with some characters
* clicks the login button

Using this i might be able to place a breakpoint somewhere to understand where the post is generated.

Thanks.

**Comment by vasucomandur** [comment]
Ronald,

    The problem happens even before the login page gets rendered on the
browser.
    There are a lot of POST requests going on the wire apart from
downloading the CSS, JS files.
     One of the POST requests fails.

     If you need any trace through Web Proxy, I can send you that

Regards
 Vasu

**Comment by rbri** [comment]
HtmlUnit development is impossible without Charles :-)
Can see you point - cross your fingers

**Comment by rbri** [comment]
ok this was the missing link, with some hacks i'm able to send the correct request. 
Have to think about this a bit and write the missing unit tests.
You can de-cross your fingers and expect a solution during the next days - checkout HtmlUnit @ twitter

**Comment by vasucomandur** [comment]
Thanks Ronald for a quick response.
 HTMLUnit is a good tool for screen scraping and if the Rhino engine side
(JS) is strengthened it will be
 a great tool.

Regards
 Vasu

**Comment by rbri** [comment]
You can try the latest build from the ci server if you like

**Comment by vasucomandur** [comment]
Thanks Ronald. The fix has worked on the latest build (2.38 Build 535).
The login screen has come.

Thanks once again for your quick fix.

Regards
 Vasu

**Comment by rbri** [comment]
Great and thanks for the feedback. I estimate one more week to write the required test and implementation fixes. Will publish a new release afterwards.

**Comment by rbri** [comment]
Hope i can release this  week.
