### ISSUE TITLE
Support ComputedCSSStyleDeclaration when JS engine is disabled.

### ISSUE THREAD

**Issue by shapiroronny** [HtmlUnit/htmlunit#131]
When initializing webClient without JSEngine, there's no way to access any computed styles because the API is based on JS pairing.

**Comment by cdalexndr** [comment]
I'll make a PR for this issue

**Comment by rbri** [comment]
Great

**Comment by rbri** [comment]
Ok, was a long way to get this done but finally the 3.7.0 version supports this.
Thanks for reporting this and sorry for the long delay.
