### ISSUE TITLE
Forms do not submit values for elements that use the "form" attribute

### ISSUE THREAD

**Issue by cbartolome** [HtmlUnit/htmlunit#132]
The `form` attribute on the following `textarea` element should mean that the element's value is submitted when the form is submitted:
```
<html>
<body>
  <textarea form="myForm" name="data">Some data</textarea>
  <form id="myForm">
    <button type="submit">Submit</button>
  </form>
</body>
</html>
```
It looks like `HtmlForm.getSubmtitableElements()` doesn't look for elements outside the form whose `form` attributes match the ID of the form, though, so the submitted form contains no data.

**Comment by rbri** [comment]
You are right, this is a really old issue. Think i can fix this soon.

**Comment by rbri** [comment]
Have done a first fix - check twitter to see if the next snapshot is available

**Comment by rbri** [comment]
Snapshot is available - please test

**Comment by cbartolome** [comment]
Thanks for the quick update!

I think the new code in `HtmlForm.getSubmittableElements()` may need to iterate over `getBody().getDescendents()`, not `getBody().getChildren()`, for my use case to work. There may also be an issue if the input element with the `form` attribute comes before the `form` element itself in the HTML.

**Comment by rbri** [comment]
Ok, will check your suggestions. Thanks.

**Comment by rbri** [comment]
Tests added and iterator fixed - thanks for looking at the impl.

**Comment by cbartolome** [comment]
Works great! Thanks again for responding so quickly.

**Comment by rbri** [comment]
Your welcome
