### ISSUE TITLE
CSSStyleSheet cache fails if request is redirected

### ISSUE THREAD

**Issue by cdalexndr** [HtmlUnit/htmlunit#14]
When trying to get a stylesheet from cache, the **request** url is used:
_CSSStyleSheet.java(line 291)_
` final Object fromCache = cache.getCachedObject(request);`
_Cache.java(line 286)_
`final URL url = request.getUrl();`

,but when it is stored in cache, the url  is retrieved from the **response**:
_Cache.java(line 127)_
`final URL url = response.getWebRequest().getUrl();`

In case of a redirect, the urls will be different, thus it will reparse the stylesheet instead of retrieving it from cache.

**Comment by cdalexndr** [comment]
As a workaround, I extended _Cache_ and overriden the method:
```
    @Override public boolean cacheIfPossible( WebRequest request, WebResponse response, Object toCache ) {
        response.getWebRequest().setUrl( request.getUrl() );
        return super.cacheIfPossible( request, response, toCache );
    }
```

**Comment by rbri** [comment]
Many thanks for the report, should be fixed now together wit a minor code optimization
Will inform via Twitter  (https://twitter.com/HtmlUnit) if a new snapshot is available.
