### ISSUE TITLE
input type="number" does not allow floating point numbers

### ISSUE THREAD

**Issue by trajano** [HtmlUnit/htmlunit#141]
the spec allows for floating point numbers if you have step specified e.g.

`<input type="number" step="0.01" min="0.01" name="amount" />`

But setValueAttribute of HtmlNumberInput requires a long v alue

```
    @Override
    public void setValueAttribute(final String newValue) {
        try {
            if (!newValue.isEmpty()) {
                Long.parseLong(newValue);
            }
            super.setValueAttribute(newValue);
        }
        catch (final NumberFormatException e) {
            // ignore
        }
    }
```

**Comment by rbri** [comment]
You are right - this is a known issue ( #123) and already fixed.
Please use the latest snapshot build.

BTW: i plan to make a new release available by the end of this week
Check twitter for regular updates.
