### ISSUE TITLE
DedicatedWorkerGlobalScope should extend from EventTarget

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#150]
According to the [specification](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope#Methods):

> This interface inherits methods from the WorkerGlobalScope interface, and its parent EventTarget

In current implementation DedicatedWorkerGlobalScope inherits from HtmlUnitScriptable. This makes some common use patterns such as "self.addEventListener" fail in Work scripts.

**Comment by RuralHunter** [comment]
I tried to change DedicatedWorkerGlobalScope to extend from EventTarget but it doesn't work. It seems js functions from parent class are not scanned and defined. DedicatedWorkerGlobalScope.addEventListener is undefined in this case. But the similar Window.addEventListener class is working. Window also extends from EventTarget. What's the secret of Window class?

**Comment by rbri** [comment]
Hi Rural,
thanks for the report.
It will be great if you can provide a working test case. Maybe you can create a class named DedicatedWorkerGlobalScopeTest (use com.gargoylesoftware.htmlunit.javascript.host.worker.WorkerTest as template) and add at least one test method (maybe you can use thisAndSelf() as template) to show your problem in the most simple way.
If you have more than one method not supported, it will be great if you can write a test method for every method.
Will try to fix that.

**Comment by rbri** [comment]
sorry was able to reproduce your case. Please check my last commit.

**Comment by rbri** [comment]
i guess i found it... the fix requires some research.

**Comment by RuralHunter** [comment]
I found the difference between DedicatedWorkerGlobalScope and other pre-configured js classes. There is a step to [set the prototype to its parent](https://github.com/HtmlUnit/htmlunit/blob/3931f473e5ad400dfe8b704be78a0b65ad139278/src/main/java/com/gargoylesoftware/htmlunit/javascript/JavaScriptEngine.java#L396) when pre-configuring other classes. This step is missing for DedicatedWorkerGlobalScope. So add this step [here](https://github.com/HtmlUnit/htmlunit/blob/3931f473e5ad400dfe8b704be78a0b65ad139278/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/worker/DedicatedWorkerGlobalScope.java#L98) should fix the issue:
`

if (!StringUtils.isEmpty(config.getExtendedClassName())) {
            final Scriptable parentPrototype = owningWindow.getPrototype(config.getExtendedClassName());
            prototype.setPrototype(parentPrototype);
        }

`

**Comment by rbri** [comment]
Yes you are correct. Found the same. Will try to finish the fix soon

**Comment by rbri** [comment]
Please try with the latest snapshot build

**Comment by RuralHunter** [comment]
It works. Thanks for the quick fix as always!
