### ISSUE TITLE
Page doesn't finish loading

### ISSUE THREAD

**Issue by jeffcjohnson** [HtmlUnit/htmlunit#151]
First, thanks for HtmlUnit, it's great!

The following never finishes loading the page in 2.38.0 nor 2.39.0.  The CPU usage goes high.

```
import com.gargoylesoftware.htmlunit.WebClient
import com.gargoylesoftware.htmlunit.html.HtmlPage

fun main() {
    println("0")
    val page = WebClient().getPage<HtmlPage>("https://www.arvest.com/")
    println("1")
}
```

**Comment by rbri** [comment]
from a first look it seems to be the same issue as #147 

This js seems to run into some endless loop.

https://www.arvest.com/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=2131618594CookieSpec

**Comment by rbri** [comment]
see #552 for details

**Comment by rbri** [comment]
Should work with 3.0.0 - please reopen if this still fails
