### ISSUE TITLE
Viewing AJAX requests before sending (not really issue)

### ISSUE THREAD

**Issue by RabeeHanna** [HtmlUnit/htmlunit#16]
I am using the NicelyResynchronizingAjaxController to make synchronous calls rather than async. The webpage automatically makes calls to certain advertisement pages as well, thus those requests are also being synchronized and called by my application. 

Currently, i allow these calls to be made but when i receive the response I replace it with a default "blank" response (I do this by overriding getResponse method in WebConnectionWrapper class). 

Is it possible to view the requests that the page is about to send before it sends them? I want do do this so I can cancel certain ads without having to replace the responses with a blank one.

Attaching my override function to return blank response from some type of ads:

![capture](https://user-images.githubusercontent.com/8762100/51929709-da088900-23c6-11e9-83ff-d5840f185c41.PNG)

**Comment by rbri** [comment]
Nu sure if i got you right, but you have the request already, simply do whatever you like with the request before calling super.getResponse()

**Comment by RabeeHanna** [comment]
You are correct, I must have missed this before sorry. Will close!
