### ISSUE TITLE
TimeToLive in HttpWebConnection Pooling

### ISSUE THREAD

**Issue by Peter0x48** [HtmlUnit/htmlunit#161]
Hi,

in my usecase of HtmlUnit I request a site with a DNS name which has a TTL of 5 seconds and the IP behind the name may changes due to a failover. 
It looks like a HTTP Pooling from Apache HttpClient is enabled which would then cause this TTL to be ignored as long as the connection exists.

https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/HttpWebConnection.java#L1143

Is that assumption correct? Is there a way to configure the "connTimeToLive" or to disable connection pooling completely?

Thanks!

**Comment by rbri** [comment]
There is a new WebClientOption property for setting the connectionTimeToLive. Please try with the latest snapshot and please inform me about the results.

**Comment by rbri** [comment]
Any feedback?

**Comment by Peter0x48** [comment]
> There is a new WebClientOption property for setting the connectionTimeToLive. Please try with the latest snapshot and please inform me about the results.

Thanks! Do you think a value of 0 will disable the reuse of an connection entirely? I've tested with 0 and my first impression looks good, but I have no exact test case for that.

**Comment by rbri** [comment]
Yes i think so.
I forward the value more or less directly to the httpclient (using ms as unit)

    httpClientBuilder.setConnectionTimeToLive(connectionTimeToLive, TimeUnit.MILLISECONDS);

**Comment by rbri** [comment]
I guess the silence means this is working. This was part of the last release.

**Comment by Peter0x48** [comment]
Yes, thank you very much.
