### ISSUE TITLE
URL that messes up memory.

### ISSUE THREAD

**Issue by smatei** [HtmlUnit/htmlunit#163]
snapshot 2.40
-Xmx4096m
javascript enabled

I found an url, https://www.bizjournals.com/phoenix/bio/2711/Angela+Gonzales that messes up the memory when javascript is enabled

![javascript-enabled-memory](https://user-images.githubusercontent.com/17740806/79839168-cdea5c00-83bc-11ea-8087-178417760439.png)

Please check this case too. Until then I will disable javascript.

_Originally posted by @smatei in https://github.com/HtmlUnit/htmlunit/issues/156#issuecomment-617012324_

**Comment by rbri** [comment]
seems to be again the Incapsula stuff as in #147

**Comment by rbri** [comment]
see #552 for details

**Comment by rbri** [comment]
Should work with 3.0.0 - please reopen if this still fails
