### ISSUE TITLE
Object.seal() behavior is not correct

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#174]
This should be a rhino problem. 
According to the specification, the values of present properties of a sealed object can be changed as long as they are writable. The code below runs correctly in real browsers but fails in htmlunit with net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot add properties to this object because extensible is false.

```javascript
fun=function() 
{
    "use strict";
    var r = {};
    Object.defineProperties(r, {
        a: {
            writable: true,
            value: 'aaa'
        }
    });
    r.a='abefore';
    alert('r.a before='+r.a);
    Object.seal(r);
    r.a='aafter';
    alert('r.a after='+r.a);
};
fun();
```

**Comment by rbri** [comment]
Can you please open a Rhino issue for this.

**Comment by RuralHunter** [comment]
yes sure: https://github.com/mozilla/rhino/issues/676

**Comment by rbri** [comment]
Made a PR for rhino, as soon as this is merged i will update our core-js snapshot.

**Comment by rbri** [comment]
fixed with the lastes core-js snapshot build
