### ISSUE TITLE
console.trace() is mis-implemented

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#179]
According to the [MDN DOC](https://developer.mozilla.org/en-US/docs/Web/API/Console/trace): The console interface's trace() method outputs a stack trace to the Web Console. But in [htmlunit](https://github.com/HtmlUnit/htmlunit/blob/d3b9638326105c636566e2261e78abda4528b780/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Console.java#L220): This method performs logging to the console at trace level.

**Comment by rbri** [comment]
Better late than never - this is implemented now. The trace depends on the current Rhino capabilities - so don't expect too much.
