### ISSUE TITLE
RegEx expression failure.

### ISSUE THREAD

**Issue by dwayne-mss** [HtmlUnit/htmlunit#186]
According to some online RegEx parsers, the expression [_-\\s]+ is invalid in most RegEx parsers, but valid in ECMAScript. Most browsers will handle the expression fine, but the Rhino implementation complains that an invalid character range is being specified.

var r = "abc-123_456"
r.replace(/[_-\s]+/g, 'hi')

Results in (when run in a browser's javascript console)
"abchi123hi456"

But fails with a invalid character range exception when encountered by HtmlUnit's javascript implementation.  Also fails when running interactive Rhino console, so I know ultimately this is a Rhino issue, but since HtmlUnit contains its own Rhino source, thought it might apply here too.

**Comment by rbri** [comment]
will try to fix this

**Comment by rbri** [comment]
Have fixed this in Rhino. The fix is now in the core-js branch also.
Additionally some unit tests are added to the HtmlUnit test suite.

You can now use the latest snapshot.

Many thanks for the report. Enjoy using HtmlUnit.

**Comment by dwayne-mss** [comment]
Thanks!

Sent from my iPhone

On Jul 3, 2020, at 4:14 AM, RBRi <notifications@github.com> wrote:

﻿

Closed #186<https://github.com/HtmlUnit/htmlunit/issues/186>.
