### ISSUE TITLE
HtmlRangeInput Value Problem

### ISSUE THREAD

**Issue by cheeseng** [HtmlUnit/htmlunit#19]
I wonder why HtmlRangeInput always set value to 50 on creation: 

https://github.com/HtmlUnit/htmlunit/blob/fb43bb9c3dba8beaf988172433d028716bfd6b71/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlRangeInput.java#L38

Given the code, even though I have range input like this: 

```
<input id="secret1" type="range" value="12" />
```

when element.getAttribute("value"), the value is 50, not 12.

Is there any reason for that?

**Comment by rbri** [comment]
Yes there is one, 50 is the default but only if there is not value set. Have fixed this. But i fear there is more to do. Please open more issues if you find more.
Test cases are also very welcome.
