### ISSUE TITLE
What happened to com.gargoylesoftware.htmlunit.html.InputElementFactory?

### ISSUE THREAD

**Issue by dwayne-mss** [HtmlUnit/htmlunit#190]
This class seems to have disappeared in 2.37.0, but I don't see any information in the change history as to why.  I haven't even found the commit that removed it.  Was this an intentional change?

**Comment by dwayne-mss** [comment]
Nevermind... my poor log searching ability... I found commit that references use of DefaultElementFactory for input items too.

**Comment by rbri** [comment]
Sorry for not mention this in the changes, but from my point of view these factories are part of the internal API.

There is still the plan to (optionally) replace the neko parser with a different one - that is more or less the reason for doing the refactoring in that area.

**Comment by dwayne-mss** [comment]
So I tripped over this change when I was trying to upgrade Webtest to use latest HtmlUnit.  An old application I know, but I still like it because of it’s Ant/XML driven test cases… which seems easier to write for QA teams composed of non-developers.  I’ll dig around and see if I can figure out how to avoid this internal API call.

Thanks for the response!

On Jul 9, 2020, at 5:23 AM, RBRi <notifications@github.com<mailto:notifications@github.com>> wrote:



Sorry for not mention this in the changes, but from my point of view these factories are part of the internal API.

There is still the plan to (optionally) replace the neko parser with a different one - that is more or less the reason for doing the refactoring in that area.
