### ISSUE TITLE
CSS files with UTF-8 BOM triggers CSS errors

### ISSUE THREAD

**Issue by alitokmen** [HtmlUnit/htmlunit#192]
I noticed that if a CSS file has a UTF-8 BOM then HtmlUnit seems to not like it - It throws a CSS error:

```
com.gargoylesoftware.htmlunit.DefaultCssErrorHandler error
WARNING: CSS error: 'http://localhost:59425/cargo-daemon-webapp/cargo.css' [38:1] Error in style rule. (Invalid token "body". Was expecting one of: <S>, <LBRACE>, <COMMA>.)
```

The UTF-8 BOM _doesn't seem to_ "bother" Web browsers, could HtmlUnit also be updated to behave similarly?

**Comment by rbri** [comment]
can you please provide the whole css file.

**Comment by alitokmen** [comment]
Thanks for your quick reply!

The CSS file is on: https://github.com/codehaus-cargo/cargo/blob/d60fb4e650557ff8754960c6a4ea608d29478db7/extensions/daemon/webapp/src/main/webapp/cargo.css

**Comment by rbri** [comment]
Thanks, will have a look during the next days.

**Comment by rbri** [comment]
The parsing fails because the file has a bom header. Do you face the problem while using HtmlUnit with some webpage?

**Comment by alitokmen** [comment]
@rbri , you know very well your code !! :)

Yes, removing the UTF-8 BOM fixed the issue. I think it could be worthwhile to enable HtmlUnit to work with UTF-8 BOMed files, as Windows tends to save with a BOM and browsers seem to be fine with it.

**Comment by rbri** [comment]
> I think it could be worthwhile to enable HtmlUnit to work with UTF-8 BOMed files, as Windows tends to save with a BOM and browsers seem to be fine with it.

Yes this is the plan - removing the BOM is not so tricky (i already did it at some other places) but it will require some time to think about test cases to ensure the same behavior as real browsers.

**Comment by rbri** [comment]
Ok, hopefully i have covered the most important cases. Please check twitter for a new snapshot build.

Many thanks for reporting this.
