### ISSUE TITLE
DOMParser.parseFromString doesn't return element with body

### ISSUE THREAD

**Issue by twendelmuth** [HtmlUnit/htmlunit#193]
Hi,

I'm facing some issues testing a WebPage that uses Bootstrap.js.
I could isolate the issue so far to notice differences in the behavior of DOMParser.parseFromString(), the issues occur in the sanitizeHtml function of bootstrap (see: https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.js - Line 2750-2753, crash at 2753, createdDocument.body == null)

I tested the following javascript with Chrome, FF, IE & Edge:
```
	var unsafeHtml = '<div></div>';
	var domParser = new window.DOMParser();
	var createdDocument = domParser.parseFromString(unsafeHtml, 'text/html');
	alert(createdDocument.body.innerHTML);
```

all returning `<div></div>` as the result.

On the other hand the following test fails with `net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot read property "innerHTML" from null`

```
    @Test
    @Alerts({"<div></div>"})
    public void domParserBodyTest() throws Exception {
        final String html
            = "<html><head><script>\n"
            + "function test() {\n"
            + "	var unsafeHtml = '<div></div>';\n" 
            + " var domParser = new window.DOMParser();\n" 
            + " var createdDocument = domParser.parseFromString(unsafeHtml, 'text/html');\n" 
            + " alert(createdDocument.body.innerHTML);"
            + "}\n"
            + "</script></head><body onload='test()'>\n"
            + "</body></html>";

        loadPageWithAlerts2(html);
    }
```

**Comment by rbri** [comment]
Will have a look, thanks for the well prepared bug report.

**Comment by rbri** [comment]
Thanks for the test case - i can reproduce your problem. From the code it is clear, the html-support of the DOMParser is not there. Have done some first tries, but it  is not that easy.
Will require some time...

**Comment by rbri** [comment]
Hi Thorsten,
hopefully this is now fixed. As usual will inform on  twitter if the next snapshot build is available.
Can you then please test the new snapshot and report about your findings here. Maybe there is more to do the fully support this function.

Thanks for the clear bug report.

**Comment by twendelmuth** [comment]
Yup that seemed to have done the trick 👍 
At least I'm getting no more exceptions that are in direct relation to it/BootStrap.js

Thanks for the quick fix!
