### ISSUE TITLE
How can i get each requests and responses using HtmlUnit?

### ISSUE THREAD

**Issue by shaodong-hub** [HtmlUnit/htmlunit#194]
Want to know how to get the number of requests on the current page and the response code for all requests.

**Comment by rbri** [comment]
Not sure to get the point of your question....

You can register your own WebConnectionWrapper (https://htmlunit.sourceforge.io/faq.html#HowToModifyRequestOrResponse) to be informed about any request/response and implement your own counters there.

Does this help?

**Comment by rbri** [comment]
no further feedback from the reporter - will close this.
