### ISSUE TITLE
How to disable printing javascript exceptions on console?

### ISSUE THREAD

**Issue by LukeChow** [HtmlUnit/htmlunit#20]
I have tried all methods about disable printing exceptions, but console still printed a bunch of javascript  exceptions information.
Here is gradle setting:
`compile 'net.sourceforge.htmlunit:htmlunit:2.34.1'`
Here is my code:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/8969860/54473778-52ac9300-4817-11e9-9266-f0add0434395.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/8969860/54473789-72dc5200-4817-11e9-96ad-0fc0a14525c7.png">
`HtmlPage page = webClient.getPage(pageURL);`

**Comment by rbri** [comment]
Please provide the pageUrl and your source code as text not at image.

**Comment by LukeChow** [comment]
pageURL= https://www.gushiwen.org/shiwen/default_3A777777777777A12.aspx
===========================
java.util.logging.Logger.getLogger("com.gargoylesoftware.htmlunit").setLevel(Level.OFF);
        java.util.logging.Logger.getLogger("org.apache.commons.httpclient").setLevel(Level.OFF);
        webClient = new WebClient(BrowserVersion.CHROME);
        webClient.setAjaxController(new NicelyResynchronizingAjaxController());
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setActiveXNative(false);
        webClient.getOptions().setCssEnabled(false);
        webClient.getOptions().setPrintContentOnFailingStatusCode(false);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
        webClient.setCssErrorHandler(new CSSErrorHandler() {
            @Override
            public void warning(CSSParseException exception) throws CSSException {
            }
            @Override
            public void error(CSSParseException exception) throws CSSException {
            }
            @Override
            public void fatalError(CSSParseException exception) throws CSSException {
            }
        });
        webClient.setJavaScriptErrorListener(new JavaScriptErrorListener() {
            @Override
            public void scriptException(HtmlPage page, ScriptException scriptException) {
            }
            @Override
            public void timeoutError(HtmlPage page, long allowedTime, long executionTime) {
            }
            @Override
            public void malformedScriptURL(HtmlPage page, String url, MalformedURLException malformedURLException) {
            }
            @Override
            public void loadScriptError(HtmlPage page, java.net.URL scriptUrl, Exception exception) {
            }
        });
        webClient.setHTMLParserListener(new HTMLParserListener() {
            @Override
            public void error(String message, java.net.URL url, String html, int line, int column, String key) {
            }
            @Override
            public void warning(String message, java.net.URL url, String html, int line, int column, String key) {
            }
        });
HtmlPage page = webClient.getPage(pageURL);

**Comment by rbri** [comment]
Thanks, will have a look

**Comment by rbri** [comment]
This is really a pain with the current version. Will cleanup the source and make a new snapshot available soon.

**Comment by rbri** [comment]
Ok, have done a lot of changes to fix this pain.
In theory not it will be sufficient to do

 `webClient.setJavaScriptErrorListener(new SilentJavascriptErrorListener());
webClient.setCssErrorHandler(new SilentCSSErrorHandler());`

As always this requires a build from the latest code. You can have a look at [twitter](https://twitter.com/HtmlUnit); will inform there if a new snapshot is available.
