### ISSUE TITLE
Javascript: new File(bits, name[, options]) constructor not implemented

### ISSUE THREAD

**Issue by twendelmuth** [HtmlUnit/htmlunit#202]
Anyone calling `new File(bits, name)` (see: https://developer.mozilla.org/en-US/docs/Web/API/File/File) in javascript code will seen unexpected behavior.
The first issue is that most calls on the object will fail with an NullPointerException (`getName()`, `getLastModified()`, `getSize()` all require the underlying `file_` to be not null).

Therefore the following test will fail:
```
    @Test
    @Alerts({"myfilename", "application/octet-stream", "1000", "0"})
    @NotYetImplemented(IE)
    public void fileConstructor() throws Exception {

		final String html = "<html><head><script>\n" + "	function test() {\n"
				+ "		var newFile = new File([], 'myfilename', {type: 'application/octet-stream', lastModified: '1000'});"
				+ "     alert(newFile.name);"
				+ "     alert(newFile.type);"
				+ "     alert(newFile.lastModified);"
				+ "     alert(newFile.size);"
				+ " } "
				+ "</script></head><body onload='test()'>\n"
				+ "</body>\n" + "</html>";
		loadPageWithAlerts2(html);
	}
```

**Comment by rbri** [comment]
Any PR is welcome... even if you only add test cases to class FileTest.

**Comment by rbri** [comment]
Many thanks for your PR -will have a look later this week

**Comment by rbri** [comment]
Hi Thorsten, do you have a case where the new file object is used for some kind of upload to the server?

**Comment by twendelmuth** [comment]
Hi. Right now I don't. We're still trying to make the page testable with Htmlunit where you could use a FileUpload module.
I also have another issue right now that might be related (well it's also relating to Files) ... but I'm unable to reproduce the functionality within the unit test scope.
I'm going to give your changes a try 👍

**Comment by twendelmuth** [comment]
For completeness sake: The one way that I saw new File() being used it to init it with dummy data (`new File([],"")`) in the frameworks that I looked at. 
The problem mainly surfaced during the FormData serialization of the data.
