### ISSUE TITLE
How to disable brotli support

### ISSUE THREAD

**Issue by cda007** [HtmlUnit/htmlunit#208]
Hi,

In a previous version, support to brotli compression has been added. is there any option to disable that option ?

Regards,
Christophe

**Comment by rbri** [comment]
Not really, why do you like to do that?

**Comment by rbri** [comment]
Any feedback on this - do you like to see an option to disable this?

**Comment by cda007** [comment]
Hi,

No, it is ok, I found a way to disable it.

Regards,

**Comment by rbri** [comment]
Ok, great, will close this.
Thanks for using HtmlUnit.
