### ISSUE TITLE
WESTERNUNION website does not load properly in htmlunit

### ISSUE THREAD

**Issue by girish-pisharath** [HtmlUnit/htmlunit#21]
My code is as below:

    URL url = new URL("https://www.westernunion.com/ca/en/send-money/app/sm-login");
    WebRequest requestSettings = new WebRequest(url, HttpMethod.GET);
    requestSettings.setAdditionalHeader("Content-Type", "application/json,text/html; charset=UTF-8");

    WebClient webClient = new WebClient(BrowserVersion.INTERNET_EXPLORER);
    webClient.getOptions().setCssEnabled(false);
    webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
    webClient.getOptions().setThrowExceptionOnScriptError(false);
    HtmlPage redirectPage = webClient.getPage(requestSettings);
    webClient.close();

This runs in an infinite loop of errors and finally JVM crashes.Can you please help?

**Comment by rbri** [comment]
Have tested this again today with the latest code - seems to finish now after some time (~1min).
Maybe the web page itself was changed in between or this is fixed as a side effect of other fixes.

Will close this, please open a new one if you still have problems.
