### ISSUE TITLE
Add support for placeholder-shown / -ms-input-placeholder

### ISSUE THREAD

**Issue by twendelmuth** [HtmlUnit/htmlunit#212]
Currently HtmlUnitDriver is unable to support the css pseudos placeholder-shown / -ms-input-placeholder.

used https://caniuse.com/#search=placeholder-shown to get compatibility
however I tested in IE 11.1016.18362.0 and number fields seem to be also supported 🤷 So I left the support in there for now.

**Comment by rbri** [comment]
Thanks for the PR - have done some 'review' :-)

**Comment by rbri** [comment]
Merged - thanks for your contribution.
