### ISSUE TITLE
Provide code formatting rules

### ISSUE THREAD

**Issue by twendelmuth** [HtmlUnit/htmlunit#214]
For contribution it would be nice to have the formatting rules somewhere checked in
So that contributors also can format their code without ending up with changing 1000 loc 😁

**Comment by rbri** [comment]
As far as i remember the maven plugin is able to generate a eclipse configuration based on the given rules.

**Comment by twendelmuth** [comment]
I guess you're referring to https://maven.apache.org/plugins/maven-eclipse-plugin/configure-workspace-mojo.html ? 
This one would still require the style rules to be somewhere 👼

**Comment by rbri** [comment]
I think more in this direction https://stackoverflow.com/questions/984778/how-to-generate-an-eclipse-formatter-configuration-from-a-checkstyle-configurati.

Looks like there is a problem with the current version of the plugin but there is some hope https://github.com/checkstyle/eclipse-cs/issues/107

**Comment by rbri** [comment]
Looks like there is some progress on the issue. Let us test (and document) if the next eclipse-cs release is out.

**Comment by rbri** [comment]
looks like we have to wait for version 8.36.0

**Comment by rbri** [comment]
Have checked this again, it seems to work now (even if the feature is declared as experimental).

![image](https://user-images.githubusercontent.com/2544132/160082946-8ed05b0b-e27d-4cbf-86fd-751865978e4c.png)

On the project property dialog select checkstyle and check the option on the right to generate the configs. Then enable to code style and formatter setting by importing them.
