### ISSUE TITLE
kotlin and android support?

### ISSUE THREAD

**Issue by unicornlox** [HtmlUnit/htmlunit#219]
Can this library be used in Kotlin language with the android system without any problem?

**Comment by rbri** [comment]
Not sure, at least i have not tested this at all.

But please try and report any findings. If possible i will fix the issues.

**Comment by unicornlox** [comment]
Thank you very much for your interest.

**Comment by udittmer** [comment]
I don't see how it could work, given that quite a few source files import java.awt classes - which don't exist on Android. There are ways of using AWT classes on Android (by using https://github.com/andob/android-awt, for example), but it'd be a hack.

**Comment by rbri** [comment]
please use https://github.com/HtmlUnit/htmlunit-android.
