### ISSUE TITLE
Can't Click Submit Button using HtmlUnit in Java

### ISSUE THREAD

**Issue by Ulico** [HtmlUnit/htmlunit#225]
I  am trying to log into a page using HtmlUnit as a headless browser. I've gotten to the point of this URL (https://learn.illinois.edu/auth/saml2sso/gateway.php), and after clicking login I need to input my username into a text input and my password into a password input. Finally, there is submit input that would allow me to proceed to the next URL on a normal browser. I can input my username and password just fine, but I have not been able to proceed to the next URL. Here is what my code looks like for this part:

```Java
final HtmlForm loginForm = page.getForms().get(0); 
final HtmlTextInput netID = loginForm.getInputByName("j_username");     
netID.type(username);  
final HtmlPasswordInput password = loginForm.getInputByName("j_password");
password.type(password);
final HtmlSubmitInput submit = loginForm.getInputByValue("Login");
page = submit.click();
```
This does not proceed the same way it would on a regular browser. I'd take any suggestions or help to make this work, thanks!

**Comment by twendelmuth** [comment]
Hm I don't even see the two inputs you're referencing in the code.
Are you logging potential javascript errors?
Can you confirm that an request is sent when `submit.click()` is executed - if so the response might tell you something.

**Comment by Ulico** [comment]
It's the page after pressing NetID Login. I'll let you know about the other stuff. Do javascript errors appear in the console by default? And can you explain how I would confirm the request? Sorry, I'm a bit new to this.

**Comment by twendelmuth** [comment]
In theory it should log the javascript errors. But honestly I've always a hard time getting the log configuration correct for htmlunit. I'm using something like this:

```
public class MyHtmlUnitDriver extends HtmlUnitDriver {
//init loggers, other things, etc

	public MyHtmlUnitDriver() {
		new WebConnectionWrapper(getWebClient()) {
			@Override
			public WebResponse getResponse(WebRequest request) throws IOException {
				WebResponse response = super.getResponse(request);
				LOGGER.info("request {}, got response {}", request,	response.getStatusCode());
				return response;
			}
		};
		getWebClient().setJavaScriptEngine(new JavaScriptEngine(getWebClient()) {

			@Override
			protected void handleJavaScriptException(ScriptException scriptException, boolean triggerOnError) {
				LOGGER.info("Got javascript exception, could be that something is not working correctly", scriptException);
			}

		});
	}
}
```

**Comment by Ulico** [comment]
Sorry quick question, what do I put for LOGGER? This doesn't work for me, I'm using Eclipse by the way! Thank you so much for your help!

**Comment by twendelmuth** [comment]
Any Logging Framework that you use ... or `System.out.println` if you have to ;-) (and then scriptException.printStackTrace() instead of logging it).

**Comment by Ulico** [comment]
Ok, so I ran the code listed in my original post and added logging for javascript errors and requests. I've attached the console file, there's a lot there:
[console (1).log](https://github.com/HtmlUnit/htmlunit/files/5214833/console.1.log)

**Comment by twendelmuth** [comment]
Okay that's difficult too pinpoint since the error is in the minified version of jQuery.
Could you modify the code so that we're loading the uncompressed version of jQuery to get an better idea on which line the code has issues?

```
	            public WebResponse getResponse(WebRequest request) throws IOException {
	                if (request.getUrl().toString().equals("https://discovery.illinois.edu/wayf/js/jquery.js")) {
	                    request.setUrl(new URL("https://code.jquery.com/jquery-1.11.2.js"));
	                }
	                
	                WebResponse response = super.getResponse(request);
	                LOGGER.info("request {}, got response {}", request, response.getStatusCode());
	                return response;
	            }
```

**Comment by rbri** [comment]
@Ulico will close this as outdated - sorry for not working on this.
Please open a new one if you still have problems.
