### ISSUE TITLE
DefaultCssErrorHandler class logged to stdout

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#226]
I couldn't yet figure out where but at some place there must be some sort of debug logging left, I see a couple of

```
com.gargoylesoftware.htmlunit.DefaultCssErrorHandler@54478411
```

in my console output. Looks like some `System.out.println(someObject)`.

HtmlUnit `2.43.0` - hmtlunit-driver `2.43.1`.

/edit: even with `SilentCssErrorHandler` in place

**Comment by twendelmuth** [comment]
https://github.com/HtmlUnit/htmlunit/pull/215 :)

**Comment by black-snow** [comment]
https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/htmlunit/htmlunit/2.44.0-SNAPSHOT/ from Sep 6th fixes this indeed - thanks!
