### ISSUE TITLE
NullPointerException with javaScriptEnabled=false

### ISSUE THREAD

**Issue by dhcode** [HtmlUnit/htmlunit#227]
Exception: 
Caused by: java.lang.NullPointerException
	at com.gargoylesoftware.htmlunit.html.HtmlInput.executeOnChangeHandlerIfAppropriate(HtmlInput.java:509)
	at com.gargoylesoftware.htmlunit.html.HtmlCheckBoxInput.setChecked(HtmlCheckBoxInput.java:122)

Reproduce:
* Create a WebClient with the constructor option javaScriptEngineEnabled=false.
* Load a page with an Checkbox
* Set the checkbox to checked

Location: https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlInput.java#L509

It seems like engine is null in this case:
```
        final AbstractJavaScriptEngine<?> engine = htmlElement.getPage().getWebClient().getJavaScriptEngine();
        if (engine.isScriptRunning()) {
            return page;
        }
```

**Comment by rbri** [comment]
Thanks for the report, will try to make a new snapshot with a fix soon.

**Comment by rbri** [comment]
Made a new snapshot build available - please try and report your results.

**Comment by dhcode** [comment]
Thank you very much. I tried the snapshot version with javaScriptEngineEnabled=false and my test case works now without any Exception.

**Comment by rbri** [comment]
Thanks for the feedback - enjoy using HtmlUnit.
