### ISSUE TITLE
Polyfill webcomponentjs is not supported 

### ISSUE THREAD

**Issue by bp-alex** [HtmlUnit/htmlunit#23]
HtmlUnit does not support web pages that render Polyfill components.

This bug was originally reported in [SourceForge Issue 1930](https://sourceforge.net/p/htmlunit/bugs/1930/) and then [SourceForge Issue 2005](https://sourceforge.net/p/htmlunit/bugs/2005/).

The following minimal test (with HtmlUnit 2.34.1) illustrates the issue.

```java
import static com.gargoylesoftware.htmlunit.BrowserVersion.BEST_SUPPORTED;
import com.gargoylesoftware.htmlunit.NicelyResynchronizingAjaxController;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import java.io.IOException;
import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.assertThat;
import org.junit.Test;

public final class PolymerTest {

  @Test
  public void homePage() {
    try (final WebClient wc = new WebClient(BEST_SUPPORTED)) {
      wc.setAjaxController(new NicelyResynchronizingAjaxController());

      final HtmlPage result = wc.getPage(
          "http://webcomponents.github.io/hello-world-polymer/bower_components/hello-world-polymer/");

      wc.waitForBackgroundJavaScript(10000);
      wc.waitForBackgroundJavaScriptStartingBefore(10000);

      assertThat(result.asText(), containsString("Hello Unicorn :)"));

    } catch (final IOException ex) {
      throw new IllegalStateException(ex);
    }
  }
}
```

**Comment by rbri** [comment]
Sorry Ben for not working that much on your issue so far. But i'm the only one working on this project and i'm doing all the work in my spare time.
Any contributions are welcome....

Have done a look at this (again) and the next step to solve this is to support html includes. Have to read the spec and look if this is possible.
If you like you can have a look at my [twitter](https://twitter.com/HtmlUnit) page - will try to post regular updates there.

**Comment by Zephias** [comment]
Not sure if these issues are prioritized by how many people are encountering the problem, but I am seeing this issue as well. I have an app that used to be working with a website, but they updated their system to use polyfill and my app no longer functions.

I understand that you are the only one working on this project, so kudos to you! I hope you can find time to figure out this issue

**Comment by rbri** [comment]
Have added a test case for this (com.gargoylesoftware.htmlunit.libraries.PolymerWebComponentsTest)

**Comment by rbri** [comment]
Was a log way but with version 3.0.0 the simple PolymerTest passes.
