### ISSUE TITLE
driver.get(urlstring) prints out DefaultCssErrorHandler object into console

### ISSUE THREAD

**Issue by Cherubrine** [HtmlUnit/htmlunit#230]
I am working on a webscaper and as I am running ~30-100 threads, my console consists mostly of these lines:
com.gargoylesoftware.htmlunit.DefaultCssErrorHandler@6b15b6d8

I already attached the source code of htmlunit to the jar in my IDE but I havent found the reason while debugging.
It appears to print it out while being in the getPage method.

Is there a way to remove that?

The only way I found is to do System.setOut(null), but this disables everything and I still need some other outputs.

**Comment by twendelmuth** [comment]
See #226  #215 
Your options right now are:
- Downgrade to 2.42.0
- Upgrade to 2.44-SNAPSHOT

**Comment by rbri** [comment]
Maybe i will do a release tomorrow - will close this.

Thanks for the report.
