### ISSUE TITLE
TypeError: Cannot find default value for object for functions of DedicatedWorkerGlobalScope

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#233]
I added following test in DedicatedWorkerGlobalScopeTest:
```java
    @Test
     public void functionDefaultValue() throws Exception {
        final String html = "<html><body><script>\n"
            + "try {\n"
            + "  var myWorker = new Worker('worker.js');\n"
            + "  myWorker.onmessage = function(e) {\n"
            + "    alert('Received: ' + e.data);\n"
            + "  };\n"
            + "} catch(e) { alert('exception'); }\n"
            + "</script></body></html>\n";

        final String workerJs = "postMessage('func='+self.addEventListener);";

        getMockWebConnection().setResponse(new URL(URL_FIRST, "worker.js"), workerJs);

        loadPageWithAlerts2(html, 20000);
    }
```
The worker script fails when trying to execute 'func='+self.addEventListener. It can not convert the addEventListener to String. I checked a bit and found the function in JVM is created as a FunctionObject in JavaScriptEngine which doesn't have a default value. However, 'func='+windows.addEventListener executes without problem in non-worker script. It seems windows.addEventListener and DedicatedWorkerGlobalScope.addEventListener is defined differently. According to the output windows.addEventListener is a NativeFunction but I have not found where windows.addEventListener is defined yet.

The same test runs in real browser and outputs: 
```
func=function addEventListener() {
    [native code]
}
```

**Comment by rbri** [comment]
addEventListener is inherited from EventTarget - looks like the setup of DedicatedWorkerGlobalScope is not correct. Will have a look.

**Comment by RuralHunter** [comment]
I can see EventTarget.addEventListener is defined [here](https://github.com/HtmlUnit/htmlunit/blob/3810fbd4c2cb70ecdd977b6736cd553ba7adfd88/src/main/java/com/gargoylesoftware/htmlunit/javascript/JavaScriptEngine.java#L626). Not sure if window.addEventListener is defined separately or not.

**Comment by rbri** [comment]
Please try the latest snapshot

**Comment by RuralHunter** [comment]
Thanks, it works now!

**Comment by rbri** [comment]
Thanks for the testcase and the test.
