### ISSUE TITLE
Object() constructor fails for non-extensible functions

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#234]
Test case:
```javascript
            var a=JSON.stringify;
            Object.preventExtensions(a);
            console.log("a.isExtensible="+Object.isExtensible(a));
            var b=Object(a);
            console.log(b);
            console.log(a===b);
            console.log("b.isExtensible="+Object.isExtensible(b));
```
The code runs in real browser but fails at 'Object(a)' in htmlunit with Exception: com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot add properties to this object because extensible is false. 
I traced the code and it seems rhino checks if the object is extensible when setting prototype in constructor or getting prototype([here](https://github.com/mozilla/rhino/blob/abb8f56abe8df6902f6e3429fe059d1b7fe02861/src/org/mozilla/javascript/BaseFunction.java#L399) and [here](https://github.com/mozilla/rhino/blob/abb8f56abe8df6902f6e3429fe059d1b7fe02861/src/org/mozilla/javascript/IdFunctionObject.java#L91)) but real browser doesn't.

**Comment by rbri** [comment]
PR for Rhino is on the way

**Comment by rbri** [comment]
Made a new core-js snapshot build - please test.

**Comment by RuralHunter** [comment]
It works. Thanks!
