### ISSUE TITLE
HtmlUnitDriver a page is not loading properly but other do

### ISSUE THREAD

**Issue by Uceef94** [HtmlUnit/htmlunit#236]
I'm facing a problem with HtmlUnitDriver which is that the following page ([link](https://www.nakedcph.com/)) doesn't load properly, but other pages do.
```
HtmlUnitDriver driver = new HtmlUnitDriver(BrowserVersion.CHROME) 
        {
            protected WebClient modifyWebClient(WebClient client)
            {
                final DefaultCredentialsProvider credentialsProvider = new DefaultCredentialsProvider();
                credentialsProvider.addCredentials(username, password, ip, port, AuthScope.ANY_REALM);
                client.setCredentialsProvider(credentialsProvider);
                return client;
            }
            
        };

driver.setJavascriptEnabled(true);

driver.get(website.getRegisterUrl());

System.out.println(driver.getPageSource());
```

This is what I'm getting with "driver.getPageSource()". I had to shorten the value of src since it has 114616 characters.
```
        <img id="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU...AAAAAAAgPAIAAAAAAAAIjwAAAAAAAIDwCAAAAAAAAAiPAAAAAAAAwEX0PwMAIrYj8Sz00rEAAAAASUVORK5CYII="/>
      </div>
    </div>
  </body>
</html>
```
Any help would be greatly appreciated and thank you for your time!

**Comment by rbri** [comment]
Closed without a comment? Is this problem solved?

**Comment by Uceef94** [comment]
I apologize for not leaving a comment, I was going to once I was sure the problem is solved. But currently I'm not sure if it was a problem at first place, because by calling the same page using HtmlUnit and not HtmlUnitDriver the `page.getWebResponse().getContentAsString()` returns the same result but when calling `page.asText()` it shows the content of the page as it should be shown and nothing is missing. I think this might be happening because of the large size of the img value.

I've left a reply to your comment on stackoverflow concerning the recaptcha couldn't load problem. I think you might have seen it, in case you didn't :
> I noticed that after removing client.getOptions().setDoNotTrackEnabled(true); and client.getOptions().setGeolocationEnabled(false); the problem disapeared but I won't say it's the final solution because the problem is there again sometimes, so I guess that recaptcha has something to do with the tracking.

I had to switch back to HtmlUnit because it starts faster than HtmlUnitDriver under a proxy, but now I'm facing another problem with the same website. I opened a new question on stackoverflow ([Link](https://stackoverflow.com/questions/64107793/htmlunit-enabling-cookies)). 

Please let me know if I should open a new issue about it with more details.

Thank you for your time!
