### ISSUE TITLE
TypeError: Cannot modify readonly property: constructor

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#238]
Test case:
```javascript
            "use strict";
            var e = Promise.resolve(1);
            e.constructor = {};
            console.log('done');
```
In real browser, the script runs fine with both strict and non-strict mode. In htmlunit, the script runs with non-strict mode but fails with strict mode.

**Comment by rbri** [comment]
Will this ever end? :-)
As always thanks for the report - will require some time to nail down the problem.

**Comment by RuralHunter** [comment]
I'm sorry it won't end shortly. :) I'm tracing a complex web page and trying to nail down those js errors.
But please always take your time and no hurry.

**Comment by rbri** [comment]
have added some tests for this

    ScriptableObjectTest
        ctorChangeableHasNoEffectForSealed()
        ctorChangeableHasNoEffectForSealedStrict()
        ctorChangeableHasNoEffectForTypeOf()
        ctorChangeableHasNoEffectForTypeOfStrict()
        ctorNotChangeableForPrimitives()
        ctorNotChangeableForPrimitivesStrict()

**Comment by RuralHunter** [comment]
I found the problem is because constructor is defined as read only [here in rhino](https://github.com/mozilla/rhino/blob/49fa79350ea14df784fc08f07d3f44c9f3801f34/src/org/mozilla/javascript/FunctionObject.java#L300). Not sure if it is correct or not.

**Comment by vkadam** [comment]
Hello, first of all, thanks for creating and maintaining htmlunit 🙇 

If anyone can please provide some update on this, will be appreciated?

**Comment by rbri** [comment]
Thanks for pointing at this again. The original case works already, another improvement will land soon.

**Comment by RuralHunter** [comment]
Yes, I confirm this works now.

**Comment by rbri** [comment]
@RuralHunter i guess your special case works since the switch to the Rhino promises.

**Comment by rbri** [comment]
Reopened to track the general change of the upcoming property adjustment of constructors.

https://github.com/mozilla/rhino/pull/1285

**Comment by rbri** [comment]
hope this is fixed for other cases also
