### ISSUE TITLE
Problem with using htmlunit together with spring

### ISSUE THREAD

**Issue by pikonradNCU** [HtmlUnit/htmlunit#241]
I use the following code:

            java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(Level.OFF);
            java.util.logging.Logger.getLogger("org.apache.commons.httpclient").setLevel(Level.OFF);

            WebClient webClient = new WebClient(BrowserVersion.CHROME);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setJavaScriptEnabled(true);

            HtmlPage page = webClient.getPage("https://wp.pl");

When I use it in plain java application it works perfectly, but when I put it in springBootApplication it produce a lot of errors:
[htmlunitErrorWithSpring.txt](https://github.com/HtmlUnit/htmlunit/files/5307740/htmlunitErrorWithSpring.txt)

**Comment by twendelmuth** [comment]
I think the difference between the two is that Spring Boot properly configures the logging and the vanilla project most likely doesn't.

So I'd assume that the same errors are logged in the vanilla project but you don't see them.
Is the side by chance yours? It would be helpful to provide the error messages with unminified versions of the javascript.

**Comment by rbri** [comment]
@pikonradNCU can we close this?

**Comment by pikonradNCU** [comment]
I stop to use htmlunit, i just call post which is called by the page I wanted to analyze, and received direct data.
