### ISSUE TITLE
How to get pop-up window in htmlunit ?

### ISSUE THREAD

**Issue by diaowenyang** [HtmlUnit/htmlunit#243]
I use the following code:

    HtmlPage page1 = webClient.getPage("https://***");
    HtmlForm form = page1.getFormByName("form");
    HtmlTextInput user = form.getInputByName("User");
    user.setValueAttribute("username");
    HtmlPasswordInput pwd = form.getInputByName("Pwd1");
    pwd.setValueAttribute("password");
    HtmlParagraph paragraph = (HtmlParagraph) page1.getByXPath("//p[@class='txt_center b_mrgn9 t_mrgn9']").get(0);
    DomElement dom = paragraph.getFirstElementChild();
    HtmlPage page2 = dom.click();
    log.info("page2网页html:{}", page2.asXml());

page2 is same as page1.
In actual operation, after clicking the submit button, a new window pops up. How do I get the information of the pop-up window?

Thanks a lot!

![WechatIMG407](https://user-images.githubusercontent.com/18416111/95214158-923c3500-082a-11eb-9145-4403fdf649ab.png)

**Comment by Uceef94** [comment]
I think you will need to add a web window listener to your WebCLient.

To save the pop up window:
`final static LinkedList<WebWindow> windows   = new
LinkedList<WebWindow>();`

Add this to your WebClient:
webClient.addWebWindowListener(new WebWindowListener() {
			
			@Override
			public void webWindowOpened(WebWindowEvent event) {
				windows.add(event.getWebWindow());
			}
			
			@Override
			public void webWindowContentChanged(WebWindowEvent event) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void webWindowClosed(WebWindowEvent event) {
				// TODO Auto-generated method stub
				
			}
		});

And finally you can get the window as follow:
`
private static  HtmlPage getPopupPage()
        {
                WebWindow latestWindow = windows.getLast();
                return (HtmlPage) latestWindow.getEnclosedPage();
        }
`

More details [check this](http://htmlunit.10904.n7.nabble.com/how-to-access-popup-windows-td25226.html).

**Comment by rbri** [comment]
@diaowenyang does the WebWindowListener work for you - if yes please comment here an close this.

**Comment by rbri** [comment]
So response from the author will close this for now. Please give me a hint if you still have this problem.
