### ISSUE TITLE
jQuery (1.11.x) syntax error on attribute selector

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#246]
HtmlUnit 2.44.0

```js
$("input[id^=validToDate")
```

somehow throws an SyntaxError (thrown in jquery 1.11.0 minfied line 333:)

```js
throw new Error("Syntax error, unrecognized expression: " + a)
```

But it only happens with HtmlUnit. No issues with current FF or Chrome. Might be due to some fallback that jQuery does for HtmlUnit / Rhino because of some missing features?

Might be due to missing quotes and somehow this just works in actual browsers.
/edit: nope, no issues with a simple example - need to investigate further

```html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
	<div id="a"></div>
	
	<script>
		console.log($('div[id^=a]'))
		$('div[id^=a]').html('test')
	</script>
</body>
</html>
```

**Comment by rbri** [comment]
Ok, will wait for a reproducible case

**Comment by black-snow** [comment]
Wtf, I just realize that there's a bracket missing - gotta see tomorow if this is a c&p error or if that's actually the reason for all this,

**Comment by rbri** [comment]
?

**Comment by rbri** [comment]
Hope your are doing well these times - can we close this?

**Comment by black-snow** [comment]
seems like it, in fact, was a typo :)
