### ISSUE TITLE
HtmlFileInput how to upload a directory

### ISSUE THREAD

**Issue by zzzzzz886** [HtmlUnit/htmlunit#248]
Hi  
What should i do
`<input type="file" id="dir" name="file"  webkitdirectory mozdirectory />`

**Comment by rbri** [comment]
In the best case provide a PR ;-)

This is not supported at the moment, will have a look.
But if you like to help it will be great if you can provide testcases like we have in com.gargoylesoftware.htmlunit.html.HtmlFileInput2Test
com.gargoylesoftware.htmlunit.html.HtmlFileInputTest.

**Comment by rbri** [comment]
Have added some support for this, please wait for the next snapshot and check

**Comment by rbri** [comment]
released in between, will close this.
