### ISSUE TITLE
Not able to log in into website using HtmlUnit. Returning the same url after loginBtn.click()

### ISSUE THREAD

**Issue by ramkendre9818** [HtmlUnit/htmlunit#25]
HtmlPage resultPage = null;
try {
  HtmlPage signinPage = (HtmlPage)webClient.getPage("https://imeidb.gsma.com/imei/index");
  System.out.println("signinPage -----------------------------------" + signinPage.getUrl());
  HtmlForm form = signinPage.getFormByName("signIn");
  HtmlTextInput loginField = (HtmlTextInput)form.getInputByName("username");
  loginField.setValueAttribute(userName);
  System.out.println("Username :"+loginField);
  HtmlPasswordInput pwdField = (HtmlPasswordInput)form.getInputByName("password");
  pwdField.setValueAttribute(password);
  System.out.println("Password :"+pwdField);
  HtmlButtonInput loginBtn = (HtmlButtonInput)signinPage.getHtmlElementById("loginImg");
 // HtmlSubmitInput loginBtn = (HtmlSubmitInput)signinPage.getHtmlElementById("loginImg");
 // resultPage = (HtmlPage)loginBtn.click();

  WebWindow window = signinPage.getEnclosingWindow();
  resultPage = (HtmlPage)loginBtn.click();
  while(window.getEnclosedPage() == signinPage) {
      // The page hasn't changed.
      Thread.sleep(500);
  }
  // This loop above will wait until the page changes.
  signinPage = (HtmlPage) window.getEnclosedPage();
  System.out.println("2nd Page : "+signinPage.asText());

//  webClient.closeAllWindows();

  System.out.println("resultPage -----------------------------------" + resultPage.getUrl());
} catch (Exception e) {
  e.printStackTrace();
  logger.error(e, e);
  sendAlert(errorMessage);
}

**Comment by rbri** [comment]
Can you please provide credentials (via mail) to give me a chance to reproduce this.

**Comment by ramkendre9818** [comment]
Username : xxxx
Password : xxxx

Please help to resolve this issue.And don't share this credentials with
anyone.Thanks in advance.

**Comment by ramkendre9818** [comment]
I have tried this as well but it is giving me null.
loginBtn.fireEvent("onclick").getNewPage()

**Comment by rbri** [comment]
This produces the same result as the browser

```
        String uri = "https://imeidb.gsma.com/imei/index";
        String username = "****";
        String password = "****";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_60)) {
            // webClient.getOptions().setUseInsecureSSL(true);
            webClient.getOptions().setThrowExceptionOnScriptError(false);

            HtmlPage page = webClient.getPage(uri);
            // System.out.println("----------------");
            // System.out.println(page.asText());

            HtmlForm form = page.getFormByName("signIn");

            HtmlTextInput loginField = (HtmlTextInput) form.getInputByName("username");
            loginField.type(username);

            HtmlPasswordInput pwdField = (HtmlPasswordInput)form.getInputByName("password");
            pwdField.type(password);

            HtmlButtonInput loginBtn = (HtmlButtonInput)page.getHtmlElementById("loginImg");
            loginBtn.click();

            webClient.waitForBackgroundJavaScript(20000);
            page = (HtmlPage) page.getEnclosingWindow().getTopWindow().getEnclosedPage();

            System.out.println("----------------");
            System.out.println(page.asText());
        }
```

**Comment by ramkendre9818** [comment]
I have tried this earlier as well.
It gives org.apache.http.conn.ConnectTimeoutException: Connect to
imeidb.gsma.com:443 [imeidb.gsma.com/34.192.206.161,
imeidb.gsma.com/54.173.98.95] failed: connect timed out
error

**Comment by rbri** [comment]
Maybe you have a network related problem; any Proxy &| Firewall active on your system?

**Comment by rbri** [comment]
No further response - will close this.
