### ISSUE TITLE
Button Not Responding To Click

### ISSUE THREAD

**Issue by BrianJavaJazz** [HtmlUnit/htmlunit#255]
Hello!

I am using HtmlUnit driver version 2.44.0-jar-with-dependencies.jar.

I have a specific button that I am unable to click.  It appears to be an AngularJS button.

The test code navigates to a specific page, searches for a specific item, then attempts to click a button/checkbox associated with that item.  Once this button has been clicked, a Next button is shown on the page and the user can proceed to the next page.  

While ChromeDriver code can click the button, the HtmlUnit code cannot.  

Let me know if there are questions or pieces I may have left out.  I am happy to continue the discussion.  

Many thanks!
Brian

**Details:**  
I am rendering the driver by using:
```
   driver = new HtmlUnitDriver(BrowserVersion.CHROME);
   driver.setJavascriptEnabled(true);
```

**Can access  be provided to the site?**
Unfortunately, the code is part of a cybersecurity project so no access can be provided.  

**What does the code behind the button look like?**
Here is the button code. It is an angular button that is only shown if a search (above it on the page) reveals it.  
You can see some details about the functionality of the button inside the ng-class description.  

```
<button id="" ng-click="handleClick()" class="btn btn-sm btn-rounded v-middle m-r-sm ng-isolate-scope btn-white" ng-class="{ 'disabled': isDisabled(), 
                    'btn-white': !isSelected(), 
                    'btn-success': (isSelected() &amp;&amp; isAddButton()),
                    'btn-danger': (isSelected() &amp;&amp; isRemoveButton()) }" aria-checked="false" aria-disabled="false" aria-label="Handle Dangerous Goods" role="checkbox" type="button" sp-selected="false" sp-on-select="itemsCtrl.selectItem(item, null)" sp-on-deselect="itemsCtrl.deselectItem(item)" sp-label="Handle Dangerous Goods" style="">
  <i class="fa fa-check" ng-class="{ 'fa-check': isAddButton(), 'fa-times': isRemoveButton() }" role="presentation"></i>
</button>
```

**What is actually happening?**
The button is not being clicked, or is not responding to click event generated in the test code. 

Locating the button is not an issue.  Using Intellij I am able to watch the element with the Evaluate window, and can throw code at the page while sitting at a breakpoint.  

Testing by hand, and in a standard Chrome window with the Developer Tools and using standard Selenium code, 
I can see that when the button is clicked:
 * the class changes from btn-white to btn-success
 * aria-checked changes from false to true
 * selected changes from false to true

**What do I expect to happen?**
I expect to locate the button in some way, send a click event, and have the button respond by changing the above-noted details. 

**What is the process for getting the button displayed on the page?**
In the application: 

- click Manage User Access
- select a user by selecting a check box
- click Next button
- enter the entitlement to be requested for this user
- click Search button
- entitlement button is displayed

**TO NOTE:** After clicking the Search button, the focus stays on the Search button.  

**What have I tried?**
Lots and lots of things!  I have attempted many standard button clicking methodologies, starting from a simple button.click() method which traces back to the WebElement interface.  The click code comes from my Windows test code branch, and so is based on ChromeDriver.  Many other lines were written below to use specifically with HtmlUnit (you will recognize these.)

Other lines of code have been tested and deleted, but these are the remaining lines from 
tests.  **As stated, none of the following code works to click this button.**  In the code examples below, if it is commented out then it didn't work.  

```
        WebElement warp;  //defined earlier in the class
        Actions actions = new Actions(webDriver);
//        actions.click(warp);
//        actions.doubleClick();
//        actions.moveToElement(warp);
//        actions.click();
//        actions.click(warp);
```

This also does not work
`//        warp.sendKeys(Keys.RETURN);`

These cause errors...
```
//        actions.moveToElement(warp).perform();
//        actions.moveToElement(warp).click().perform();
```

In the first line below, webDriver is HtmlUnit driver
```
        JavascriptExecutor executor = (JavascriptExecutor) webDriver;
//        executor.executeScript("arguments[0].focus();", warp);
//        executor.executeScript("arguments[0].click();", warp);
```

Using WebDriverWaits to allow any javascript time to complete
```
//        new WebDriverWait(webDriver, 20).until(
//                ExpectedConditions.elementToBeClickable(warp)).click();
```

Attempts to cast the element to something else so that it can be manipulated by htmlunit:
```
        HtmlUnitWebElement fourteen = (HtmlUnitWebElement) webDriver.findElement(By.cssSelector("#ext-gen1035 > 
	div.sp-body-container > div.sp-body > div > div > div > div > div > div.ng-scope > 
	section:nth-child(2) > div.list-result-container.ng-isolate-scope > div > div.row.ng-scope > 
	div > div > div.panel-heading.bg-light.lter > div.header-cell > button"));
```

Render the client, an htmlpage so that I could get the element from a point
```
        WebClient client = new WebClient();
        client.getOptions().setUseInsecureSSL(true);
        HtmlPage htmlpage = null;
        String yurl = webDriver.getCurrentUrl();
        try {
            htmlpage = client.getPage(yurl);
        } catch (IOException e) {
            e.printStackTrace();
        }

//HtmlButton sixteen = (HtmlButton) htmlpage.getElementFromPoint(alsoUseless.getLocation().x, fourteen().y);
```
```

        HtmlForm form = (HtmlForm) htmlpage.getDocumentElement().
		getElementsByAttribute("button",  "class", "btn btn-sm btn-rounded 
		v-middle m-r-sm ng-isolate-scope btn-white");
```

**EDIT (10/15/2020):**
As I think about this, I am reminded that the button has no Id and no name.  I do not have access to change the source code.  Otherwise, I might be able to try something conventional such as:
```
HtmlPage htmlPage= webClient.getPage("http://localhost:8000/");
HtmlButton button = (HtmlButton) htmlPage.getElementById("buttonId");
button.click();
```
Adapting my code to this looks like:
```
        WebClient client = new WebClient();
        client.getOptions().setUseInsecureSSL(true);
        HtmlPage htmlpage = null;
        String yurl = webDriver.getCurrentUrl();
        try {
            htmlpage = client.getPage(yurl);
        } catch (IOException e) {
            e.printStackTrace();
        }

        HtmlButton buttawn = (HtmlButton) warp;
        try {
            buttawn.click();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

This code, in particular, throws up a:
`java.lang.ClassCastException: org.openqa.selenium.htmlunit.HtmlUnitWebElement cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlButton`

**EDIT (10/15/2020):**
As the casting does not work in the cases above, if there were an alternate way to get that button such as the following two, that would be excellent.  
`HtmlButton btn = (HtmlButton) htmlPage.getElementByCss("[ng-click*='handleClick'][class*='btn btn-sm btn-rounded v-middle m-r-sm ng-isolate-scope btn-white']"));`

`HtmlButton btn = (HtmlButton) htmlPage.getElementByCss("button[ng-click*='handleClick'][class*='btn btn-sm btn-rounded v-middle m-r-sm ng-isolate-scope btn-white']"));`

**Comment by BrianJavaJazz** [comment]
I have edited my post with some updated information and a suggestion, just for the record.

**Comment by BrianJavaJazz** [comment]
Hello!  Is there any other information I can provide?  

As mentioned in my edits on 10/15 it seems an enhancement to add method getElementByCss would be the best first start.  Hopefully that would return the element which could be cast to an HtmlButton which could then be clicked.  

Many thanks!  BJJ

**Comment by rbri** [comment]
Will have a look

**Comment by BrianJavaJazz** [comment]
Another comment..!..

The button is being rendered with AngularJS.  At one point in my testing I refreshed the page and tried to get htmlunit to see the button, but it did not.  The button is not invisible to htmlunit, but it cannot be clicked or acted upon for some reason. 

Thanks!

**Comment by rbri** [comment]
Hi Brian,
sorry for being not that responsible these days.

You wrote: Locating the button is not an issue. Using Intellij I am able to watch the element with the Evaluate window, and can throw code at the page while sitting at a breakpoint.

Does this mean you are able to see the HtmlUnit Element  (HtmlButton) inside the debugger. I like to make sure that the page update magic from Angular works inside HtmlUnit and creates the button.

**Comment by BrianJavaJazz** [comment]
Hi rbri, 

Sorry for the delay in my own response.  I was testing some theories for this discussion.  

First off: no problem with your availability.  I have looked through the issues list and it seems to be never ending.  I understand!

To clarify my statement: I can locate the button only with standard Selenium code, but that location strategy returns a WebElement which also does not react to a click.  

I cannot locate the button using HtmlUnit code because the only location strategy there is to use htmlPage.getElementById("buttonId").  Since the problem element is generated on the fly by Angular I don't have an Id to use.  This is why I suggested adding a method of getElementByCss.  

So to answer your question, currently I cannot see the element as an **HtmlButton** and casting attempts are not working.  


I can see it in other forms, though.  

If I do something like this:
`List<WebElement> buttonTags = webDriver.findElements(By.tagName("button"));`

...and the button will show up in the list, but it is on this list as an HtmlUnitWebElement.  If I get the button out of that list and apply a click() then nothing happens.  

I realize I have posted a _lot_ of data so please let me know if there is something that you don't see.  

Many thanks!

**Comment by skyhirider** [comment]
Maybe a long shot, but have you tried firing a click javascript even instead?  See #259 

I have a similar case where a button was not responding to clicks and the workaround was to use javascript. It was working for Firefox, not so much in HtmlUnit. The latest snapshot release should have the javascript events fixed, thanks to rbri.

The issue has some sample code you can try and implement.

**Comment by BrianJavaJazz** [comment]
> Maybe a long shot, but have you tried firing a click javascript even instead? See #259
> 
Thanks for the suggestion.  Much appreciated, skyhi!  I am using the jar-with-dependencies version.  Not sure if I can get that one through the pom, but will certainly hack at it.  I definitely need the jar since my deployment location will not be able to work otherwise.

**Comment by skyhirider** [comment]
I think there will be a new release of the library soon with the javascript event fixes incorporated, so you should be able to get it if you wait a bit. Or use the snapshot repository.

Is the page that is not working publicly accessible? I could try the event if it is.

**Comment by BrianJavaJazz** [comment]
To be clear, I was using the htmlunit-driver release that comes from Selenium-HQ, so there are other bits included which I need in my project.  Still, I'm going to attempt to cobble together a working "jar" for my test.  One never knows.

**Comment by skyhirider** [comment]
A new version of HTMLunit came out with the click fixes.

You could give it a try.

I could test it as well but would need to know a page that you are having issues with.

**Comment by BrianJavaJazz** [comment]
I see htmlunit-2.45.0 out on SourceForge, and version 2.44.0 on SeleniumHQ.  Any chance of getting a _htmlunit-driver-2.45.0-jar-with-dependencies.jar_ out on SeleniumHQ?  

EDIT: Just spotted this at https://github.com/SeleniumHQ/htmlunit-driver/releases  
Will test this out soon!

Thanks!

**Comment by BrianJavaJazz** [comment]
My apologies for disappearing!  Hard to believe it has been over a month.  What happened???

Ok, was able to pull down the 2.46 jar with dependencies and want to report that it is now able to click the subject button described in this issue.  Nice work!  I appreciate the time taken to get this working, and the kind suggestions of others in this thread.  Thank you!

Brian

**Comment by BrianJavaJazz** [comment]
Now appears to be working with Java 8.
