### ISSUE TITLE
HtmlUnit setJavaScriptTimeout returns immediately

### ISSUE THREAD

**Issue by sowjanyaboddeti** [HtmlUnit/htmlunit#256]
Eg URL: https://www.tdsinc.com/investor-relations/financials/quarterly-results/default.aspx

Using 2.44 HtmlUnit version, I have tried getting the entire page with webClient.getPage(url), the page was returned immediately though the following options are set:
`webClient.waitForBackgroundJavaScript(100000);
		webClient.setJavaScriptTimeout(20000);`

While, I added an explicit Thread.sleep(3000) //3s  after calling webclient.getPage(url) returned me the entire page. Is this expected or is there something I am missing out.

**Comment by rbri** [comment]
can you please check if page.getFrames() returns some frame windows

**Comment by sowjanyaboddeti** [comment]
Getting an empty list on calling page.getFrames() on the above URL

**Comment by rbri** [comment]
Ok, thanks, will try to reproduce your problem here

**Comment by rbri** [comment]
webClient.waitForBackgroundJavaScript(100000);

is not an option. You have to call this after getPage().

This code works here

        String url = " https://www.tdsinc.com/investor-relations/financials/quarterly-results/default.aspx";

        WebClient webClient = new WebClient(BrowserVersion.FIREFOX);

        HtmlPage page = webClient.getPage(url);
        webClient.waitForBackgroundJavaScript(20_000);

        System.out.println("#### ---- ");
        System.out.println(page.asText());
        System.out.println("#### ---- ");

**Comment by sowjanyaboddeti** [comment]
It is working now. Thanks for your help.
