### ISSUE TITLE
maven reference cannot be used

### ISSUE THREAD

**Issue by willdas** [HtmlUnit/htmlunit#257]
Below is my screenshot, the package cannot be imported.
<img width="635" alt="1" src="https://user-images.githubusercontent.com/26112941/96570360-dcc6b280-12fc-11eb-8e35-cfbd759324ad.png">
<img width="941" alt="2" src="https://user-images.githubusercontent.com/26112941/96570364-de907600-12fc-11eb-940c-74428f125281.png">
<img width="497" alt="3" src="https://user-images.githubusercontent.com/26112941/96570370-e05a3980-12fc-11eb-8dd9-929535bf3b78.png">

**Comment by willdas** [comment]
<img width="835" alt="4" src="https://user-images.githubusercontent.com/26112941/96570723-447cfd80-12fd-11eb-8f6a-bda1ef80d7c7.png">

**Comment by willdas** [comment]
Could not import package
It has troubled me for a long time, how to solve it
Thanks

**Comment by rbri** [comment]
Hi Willdas,

still have no idea why you are facing this problems. Might it be related to the JDK version you are using?
Maybe there is a hint in #10.

I use the maven dependency here in the HtmlUnit-driver project (eclipse) without any problems.

**Comment by willdas** [comment]
I use jdk1.8 and the development tool is idea.
Is it related to the development tool idea?
