### ISSUE TITLE
Thread interactions and ajax when running with Selenium?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#258]
How is HtmlUnit handling the threads when it is run via the driver?

I have been running it on an ajax heavy website according to the faq on your website (niceleysync ajax controller and waitForJs set to 150000) yes some aspects are still not working as expected.

I am now wondering if the main thread goes to sleep after a certain amount of time and does not respond to any followup ajax commands from the server.

Specifically, the parts where I either receive an attachment response in up to a minute after a page loads or a popup window are not working as expected. I am using Selenium waits.

I also seem to have issues when dispatching a click event (var event = new Event(click) and (element.dispatchEvent(event) via javascript.

The code above works perfectly in Firefox when ran in the console, but does not trigger when ran via the js executor in selenium.

Is there a way or a configuration option for the main thread to keep taking in the those requests? Or does it actually do so already?

And the attachment handling you implemented is perfect, sorry for not commenting on the issue earlier. It really makes downloading attachments a breeze!

**Comment by rbri** [comment]
Thanks for closing - is this solved?

**Comment by skyhirider** [comment]
It was related to the other two issues I opened - the click event not firing and the isAttachment triggering only after the full file has been downloaded. One has been closed, the other is on your enhancement list. So thought I would clean up after myself and close these.

I also used VisualVM to check how the threads are spawned.
