### ISSUE TITLE
Promise doesn't handle then-able result

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#260]
In real browser(Chrome), if the resolve function returns a then-able object(having then function), Promise.then handles it. But htmlunit fails to do so. Test case:
```javascript
           var thenable={
                then: function(onFulfill, onReject) { onFulfill('fulfilled!'); },
                value: 'aaa'
            };
            var p = Promise.resolve(1);
            var p1=p.then(function(value) {
                //console.log(value);
                return thenable;
            });
            p1.then(function(value) {
                console.log(value);
            });
```
chrome outputs 'fulfilled!' but htmlunit outputs the thenable object.

**Comment by rbri** [comment]
Hi Rural,
any chance to make a bunch of test cases as PR for this?

**Comment by rbri** [comment]
Maybe you can take com.gargoylesoftware.htmlunit.javascript.host.PromiseTest.resolveThenables() as starting point

**Comment by RuralHunter** [comment]
Ok, I will try.

**Comment by RuralHunter** [comment]
PR created.

**Comment by rbri** [comment]
Hi @RuralHunter,

hopefully i have fixed your case. Please check the tests i wrote and feel free to add more test cases if you think there is something missing.
Will make a new snapshot as soon as the CI build is green.

**Comment by rbri** [comment]
Have added on more test. 

Will close this - please open a new one if you have more problems. Will work on you other issues later.
Thanks for the contribution.
