### ISSUE TITLE
JSF/PrimeFaces Ajax: Script is not JavaScript (type: 'true/text/javascript')

### ISSUE THREAD

**Issue by ere-one** [HtmlUnit/htmlunit#268]
I'm using JSF with PrimeFaces 8.0 and trying to test it with Selenium HtmlUnitDriver. On some/all Ajax calls i see following warning:

**WARN  ScriptElementSupport:269 - Script is not JavaScript (type: 'true/text/javascript', language: ''). Skipping execution.**

It seems the same problem as described in issue 228.
I prepared a small project where it is possible to reproduce the warning. 

I already tested it with older PrimeFaces, HtmlUnitDriver and Java Versions but warning was still there.
I also debugged it, but was not able to find the sources for the strange 'true/' part from 'true/text/javascript'.

In the attached project the test case is actually passed, despite the above warning. But in my business application i have cases where some tests are not passed with HtmlUnitDriver but have no problems with ChromeDriver. So I think the reason must be the above warning.

Edit:
Was not able to attach a file to the this issue, so here ist the repo with the small project:
https://github.com/ere-one/primefaces-selenium-htmlunitdriver-problem

**Comment by rbri** [comment]
Will have a look, but this will require some time because i have far too many tasks on my desk.
Many thanks for the sample.

**Comment by rbri** [comment]
From a first analysis; the log entries are more or less expected. The root is jquery manipulating the scripts

    // Replace/restore the type attribute of script elements for safe DOM manipulation
    function disableScript( elem ) {
	elem.type = ( elem.getAttribute( "type" ) !== null ) + "/" + elem.type;
	return elem;
    }

    function restoreScript( elem ) {
	if ( ( elem.type || "" ).slice( 0, 5 ) === "true/" ) {
		elem.type = elem.type.slice( 5 );
	} else {
		elem.removeAttribute( "type" );
	}

	return elem;
    }

**Comment by rbri** [comment]
Back to this - have done some more research but from my point of view everything is ok. I can understand that this warning is confusing and browsers are not reporting this case as warning. Based on this i have change the level to debug - with the new version you will no longer see the warning.

Outside of the warning, the provided sample works like expected for me. The page gets changed like in the browser.

Can you please provide more details or better a sample of your real problems.
BTW: please try with the latest snapshot build, i have done some more fixes for Ajax requests.

**Comment by ere-one** [comment]
I'm out of the project and have no access to the code any more. We had some strange behaviours and all the time such warnings and it looked like they are related. IIRC, one of the strange things was with the PrimeFaces TabView component.

May be one of my previous colleagues will provide a better sample.

**Comment by rbri** [comment]
OK, thanks and sorry for being late on this. Will close this now. Please ask your colleagues to open new issues if they still facing problems.

Again thanks.
