### ISSUE TITLE
Huge number of responses when WebConnectionWrapper.getResponse is overridden and webClient.getPage() is called

### ISSUE THREAD

**Issue by sowjanyaboddeti** [HtmlUnit/htmlunit#269]
Created a WebConnectionWrapper and overridden getResponse() to see the count of responses and to ignore any 404 issues for .js or .img files.

When webClient.getPage(url) is called it is invoking getResponse more than 1000+ times for the below URL:
http://www.profuturo.mx/content/wps/portal/Grupo-Profuturo/Informacion-financiera

But on seeing the number of requests on chrome or any browser, it should be around 119. Is this expected because HtmlUnit is using Rhino Engine? Would we miss the webpage content if we try to parse it in parallel to getPage()

**Comment by rbri** [comment]
Sorry for working that late on this - looks like the page was changed and has new problems now.
Will close this - please open a new one if you still have problems (and you still use HtmlUnit ;-))
