### ISSUE TITLE
Custom default Accept-Language header will be ignored

### ISSUE THREAD

**Issue by jowerner** [HtmlUnit/htmlunit#27]
Recently, I had the need to switch to another browser language in the middle of my test case (en-US to de-DE). To this end, I programmatically configured an "Accept-Language: de-DE" header as a new default header at the web client hoping that this one would be sent with each request from now on. But I still see "Accept-Language: en-US" being transmitted over the wire.

**Comment by jowerner** [comment]
I wanted to provide a patch that fixes this problem, however, there is a test case that explicitly checks that a custom default Accept-Language header will be ignored (see WebClientTest.requestHeaderDoNotOverwriteExisting()). Now I wonder whether there is a reason for that or whether the test case is wrong here.

**Comment by rbri** [comment]
Hi Joerg, nice to see you still around. Provide your patch i will have a look. This header handling seems to be strange in some way. Hope we can fix it together.

**Comment by jowerner** [comment]
Alrighty! Pull request is on the way.

Not sure what to do with that test case. Since it is possible to override the Accept-Language header at web request level, it should probably be possible at web client level as well. If you agree we could simply delete that test case. All other specialties are already checked in tests right above and below that one.

**Comment by rbri** [comment]
Have merged parts of your PR, thanks a lot.
Test are also updated and some more documentation is also ready. Hope this will clarify this for the future.

Again thanks

**Comment by jowerner** [comment]
As always, thanks a lot for your swift support!

**Comment by rbri** [comment]
You are welcome, will make a new snapshot (or maybe a new release) version available during the next days.
