### ISSUE TITLE
HtmlUnit is not submiting form.

### ISSUE THREAD

**Issue by Szelwiga** [HtmlUnit/htmlunit#272]
So i'm trying to visit the website and fill sample form in it. After doing it manualy, the webpage is redirecting me to website with adress like this: *http://wklejto.pl/[number]*, what I want to do in following code is:
 - Writing something in form.
 - Submiting it.
 - Get the adress of webpage with uploaded text.
```
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.*;

public class Main{
	public static void main(String[] args) throws Exception {
		java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF);
		WebClient webClient=new WebClient(BrowserVersion.CHROME);
		webClient.getOptions().setUseInsecureSSL(true);
	        HtmlPage page=webClient.getPage("http://wklejto.pl/");
		HtmlElement samp=page.getElementByName("source20201129");//IT's updating daily in form: "source" + year + month + day
		HtmlForm form=page.getHtmlElementById("formwyslij");
		HtmlElement submit=form.getInputByName("submit");
		samp.click(); samp.type("It's Working"); submit.click();
		webClient.waitForBackgroundJavaScript(1000);
                page=(HtmlPage) webClient.getCurrentWindow().getEnclosedPage();
		System.out.println(page.getUrl());
		webClient.close();
	}
}
```
After running this code, the System.out.println(), prints:
```
http://wklejto.pl/index.php
```
instead of what i'm expecting:
```
http://wklejto.pl/[number of uploaded text]
```
Is it a bug? What am i doing in wrong way?

**Comment by rbri** [comment]
Sorry for being that late on this ....

At first i think it is no good idea to disable logging if something does not work - maybe there is a hint inside the logs helps you with your issues.

Have done some tests and it looks like there is some js-handler attached to the textarea that is required to finish before the click processes correctly.

This code works for me (maybe you have to increase the wait times depending on your machine)

        WebClient webClient=new WebClient(BrowserVersion.CHROME);
        webClient.getOptions().setUseInsecureSSL(true);

        HtmlPage page=webClient.getPage("http://wklejto.pl/");

        //IT's updating daily in form: "source" + year + month + day
        HtmlElement samp=page.getElementByName("source20201205");
        HtmlForm form=page.getHtmlElementById("formwyslij");
        HtmlElement submit=form.getInputByName("submit");

        // samp.click(); // no need to click, type triggers the required focus events
        samp.type("It's Working");
         // wait a bit to let the textarea onkey handler do there magic
        webClient.waitForBackgroundJavaScript(4_000);

        submit.click();
        webClient.waitForBackgroundJavaScript(1_000);

        // get the current page from the window
        page=(HtmlPage) webClient.getCurrentWindow().getEnclosedPage();
        System.out.println(page.getUrl());

        webClient.close();
