### ISSUE TITLE
ScriptElementSupport#onAllChildrenAddedToPage is slow due to not needed HtmlScript#toString

### ISSUE THREAD

**Issue by markusheiden** [HtmlUnit/htmlunit#277]
com.gargoylesoftware.htmlunit.html.ScriptElementSupport#onAllChildrenAddedToPage:
```
... new PostponedAction(element.getPage(), "Execution of script " + element)...
```
is very inefficient, because `element` (e.g. a HtmlScript) is rendered unnecessarily. This eats up all our CPUs, because it renders the whole HtmlScript in toString() in our case. I suggest to use e.g. `"Execution of " + element.getClass().getSimpleName()` instead or another more reduced string representation.

**Comment by rbri** [comment]
Good point - will have a look. Thanks.

Do you like to provide a PR?

**Comment by markusheiden** [comment]
@rbri I did a MR, but I am not sure, if there is no better description than the class name...

**Comment by rbri** [comment]
Hi @markusheiden,

thanks for the patch (and for pointing at this stupid impl). Have done a bit more for generating the description. Please check if this is ok for you or if we have to go with your simpler (and faster) solution.

Will make a new snapshot build available soon - as always check twitter for news.

**Comment by markusheiden** [comment]
Thanks, that looks perfectly fine. I had done it the same way, if I had been more into HtmlUnit.

**Comment by rbri** [comment]
OK, will be great to know how big the performance impact is.

**Comment by markusheiden** [comment]
I have no exact numbers, because I currently cannot test this on our test servers. But before the profiler showed 80% execution time just in the unnecessary rendering. Now the complete HTML parsing is below 50%.

**Comment by rbri** [comment]
Thanks, will close - hope to see more pr's from your side in the future :-)
