### ISSUE TITLE
HtmlUnit 2.34.1 Click() Issue

### ISSUE THREAD

**Issue by dermot-mctaggart-epl** [HtmlUnit/htmlunit#28]
I Have encountered an issue with the Click() method in HtmlUnit 2.34.1.
In the below code, the page = a.click(false, false, false, true, true, false); code will correctly redirect the page, whereas the a.click() method will not.
I have a range of WebScraping tools which use the standard .click() method that has worked in previous versions of HTMLUnit and was wondering why this method does not work in the current version.
I have encountered this issue a few times using the new version, the code below is just an example I came up with that was easily testable.

public class DropDownClickTest
{
	public static void main(String[] args) throws FailingHttpStatusCodeException, MalformedURLException, IOException, InterruptedException
	{
		WebClient wC = new WebClient();
		HtmlPage page = wC.getPage("https://www.mozilla.org/en-CA/");
		HtmlAnchor a  =page.getFirstByXPath("//a[@href='/en-CA/firefox/new/']");
		System.out.println(page.asXml());
		//Works!
		//page = a.click(false, false, false, true, true, false);
		//Doesnt
		page = a.click();
		Thread.sleep(10000);
		page = (HtmlPage) wC.getCurrentWindow().getEnclosedPage();
		System.out.println(page.asXml());
	}
}

**Comment by rbri** [comment]
The change for this was introduced more than 2 years ago in version 2.25.
> DomElement: .click() should does nothing when the element is not displayed.

Have done a check with your example and this works

```
        String uri = "https://www.mozilla.org/en-CA/";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_60)) {
            webClient.getOptions().setThrowExceptionOnScriptError(false);

            HtmlPage page = webClient.getPage(uri);

            System.out.println("----------------");
            HtmlAnchor a = page.getFirstByXPath("//a[@href='/en-CA/firefox/new/']");
            System.out.println(a.isDisplayed());
            System.out.println("----------------");

            HtmlAnchor menu = page.getFirstByXPath("//a[@href='/en-CA/firefox/']");
            menu.mouseOver();
            System.out.println(a.isDisplayed());
            System.out.println("----------------");

            a.click();
            webClient.waitForBackgroundJavaScript(1000);

            page = (HtmlPage) webClient.getCurrentWindow().getEnclosedPage();
            System.out.println("----------------");
            System.out.println(page.asText());
        }
```

This seems to be a common problem, will add at least some log output in case a click is ignored based on visibility.
