### ISSUE TITLE
Platform dependent EOL behaviour of DomNode.asText() makes it hard to use

### ISSUE THREAD

**Issue by atnak** [HtmlUnit/htmlunit#283]
# Summary

`DomNode.asText()` depends on `HtmlSerializer` which internally formats lines using [the value of `System.lineSeparator()` as the line separator](https://github.com/HtmlUnit/htmlunit/blob/2.45.0/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlSerializer.java#L581).

As an API interface, this behaviour of `DomNode.asText()` and `HtmlSerializer.asText()` may be ill-suited, since applications are required to take this into consideration any time they're working with values returned by these methods.

Moreover, I believe EOL style is a function of the output medium (be it a text file or an OS console) and perhaps not something that should be done in a library, this far from the presentation layer.

**Comment by rbri** [comment]
With version 2.48.0 we added DomNode#asNormalizedText() to address this and with 2.55 DomNode#asText() was removed. This is solved.
