### ISSUE TITLE
[Rhino] Error.stack lines are separated by CR LF on Windows where LF is expected

### ISSUE THREAD

**Issue by atnak** [HtmlUnit/htmlunit#284]
# Problem in brief

When HtmlUnit is run in Windows, `new Error().stack` contains lines are separated by `CR LF`.  However, major browsers separate lines using `LF` only.

The likely cause is Rhino's use of [`line.separator` when creating the stacktrace string](https://github.com/HtmlUnit/htmlunit-rhino-fork/blob/5ff6bb8a71c5762af692102278ceeffb94d688b2/src/org/mozilla/javascript/RhinoException.java#L228).

# Testing

The following JS code was used to test behaviour in Chrome/FF/Edge:

```js
console.log(new Error().stack.replace('\r', '\\r').replace('\n', '\\n'));
```

The following was used to test behaviour in IE 11:

```html
<html>
<head>
<script>
try {
  throw new Error()
} catch (e) {
  console.log(e.stack.replace('\r', '\\r').replace('\n', '\\n'));
}
</script>
</head>
</html>
```

# Extra

`line.separator` is used for various reasons in mozilla/rhino with currently [four places in total](https://github.com/mozilla/rhino/search?q=%22line.separator%22+-path%3Atestsrc%2F&type=code).

**Comment by rbri** [comment]
Sorry for being that late on this but there is far too much to do.

This should be fixed now. Please use the latest snapshot build (you need the latest core-js snapshot also) and try.

**Comment by atnak** [comment]
Oh wow, backwards compatibility!  I was wondering how that could be done.  Thanks, the changes look good.

**Comment by rbri** [comment]
Ok, will close this. Please open a new one if you still have problem.

Thanks again for your report.
