### ISSUE TITLE
Javascript seems to not run

### ISSUE THREAD

**Issue by Aaron2550** [HtmlUnit/htmlunit#285]
Hi, im trying to check if the login on the german learn-platform Lernsax.de is available, but i always get
`Your browser has JavaScript disabled.`
back from the site. The code im trying to use is:
```
WebClient webClient = new WebClient(BrowserVersion.CHROME);
webClient.getOptions().setJavaScriptEnabled(true);
HtmlPage page = webClient.getPage("https://www.lernsax.de/wws/9.php#/wws/100001.php");
```
I have also tried FIREFOX and none in `new WebClient(BrowserVersion.CHROME);` which yields the same result.
Im using version 2.46.0, no warnings or other messages pop up.

**Comment by rbri** [comment]
Will try to help you - but at the moment the page seems to be down

**Comment by Aaron2550** [comment]
it seems that theres a firewall that blocks requests from non-german IPs

**Comment by Aaron2550** [comment]
Using https://reqbin.com/

US: Operation timeout.
DE: Status: 200 (OK) Time: 145 ms Size: 1.09 kb

**Comment by rbri** [comment]
i'm in germany

**Comment by Aaron2550** [comment]
yeah it takes ~45 seconds to load the page, on the page it says "LernSax ist auf Grund einer Störung im Rechenzentrum nicht erreichbar."

**Comment by rbri** [comment]
Ok, site seems to be back, looks like a problem with the redirection done by the page. Will require some time to figure out what is going on here.

**Comment by Aaron2550** [comment]
Classes start in like 20 minutes. Don't expect anything... Tell me if I can help you in any way

**Comment by rbri** [comment]
Ok, found the problem - next step is to build some unit tests to reproduce this.

**Comment by rbri** [comment]
Hopefully i have a solution ready at the end of this week.

**Comment by rbri** [comment]
Ok, i think i have found the problem and the fix is commited. Will inform as usual via twitter if a new snapshot build is available. This usually requires some time because i have to run the whole test suite.

Please keep in mind you web page uses an iframe.

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX)) {
        // try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX, "localhost", 8888)) {
            webClient.getOptions().setUseInsecureSSL(true);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            HtmlPage htmlPage = webClient.getPage("https://www.lernsax.de/wws/9.php#/wws/100001.php");
            webClient.waitForBackgroundJavaScript(2_000);

            HtmlInlineFrame iframe = (HtmlInlineFrame) htmlPage.getElementById("main_frame");
            HtmlPage enclosedPage = (HtmlPage) iframe.getEnclosedPage();

            System.out.println();
            System.out.println("------------------------------------------------------");
            System.out.println(enclosedPage.asText());
            System.out.println("------------------------------------------------------");
            System.out.println();
            System.out.println(enclosedPage.asXml());
            System.out.println("------------------------------------------------------");
            System.out.println();
        }

**Comment by rbri** [comment]
Please use the latest SNAPSHOT build and also have a look at the code from my last comment.

Many thanks, feel free to open new issues if you have more problems.

**Comment by Aaron2550** [comment]
thanks, will check if it works tomorrow while im supposed to do school work :)
