### ISSUE TITLE
TextPage using HtmlUnit with Javascript not updated as expected

### ISSUE THREAD

**Issue by lrpowell** [HtmlUnit/htmlunit#286]
This is my first time using HtmlUnit, and I am having trouble getting back the updated page from the webClient.   The page text returned is only the original source in the .html file (invoked at start using getPage(url).
I also can only seem to get TextPage format and not convert to HtmlPage.  Maybe this is related to what I am doing wrong.

Here is my **Java Source**:
```
try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX)) {
				java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF);

				webClient.getCache().clear();
				webClient.getOptions().setCssEnabled(true);
				webClient.getOptions().setJavaScriptEnabled(true);
 
				webClient.setAjaxController(new NicelyResynchronizingAjaxController());
				webClient.getOptions().setThrowExceptionOnScriptError(true);			  

				   Page page = webClient.getPage(url);

				   WebResponse response = page.getWebResponse();//page
				   String content = response.getContentAsString();
				   
				   if (webClient.isJavaScriptEnabled())
					   System.out.println("web client enabled");
				   else
					   System.out.println("NO javascript enabled");
				   
				   Page page2 =  webClient.getWebWindows().get(0).getEnclosedPage();
				   List<TopLevelWindow> topWinList = webClient.getTopLevelWindows();
				   for (TopLevelWindow oneWin : topWinList ) {
					  System.out.println("window: "+ oneWin.getName());
				   }

				   webClient.waitForBackgroundJavaScript(1000); 
				   webClient.waitForBackgroundJavaScriptStartingBefore(10000);
			       				   
				   int tries = 5;  // Amount of tries to avoid infinite loop
				   while (tries > 0) {
				       tries--;
				       try {
				       synchronized(page) { // page
				           page.wait(2000);  // How often to check - page
				       }
				       } catch(Exception ex) {
				    	   System.out.println("exception waiting for page"+ex);
				       }

				       if (page.getWebResponse().getContentAsString().contains("Hello")) {
						   System.out.println ("found Hello"+page.getWebResponse().getContentAsString());
				    	   break;
				       }
				       
			page2 = webClient.getWebWindows().get(0).getEnclosedPage();				       			       
				       if (	page2.isHtmlPage())
				    	   System.out.println("HTML page");
					   }
		            final HTMLParser htmlParser = webClient.getPageCreator().getHtmlParser();		    
		            final WebWindow webWindow = webClient.getCurrentWindow();
		            
		            String pageStr2 = page.getWebResponse().getContentAsString();
                            boolean hasUpdate = pageStr2.contains("Hello");
			   System.out.println("hasUpdate:"+hasUpdate);   

			       webClient.close();
			}
```

On running always generates: hasUpdate:false

__
My 2 main questions are:
- why is my content from the server not available in htmlPage format?
- why is my response from server not showing the updated page?

I can go to the same html URL in my browser and go into debug and see the JavaScript has been run there.

> http://9.5.x.y:2004/SystemiNavigator/com/ibm/as400/pt/dojoChart/DojoGraphScriptLauncher.html?packageId=IBM_CS&perspectiveId=P_WAITS_OVERVIEW&perspectiveName=WaitsOverview&collectionName=TEST1&collectionLib=PDI&collectionType=Collection Services File Based Collection&fileLevel=48&startTime=Aug 26, 2020 2:26:32 PM&endTime=Aug 27, 2020 12:00:02 AM&systemName=A405BP3 &release=V7R3M0&collectionFormat=*CSFILE&basePerspId=         

When I use page.getWebResponse().getContentAsString() it returns the same text as is in the original .html file.

I feel like I have tried all the tips I have found on waiting and setting options. I am obviously missing something...

For getting the results in htmlPage format, If I try to convert it to htmlPage, I get this error:

> Exception in thread "main" java.lang.ClassCastException: com.gargoylesoftware.htmlunit.TextPage cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlPage at com.ibm.PDIScript.runDojoChart.export(runDojoChart.java:395) at com.ibm.PDIScript.runDojoChart.main(runDojoChart.java:154)

**HTML source:**
```
<body class="claro histTheme">
<!--catch JavaScript errors for later retrieval -->
<!-- to capture use: ((JavascriptExecutor) driver).executeScript("return window.jsErrors");-->
<script type="text/javascript">
window.jsErrors = [];
window.onerror = function(errorMessage) {
  window.jsErrors[window.jsErrors.length] = errorMessage;
}
</script>

<!-- set Dojo configuration, THEn load dojo.js -->
<script>
    var dojoConfig = {
        async: true,
        has:{'dojo-bidi': true},
        //dojoBlankHtmlUrl: location.pathname.replace(/\/[^/]+$/, "") + "/blank.html",
        packages: [{
            name: "hist",
            location: "/SystemiNavigator/com/ibm/as400/pt/hist"
        },{
            name: "dojoChart",
            location: "/SystemiNavigator/com/ibm/as400/pt/dojoChart"
        }
        
        ]
    };
</script>
<!-- load dojo FIRST -->
<script type="text/javascript" src="/auiruntime8106/dojo/dojo/dojo.js" ></script>
<script>
    require([
        "dojo/parser",
        "dojo/ready",
        "hist/utils",
        "dojoChart/DojoGraphScript",
        
        "dijit/layout/BorderContainer",
        "dijit/layout/ContentPane",
        "dijit/TitlePane",
        "dojox/layout/TableContainer",
        "dijit/form/TextBox",
        "dijit/form/CheckBox",
        "dijit/form/Textarea",
        "dijit/form/NumberSpinner",
        "dijit/form/FilteringSelect",       
        "dijit/form/TimeTextBox",
        "dijit/form/DateTextBox",
        "dijit/form/Button",        
        "hist/widget/SelectableChart",
        "dijit/form/Button",
        'dojo/dom', 'dojo/on', 'dojo/domReady!'
    ], function(parser,ready,utils,DojoGraphScript) {
        
        ready(function(){
        // Invoke the dojo/parser to process the dijit layout widgets specified in the body declaratively
        parser.parse();
        var rtl = utils.isRTL();
        if(rtl){
            dijit.byId("mainBC").dir = 'RTL';
            dojo.style(dijit.byId("mainBC").domNode,"direction","rtl");
            dijit.byId("TitleBar").dir = 'RTL';
            dijit.byId("titleLeftPane").dir = 'RTL';
            dijit.byId("titleCenterPane").dir = 'RTL';
            dijit.byId("titleRightPane").dir = 'RTL';
            dijit.byId("titleRightActionPane").dir = 'RTL';
            dijit.byId("leftPane").dir = 'RTL';
            dijit.byId("leftTopPane").dir = 'RTL';
            dijit.byId("leftTopTitlePane").dir = 'RTL';
            dijit.byId("leftBottomPane").dir = 'RTL';

            var link2 = document.createElement("link");
            link2.type = "text/css";
            link2.rel = "stylesheet";
            link2.href = "/auiruntime8106/dojo/gridx/resources/claro/Gridx_rtl.css";
            document.getElementsByTagName("head")[0].appendChild(link2);
        } else {
            var link2 = document.createElement("link");
            link2.type = "text/css";
            link2.rel = "stylesheet";
            link2.href = "/auiruntime8106/dojo/gridx/resources/claro/Gridx.css";
            document.getElementsByTagName("head")[0].appendChild(link2);
        }
        
        var pGraph = new DojoGraphScript({isRTL: rtl});
        
        pGraph.postCreate();
        console.debug("pGraph.postCreate()");   
        
        });
    });
</script>
    
<!-- load dojo -->  
<div data-dojo-type="dojoChart/DojoGraphScript" ></div> 
   <div data-dojo-type="dijit.layout.BorderContainer" id="mainBC" data-dojo-props="region:'center'">
        <div data-dojo-type="dijit.layout.BorderContainer" id="TitleBar" data-dojo-props="region:'top'" style="height:30px; background-color:#cce6ff;">        
            <div data-dojo-type="dijit.layout.ContentPane" id="titleLeftPane" data-dojo-props="region:'leading'" style="width:140px;padding:0px;background-color:#cce6ff; border:none;overflow:hidden;">
                 <div id="ActionButton" style="padding:0px;"></div>
           </div>
           <div data-dojo-type="dijit.layout.ContentPane" id="titleCenterPane" data-dojo-props="region:'center'" style="padding:0px;background-color:#cce6ff; border:none;">
                   <div id="Title" style="padding-top:6px;"></div>
           </div>
           <div data-dojo-type="dijit.layout.ContentPane" id="titleRightPane" data-dojo-props="region:'trailing'" style="width:30px;padding:0px;background-color:#cce6ff; border:none;"></div>
           <div data-dojo-type="dijit.layout.ContentPane" id="titleRightActionPane" data-dojo-props="region:'trailing'" style="width:40px;padding:0px;background-color:#cce6ff; border:none;"></div> 
        </div>  
        <div data-dojo-type="dijit.layout.BorderContainer" id="leftPane" data-dojo-props="region:'center',splitter:'true'">
             <div data-dojo-type="dijit.layout.ContentPane" id="leftTopPane" data-dojo-props="region:'top'" style="height:150px;border:none;">
                <div data-dojo-type="dijit.TitlePane" id="leftTopTitlePane">
                    <div id="filtersTableContainer" style="width:925px;overflow:auto;"></div>
                    <div id="buttonsContainer"></div>
                </div>  
            </div>
            <div data-dojo-type="dijit.layout.ContentPane" id="leftBottomPane" data-dojo-props="region:'center'" style="padding:0px;">
                <!-- id="selectableChartContainer" style="width:100%;height:100%;" -->
                <div id="chartGridContainer" style="width:100%;height:100%;overflow-y:auto"></div>
            </div>
         </div>
    </div>
</body>
</html>
```

**DojoGraphScript.js constructor and postCreate:** 
```
			constructor: function(args  ){ 
				var urlParms = utils.getUrlParms();
		    this.packageId = urlParms.packageId;
			this.perspectiveId = urlParms.perspectiveId;
			this.basePerspId = urlParms.basePerspId;
			this.perspectiveName = urlParms.perspectiveName;
			this.colName = urlParms.collectionName.trim();
			this.library = urlParms.collectionLib.trim();
			this.colType = urlParms.collectionType.trim();
			this.colFormat = urlParms.collectionFormat.trim();
			this.fileLevel = urlParms.fileLevel;
			this.startTime = urlParms.startTime;
			this.endTime = urlParms.endTime;
			this.systemName = urlParms.systemName.trim();
			this.release = urlParms.release;
			this.GUIInterval = urlParms.GUIInterval;
			this.collectionInt = this.GUIInterval;
				console.log("collectionName:"+this.colName+ " type:"+this.colType+" format:"+this.colFormat);
					if(this.GUIInterval == undefined || this.GUIInterval == "---"){
					this.GUIInterval = -1; 
				}
				this.viewType = 'dojo';
				this.viewNum = 1;			
					console.log("Constructor dojographscript.js");
				this._createNewPage();
			lang.mixin(this, args);
			},

			/** postCreate - function called after DOM has been created" +
			 * This is where it all begins.
			 */
			postCreate: function(){
				console.log("B postCreate dojographscript.js");
				dom.byId("buttonsContainer").innerHTML = "Hello World";
			
				var args = '{action: "helloWorld.12", perspectiveId: this.perspectiveId}';
				this.processHelloWorld(args);			
			},
```

**Comment by rbri** [comment]
Hi Lora,

thanks for taking the time to write down all the details. I have no general answer but i hope we can work together on finding a solution.

So far i'm not sure i really understand what you like to do - let me write here my understanding

    Page page = webClient.getPage(url);

This is similar to open the page in the browser. Sometimes the pages have dynamic parts updated async. Because of this it is a good idea to add some wait..

    Page page = webClient.getPage(url);
    webClient.waitForBackgroundJavaScriptStartingBefore(10_000);

And if the async stuff reloades the whole page (redirects to another url) you have to reget the page.

    Page page = webClient.getPage(url);
    webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
    page = page.getEnclosingWindow().getEnclosedPage();

After that, the page (yes the var) should contain the same content as the browser.

If you do something like

    WebResponse response = page.getWebResponse();//page
    String content = response.getContentAsString();

than you are dealing with the WebResponse. This response is really the stuff sent from the server as response for your page request (the GET). This is never changed by e.g. Ajax. If you like to get an idea of the current state of the page you have to use

    System.out.println( page.asXML() );
    System.out.println( page.asText() );

Hopefully by doing this you will get the content you expect in your page. In some situations a more complicated wait code is required but lets see.

So far for a first step - i cross my fingers :-)

**Comment by lrpowell** [comment]
I didn't have the asText or asXML because I could not get the page into a text or xml format.  I am not able to use **asXML()** or **asText()** on the **Page** object.  I get the error:  method xx is undefined for the type Page:
![image](https://user-images.githubusercontent.com/50636108/103923362-3d7eb380-50d2-11eb-901d-0aec141eb7f1.png)

Hovering over the declare for page, I can see that Page is from **com.gargoylesoftware.htmlunit.Page**

```
`	Page page = webClient.getPage(url);
	webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
				   
	WebResponse response = page.getWebResponse();
			
	 //System.out.println( page.asXML());  // asXML is undefined for type Page
	System.out.println(page.asText());  // asText() is undefined for type Page
`
```

**Comment by rbri** [comment]
You have to cast the page into an HtmlPage

**Comment by lrpowell** [comment]
I will need help with specific source code, now, just as before, when I tried to cast, I get either compile-time or run-time errors:
HtmlPage is from com.gargoylesoftware.htmlunit.html.**HtmlPage**
**1. compile time error:**
		`System.out.println( ((HtmlPage)page).**asXML**()); ``

> asXML() is undefined for the type HtmlPage

**2. runtime error:**
` System.out.println( ((HtmlPage)page).**asText**()); ` 

![image](https://user-images.githubusercontent.com/50636108/103951957-c9a5d080-50fc-11eb-9a36-bd3303e9ea59.png)

similar to what I posted above: 
> Exception in thread "main" java.lang.ClassCastException: com.gargoylesoftware.htmlunit.TextPage cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlPage at com.ibm.PDIScript.runDojoChart.export(runDojoChart.java:395) at com.ibm.PDIScript.runDojoChart.main(runDojoChart.java:154)

**Comment by rbri** [comment]
Ok, my fault - wrong caseing - asXml() ;-)

But not to the interesting part - you like to say that executing this

	Page page = webClient.getPage(url);
	webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
				   
	WebResponse response = page.getWebResponse();
			
	System.out.println( (HtmlPage)page).asText());

throws an runtime error - the ClassCastException from above?
If yes then we have a real strange problem :-) and a need some more help from you to nail that down.

**Comment by lrpowell** [comment]
OK.  What can I provide.  I just put the 4 lines you have replaced in my code block (plus a paren around "page" conversion, and repeated the error:

> url:http://9.5.57.189:2004/SystemiNavigator/com/ibm/as400/pt/dojoChart/DojoGraphScriptLauncher.html?packageId=IBM_CS&perspectiveId=P_WAITS_OVERVIEW&perspectiveName=Waits Overview&collectionName=TEST1&collectionLib=PDI&collectionType=Collection Services File Based Collection&fileLevel=48&startTime=Aug 26, 2020 12:26:32 PM&endTime=Aug 26, 2020 10:00:02 PM&systemName=A405BP3 &release=V7R3M0&collectionFormat=*CSFILE&basePerspId=
> Exception in thread "main" java.lang.ClassCastException: com.gargoylesoftware.htmlunit.TextPage cannot be cast to com.gargoylesoftware.htmlunit.html.HtmlPage
> 	at com.ibm.as400.pt.viewer.script.runDojoChart.export(runDojoChart.java:396)
> 	at com.ibm.as400.pt.viewer.script.runDojoChart.main(runDojoChart.java:142)
> 

![image](https://user-images.githubusercontent.com/50636108/104038943-f9071c80-5192-11eb-9697-2bb6acb01d62.png)

**Comment by rbri** [comment]
And opening the same url in with the browser results in a real Html page?

**Comment by lrpowell** [comment]
Yes - 
![image](https://user-images.githubusercontent.com/50636108/104065681-66c83e00-51bd-11eb-8daf-1b2761e87a47.png)

**Comment by rbri** [comment]
Sorry for asking stupid questions....

Can you please check the headers sent from the server for the url response - i like to make sure HtmlUnit's content type detection.

**Comment by lrpowell** [comment]
Do you mean using the getResponseHeaders() like this?
```
				WebResponse response = page.getWebResponse();
				**System.out.println(response.getResponseHeaders());**  
				System.out.println("now getting asText");
```


> url:http://9.5.57.189:2004/SystemiNavigator/com/ibm/as400/pt/dojoChart/DojoGraphScriptLauncher.html?packageId=IBM_CS&perspectiveId=P_WAITS_OVERVIEW&perspectiveName=Waits Overview&collectionName=TEST1&collectionLib=PDI&collectionType=Collection Services File Based Collection&fileLevel=48&startTime=Aug 26, 2020 12:26:32 PM&endTime=Aug 26, 2020 10:00:02 PM&systemName=A405BP3 &release=V7R3M0&collectionFormat=*CSFILE&basePerspId=
> **[X-Powered-By=Servlet/3.0, Content-Language=en-US, Transfer-Encoding=chunked, Date=Mon, 11 Jan 2021 01:43:03 GMT]**
> now getting asText

**Comment by rbri** [comment]
What i like to get is an screenshot from the Chrome DevTools like this one
![image](https://user-images.githubusercontent.com/2544132/104154742-f18b8180-53e5-11eb-8414-fe3aed324cef.png)

I need the real response headers for the html page to be sure HtmlUnit is able to detect the response as Html.

**Comment by lrpowell** [comment]
Let me know if this is not sufficient.  This is when I am calling the html on the browser.  It does look like the same output as what was provided when I ran with htmlunit and output the response headers (above)
![image](https://user-images.githubusercontent.com/50636108/104166472-1963f080-53b8-11eb-9dd3-f13bb0991530.png)
 

a little further down it shows the request content-type, but it is not shown on the response
![image](https://user-images.githubusercontent.com/50636108/104167372-70b69080-53b9-11eb-8745-770d7e317e76.png)

**Comment by rbri** [comment]
Thanks, will write some tests and will come back to you soon.

**Comment by rbri** [comment]
Sorry, but can you please also attach the content returned from the above request?

**Comment by lrpowell** [comment]
[DojoGraphScriptLauncherResult.html.txt](https://github.com/HtmlUnit/htmlunit/files/5796994/DojoGraphScriptLauncherResult.html.txt)

**Comment by rbri** [comment]
Hi Lora,

thanks for all the details. Have done some changes to the code but i fear this will not cure your problem. You can try using the latest snapshot build and check if you see any changes.

-----

If the problem is still there i need some more debugging - hope you like to help further with this....

This is the plan for the next steps

For getting a better idea why HtmlUnit wrongly creates a TextPage instead of a HtmlPage i like to add some log output to the lib and please you to configure logging
Do you use maven or some other dependency mgnt tool or just download the jars?

**Comment by lrpowell** [comment]
Thanks for your time on this!  I do want to continue because it has been the only solution I could find for what we are doing.  Just for background, I am running this on IBM i so the JVM is running in an AIX environment.  Since I am not doing anything very complicated (yet), I'm wondering if there could be some unique configurations or code there causing issues.

I do just download the libraries and update the configured build path in my Eclipse .classpath.  This entire code base is moving to a newer git repository and utilizing Maven there, but at this point we are not able to build this source there.

I don't see new code at the download site, do you want me to do the download here from the Git project?

**Comment by lrpowell** [comment]
I see the latest build, but only the .pom seems to be available.  Can you point me to where I would find the downloads?

**Comment by rbri** [comment]
You can download the latest dev builds from https://jenkins.wetator.org/job/HtmlUnit%20-%20Headless/ws/target/

**Comment by lrpowell** [comment]
I replaced htmlunit-2.46.0 with htmlunit-2.47.0-SNAPSHOT.  Running the basic test with 
			`	System.out.println( ((HtmlPage)page).asText());`

Now results in: 
> url:http://9.5.57.189:2004/SystemiNavigator/com/ibm/as400/pt/dojoChart/DojoGraphScriptLauncher.html?packageId=IBM_CS&perspectiveId=P_WAITS_OVERVIEW&perspectiveName=Waits Overview&collectionName=TEST1&collectionLib=PDI&collectionType=Collection Services File Based Collection&fileLevel=48&startTime=Aug 26, 2020 12:26:32 PM&endTime=Aug 26, 2020 10:00:02 PM&systemName=A405BP3 &release=V7R3M0&collectionFormat=*CSFILE&basePerspId=
> [Content-Type=text/html; charset=UTF-8]
> list:
> 1: Content-Type = text/html; charset=UTF-8
> now getting asText
> 'FiltersTableContainer'
> Hello World
> '

Looks successful!?

**Comment by rbri** [comment]
> now getting asText
> 'FiltersTableContainer'
> Hello World
> '

I guess this is the expected result - at least one of the screenshots from you are showing the same text.

**Comment by lrpowell** [comment]
Yes, that is great.  I will now move on to some more interesting work and hopefully will continue to get expected results reflected in the response text.  Thanks for your help!  Do you still feel there is a need to do any more debugging or not unless I find something not working as expected?

**Comment by lrpowell** [comment]
Also, I am curious, was there something unique about my environment or what I was doing that made this something new that was being run into?

**Comment by rbri** [comment]
:-)

There is nothing unique regarding the web - every dirty hack is around at least two times. In your case there was no content type in the response header - what is fine from the spec. In this case the browsers have to do content type sniffing to figure out if it is html or not. Have done some improvements in this field to bring HtmlUnit closer to the spec (and the real browsers).

https://github.com/HtmlUnit/htmlunit/commit/7ee340dafe3cc16ea7900a87609da54d77b7ae77

**Comment by rbri** [comment]
For now i like to close this - if it is ok for you - and will wait for your next issue.

Thanks a lot for your patience and all the fast answers to my stupid questions.

**Comment by lrpowell** [comment]
Thanks to you!  I am excited to have this tool help us provide a scriptable solution to our web charts!
