### ISSUE TITLE
KeyboardEvent constructor args ignored

### ISSUE THREAD

**Issue by jowerner** [HtmlUnit/htmlunit#292]
According to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent, a `KeyboardEvent` object may be created and populated using its constructor:

```
event = new KeyboardEvent(typeArg, KeyboardEventInit);
```

HtmlUnit seems to ignore both constructor arguments, so the event object is basically empty.

**Comment by rbri** [comment]
Have fixed many of the EventXXX constructors some weeks ago (last November) - will be great if you can provide a PR for this.
Maybe MouseEvent can be used as blueprint.

And btw. all the best for 2021

**Comment by jowerner** [comment]
Thanks, man! Hope 2021 will be a good year for you too.

Regarding the PR: Roger. Let's see what I can come up with during the next days. May need your help, though.

**Comment by rbri** [comment]
As always many thanks for the PR.
Have to merge the latest Rhino changes over the weekend and will make a new snapshot build available afterwards.
