### ISSUE TITLE
HtmlUnit caches javascript file?

### ISSUE THREAD

**Issue by lrpowell** [HtmlUnit/htmlunit#294]
I am updating the javascript on the remote system where I am running my java class which uses HtmlUnit to return the results from the javascript file.  I have modified the javascript with a simple text change and it is not being shown when I run the test.  Does HtmlUnit store a copy of the javascript anywhere or in /tmp directories?

**Comment by rbri** [comment]
As far as i know - no.

Maybe some infrastructure component in between?

**Comment by rbri** [comment]
Hope you found the reason. Will close this for now. Please open a new one if there is something i have to look at.

**Comment by lrpowell** [comment]
Yes, OK to close.  For now I am restarting the entire subsystem when I make javascript changes.  Just restarting the one server in the subsystem did not clear things.  I found this statement but nothing more on any details on what this person saw for caching - 
https://stackoverflow.com/questions/10691638/htmlunit-slower-than-gui-browser - “HTMLUnit does actually cache the pages”
