### ISSUE TITLE
Unit testing code using HtmlUnit

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#295]
Which classes would you recommend for unit testing custom code using HtmlUnit and HtmlUnitDriver ?

I had a look at your tests and there is WebDriverTestCase and I specially like how DomElementTest.java is set up.

Is there a better class you would recommend as a unit test blueprint?

Specifically, am researching how to unit test a web robot, and creating a mock using your test classes and feeding it a string with the page seems like the best way to go. 

Using Selenium Page Object Models for this, and my main aim is to unit test these page object model classes.

**Comment by rbri** [comment]
Hy Skyrider - not sure i got your point.

WebDriverTestCase if from my point of view the only way to maintain the compatibility of this lib with the latest browsers (at least to some extend). From my point of view all subclasses of WebDriverTestCase are more or less the same (hopefully) - outside the idea of switching between real browsers and the HtmlUnit simulation i think the other crucial part is to test only one function per test.

**Comment by skyhirider** [comment]
Thanks rbri. I was asking as I want to see if I can unit test some scenarios, so wanted to be sure there isn't a better way to do it via HtmlUnit. Beats having to implement something new.
