### ISSUE TITLE
HtmlAnchor click() not triggering JavaScript Events

### ISSUE THREAD

**Issue by MichaelHegner** [HtmlUnit/htmlunit#301]
HtmlAnchor click() is not triggering javascript which is listening to that event. 

```
HtmlAnchor anchor = element.getFirstByXPath("//a[@id='...']");
anchor.click(); // This is not firing events on js side!!!!

```

Using fireEvent but does the job

```
HtmlAnchor anchor = element.getFirstByXPath("//a[@id='...']");
anchor.fireEvent("click"); // JS running which listening on click events!
```

**Comment by Deadc00l** [comment]
I have a similar issue. After clicking on anchor element, my javascript does not execute this command:


```javascript
$('#SomeTable tr').find('td:first :checkbox').each(function () {
        if (!$(this).prop('disabled')) {
            $(this).prop('checked', nextCheckboxStatus);
        }
    });
```
The rest of the function works fine.
Using lates HTMLUnit Version and jQuery 3.5.1 / jQuery UI 1.12.1

**Comment by rbri** [comment]
sorry for being late on this

First guess:
The click() processes the click only if the element is visible.

Can you please check the log output - if the element is not visible there should be a warning in the log 
something like

    Calling click() ignored because the target element 'xxxx' is not displayed.

or

    Calling click() ignored because the target element 'xxxx' is disabled.

If this is the case then we have two options
use a more advanced version of the click method to ignore the visibility checks 

    click(final boolean shiftKey, final boolean ctrlKey, final boolean altKey, final boolean triggerMouseEvents, final boolean ignoreVisibility, final boolean disableProcessLabelAfterBubbling)
    anchor.click(false, false, false, true, true, false);

or there is a bug in the visibility check. If you think the anchor should be visible, please try

    anchor().isDisplayed()

and if you see false here, we have to dig deeper to understand why HtmlUnit (falsy) thinks the anchor is not visble/clickable.

**Comment by rbri** [comment]
Any findings here?

**Comment by MichaelHegner** [comment]
Hi, I am sorry, I am not in this project more. It could be, that the Html Element was not visible. From my opinion, triggerEvent("click") and .click() should behave on the same way.

**Comment by rbri** [comment]
Have added some sentences to the documentation of the click methods.

> From my opinion, triggerEvent("click") and .click() should behave on the same way.

From my point of view fireEvent("click") is something total different. This only fires the given event, click does a lot more.

**Comment by rbri** [comment]
@dennisduysak have you found the time to check the visibility of the element for you case?

**Comment by Deadc00l** [comment]
will check this today

**Comment by rbri** [comment]
Any news?

**Comment by Deadc00l** [comment]
Cant reproduce my issue, sorry.

**Comment by rbri** [comment]
Ok, will close this. Please open a new one if you have problems.
