### ISSUE TITLE
Provide CI

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#304]
A CI integration would be great for easier contribution on the HTMLUnit project. This makes it much easier to track failed branch builds.

**Comment by rbri** [comment]
good point

i guess you like to see a jenkins build running on top of your PR?
If yes - do you know hot to setup this - any help is welcome

**Comment by rbri** [comment]
Should i do this?

https://devopscube.com/jenkins-build-trigger-github-pull-request/

**Comment by rbri** [comment]
or better using blue ocean?

**Comment by ingomohr** [comment]
Hi @dennisduysak  and @rbri ,

Great idea. This would be very cool.
Imho, it's not that important what technical way the repo is using to add a running CI - i.e. whether it's Jenkins, Jenkins w/ Blue Ocean, Travis or something else.

From my point of view, it would be great if for each fork and each branch CI would be triggered automatically for each Git-Push, and CI results would be denoted on the corresponding comment that was pushed.

This would make contributing much easier, I think. :)

For my repos, I use Travis - it's free, and you can integrate CI simply by adding a YAML build script in your repo.
For instance: https://github.com/ingomohr/docwriter/blob/master/.travis.yml

What do you think?

**Comment by rbri** [comment]
Had done some experiments with travis in the past, our build runs far too long for the free travis version. Thats the reason for setting up our own jenkins.

**Comment by rbri** [comment]
Ok, this is now on my list, maybe there is some time next week to dive into the ocean and make this happen.

**Comment by rbri** [comment]
BlueOcean is installed, will discuss the next steps with a college next week

**Comment by rbri** [comment]
Have done a lot of work on our jenkisn build. Maybe i have to polish this a bit but we have a ci build for pull requests now in place.

https://jenkins.wetator.org/job/htmlunit/view/change-requests/

Will close this for now - hope this is ok for you.

**Comment by ingomohr** [comment]
Thanks, @rbri ! This is great. :)
