### ISSUE TITLE
Test classes as separate library?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#306]
The test classes for unit testing HtmlUnit are interesting and I would like to use them in projects that I am working on as part of unit testing. The classes are however not a part of the available package due to them being test classes.

Have you ever though about making a new library that would contain these classes that could then be used by others to unit test their automation tools?

The issue I am facing is creating tests for Selenium page objects that are not dependent on an external system, and it seems your test cases would work nicely.

Could build and import as a non maven library, but having a library with tests in a neat package could be useful to not only me but others as well.

**Comment by rbri** [comment]
Sorry for being late on this...

I'm not sure i got your point - you like to have a separate package like htmlunit-tests available im maven?
and you like to have the whole tests inside or only the (useful) parent classes?

**Comment by skyhirider** [comment]
Yes, was looking at options to run unit tests on page object models that I created and using the test classes you are using seemed like a good idea. 

I wanted to avoid creating more complex integration tests, using your classes to define a string, load it into the HtmlUnit driver and then run a few test cases would cover a lot of the tests.

Not sure if there is a way now to access your test classes without downloading the source directly from GitHub and adding it to my classpath. 

And ideally the useful parent classes would be enough, but even having it all would be fine as I would only use the package for testing, not for building.

**Comment by skyhirider** [comment]
I think this suggestion can be closed as implementing data urls into the driver did simplify making tests even if they require selenium to run

https://github.com/SeleniumHQ/htmlunit-driver/issues/102
