### ISSUE TITLE
TypeError: Cannot set property [HTMLInputElement].src that has only a getter to value 

### ISSUE THREAD

**Issue by lrpowell** [HtmlUnit/htmlunit#309]
I am getting this error while running.  It doesn't seem to stop things from executing, but I thought I should figure it out before it causes problems down the line (or maybe already is and I just don't know it yet).

> Feb 08, 2021 5:06:05 PM com.gargoylesoftware.htmlunit.WebConsole error
> SEVERE: ERROR TypeError: Cannot set property [HTMLInputElement].src that has only a getter to value 'images/dashboardList.png'.

When I turn on logging for WARNING and above I see these warnings:

> Feb 08, 2021 5:12:52 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:52 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:52 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:53 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:54 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:54 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:54 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:54 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:55 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:55 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> Feb 08, 2021 5:12:55 PM com.gargoylesoftware.htmlunit.IncorrectnessListenerImpl notify
> WARNING: Obsolete content type encountered: 'application/x-javascript'.
> 

and additionally (doesn't occur every run):

> 2021-02-08 17:12:58.329:INFO::main: Logging initialized @8155ms to org.eclipse.jetty.util.log.StdErrLog
> Feb 08, 2021 5:13:00 PM com.gargoylesoftware.htmlunit.WebConsole error
> SEVERE: ERROR TypeError: Cannot set property [HTMLInputElement].src that has only a getter to value 'images/arrow-up.png'.
>

**Comment by rbri** [comment]
Ok, thanks, will fix this later. Usually a simple task but in this case changing the src attribute should trigger a load of image from the new url. Have to write some more tests for this.

**Comment by rbri** [comment]
fixed in git, will make a new snapshot build available soon.

For the records: ImageInput does not load the image (for performance) so the src change will also not download the image - for the moment. Maybe some day some nasty user tracker will work based on this (or maybe there is already one out there)

**Comment by rbri** [comment]
Thanks for the report.

**Comment by lrpowell** [comment]
Ok.  Thanks for the fix.  From your statement about "will also not download the image" I'm not sure if that will affect my final outcome (wanting to download the chart page as described in issue #305

**Comment by rbri** [comment]
i think the chart is a different story - snapshot build is out
