### ISSUE TITLE
HtmlUnit won't retrieve the expected page

### ISSUE THREAD

**Issue by DSantiagoBC** [HtmlUnit/htmlunit#31]
I'm trying to access [this page](https://muisca.dian.gov.co/WebRutMuisca/DefConsultaEstadoRUT.faces) from HtmlUnit 2.34.1 to fill a form and save the result. The problem is I don't get the same resulting page I get when loading from a "real" browser. The page I get from HtmlUnit has just one `noscript` element inside its `body` with the following message:

> Please enable JavaScript to view the page content.
Your support ID is: _(A large number that changes on each execution)_.

I am sure I have enabled JavaScript in my `WebClient` options and setted 30 seconds as the JavaScript timeout (the hole page load takes less than a second). I also tried using the 2.34.2-SNAPSHOT, but the problem persists.

I have been using HtmlUnit almost a year ago and it has been really useful filling forms and retrieving information from the resulting pages, so that's why this issue surprises me that much.

Thank you so much for all the efford. If you need clarification, just ask.

**Comment by rbri** [comment]
Sorry, but this page works based on a lot of obfuscated javascript. I do not have the time to debug this. To get this working you have to nail down the problem.

**Comment by rbri** [comment]
No further feedback will close this.
