### ISSUE TITLE
Suggestions on doing updates for new releases with Maven

### ISSUE THREAD

**Issue by lrpowell** [HtmlUnit/htmlunit#312]
Sorry, this is not a specific HtmlUnit question, more of a project configuration question.  
I am new to Maven and have now moved my project into a larger project utilizing Maven for builds.
I am not sure the best way to set up for doing the updates on dependency repositories such as HtmlUnit non-manually.  
It seems that there may be a lot of options out there, so I am looking for tips.  Unless something like this is the basics and I can work with that: https://www.baeldung.com/maven-dependency-latest-version

**Comment by rbri** [comment]
Usually you can change your pom to point to the snapshot of HtmlUnit instead of the release. Outside of this you only have to make sure, the repository section of your pom contains the proper snapshot repository

see section installation here https://htmlunit.sourceforge.io/

**Comment by lrpowell** [comment]
thank you

**Comment by lrpowell** [comment]
Hmm, thinking about this again.  So if I have this in my pom.xml: 
```
		<dependency>
   			 <groupId>net.sourceforge.htmlunit</groupId>
    			<artifactId>htmlunit</artifactId>
    			<version>2.48.0-SNAPSHOT</version>
		</dependency>
```
If that specific snapshot was updated, I would need to download the new version and put it into my repository.
Otherwise if a new version 2.49.0 was made, I would need to update the pom.xml and download that and put into my repository.
Correct?  I felt like I was missing something where maven would automatically pull down the new version, but I don't see where that information is in the pom.xml for it to happen.

**Comment by lrpowell** [comment]
ah, the lightbulb just went on.  that is what this "snapshotRepository" is for:
```
<snapshotRepository>
  <id>sonatype-nexus-snapshots</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</snapshotRepository>
```
