### ISSUE TITLE
How to solve the problem with lazy load?

### ISSUE THREAD

**Issue by zhenxi1023** [HtmlUnit/htmlunit#313]
Hi, I got a new problem. 
I accessed this link: https://www.bestbuy.com/site/searchpage.jsp?st=TV&_dyncharset=UTF-8&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys
I found this page has lazy load for some elements. In Chrome, I scroll to bottom slowly, they loaded. And if I use js code like this: window.scrollTo(0, document.documentElement.scrollHeight);
Nothing to work. So I think, this page, use this rule:
If the elements in the view? Yes, load it. Or without loading.
I want to ask you for help, how could I use HtmlUnit to get informations in the lazy loaded elements?
Thanks

**Comment by zhenxi1023** [comment]
Emmm, after some exprenence, this page: https://www.bestbuy.com/site/searchpage.jsp?st=TV&_dyncharset=UTF-8&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys
in the chrome, I could use this javascript code to make all lazy load element loaded.
```
let runTimes=0;
let a = document.querySelectorAll("li.sku-item")
let id=setInterval(function(){
    a[runTimes].scorllIntoView(true)
    runTimes++
    if (runTimes===a.length){
       clearInterval(id)
    }
 }, 5000)
```

But what sould I do by HtmlUnit? I used HtmlPage.executeJavaScript(codeString); . This way doesn't work. And, it executed too fast, a.length===24, so in chrome it used 2 mins, but use HtmlUnit, maybe just 2 secs.
These are my codes.


```
public void test() {
     WebClient webClient = new WebClient(BrowserVersion.CHROME);
      webClient.getOptions().setJavaScriptEnabled(false);
      webClient.getOptions().setCssEnabled(false);
      webClient.getOptions().setRedirectEnabled(true);
      webClient.getOptions().setThrowExceptionOnScriptError(false);
      webClient.getOptions().setActiveXNative(false);
      HtmlPage page = webClient.getPage("https://www.bestbuy.com/?intl=nosplash");
      webClient.getOptions().setJavaScriptEnabled(true);
      webClient.setAjaxController(new NicelyResynchronizingAjaxController());
      ScriptResult result = htmlPage.executeJavaScript("let runTimes = 0;" +
              "let a = document.querySelectorAll(\"li.sku-item\");" +
              "let id=setInterval(function(){\n" +
              "    a[runTimes].scrollIntoView(true)\n" +
              "    runTimes++\n" +
              "    if (runTimes===a.length){\n" +
              "        clearInterval(id)\n" +
              "    }\n" +
              "},5000)");
      htmlPage = (HtmlPage) htmlPage.getEnclosingWindow().getEnclosedPage();
      Document document = Jsoup.parse(htmlPage.asXml());
      Element element = document.select("ol.sku-item-list > li.sku-item").get(0);
      String strongString = element.selectFirst(".fulfillment-fulfillment-summary div > strong").text();   // NullPointerException
   }
```

Thanks

**Comment by rbri** [comment]
You have the javascript support disabled

    webClient.getOptions().setJavaScriptEnabled(false);

**Comment by rbri** [comment]
Just a guess: because you have javascript support disabled while loading the page, all the page elements dynamically generated via js are not there. Maybe you can do page.asXML() after the getPage call to get an idea

**Comment by zhenxi1023** [comment]
I think you are right, I will try this way to solve my problem. Thanks for your advice.
