### ISSUE TITLE
`window.getSelection().toString()` returns `[object Selection]` not the selected text

### ISSUE THREAD

**Issue by felixscheinost** [HtmlUnit/htmlunit#319]
According to MDN `window.getSelection().toString()` is supposed to return the text the user selected.

I am using this by checking that the selection is empty that the user is actually clicking and not selecting text.

The problem is that when running in HtmlUnit this method is always returning `[object Selection]` and not the selected text.

**Comment by rbri** [comment]
will have a look - thanks for the report

**Comment by rbri** [comment]
it will be a great help if you can provide some test cases for different selections

see com.gargoylesoftware.htmlunit.javascript.host.dom.SelectionTest

**Comment by rbri** [comment]
Yes this is clearly a bug, but i fear it will be not that simple to provide a correct selection implementation.
But i will try to make a first shot on this.

Can you please tell me a bit more about your use case - what do you like to do with the selected text, what kind of selections you are doing?

**Comment by rbri** [comment]
The implicit conversion was already working, now toString() produces the same result.

**Comment by rbri** [comment]
As always will inform on twitter if a new snapshot is available.

Many thanks for the report.

**Comment by felixscheinost** [comment]
Sorry, for coming back to you just now.

I used it for checking whether the user had selected some text in an `onClick` listener to filter out clicks while the user is selecting text. As a workaround I used `window.getSelection().type === "Range"` instead to check whether text is selected.

Thanks a lot for your help!

**Comment by rbri** [comment]
Thanks for the feedback, the current snapshot impl. has a fix for the toString() method that should do the job for your case.

BTW: i found two more classes with the same error - thanks again for using HtmlUnit and the error report.
