### ISSUE TITLE
Setting browser language has no effect

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#329]
When I change the language for the browser via BrowserVersionBuilder, the language remains on my default settings. This feature worked before the BrowserVersionBuilder was introduced

```java
BrowserVersionBuilder browserVersionBuilder = new BrowserVersionBuilder(BrowserVersion.CHROME);
browserVersionBuilder.setBrowserLanguage("fr");
WebClient client = new WebClient(browserVersionBuilder.build());
```

**Comment by rbri** [comment]
Sorry - where do you face the wrong language?

**Comment by Deadc00l** [comment]
The content of the page changes depending on the language set. For example, if I go to google.com and search for the button with the id "gbqfbb", I always get the German text "Auf gut Glück!" instead of the French translation.

**Comment by rbri** [comment]
ok, will have a look - i think i had a unit test for this but ....

**Comment by Deadc00l** [comment]
Thanks a lot!

**Comment by rbri** [comment]
Usually the web pages using the Accept-Language header to determine the locale. The builder has a separate setter for this. Can you please check if setting the also helps.

**Comment by Deadc00l** [comment]
Thank you very much, that helped :)

**Comment by rbri** [comment]
have to think about this dependency - maybe at least the docu needs some improvement
