### ISSUE TITLE
Throws error “java.util.NoSuchElementException” on page load

### ISSUE THREAD

**Issue by VadimStepura** [HtmlUnit/htmlunit#330]
I try to load the page using HtmlUnit, select the city "Белая Церковь" and see the availability of the drug in pharmacies, but even at the initial stage, when loading the page, I get an error java.util.NoSuchElementException. When I set the WebClient parameter (BrowserVersion.INTERNET_EXPLORER), then I get the page, but not completely. The HtmlUnit version is 2.48.0. Here is an example of my code, what am I doing wrong?

```
try {
            WebClient client = new WebClient(BrowserVersion.CHROME);
            client.setHTMLParserListener(HTMLParserListener.LOG_REPORTER);
            client.getOptions().setJavaScriptEnabled(true);
            client.getOptions().setCssEnabled(true);
            client.getOptions().setUseInsecureSSL(true);
            client.getCookieManager().setCookiesEnabled(true);
            client.getOptions().setThrowExceptionOnScriptError(false);
            client.getOptions().setThrowExceptionOnFailingStatusCode(false);
            client.setAjaxController(new NicelyResynchronizingAjaxController());
            client.getOptions().setRedirectEnabled(true);
            client.getOptions().setGeolocationEnabled(true);

            HtmlPage page = client.getPage("https://www.aptekanizkihcen.ua/ru/ynformatsyya-o-tovare/7891");
           //HtmlTextInput townInput = (HtmlTextInput) page.getByXPath("//input[contains(@class, 'dropdown-location-input')]").get(0);
            client.close();
    } catch (Exception ex) {
        ex.printStackTrace();
        throw new RuntimeException(ex);
    }
```

**Comment by rbri** [comment]
Have done some tests and this code passes here

        String url = "https://www.aptekanizkihcen.ua/ru/ynformatsyya-o-tovare/7891";

        try (WebClient webClient = new WebClient(BrowserVersion.FIREFOX)) {
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            HtmlPage page = webClient.getPage(url);

            webClient.waitForBackgroundJavaScript(20_000);
            System.out.println("***********************************");
            System.out.println("***********************************");
            System.out.println(page.asXml());
            System.out.println("***********************************");
            System.out.println("***********************************");
            HtmlTextInput townInput = (HtmlTextInput) page.getByXPath("//input[contains(@class, 'dropdown-location-input')]").get(0);
            System.out.println(townInput.asXml());
            System.out.println("***********************************");
            System.out.println("***********************************");
        }

This page is really complicated including tons of javascript. I made a bugfix to make it work here - but maybe there are other problems.

Please check at twitter - i will inform if a new snapshot build is available with including the fix.

**Comment by rbri** [comment]
There is a new snapshot available - please try

**Comment by VadimStepura** [comment]
Thanks for the answer. I checked and the page loads without problems. I have not yet been able to insert my value into the input and get a drop-down list to select the desired option, but this is probably not a library error.
I also tried to do it through Selenium WebDriver, everything was done there.

**Comment by rbri** [comment]
Thanks for your feedback. Feel free to ask more or open issues if you have other problems with HtmlUnit.
