### ISSUE TITLE
how to change Http request method and add request body?

### ISSUE THREAD

**Issue by christian-draeger** [HtmlUnit/htmlunit#339]
hey,
i am wondering how to change the http verb and add a request body in a request as well as how to render the corresponding response.

my use case is the following:
* i have an endpoint (POST that expects a json as request body) that is returning html that contains inline script tag
    * therefore i would need to add "application/json" as content-type header and a body as string that represents my serialized json body
        * ✅ adding header i have found as method of the `WebClient` and can be set via `addRequestHeader("Content-Type", "application/json")`
        * ❓could not find how to change the http method (`new WebClient().getPage("http://foo.bar")` always uses GET) 
        * ❓could not find how to add a request body (would be needed for POST, PUT and in genreal for all http methods, even GET. i know it is unusual BUT GET requests with a body are supported in the HTML specs, therefore it is an valid use-case)

* the response from the server is an html snippet that contains inline script. i want to render it / parse the html with executed javascript, since the script is manipulating the markup of the snippet - ❓how to do that best

info on how to convert a `WebResponse` to a `Page` would also be handy.

thx in advance

**Comment by rbri** [comment]
Hi Christian,

maybe you can
* create your own WebRequest
* call  WebClient#getPage(webClient.getCurrentWindow().getTopWindow(), request);

This will process your request and place the result inside the given window including the processing of js inside the page.

Hope i got your point.

**Comment by christian-draeger** [comment]
works =) awesome. big thanks

**Comment by rbri** [comment]
You're welcome 

Am 12. April 2021 21:32:54 MESZ schrieb "Christian Dräger" ***@***.***>:
>works =) awesome. big thanks 
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/HtmlUnit/htmlunit/issues/339#issuecomment-818077134

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
