### ISSUE TITLE
jQuery issues

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#34]
I sometimes have issues with jQuery that I didn't yet manage to solve. Sometimes jQuery does not seem to load or to load in the wrong order. I'll try to disclose as much information as possible but the application under test is a closed source one.

Here are some errors that pop up from time to time:

> TypeError: Cannot read property "timepicker" from undefined (xxx/js/jquery-ui-timepicker-addon.js#20)

> ReferenceError: "jQuery" is not defined. (xxx/js/base/jquery-ui.min.js?s2j=3.7.1#6)

> ReferenceError: "GridUtil" is not defined. (eval code#1(eval)#28)

Maybe related:
> TypeError: Cannot read property "style" from undefined (xxx/js/base/jquery-1.11.0.min.js#1438)
> TypeError: Cannot read property "regional" from undefined (xxx/js/jquery-ui.timepicker-de.js#4)

What happens when a request to a script resource times out? The errors pop up every once in a while so my first guess would be that jQuery just sometimes fails to load (before the other scripts).

I'll try to further investigate this myself and report back.

**Comment by rbri** [comment]
any results from your investigation - or can i close this?

**Comment by black-snow** [comment]
Seems to be obsolete, thanks.
