### ISSUE TITLE
Proxy scheme defaulted to http

### ISSUE THREAD

**Issue by nbauma109** [HtmlUnit/htmlunit#340]
The proxy scheme I need the use is https. Webclient constructor only takes proxy host/port . There could be another constructor which takes scheme/host/port. In HttpHost class there is a constructor that takes scheme/host/port in addition to the one used which takes host/port and defaults scheme to http.

**Comment by rbri** [comment]
OK, you are right - no idea why nobody has reported this before. Will try to add the https support soon

**Comment by rbri** [comment]
Have done a first commit for this, and a new snapshot build is also available. Please have a look.

**Comment by nbauma109** [comment]
I got that message "malformed reply from SOCKS server" but not sure if it's related to the code or a bug in the https proxy

**Comment by rbri** [comment]
do you use a socks proxy?

**Comment by nbauma109** [comment]
No I don't.

**Comment by rbri** [comment]
sounds a bit like the code now tries to use a socket server - maybe i have done a mistake somewhere with the ProxyConfig#isSocksProxy_ flag. Can you debug into the HtmlUnit code?

**Comment by rbri** [comment]
the magic should be here: com.gargoylesoftware.htmlunit.HttpWebConnection.setProxy(HttpRequestBase, WebRequest)

**Comment by nbauma109** [comment]
The flag is false and in setproxy the URL is correctly set to https://... Also I noticed I have the same exact error message with both http and https. For some reason the proxy does not play well with Apache http client. It works with Sun http client. I noticed that also in the eclipse egit plugin. It wasn't working until I switched to Sun http client in the configuration panel.

**Comment by rbri** [comment]
ok, maybe stackoverflow has some idea; maybe we have to do some special setup for HttpClient.

**Comment by rbri** [comment]
at least you are not alone ;-)
https://stackoverflow.com/questions/45417681/malformed-reply-from-socks-server-when-fetching-proxy-server-details-dynamically

**Comment by rbri** [comment]
anything more i can do here?

**Comment by nbauma109** [comment]
No thanks for your help, much appreciated

**Comment by rbri** [comment]
Thanks, will close this
