### ISSUE TITLE
Tag Iframe doesn't work after click Anchor in HtmlUnit

### ISSUE THREAD

**Issue by ceceussj4** [HtmlUnit/htmlunit#341]
I'm learning working with HtmlUnit. I'm with a problem. 
When I click in a anchor my page has a iFrameTag that doesn't load. The oficial page work normal.

Below follow the steps:
1- I open the page (https://www.peintegrado.pe.gov.br/portal/Mural.aspx);
2 - I click at a register in grid;
3- System open new page;
4-This new page there is a link (anchor) with name "Edital";
5- When I click this above link the system show a iframe.

My problem just is in the steps 4 e 5. When I click the anchor the iframe tag doesn't update.

OBS:  The iframe tag doesn't update is  
        <iframe id="frameResumoEdital" src="" width="800px" height="425px">
        </iframe>
--****************************************************************************************
Part of my code:
(I'm use the 2.48 version)
WebClient client = new WebClient();
CookieManager cookieManager = client.getCookieManager();
cookieManager.setCookiesEnabled(true);
client.setCookieManager(cookieManager);

client.getOptions().setPopupBlockerEnabled(true);
client.getOptions().setThrowExceptionOnFailingStatusCode(false);
client.getOptions().setJavaScriptEnabled(true);
client.getOptions().setCssEnabled(false);
client.getOptions().setUseInsecureSSL(true);
client.getOptions().setRedirectEnabled(true);
client.setAjaxController(new NicelyResynchronizingAjaxController());
client.getOptions().setThrowExceptionOnScriptError(false);

(Below follow the part of my code that I tried to do the click at anchor (step 4) and where not could to do iframe work)
HtmlAnchor linkEdital =  (HtmlAnchor) pageEdital.getByXPath("//a[@data-acao='edital']").get(0);
pageEdital = linkEdital.click();
client.waitForBackgroundJavaScript(60000);
System.out.println(pageEdital.asXml());
--****************************************************************************************
The log:
2021-04-15 10:39:32.348  INFO 5622 --- [cTaskExecutor-1] .g.h.NicelyResynchronizingAjaxController : Re-synchronized call to https://www.peintegrado.pe.gov.br/portal/WebService/Servicos.asmx/PesquisarResumoEdital

(Here show the page code. I copied just a part)
<span class="k-window-title" id="divResumoEdital_wnd_title">
          RESUMO DO EDITAL
        </span>
        <div class="k-window-actions">
          <a role="button" href="#" class="k-window-action k-link" aria-label="Close">
            <span class="k-icon k-i-close">
            </span>
          </a>
        </div>
      </div>
      <div id="divResumoEdital" data-role="window" class="k-window-content k-content" tabindex="0" role="dialog" aria-labelledby="divResumoEdital_wnd_title" style="">
        <div id="carregandoResumoEdital" class="carregandoDados" style="display: none;" ;="">
          <img src="Imagens/carregando.gif"/>
        </div>

        <iframe id="frameResumoEdital" src="" width="800px" height="425px">
        </iframe>

        <div class="botoes-kendo-window">
          <input id="btImprimirEdital" type="button" value="Imprimir" class="campoBotaoSemIcone" onclick="imprimirConteudo($('#frameResumoEdital').contents().find('html')[0])" style="width: 20%;"/>
          <input id="btDetalhesDosItens" type="button" value="Detalhes dos itens" class="campoBotaoSemIcone" style="width: 25%; display: none;"/>
          <input id="btFecharEdital" type="button" value="Fechar" onclick="$('#divResumoEdital').data('kendoWindow').close()" class="campoBotaoSemIcone" style="width: 20%;"/>
        </div>
      </div>
    </div>
    <div class="k-widget k-window" style="padding-top: 18px; min-width: 90px; min-height: 220px; max-height: 350px; width: 700px; display: none; top: 582px; left: 8818px; touch-action: none;" data-role="draggable">
      <div class="k-window-titlebar k-header" style="margin-top: -18px;">
         
        <span class="k-window-title" id="divDetalheItem_wnd_title">
          DETALHES DO ITEM
        </span>
        <div class="k-window-actions">
          <a role="button" href="#" class="k-window-action k-link" aria-label="Close">
            <span class="k-icon k-i-close">
            </span>
          </a>
        </div>
      </div>
      <div id="divDetalheItem" style="max-height: 350px;" data-role="window" class="k-window-content k-content" tabindex="0" role="dialog" aria-labelledby="divDetalheItem_wnd_title">
        <div id="carregandoDetalheItem" class="carregandoDados" style="display:none" ;="">
          <img src="Imagens/carregando.gif"/>
        </div>
        <div style="width: 100%; text-align: right; padding-top: 10px;">
          <input type="button" value="Fechar" onclick="$('#divDetalheItem').data('kendoWindow').close()" class="campoBotaoSemIcone" style="width:20%"/>
        </div>
      </div>
      <div class="k-resize-handle k-resize-n">
      </div>
      <div class="k-resize-handle k-resize-e">
      </div>
      <div class="k-resize-handle k-resize-s">
      </div>
      <div class="k-resize-handle k-resize-w">
      </div>
      <div class="k-resize-handle k-resize-se">
      </div>
      <div class="k-resize-handle k-resize-sw">
      </div>
      <div class="k-resize-handle k-resize-ne">
      </div>
      <div class="k-resize-handle k-resize-nw">
      </div>
    </div>
    <div class="k-widget k-window" style="padding-top: 18px; min-width: 90px; min-height: 50px; display: none; top: 582px; left: 8818px;">
      <div class="k-window-titlebar k-header" style="margin-top: -18px;">
         
        <span class="k-window-title" id="divDetalheAcompanhamentoLance_wnd_title">
          ACOMPANHAR LANCES
        </span>
        <div class="k-window-actions">
          <a role="button" href="#" class="k-window-action k-link" aria-label="Close">
            <span class="k-icon k-i-close">
            </span>
          </a>
        </div>
      </div>
      <div id="divDetalheAcompanhamentoLance" style="" data-role="window" class="k-window-content k-content" tabindex="0" role="dialog" aria-labelledby="divDetalheAcompanhamentoLance_wnd_title">
        <div id="carregandoDetalheAcompanhamentoLance" class="carregandoDados" style="display:none" ;="">
          <img src="Imagens/carregando.gif"/>
        </div>
      </div>
    </div>
  </body>
</html>
--****************************************************************************************
Prints for help:

![Captura de Tela 2021-04-15 às 10 14 31](https://user-images.githubusercontent.com/71467990/114875598-d446c480-9dd3-11eb-947f-030246b28b00.png)
![Captura de Tela 2021-04-15 às 10 20 01](https://user-images.githubusercontent.com/71467990/114876140-68b12700-9dd4-11eb-806f-7b811488a5cf.png)
![Captura de Tela 2021-04-15 às 10 22 28](https://user-images.githubusercontent.com/71467990/114876595-da897080-9dd4-11eb-8b99-e90a3d5f6e28.png)

**Comment by rbri** [comment]
the content of the iframe is not included per default, you have to look inside yourself

This

    public static void main(String[] args) throws Exception {
        try (final WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED)) {
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);

            HtmlPage htmlPage = webClient.getPage("https://www.peintegrado.pe.gov.br/portal/Mural.aspx");
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println("********************");
            System.out.println("********************");
            System.out.println(htmlPage.asNormalizedText());
            System.out.println("********************");
            System.out.println("********************");

            DomNodeList tds = htmlPage.getElementsByTagName("td");
            System.out.println(tds.size());

            HtmlTableDataCell td = (HtmlTableDataCell) tds.get(1);
            System.out.println("********************");
            System.out.println("********************");
            System.out.println(td.asXml());
            System.out.println("********************");
            System.out.println("********************");

            td.click();
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println("********************");
            System.out.println("********************");
            System.out.println(htmlPage.asNormalizedText());
            System.out.println("********************");
            System.out.println("********************");

            HtmlAnchor linkEdital = (HtmlAnchor) htmlPage.getByXPath("//a[@data-acao='edital']").get(0);
            System.out.println("********************");
            System.out.println("********************");
            System.out.println(linkEdital.asXml());
            System.out.println("********************");
            System.out.println("********************");


            linkEdital.click();
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println("********************");
            System.out.println("********************");
            System.out.println(htmlPage.asXml());
            System.out.println("********************");
            System.out.println("********************");

            HtmlInlineFrame iframe = (HtmlInlineFrame) htmlPage.getElementById("frameResumoEdital");
            HtmlPage iPage = (HtmlPage) iframe.getEnclosedWindow().getEnclosedPage();
            System.out.println("********************");
            System.out.println("********************");
            System.out.println(iPage.asText());
            System.out.println("********************");
            System.out.println("********************");

        }
    }

produces (iPage.asText())

    ********************
    ********************
    PE - INTEGRADO
    
     
    COMPRA DIRETA 
     0010.2021.CCD.DL.0007.PGE-PE
    Recebimento de propostas e lances somente via Internet, no endereço eletrônico http://www.peintegrado.pe.gov.br/, no período indicado abaixo.
    
    Processo: 0010.2021.CCD.DL.0007.PGE-PE
    Data de início: 15/04/2021 20:17:00
    Prazo para o envio de propostas e lances: 15/04/2021 20:20:00
    Orgão de Compras: PGE-PE
                                   
                                  
    Responsável: JACIELE VELOSO DE OLIVEIRA
    
     1 - Objeto: Contratação de empresa para fornecimento de 01 (uma) assinatura diária anual digital de segunda a domingo do Jornal do Commércio, para atender aos interesses do Gabinete do Procurador Geral desta PGE.. 
     
     2 - Detalhamento dos itens: 
    Item    Descrição   Quantidade  Unidade de medida   Quantidade de tempo Unidade de tempo
    1   (2155850) - SERVICO DE ASSINATURA DE JORNAIS E PERIODICOS - JORNAL LOCAL 
     
     
     Prazo de entrega ou execução: CONFORME EDITAL  1,0000  UN      
    
     3. Condição de pagamento: CONFORME EDITAL. 
     
     4. Condições Gerais:
     TEMPO RANDÔMICO: O sistema PE Integrado define para sua segurança um tempo randômico, que será acrescido no prazo de encerramento. 
    LANCES: Para dar seu lance unitário, atente para a variação mínima(VarMin) e máxima(VarMax) estipuladas, que serão calculadas sobre o melhor lance. Para visualizar seus lances, clique no número do item correspondente. Registrar o seu menor valor, mesmo que esteja acima do valor de referência, pois poderá ser classificado após o encerramento. 
    CANCELAR LANCE INDEVIDO: Para efetuar cancelamento de seu lance indevido, clique sobre o Nºdo Item, desmarque o lance e confirme. 
    MARCAS HOMOLOGADAS: Para visualizá-las clique na descrição do item. Somente serão aceitos lances dessas MARCAS HOMOLOGADAS E DESCRIÇÃO DETALHADA DO MATERIAL. 
     
     
    Acesse o PE - INTEGRADO (http://www.peintegrado.pe.gov.br/) e consulte os detalhes.
    
    RECIFE, 15/04/2021 20:27:46
    
     
     Atenciosamente 
     PE - INTEGRADO 
     
    
     Você recebeu este e-mail porque está cadastrado no sistema de Compras e Licitações do Governo do Estado de Pernambuco - PE-Integrado (www.peintegrado.pe.gov.br). Caso deseje cancelar o recebimento de e-mails, envie uma solicitação para suporte.peintegrado@sad.pe.gov.br, com o motivo do cancelamento e o número do CNPJ/CPF
        
     
     Paradigma Business Solution 
     
     
    ********************
    ********************

**Comment by ceceussj4** [comment]
@rbri you are simply the best! Thanks so much for help. You always help us with patience and dedication. Congratulations!

**Comment by rbri** [comment]
You're welcome 
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
