### ISSUE TITLE
dynamic change proxy

### ISSUE THREAD

**Issue by xiaowenhuman** [HtmlUnit/htmlunit#343]
Hello , 
I have started the webclient, can I change the proxy dynamically？

**Comment by rbri** [comment]
I i remember correctly this is supported by the implementations. You can chance the proxy using something like

    webClient.getOptions().setProxyConfig(new ProxyConfig(proxyHost, proxyPort, proxyScheme));

But i'm only 80% sure this will work :-) because the change has to be used for the next requests and there is a lot of web connection magic inside. Please try and cross your fingers.

**Comment by rbri** [comment]
No feedback so far - hope this works for you. Please open a new issue if you still have problems.
