### ISSUE TITLE
ng-click not working

### ISSUE THREAD

**Issue by grkephart** [HtmlUnit/htmlunit#346]
The following is an example of what we have in our code.

&lt;a id="2184139853-5471" data-toggle="tooltip" title="" data-html="true" data-animation="true" ng-click="jobActivityButtonAction(activityButton)" href="javascript:;" data-original-title="Entry Add Multiple Results Mfg Lead"></a>

However, when I call "domElement.click();", it stays on the same page with no error. I'm assuming that's because ng-click is not being executed.

Could this please be fixed?

**Comment by rbri** [comment]
Without access to the real application i can only guess....

Maybe the js replaces the current page inside the window. I guess your code looks like this.

    page = elem.click();

Please try to change this like this

    page = elem.click();
    client.waitForBackgroundJavaScript(20_000);
    page = page.getEnclosingWindow().getEnclosedPage();

Hope that helps.

**Comment by rbri** [comment]
does it work for your?

If not can you please try version 2.50.0 there is a fix regarding onclick processing.

**Comment by rbri** [comment]
Made a simple sample

	<!doctype html>
	<html lang="en">
	<head>
	  <meta charset="UTF-8">
	  <title>Example - example-ng-click-production</title>
	  <script src="https://code.angularjs.org/snapshot/angular.js"></script>
	</head>

	<body ng-app="">
	  <button id='klick' ng-click="count = count + 1" ng-init="count=0">
	  Increment
	</button>
	<span>
	  count: {{count}}
	</span>
	</body>
	</html>

And tested it with this code

        String uri = "file:///......";

        try (final WebClient webClient = new WebClient()) {
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            HtmlPage page = webClient.getPage(uri);
            System.out.println("----------------");
            System.out.println(page.asXml());
            System.out.println("----------------");

            DomElement klick = page.getElementById("klick");
            klick.click();
            klick.click();
            klick.click();
            klick.click();
            System.out.println("----------------");
            System.out.println(page.asXml());
            System.out.println("----------------");
        }

The page includes 'count: 4'.

**Comment by rbri** [comment]
And the same result if i replace the button by

    <a id="a-klick" data-toggle="tooltip" title="" data-html="true" data-animation="true" ng-click="count = count + 1" href="javascript:;" data-original-title="Entry Add Multiple Results Mfg Lead">
  	  Click
    </a>

Can you please try to provide a minimal sample that shows your problem.

**Comment by grkephart** [comment]
I tried the new version and it seemed to have the same result.

The method I use for clicking on elements is this:

    public HtmlPage clickOn(DomElement domElement, long timeoutMillis) throws IOException {
        HtmlPage htmlPage= domElement.click();
        htmlPage.getWebClient().waitForBackgroundJavaScript(timeoutMillis);

        return (HtmlPage) htmlPage.getEnclosingWindow().getEnclosedPage();
    }

And the problem element is this one:

    HtmlAnchor[<a id="2185698474-5471" data-toggle="tooltip" title="Entry Add Multiple Results Mfg Lead" data-html="true" data-animation="true" ng-click="jobActivityButtonAction(activityButton)" href="javascript:;">]

The full HTML for that portion is below. I'm trying to click on the td/div/div/a element.

<td colspan="12">
   <div class="approvals_button">
     <div class="button_actions ng-scope" ng-repeat="activityButton in 
jobOperActivity.activityButtons track by $index" style="">
       <span ng-if="!activityButton.statusEnabled" class="button_info 
ng-scope">
         <a href="javascript:;" id="info-2185698474-5471" 
data-toggle="tooltip" data-html="true" data-animation="true" 
title="click here to know the status of this button" 
ng-click="isJobActivityButtonEnabled(activityButton)">
           <i class="fa fa-info-circle"></i>
         </a>
       </span>
       <a id="2185698474-5471" data-toggle="tooltip" title="" 
data-html="true" data-animation="true" 
ng-click="jobActivityButtonAction(activityButton)" href="javascript:;" 
data-original-title="Entry Add Multiple Results Mfg Lead">
         <div class="activity_button ">
           <span>
             <img 
ng-src="/ifactory/images/entryAddMultipleCollectionPlanResult.png" 
src="/ifactory/images/entryAddMultipleCollectionPlanResult.png" 
width="35" border="0">
           </span>
           <span ng-bind-html="activityButton.activityActionButtonText | 
rawHtml" class="ng-binding">Entry Add Multiple</span>
         </div>
       </a>
     </div>
   </div>
</td>

  Thanks,
   Gary

**Comment by rbri** [comment]
Do you have control of the application code itself and can you try some changes?

**Comment by rbri** [comment]
really outdated - sorry will close this

please open a new one if you still need support
