### ISSUE TITLE
Strange exception when DOM event name is used as function name

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#347]
# Problem in brief
HtmlUnit/Rhino will throw `TypeError: <function name> is not a function, it is object.` if a DOM event name (i.e. "on-" phrases such as "onclick", "onkeydown") is used as function name.

# Testing
The following test was used to test the behavior in HtmlUnit and Chrome
```
<!DOCTYPE html>
<html>
<head>
<script>
function onclick() {
    console.log("OK");
}
</script>
</head>
<body onload="onclick()">
</body>
</html>
```

# Suspected reason
When a function is created, its parent scope is mapped to `Window`.
In `ScriptRuntime.nameOrFunction()` the prototype chain is traversed to find the "onclick" property.
It should be `NOT_FOUND` all the way to the last scope `(Window)` but because the "onclick" is an event name it is already registered as a property in couple of earlier scopes with a value of `null`.  It finds and returns this `null` but Rhino cannot execute `null` as a function and throws an error.

# Possible fix
FWIW, removing this block of code from `ScriptRuntime.nameOrFunction()` kind of "fixes" the issue but I don't know the implications of doing this. i don't understand the comment of this block and i think it could be important.
```
} else {
	// Can happen if Rhino embedding decided that nested
	// scopes are useful for what ever reasons.
	result = ScriptableObject.getProperty(scope, name);
	if (result != Scriptable.NOT_FOUND) {
		thisObj = scope;
		break;
	}
}
```

**Comment by rbri** [comment]
Thanks, will have a look.

**Comment by haranrk** [comment]
```java
// Can happen if Rhino embedding decided that nested
// scopes are useful for what ever reasons.
result = ScriptableObject.getProperty(scope, name);
if (result != Scriptable.NOT_FOUND) {
         if (!asFunctionCall){
		thisObj = scope;
		break;
	}
}
```
Since this is specific to the object being callable, this is another potential fix, without breaking any existing functionality.

**Comment by rbri** [comment]
Instead of changing rhino i have changed the scope definition during the event construction.
Looks like this solves the problem.

**Comment by rbri** [comment]
Please try the latest snapshot - this should be fixed now.

**Comment by duonglaiquang** [comment]
Thank you for fixing it. I will close the issue
