### ISSUE TITLE
not getpage

### ISSUE THREAD

**Issue by marlon-machado** [HtmlUnit/htmlunit#349]
when entering the url it remains blank and I get this error.
  origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by rbri** [comment]
Can you please add any details you have like the htmlunit version you are using and the url you calling and so on.
Without the details it will be really hard to help you.

Thanks

**Comment by marlon-machado** [comment]
url https://www.allia2net.com.co/ngx-epac/public/home
htmlunit version 2.20 jar

**Comment by rbri** [comment]
Sorry but without some more details to reproduce this here i can't help.
Will close this - please open a new one with more details if you need more help.
