### ISSUE TITLE
Error when click at the anchor - Setting innerText for html tags by HtmlUnit

### ISSUE THREAD

**Issue by ceceussj4** [HtmlUnit/htmlunit#351]
When I click at the anchor the server shows a log at error and the page doesn't update and I can not get the iframe tag.

The link page: "https://compras.cetiqt.senai.br/portal/Mural.aspx"

Here follows my code:

 try (final WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED)) {
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
        webClient.getOptions().setThrowExceptionOnScriptError(false);

    HtmlPage htmlPage = webClient.getPage("https://compras.cetiqt.senai.br/portal/Mural.aspx");
    webClient.waitForBackgroundJavaScript(20_000);

    DomNodeList tds = htmlPage.getElementsByTagName("td");
    HtmlTableDataCell td = (HtmlTableDataCell) tds.get(1);
    td.click();
    webClient.waitForBackgroundJavaScript(20_000);

    HtmlAnchor linkEdital = (HtmlAnchor) htmlPage.getByXPath("//a[@data-acao='edital']").get(0);
    linkEdital.click(); --Here happened the error. 
    webClient.waitForBackgroundJavaScript(20_000);
}

The server log:

2021-05-07 11:56:53.167 INFO 1632 --- [cTaskExecutor-1] .g.h.NicelyResynchronizingAjaxController : Re-synchronized call to https://compras.cetiqt.senai.br/portal/WebService/Servicos.asmx/PesquisarResumoEdital 2021-05-07 11:56:56.184 ERROR 1632 --- [cTaskExecutor-1] c.g.h.j.DefaultJavaScriptErrorListener : Error during JavaScript execution

com.gargoylesoftware.htmlunit.ScriptException: innerText is read-only for tag 'html' (https://compras.cetiqt.senai.br/Portal/Scripts/portaljs1?v=Ei-iqWxCMWoSqcf1vkTQ_kcBnknTwdegoFEvCAf9vgc1#1) Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: innerText is read-only for tag 'html' (https://compras.cetiqt.senai.br/Portal/Scripts/portaljs1?v=Ei-iqWxCMWoSqcf1vkTQ_kcBnknTwdegoFEvCAf9vgc1#1) at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$HtmlUnitErrorReporter.runtimeError(HtmlUnitContextFactory.java:460)

**Comment by rbri** [comment]
Work has started but will require some time. First step is to fix the innerText getter.

**Comment by rbri** [comment]
Have done some implementation for innerText - looks like your code works now.
Please try the latest snapshot.

**Comment by ceceussj4** [comment]
Thanks my friend! I will test today and will post here the result.

**Comment by ceceussj4** [comment]
Hi @rbi ! How are you?
Sorry about time long without answer. But my daughter born and I took off some days for help my wife.

About this problem I tried but the same error happened.
I changed in my pom.xml for version 2.50.0. 

Sorry too about my English.

**Comment by rbi** [comment]
@ceceussj4 I guess you meant @rbri instead of @rbi. I'm not involved in this issue.

**Comment by ceceussj4** [comment]
Hi @rbri ! How are you?
Sorry about time long without answer. But my daughter born and I took off some days for help my wife.

About this problem I tried but the same error happened.
I changed in my pom.xml for version 2.50.0.

Sorry too about my English.

**Comment by rbri** [comment]
:-)
Fine so far, but overloaded with work - so nothing new on my side.
Really strange - will have a look at this again.

**Comment by rbri** [comment]
My test code was:

    public static void main(String[] args) throws Exception {
        try (WebClient webClient = new WebClient(BrowserVersion.CHROME /*, "localhost", 8888*/)) {
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);

            HtmlPage htmlPage = webClient.getPage("https://compras.cetiqt.senai.br/portal/Mural.aspx");
            webClient.waitForBackgroundJavaScript(20_000);

            DomNodeList tds = htmlPage.getElementsByTagName("td");
            HtmlTableDataCell td = (HtmlTableDataCell) tds.get(1);
            td.click();
            webClient.waitForBackgroundJavaScript(20_000);

            HtmlAnchor linkEdital = (HtmlAnchor) htmlPage.getByXPath("//a[@data-acao='edital']").get(0);
            System.out.println("####-------------------------------");
            System.out.println("####-------------------------------");
            System.out.println(linkEdital.asXml());
            linkEdital.click();
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println("-------------------------------");
            System.out.println("-------------------------------");
            // System.out.println(page.asXml());
            System.out.println(htmlPage.asNormalizedText());
        }
    }

An this still runs without an error here (latest snapshot). 

I got this output (without any error) [output.txt](https://github.com/HtmlUnit/htmlunit/files/6696266/output.txt)

**Comment by ceceussj4** [comment]
Hi my friend @rbri ! How are you?

Sorry, but I test e continues the error:
My code :


    try (final WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED)) {
           webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);

            HtmlPage htmlPage = webClient.getPage("https://e-lic.sc.gov.br/portal/Mural.aspx");
            webClient.waitForBackgroundJavaScript(20_000);

            DomNodeList tds = htmlPage.getElementsByTagName("td");
            HtmlTableDataCell td = (HtmlTableDataCell) tds.get(1);
            td.click();
            webClient.waitForBackgroundJavaScript(20_000);


            HtmlAnchor linkEdital = (HtmlAnchor) htmlPage.getByXPath("//a[@data-acao='edital']").get(0);
            linkEdital.click();
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println("********************");
            System.out.println("********************");
            System.out.println(htmlPage.asXml());
            System.out.println("********************");
            System.out.println("********************");

            HtmlInlineFrame iframe = (HtmlInlineFrame) htmlPage.getElementById("frameResumoEdital");
            HtmlPage iPage = (HtmlPage) iframe.getEnclosedWindow().getEnclosedPage();
            System.out.println("********************");
            System.out.println("********************");
            System.out.println(iPage.asXml());
            System.out.println("********************");
            System.out.println("********************");

        }

--*****************************************************************************************************
When I test and try get iFrame  the variable  "iPage" is always like this:

<?xml version="1.0" encoding="UTF-8"?>
<html>
  <head/>
  <body/>
</html>

And in principal variable htmlPage "htmlPage" the tag iframe is not update.

 <iframe id="frameResumoEdital" src="" width="800px" height="425px">
 </iframe>

In the log continues show me:

com.gargoylesoftware.htmlunit.ScriptException: innerText is read-only for tag 'html' (https://e-lic.sc.gov.br/Portal/Scripts/portaljs1?v=Nm_n4jSJj-yOXIqEgzh2KW2EHpfyS5g24vLcUXg0tbQ1#1)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:949)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:650)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:540)

--********************************************************************************************************
Did you help me?

**Comment by rbri** [comment]
Strage,

your code passes here without any exception.

I have definitely removed the error msg from the code (see https://github.com/HtmlUnit/htmlunit/commit/3636f75b9a88c520a271ee982f136dc57661a872)

Can you please check again to only have the latest release 2.51.0 in your path.

**Comment by ceceussj4** [comment]
@rbri I would like say you are the best!
It's worked. HtmlUnit is very important for us here.
Thanks by your help.

**Comment by rbri** [comment]
Great - enjoy and feel free to open more issuse... and stars for the project are also welcome :-)
