### ISSUE TITLE
FormEncodingType

### ISSUE THREAD

**Issue by codingYouDianFeng** [HtmlUnit/htmlunit#364]
FormEncodingType lacks other ways of post request, such as application/json, remove final and private

**Comment by rbri** [comment]
Can you please add more details

**Comment by codingYouDianFeng** [comment]
such as request：
Request Method: POST
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 45
Content-Type: application/json;charset=UTF-8

**Comment by codingYouDianFeng** [comment]
new WebRequest(new URL("")).setEncodingType(FormEncodingType.TEXT_PLAIN);
FormEncodingType cannot set this type

**Comment by rbri** [comment]
you can use

webRequest_.setAdditionalHeader(HttpHeader.CONTENT_TYPE, "application/json;charset=UTF-8");

instead.

**Comment by codingYouDianFeng** [comment]
I already know that it’s a bit troublesome, can it be unified?
