### ISSUE TITLE
Compatibility with Selenium WebDriver 4

### ISSUE THREAD

**Issue by bonigarcia** [HtmlUnit/htmlunit#367]
I have the following error when trying to use it HtmlUnit with Selenium WebDriver 4:

```
The type org.openqa.selenium.internal.FindsByClassName cannot be resolved.
```

Is there any plan to make HtmlUnit compatible with Selenium 4?

**Comment by rbri** [comment]
Yes there is; the problem is the lack of time. But it looks like the Selenium 4 is getting closer to an release. Will try to find some time to have a deeper look.

**Comment by rbri** [comment]
There is a first release available.
