### ISSUE TITLE
Jquery 3 multiple $(document).ready() invoked out of order

### ISSUE THREAD

**Issue by dballardgh** [HtmlUnit/htmlunit#369]
HtmlUnit 2.51.0
JDK 8 or 11

With this HTML page:
```
<!DOCTYPE html>
<html>
<head>
<title>Jquery Ready Test</title>
</head>
<body>
<h1>Jquery Ready Test</h1>
<!--<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>-->
<!--<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="A.js"></script>
<script src="B.js"></script>
<script src="C.js"></script>
</body>
</html>
```

And the following script `A.js`:
```
console.error( "A.js loaded" );
$( document ).ready(function() {   
    console.error( "A ready" );
});
```

Script `B.js`:
```
console.error( "B.js loaded" );
$( document ).ready(function() {   
    console.error( "B ready" );
});
```
And script `C.js`:
```
console.error( "C.js loaded" );
$( document ).ready(function() {   
    console.error( "C ready" );
});
```

In a real browser I see that the files are processed in order, and the ready() functions are called in the order added:
```
A.js loaded
B.js loaded
C.js loaded
A ready
B ready
C ready
```

Using HtmlUnit 2.51.0:
```
private void runLocal() throws Exception {
  WebClient webClient = new WebClient();
  final HtmlPage page = webClient.getPage("http://localhost/mine.html");
  Thread.sleep(5000);
}
```
via the log I see:
```
SEVERE: A.js loaded
SEVERE: B.js loaded
SEVERE: C.js loaded
SEVERE: A ready
SEVERE: C ready
SEVERE: B ready
```

The files are loaded and processed in order, but under HtmlUnit, jquery is executing the ready functions out of order. The problem does not occur with jquery 1 or 2. The problem does occur with older versions of HtmlUnit. Not clear if this is related to issue #275. The problem does not occur with chrome, firefox, edge or IE.

**Comment by peberD** [comment]
Using html

```
<html>
    <head>
        <title>Jquery Ready Test</title>
    </head>
    <body>
        <h1>Jquery Ready Test</h1>
        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script>
            $(document).ready(function () {
                console.log("1 ready");
            });
            $(document).ready(function () {
                console.log("2 ready");
            });
            $(document).ready(function () {
                console.log("3 ready");
            });
            $(document).ready(function () {
                console.log("4 ready");
            });
            $(document).ready(function () {
                console.log("5 ready");
            });
            $(document).ready(function () {
                console.log("6 ready");
            });
        </script>
    </body>
</html>
```

log output:
```
info: 1 ready
info: 6 ready
info: 2 ready
info: 4 ready
info: 5 ready
info: 3 ready
```

The problem Htmlunit has with Jquery3 starts on line 3872 in jquery-3.6.0.js

```
// Support: Promises/A+ section 2.3.3.3.1
// https://promisesaplus.com/#point-57
// Re-resolve promises immediately to dodge false rejection from
// subsequent errors
            if (depth) {
                process();
            } else {

                // Call an optional hook to record the stack, in case of exception
                // since it's otherwise lost when execution goes async
                if (jQuery.Deferred.getStackHook) {
                    process.stackTrace = jQuery.Deferred.getStackHook();
                }
                window.setTimeout( process );
            }
```

Replacing

` window.setTimeout( process );`

with just

`process();`

makes it work and the output is now

```
info: 1 ready
info: 2 ready
info: 3 ready
info: 4 ready
info: 5 ready
info: 6 ready
```

Don't know why the timeout breaks this in HtmlUnit?

**Comment by peberD** [comment]
The problem can be isolated to:

```
<html>
    <head>
        <title>Timeout Test</title>
    </head>
    <body>
        <h1>Timeout Test</h1>
        <script>
            function timeoutFunction(nr) {
                return function () {
                    console.log(nr + " ready");
                }
            }
            for (let i = 1; i <= 10; i++) {
                setTimeout(timeoutFunction(i));
            }
        </script>
    </body>
</html>
```

HtmlUnit output:
```
info: 1 ready
info: 2 ready
info: 9 ready
info: 8 ready
info: 7 ready
info: 6 ready
info: 5 ready
info: 4 ready
info: 3 ready
info: 10 ready
```

Chrome, Firefox, Edge:
```
info: 1 ready
info: 2 ready
info: 3 ready
info: 4 ready
info: 5 ready
info: 6 ready
info: 7 ready
info: 8 ready
info: 9 ready
info: 10 ready
```

**Comment by dballardgh** [comment]
Hi @peberD,

Digging a little deeper here, using your scenario, when the page is loaded, the htmlunit `DefaultJavaScriptExecutor.run()` method loops over job managers and executes the earliest job. In this scenario, there is only one job manager. This job manager has a `PriorityQueue` named `scheduledJobsQ_`. Initially I can see all 10 jobs in the queue and they are in the expected order 1, 2, 3, 4, 5, 6, 7, 8, 9, 10.

The first loop iteration, `DefaultJavaScriptExecutor.run()` calls to run timeoutFunction 1 via  `jobManager.runSingleJob(earliestJob);`. That works fine, but the resulting `scheduledJobsQ_` is now in a different order, with 10 at the front of the queue, so we've got 10, 2, 3, 4, 5, 6, 7, 8, 9. The second iteration runs 10, and leaves the queue order 9, 2, 3, 4, 5, 6, 7, 8 and so on.

Looking at `JavaScriptJobManagerImpl.runSingleJob()`, there's a call to `this.scheduledJobsQ_.remove(job)` that removes the job from the queue. In our case, it is always the first element. It's the call to `remove(job)` that is reordering the queue.

It gets interesting looking at `java.util.PriorityQueue.remove(Object o)`. It delegates to internal call `removeAt(int i)` where `i` seems to be always 0 in our case. The internal javadoc for `removeAt()` says:

"Removes the ith element from queue. Normally this method leaves the elements at up to i-1, inclusive, untouched. Under these circumstances, it returns null. Occasionally, in order to maintain the heap invariant, it must swap a later element of the list with one earlier than i. Under these circumstances, **this method returns the element that was previously at the end of the list and is now at some position before i**. This fact is used by iterator.remove so as to avoid missing traversing elements."

Which appears to be exactly what is happening as far as I can tell. 

Regards,
Dave

**Comment by rbri** [comment]
i guess the fix will be easy - maybe later today

**Comment by rbri** [comment]
Thanks a lot @peberD and @dballardgh, you test case and your analyses are really awesome.
Fix is on the way, will make a new snapshot build as soon as the CI is happy (as always will inform on twitter).

Many many thanks....

**Comment by dballardgh** [comment]
Hi @rbri, I've confirmed that htmlunit-2.59.0-SNAPSHOT.jar fixes this issue.

**Comment by rbri** [comment]
Thanks

**Comment by peberD** [comment]
Nice work!
