### ISSUE TITLE
Css errors are noisy even with SilentCssErrorHandler enabled

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#378]
I believe there was a regression introduced in 2.52 that is not present in 2.51 - some parsing errors are thrown and show even when silenced handlers are enabled.

On 2.51 the log is silent, on 2.52 I see exceptions in the error log which is really messy. I don't want to disable error messages completely but silencing the webclient has no effect.

https://github.com/HtmlUnit/htmlunit/blob/4d174e28ad36c0800572c4aa096175bc2917755f/src/main/java/com/gargoylesoftware/htmlunit/html/DomElement.java#L284-L288

Link to git blame https://github.com/HtmlUnit/htmlunit/blame/master/src/main/java/com/gargoylesoftware/htmlunit/html/DomElement.java#L284

**Comment by rbri** [comment]
Correct, great finding! Thanks!

There is a new Snapshot build available (requires a htmlunit-cssparster snapshot). Please have a look if your problem is fixed.

**Comment by skyhirider** [comment]
Thanks for the quick fix, it's silent when using the snapshot. Cheers!

**Comment by rbri** [comment]
Thanks for the feedback, have fun using HtmlUnit.
