### ISSUE TITLE
Unable to find form or download file

### ISSUE THREAD

**Issue by JustThat70** [HtmlUnit/htmlunit#38]
As first reported on StackOverflow (https://stackoverflow.com/questions/55937076/htmlunit-not-finding-form-and-not-handling-postback?noredirect=1#comment98547960_55937076)

URL in question: https://www.pharmacy.ohio.gov/Licensing/RosterRequests.aspx

The following code fails to find any forms on the site, even though there is one, and never sees the postback download of the file once the Download button is clicked.

```
public static void main( String[] args ) throws IOException, InterruptedException {
        WebClient webClient;
        webClient = new WebClient( BrowserVersion.FIREFOX_60 );                    

        webClient.getOptions().setJavaScriptEnabled(false);
        webClient.getOptions().setUseInsecureSSL(true); 
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.getOptions().setSSLClientProtocols(new String[]{"TLSv1.2","TLSv1.1","TLSv1"});  
        webClient.setAjaxController(new NicelyResynchronizingAjaxController());

        HtmlPage MainPage = (HtmlPage) webClient.getPage("https://www.pharmacy.ohio.gov/Licensing/RosterRequests.aspx");
        HtmlElement body = MainPage.getBody();
        if (dbg) System.out.println("MainPage = " + MainPage); 

// All of the below are empty:

        System.out.println( "MainPageForm = " + MainPage.getFirstByXPath( "//*[@id=\"form1\"]"));
        System.out.println( "Form List = " + MainPage.getElementsByIdAndOrName( "form#form1"));
        System.out.println( "Form List = " + MainPage.getForms());
        System.out.println( "Form? = " + MainPage.querySelector("#form1"));
        System.out.println( "Form? = " + MainPage.getFirstByXPath( "//form[@action=\"RosterRequests.aspx\"]" ));
        System.out.println( "Form? = " + MainPage.getElementById( "#form1"));
        System.out.println( "MainPageButton = " + MainPage.getFirstByXPath( "//*[@id=\"phBody_rblLicenseType_5\"]") );

// Code to click buttons: 

HtmlRadioButtonInput rad_status = (HtmlRadioButtonInput)MainPage.getHtmlElementById("phBody_rblLicenseStatus_1");
rad_status.setChecked( true );
HtmlRadioButtonInput rad_tddd = MainPage.getHtmlElementById( "phBody_rblLicenseType_1");
rad_tddd.setChecked( true );
HtmlInput btn_download = (HtmlInput)MainPage.getHtmlElementById( "phBody_btnSubmit" );   
WebResponse response = btn_download.click().getWebResponse();

// ContentType never changes 

        int tries = 30;

        while ( tries > 0 ) {
            //System.out.println( response.getWebRequest().toString());
            System.out.println( response.getContentType());
            synchronized (response) { response.wait(1000);}

        tries--;
        }

        webClient.close();
    }
```

**Comment by rbri** [comment]
Thanks for the report - currently working on a fix.

**Comment by rbri** [comment]
This works now here with the lastest code

    public static void main(String[] args) throws IOException {
        final String url = "https://www.pharmacy.ohio.gov/Licensing/RosterRequests.aspx";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_60)) {
            HtmlPage page = webClient.getPage(url);

            System.out.println("----------------");
            System.out.println(page.asXml());
            System.out.println("----------------");

            HtmlRadioButtonInput rad_status = (HtmlRadioButtonInput)page.getHtmlElementById("phBody_rblLicenseStatus_1");
            rad_status.setChecked( true );
            HtmlRadioButtonInput rad_tddd = page.getHtmlElementById( "phBody_rblLicenseType_1");
            rad_tddd.setChecked( true );

            HtmlInput btn_download = (HtmlInput)page.getHtmlElementById( "phBody_btnSubmit" );

            WebResponse response = btn_download.click().getWebResponse();
            System.out.println(response.getContentType());

            try (InputStream in = response.getContentAsStream()) {
                try (FileOutputStream out = new FileOutputStream("c:/tmp/test.xlsx")) {
                    byte[] buffer = new byte[8 * 1024];
                    int bytesRead;
                    while ((bytesRead = in.read(buffer)) != -1) {
                        out.write(buffer, 0, bytesRead);
                    }
                }
            }
        }
    }

Will offer a new snapshot build soon. Please check https://twitter.com/htmlunit to get informed if the new build is available.
