### ISSUE TITLE
empty file input

### ISSUE THREAD

**Issue by ChrisFrostBSI** [HtmlUnit/htmlunit#383]
I have some JavaScript trying to clear file input element by setting the value to an empty string.  This showed 2 problems.

1: The change event should not call if JavaScript changes the value (checked on Chrome 93 and Firefox 92).

2: The file list should be empty but instead it has 1 file in the list.  This path for that file is my current working directory.  The same problem occurs with using setValue in Java test code.

**Comment by rbri** [comment]
Will have a look

**Comment by rbri** [comment]
Hopefully fixed.

> The same problem occurs with using setValue in Java test code.

Have to investigate this later.

Will inform on twitter if a new snapshot is available.

**Comment by rbri** [comment]
I fear i do not really understand your case. Can you please provide more details - best will be a case similar to 

public void setValueOnChange() in file https://github.com/HtmlUnit/htmlunit/blob/5739bd17338ff036ee63c98ce2b42ab8d91fcc9e/src/test/java/com/gargoylesoftware/htmlunit/html/HtmlFileInputTest.java

**Comment by rbri** [comment]
@ChrisFrostBSI can you please provide any more details - see the other comments; otherwise i will close this

**Comment by ChrisFrostBSI** [comment]
My live code is overwhelmed with 3rd party libraries, but I did simplify the issue to setting an empty value on a file input for the purpose of clearing the file inputted.  In my situation this is being done after fetching json inside an angularjs component.  Currently we are forcing the file input to empty everytime the angularjs fetches json (when first loading and after saving changed data).

I have been unable to get those webdriver tests working locally. My tests usually look very different but as an example using both htmlunit and webdriver with chrome here are some test.  I hope this helps.

    @Test
    public void clearFileInput() throws Exception {
        try (WebClient client = new WebClient(BrowserVersion.BEST_SUPPORTED)) {
            final HtmlPage page = client.getPage("about:blank");
            page.executeJavaScript("const f = document.createElement('input');"
                + "f.type=f.id='file';document.body.appendChild(f);");
            final HtmlFileInput file = (HtmlFileInput) page.getElementById("file");
            assertEquals(0, file.getFiles().length);
            page.executeJavaScript("f.value='';");
			// add to compare with webdriver
            assertEquals(0, page.executeJavaScript("f.files.length").getJavaScriptResult()); // failing because length = 1
            assertEquals(0, file.getFiles().length); // failing because length = 1
        }
    }

    @Test
    public void clearFileInputWebDriver() throws Exception {
        WebDriverManager.chromedriver().setup();
        final WebDriver driver = new ChromeDriver();
        try {
            final JavascriptExecutor js = (JavascriptExecutor) driver;
            driver.get("about:blank");
            js.executeScript("const f=window.f=document.createElement('input');"
                + "f.type=f.id='file';document.body.appendChild(f);");
            assertEquals("0", js.executeScript("return f.files.length").toString());
            js.executeScript("f.value='';");
            assertEquals("0", js.executeScript("return f.files.length").toString()); // passes
        } finally {
            driver.close();
        }
    }

**Comment by rbri** [comment]
Hi @ChrisFrostBSI, sorry for being that late on this...
Have added your test case and it looks like it is working fine. Can you please check if this works for you with the latest release.

Again sorry

**Comment by rbri** [comment]
> The same problem occurs with using setValue in Java test code

Ok i think i got your point now. This is fixed now also.

**Comment by rbri** [comment]
No further complains - i guess this works now. Please reopen if you still have problems.
Many thanks for this.
