### ISSUE TITLE
HTMLUNIT - Problem to get all columns from a table

### ISSUE THREAD

**Issue by ceceussj4** [HtmlUnit/htmlunit#384]
I need more a help. 
I am trying to get all columns of row of table but the variable get just 3 cells and I looked this html of page there is 7 columns.

@rbri do you help me?

I appreciate the help.

Follow the code

public class BotEditalCapturaProcesoEletronicoDispensaRJ { 

  private static final String url = "https://www.compras.rj.gov.br/Portal-Siga/ProcessoEletronicoDispensa/buscar.action";
  
  public static void main(String[] args){
      disableLogs();
      System.out.println("Starting RPA PED ...");
      initialProcess();
  }

public static void initialProcess(){
    // Init process
    WebClient client = new WebClient(BrowserVersion.BEST_SUPPORTED);

    CookieManager cookieManager = client.getCookieManager();
    cookieManager.setCookiesEnabled(true);
    client.setCookieManager(cookieManager);

    client.getOptions().setPopupBlockerEnabled(true);
    client.getOptions().setThrowExceptionOnFailingStatusCode(false);
    client.getOptions().setJavaScriptEnabled(true);
    client.getOptions().setCssEnabled(false);
    client.getOptions().setUseInsecureSSL(true);
    client.getOptions().setRedirectEnabled(true);
    client.setAjaxController(new NicelyResynchronizingAjaxController());
    client.getOptions().setThrowExceptionOnScriptError(false);

    try{
        System.setProperty("https.protocols", "TLSv1,TLSv1.1,TLSv1.2");
        System.out.println("Getting website...");

        // Get the website
        HtmlPage webPortal = client.getPage(url);
        client.waitForBackgroundJavaScript(5 * 1000);
        Set<Cookie> cookies = client.getCookieManager().getCookies();

        // Get the status select list and search link
        HtmlSelect selectStatus = (HtmlSelect) webPortal.getElementById("andamentoPed");
        HtmlAnchor btnSearch = (HtmlAnchor) webPortal.getElementById("pesquisar");
        // List the status options
        DomNodeList<HtmlElement> optionStatusList = selectStatus.getElementsByTagName("option");

        // Iterate over each status option
        for(int i = 0; i < optionStatusList.size(); i++){
            HtmlOption currentOption = (HtmlOption) optionStatusList.get(i);

            // Selecione it's a default text without value, we're going to search in the other options
            if(!currentOption.getText().equals("Selecione")){

                // Select the current iteration status and click search button
                selectStatus.setSelectedAttribute(currentOption, true);
                btnSearch.click();

                // Wait for the page
                client.waitForBackgroundJavaScript(15 * 1000);
                Page page = client.getCurrentWindow().getEnclosedPage();
                page.initialize();
                HtmlPage dataPage;

                // Sometimes, the page is returned as TextPage, compare this cases
                if(page instanceof TextPage){
                    System.out.println(currentOption.getText() + " it's a TextPage");
                    continue;
                }
                else{
                    dataPage = (HtmlPage) page;
                }

                System.out.println(currentOption.getText() + " page: " + dataPage.getBaseURL().toString());

                // If the result is a HtmlPage and the URL is distinct to original page we have results in the current status
                if(webPortal == dataPage) {
                    System.out.println("Not results for : " + currentOption.getText());
                }
                else{
                    System.out.println("Results for: " + currentOption.getText());
                    readPEDTable(dataPage, currentOption.getText());
                }

                // Return to original search page to go for next status
                client.getCurrentWindow().getHistory().back();
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        client.getCurrentWindow().getJobManager().removeAllJobs();
        client.close();
        System.gc();
    }
}

public static void readPEDTable(HtmlPage dataPage, String currentStatus){
    HtmlTable grid = (HtmlTable) dataPage.getElementById("dataTable");
    HtmlTableBody gridBody = grid.getBodies().get(0);
    List<HtmlTableRow> gridRows = gridBody.getRows();

    for (int i = 0; i < gridRows.size(); i++) {
        HtmlTableRow currentRow = gridRows.get(i);

        List<HtmlTableCell> cells = currentRow.getCells();
        for (int j = 0; j < cells.size(); j++) {
            System.out.print(cells.get(j).getTextContent() + " \t\t");
        }
        System.out.print(currentStatus);
        System.out.println("");
    }
}

      public static void disableLogs(){
          Set<String> artifactoryLoggers = new HashSet<>(Arrays.asList("org.apache.http", "com.gargoylesoftware"));
          for(String log:artifactoryLoggers) {
              ch.qos.logback.classic.Logger artLogger = (ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory.getLogger(log);
              artLogger.setLevel(ch.qos.logback.classic.Level.INFO);
              artLogger.setAdditive(false);
          }
      }
}

**Comment by rbri** [comment]
Have tried to reproduce your code but i got

The requested URL was rejected. Please consult with your administrator.

Your support ID is: 661349863259856913

**Comment by ceceussj4** [comment]
Really? I can access this url. Will be because you are in other country?

But look how this error is strange.
When I try getCells() my variable just show me 4 cells. but the table have 7 cells.

I look in the html page and it's ok

P.S: I defined client.getOptions().setCssEnabled(true) so the 4 column was displayed. Before it was only shown 3

<img width="1127" alt="Captura de Tela 2021-09-23 às 14 50 18" src="https://user-images.githubusercontent.com/71467990/134559425-2711099e-4aec-4eeb-aa52-ba51d7a73ee4.png">


<img width="1103" alt="Captura de Tela 2021-09-23 às 14 50 51" src="https://user-images.githubusercontent.com/71467990/134559648-67c36c51-04d8-42d5-8d6d-0b27df975fe1.png">


<img width="541" alt="Captura de Tela 2021-09-23 às 14 57 38" src="https://user-images.githubusercontent.com/71467990/134559680-ba974985-e6b7-4d69-81d1-0629d9c7708b.png">

**Comment by rbri** [comment]
Will try with some VPN. Can you please check if the table in page.asXML() is also correct

**Comment by rbri** [comment]
OK got it working using VPN and a US server. Will have a look later on.

**Comment by ceceussj4** [comment]
@rbri thank you so much. I appreciate your help.
In page.as Xml just is showed the 4 collumn the correct would be 7 column.

<img width="1083" alt="Captura de Tela 2021-09-24 às 09 37 05" src="https://user-images.githubusercontent.com/71467990/134677517-154a7243-7ec7-4ca9-a011-a1445244767f.png">

**Comment by rbri** [comment]
Ok, did a first look at this, i think the table is generated at runtime from javascript. At the moment i have no idea why the two columns are missing.
Will try to have a deeper look at this during next week.

**Comment by ceceussj4** [comment]
Ok my Friend! Thank you so much.

**Comment by ceceussj4** [comment]
Hi my friend! How are you? Really this problem is strange. 
I tried everything but I can't get all columns of the table. I setted more time in this wait, I put the true and false in many variables, but not changed the result.

**Comment by rbri** [comment]
hi and sorry but for private reasons there was no chance to work on this so far

Today i took the option to debug this monster several hours and finally found the reason.
The list you like to grab is a jquery datatable control; an js monster having many cool options to do some magic. And your one is set up to be responsible - means adapt to the screen/window size.

As HtmlUnit a a headless browser all the layout related calculations are more worst guesses than correct values. And this is what happens here, the columns are simply cuted because it looks like there is no enough space on the screen.

So let us make mooooooooore room by adding this to your setup section on top

    client.getCurrentWindow().setInnerWidth(40_000);
    client.getCurrentWindow().setOuterWidth(40_020);

And voila :-)

Thanks for using HtmlUnit
    and please ask your boss for sponsoring ;-)
    or at least ask your colleges to star this project

**Comment by rbri** [comment]
Good morning,

after some sleep and a fresh shower in the morning :-) i had a better idea. The width estimation for the header cell was based on a stupid calculation of the content an thereof far away from reality in your case.
Based on some work done some weeks ago i was able to replace this with a much better content calculation that condenses e.g. white space if needed.
And with this fix the whole table is visible - no need to expand your window.

As always i will inform on twitter if a new snapshot is available. Will try to finally close some more issue and make a new release soon.

Have a nice weekend
    RBRi
