### ISSUE TITLE
normalize space not parsing correctly under some circumstances

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#386]
I am using an xpath that includes a special character and the xpath is working in Firefox but failing in HtmlUnit when called via the driver.

What is odd is that it works for "@x" but fails for "@X" - case sensitivity breaks it somehow. Its also interesting that I noticed this earlier when searching for "=)" as part of a string, I presume there are other special cases that are not working correctly.

Edit: tested  more and same issue with ")X" but lowercase x works fine.

The code I used to test

```java
public class HtmlUnitXpath {
    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "\\geckodriver.exe");
        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.FATAL);
        WebDriver ffDriver = new FirefoxDriver(options);
        WebDriver huDriver = new HtmlUnitDriver(BrowserVersion.FIREFOX, true) {
            @Override
            protected WebClient modifyWebClient(WebClient client) {
                final WebClient webClient = super.modifyWebClient(client);
                WebClientOptions options = webClient.getOptions();
                options.setCssEnabled(true);
                options.setThrowExceptionOnScriptError(false);
                webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener());

                return webClient;
            }
        };
        try {
            doStuff(ffDriver);
            doStuff(huDriver);
        } finally {
            ffDriver.close();
            huDriver.close();
        }
    }

    private static void doStuff(WebDriver driver) {

        String misbehavingString = "@X";
        String pageAsText = "<body><table><tr><td>" + misbehavingString + "</td></tr></table></body>";
        driver.get("data:text/html;charset=utf-8," + pageAsText);
        String text = driver.findElement(By.xpath("//body")).getText();
        System.out.println(driver.getClass().getName() + " printed " + text);
        int numberOfOccurences = driver.findElements(By.xpath("//td[normalize-space()='" + misbehavingString + "']")).size();
        System.out.println(driver.getClass().getName() + " found " + numberOfOccurences);
    }
}

**Comment by rbri** [comment]
nice catch - found the reason and start thinking about a solution

**Comment by rbri** [comment]
Ok, this was another strange one and many thanks to nail down the problem to this point.

HtmlUnits XPath handling does some manipulation of the xpath before calling xalan to handle case insensitive processing of html code. This preprocessing was too stupid - in your case the string '@X' was handled like an attribute selector and therefore changed to '@x'. Have changed the code to take care of strings.
This also fixes the problem if the string contains ( or ) as you also mention.

Again many thanks for reporting this - watch out on twitter for a new snapshot.

**Comment by skyhirider** [comment]
Thanks, will test it out on Monday if it covers all the corner cases I had issues with. Took me a while to pinpoint this one, first though it was encoding or something else at first but your patch enabling data:text in the driver really helped.

**Comment by rbri** [comment]
> Took me a while to pinpoint this one

That's for most of the problems with HtmlUnit the hardest part of the story. If i have a simple test case the issue is usually more or less solved.
That's the reason why i so happy with bug reports like this one (and a try to fix it fast).

**Comment by skyhirider** [comment]
Yeah, I always try to imagine if it was me doing the bug testing and fixing, the more info I have the faster I can fix it. Plus shows I at least tried to find the cause instead of pasting a generic error code and asking for help.
