### ISSUE TITLE
XMLHttpRequest-class is missing `response`-attribute

### ISSUE THREAD

**Issue by markoandersson** [HtmlUnit/htmlunit#388]
I think that there should be `response`-attribute in the [XMLHttpRequest-class](https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/xml/XMLHttpRequest.java) as stated in the [XMLHttpRequest-specification](https://xhr.spec.whatwg.org/#the-response-attribute).

I stumbled on to this when debugging 3rd party Javascript library which didn't work with HtmlUnit and it relied on `xhr.response`-attribute when handing Ajax responses.

Is there any workaround for this issue, for example, could I extend HtmlUnit's XMLHttpRequest-class and use it instead?

Thanks for any assistance.

**Comment by rbri** [comment]
Sorry there is not really a work around for this.
Will try to fix this soon - do you use the latest version?

**Comment by markoandersson** [comment]
Yes, version 2.53.0.

Thanks for the quick reply!

**Comment by rbri** [comment]
ok great, will have a look and come back to you (hopefully) soon.
Usually the implementation of that is not that hard (e.g. responseText is already here but writing detailed test for most of the cases takes some time.

**Comment by rbri** [comment]
Just made a new Snapshot build including a first impl for this. Please try and report your findings.

**Comment by markoandersson** [comment]
Works like a charm! Thank you for your fast response!

Btw. the third-party JS library is [htmx](https://htmx.org/) and after this fix, at least all our (basic) use cases are covered and working with HtmlUnit.

With version 2.53.0 I got an error

```
2021-09-30 08:16:30.329 ERROR 91688 --- [           main] c.gargoylesoftware.htmlunit.WebConsole   : htmx:swapError
2021-09-30 08:16:30.338 ERROR 91688 --- [           main] c.gargoylesoftware.htmlunit.WebConsole   : TypeError: Cannot call method "indexOf" of undefined
```

And with the snapshot version, our unit tests are passing.

**Comment by rbri** [comment]
Great. Thanks for the fast feedback and the report.

**Comment by rbri** [comment]
Have added initial support for contentType 'document'.
