### ISSUE TITLE
offsetHeight too large for grid aranged elements

### ISSUE THREAD

**Issue by cdalexndr** [HtmlUnit/htmlunit#39]
Using `HTMLElement::getOffsetHeight` method returns a value that is too large.
This method is using `ComputedCSSStyleDeclaration::getTop` method that calculates the top value by adding previous siblings height. When the elements are arranged into a grid, this value is incorrect, because only previous sibling rows affect the top position, not all elements.

**Comment by rbri** [comment]
Thanks for the report, it will be great if you can provide some more details - or better a short example - to make your point a bit more clear for me.

**Comment by cdalexndr** [comment]
For the following html, computing the height of the body, results in 100px, instead of 50px.
https://jsfiddle.net/xqfd1vnL/

**Comment by rbri** [comment]
test added com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement2Test.offsetHeightFloatLeft()

but:

com.gargoylesoftware.htmlunit.javascript.host.html.HTMLElement.getOffsetHeight() does not use getTop(). Where is my mistake?

**Comment by cdalexndr** [comment]
htmlunit-2.33
`ComputedCSSStyleDeclaration.java::getContentHeight()`

```
       for (final ComputedCSSStyleDeclaration style : styles) {
            final int h = style.getTop(true, false, false) + style.getCalculatedHeight(true, true);
            if (h > max) {
                max = h;
            }
        }
```

**Comment by rbri** [comment]
Fixed with the current snapshot build.
