### ISSUE TITLE
Testexecution Thread stopped endless

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#390]
While test execution of different scenarios the test execution hangs in:

	Unsafe.park(boolean, long) line: not available [native method]	
	LockSupport.park(Object) line: 175	
	CountDownLatch$Sync(AbstractQueuedSynchronizer).parkAndCheckInterrupt() line
	
This happens for different actions on Html pages

- webWindow.getWebClient().getPage(pUrl)
- htmlElement.click();

If the action runs into the following method and js script is enabled, the thread is parked forever

	HtmlPage.executeEventHandlersIfNeeded(String)

An analysis shows that this behavior shows up since commit c23eaf8865291de1d031d6e9140b76eb7b19102f ("use our own executorService") from 11. Apr 2020
The number of Websockets threads for our testapplication is often greater than 10. The fixed size of the added threadpool leads to an endless wait.

Supposed fix: switch to a cached ThreadPool.
Replace in com.gargoylesoftware.htmlunit.WebClient.getExecutor() fix value of "10" into:

`final ThreadPoolExecutor tmpThreadPool = (ThreadPoolExecutor) Executors.newCachedThreadPool();`

**Comment by rbri** [comment]
Many thanks for pointing at this and the fix.

Have added an option to replace the executor with your own one and also some documentation.
Maybe you can have a short look at the changes and provide some feedback.

https://github.com/HtmlUnit/htmlunit/commit/46dd88b6490c23dda2e79544d20df146cb0d331e

**Comment by Deadc00l** [comment]
Looks fine me, thanks a lot.

**Comment by rbri** [comment]
Made a new snapshot in between - you can try it now in reality.
