### ISSUE TITLE
`ProxyConfig` class: Support for proxy server credentials: `user` and `password`

### ISSUE THREAD

**Issue by svbrunov** [HtmlUnit/htmlunit#394]
Dear Maintainers,

I am using HtmlUnit 2.53.0.
My current use case: get a page through the configured **authenticating** SOCKS5 proxy server.
I have not found the ability to specify the credentials for the proxy server.
It seems that such ability is not supported.

It would be great to have the ability to specify the proxy server credentials using the extended `ProxyConfig` class with the `user` and `password` properties (constructor, getters, etc.).

# Update
An issue related to the current issue (the feature request): [HtmlUnit / Bugs / #1960 Authenticated SOCKS5 with username/password does not work](https://sourceforge.net/p/htmlunit/bugs/1960/).

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
Hi Sergey,

can you please try something similar to this

        credentialProvider = new DefaultCredentialsProvider();
        webClient.setCredentialsProvider(credentialProvider);

        tmpCredentialProvider.addCredentials(proxyUser, proxyPassword, proxyHost, proxyPort, null);

If my memories are correct this should work.... but ;-)

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

Thank you very much for the prompt reply!

I have applied your suggestion as follows:

```java
final String socks5ProxyHost = "HOST";
final int socks5ProxyPort = 30000;
final String socks5ProxyUser = "USER";
final String socks5ProxyPassword = "PASSWORD";

final ProxyConfig proxyConfig = new ProxyConfig(socks5ProxyHost, socks5ProxyPort, null, true);
webClient.getOptions().setProxyConfig(proxyConfig);

final DefaultCredentialsProvider credentialProvider = new DefaultCredentialsProvider();
webClient.setCredentialsProvider(credentialProvider);
credentialProvider.addCredentials(socks5ProxyUser, socks5ProxyPassword, socks5ProxyHost, socks5ProxyPort, null);

<…>

final HtmlPage page = webClient.getPage("https://web-server-here.ru/");
```

The exception with the following stack trace (provided partially) is thrown:

```
java.net.SocketException: SOCKS: Connection not allowed by ruleset
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:490)
	at java.base/java.net.Socket.connect(Socket.java:645)
	at com.gargoylesoftware.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.connectSocket(HtmlUnitSSLConnectionSocketFactory.java:172)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:192)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1582)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1504)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:493)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:413)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:548)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:529)
<…>
```

The exception represents an authentication error.

Verified the same proxy server with `curl`:

```shell
$ curl -v --proxy 'socks5://USER:PASSWORD@HOST:PORT/' …
```

It works fine.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
Ok, will try to have a deeper look at this... thanks for the details.

**Comment by rbri** [comment]
After digging around and doing some check (without having a chance to test this with a real proxy) i think there no no really nice solution.

But as a first step it will be great if you can do something like this before setting up your client (taken from https://stackoverflow.com/questions/51269160/apache-httpclient-socks5-proxy-with-authentication)

    Authenticator.setDefault(new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(proxyUser, proxyPassword.toCharArray());
        }
    });

If this works we can discuss about adding some support in HtmlUnit.

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

Thank you very much for your support!

I have applied the workaround you suggested and verified it: it works fine.

This workaround does not cover my use case «completely».
There is the need to assign a specific SOCKS5 proxy server (with its credentials, etc.) for each instance of the `WebClient` class.
Therefore, my first message of this GitHub issue (the feature request) is actual.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
Hi Sergey,

thansk for the fast reply, your problem is clear.
But: :-)
This java Authenticator stuff is something global for the JVM and there is no way (as far as i can see) to handle this graceful (e.g. by decoration the current one and forward all requests not for HtmlUnit to the decorated one).

I think i have an idea how to handle this in HtmlUnit but this requires some more time.

But for your code you can enhance the workaround a bit

    Authenticator.setDefault(new Authenticator() {
        protected PasswordAuthentication getPasswordAuthentication() {
            if (  check condition  ) {
                return new PasswordAuthentication(proxyUser, proxyPassword.toCharArray());
            } else ....
        }
    });

For checkCondition you have access to
* getRequestingHost()
* getRequestingPort()
* getRequestingPrompt()
* getRequestingProtocol()
* getRequestingScheme()
* getRequestingSite()
* getRequestingURL()
* getRequestorType()
of the current request. Based on this is should be possible to implement the single authenticator that handles all your different proxies.

My plan is to implement a (generic) authenticator that handles all SOCKS proxies with credentials known by HtmlUnit and set this for the jvm.

Please try and give me a sign, if the enhanced workaround does the job for you. Hope we can implement the  HtmlUnit support for this based in this step by step approach.

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

> Please try and give me a sign, if the enhanced workaround does the job for you. Hope we can implement the HtmlUnit support for this based in this step by step approach.

Thank you very much for your support!
I have a suitable network level workaround for my use case.

P.S. Just for your information.
I have updated the description (the first message) of this GitHub issue: added a link to a related issue.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
> I have a suitable network level workaround for my use case.

Network level means you have solved this outside of Java/HtmlUnit? So no need to improve this further?

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

> Network level means you have solved this outside of Java/HtmlUnit?

Yes.

> So no need to improve this further?

The network level workaround is just a workaround (i.e. a temporary solution).
Therefore, there is a need.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
Hopefully the current snapshot solves this problem.

Please have a look at the (new) proxy configuration docu at https://htmlunit.sourceforge.io/proxy-howto.html and try the latest snapshot build with your setup.

**Comment by rbri** [comment]
@svbrunov any update on this?

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

I have just tested the `2.55.0-SNAPSHOT` (`2.55.0-20211021.173458-2`) version: it does not work correctly: authentication fails.
The root cause: this version does not use the specified credentials.

I have debugged this version a little bit: in particular, the `SocksProxyAuthenticator` class.

Please, see the following partial screenshot:
![image](https://user-images.githubusercontent.com/3449295/139523948-d480162e-70c6-40f4-8e25-a387cdd2d72a.png)

The problem is that the `getRequestorType()` method returns the `RequestorType.SERVER` value.

I am not going to continue the analysis further.
But I would like to share with you an interesting related example of the SOCKS proxy detection: [git.jetbrains.org - idea/community.git/commitdiff](http://git.jetbrains.org/?p=idea/community.git;a=commitdiff;h=bd5d0e2ab439b97c4e99fa8c6934b959e69d7969).

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
Ok thanks will make a new snapshot available

**Comment by rbri** [comment]
Please try the new snapshot

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

I have just tested the `2.55.0-SNAPSHOT` (`2.55.0-20211031.121914-4`) version: it works fine with the authenticating SOCKS proxy server.

Best regards,
Sergey Vyacheslavovich Brunov.

**Comment by rbri** [comment]
thanks for the feedback and all your debug work

**Comment by svbrunov** [comment]
Dear RBRi (@rbri),

Thank you too: for your work and collaboration!

Best regards,
Sergey Vyacheslavovich Brunov.
