### ISSUE TITLE
HtmlSerializer css white-space

### ISSUE THREAD

**Issue by cdalexndr** [HtmlUnit/htmlunit#397]
All variants of `HtmlSerializer` (even `HtmlSerializerVisibleText`) for html
`<span style='white-space:pre'>a\nb</span>`
output `a b`, but in browser it's displayed as `a\nb`.

Only `<pre>` tag is respected (wrap in `<pre>`).

**Comment by cdalexndr** [comment]
Note that for `HtmlSerializerVisibleText` class that takes into account css `white-space`, it works only when computing directly on an element:
` page.getElementById("tester").getVisibleText()` will return the correct value `a\nb`
but using `page.getVisibleText()` will return incorrectly `a b`

**Comment by rbri** [comment]
Have adapted you solution a bit to avoid traversing the parent tree many times. Hope this fix you problem (at least the tests are passing).
Please provide more tests if you still have problems.

Again Thanks for your contributions.
