### ISSUE TITLE
Cookie Request

### ISSUE THREAD

**Issue by harryizquierdo** [HtmlUnit/htmlunit#4]
Problem when sending cookie parameters in the header, when I send using curl it responds correctly, when making the request from htmlunit I get an HTTP status returned 999, that state responds when cookies are sent badly. Please your help.

**Request Curl:**
`
curl -I 'https://ec.linkedin.com/company/momazomio' -H 'authority: ec.linkedin.com' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'accept-language: es-ES,es;q=0.9' -H 'cookie: JSESSIONID=ajax:3008950748410332945; lang=v=2&lang=es-es; bcookie="v=2&1b9a53aa-8cfd-473a-8b7c-07da777b033d"; bscookie="v=1&20181025151642877f5366-e950-4fda-8a93-431be2f1fb13AQEIiBWXdWzaopBR2O7mvKIPHB3qPHqG"; lidc="b=TGST05:g=1105:u=1:i=1540480602:t=1540567002:s=AQEena2MYZkALwCkBgYd4rhY9yzSMsea"; _ga=GA1.2.733376380.1540480609; _gat=1' --compressed
`

**Request Java:**

        WebClient client = new WebClient();
        client.getOptions().setCssEnabled(false);
        client.getOptions().setJavaScriptEnabled(false);
        client.getOptions().setThrowExceptionOnFailingStatusCode(false);//para tomar todos los estados HTTP
        client.getOptions().setPrintContentOnFailingStatusCode(false);
        client.getCookieManager().setCookiesEnabled(true);
        try {
            String searchUrl = "https://ec.linkedin.com/company/festinfest";
            WebRequest request = new WebRequest(new URL(searchUrl), HttpMethod.GET);
                    
            Map<String, String> headers = new HashMap<String, String>();
            headers.put("authority","ec.linkedin.com");
            headers.put("pragma","no-cache");
            headers.put("cache-control","no-cache");
            headers.put("upgrade-insecure-requests","1");
            headers.put("user-agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36");
            headers.put("accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8");
            headers.put("accept-encoding","");
            headers.put("accept-language","es-ES,es;q=0.9");
            headers.put("cookie","JSESSIONID=ajax:3008950748410332945; lang=v=2&lang=es-es; bcookie=\"v=2&1b9a53aa-8cfd-473a-8b7c-07da777b033d\"; bscookie=\"v=1&20181025151642877f5366-e950-4fda-8a93-431be2f1fb13AQEIiBWXdWzaopBR2O7mvKIPHB3qPHqG\"; lidc=\"b=TGST05:g=1105:u=1:i=1540480602:t=1540567002:s=AQEena2MYZkALwCkBgYd4rhY9yzSMsea\"; _ga=GA1.2.733376380.1540480609; _gat=1");
            request.setAdditionalHeaders(headers);

            Page page = client.getPage(request);
            WebResponse response = page.getWebResponse();
            int x = response.getStatusCode();
            System.err.println("status" + response.getStatusCode());
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by rbri** [comment]
Can you please use some local proxy (like Charles or Fiddler) to capture and compare the data send over the wire. This will be a great help.

**Comment by rbri** [comment]
@harryizquierdo any news for this one? Will close it otherwise.

**Comment by rbri** [comment]
Will close this for now. Have done some more cleanup on request header handling. If you like to have this solved use a web proxy and provide more details.
