### ISSUE TITLE
Origin request header same as page URL on HtmlSubmitInput.click()

### ISSUE THREAD

**Issue by amarkevich** [HtmlUnit/htmlunit#40]
```
HtmlPage page1 = webClient.getPage(url_with_query_parameters);
HtmlForm form = page1 .getFormByName("...");
HtmlSubmitInput button = form.getInputByName("...");
HtmlPage page2 = button.click(); // Origin header is the same as url_with_query_parameters
```
Expected [1]
> scheme "://" host [ ":" port ]

For version 2.31 following workaround works:
`webClient.addRequestHeader(HttpHeader.ORIGIN, "https://localhost:12345");`

1. https://tools.ietf.org/html/rfc6454#section-7

**Comment by rbri** [comment]
have added two more test cases; they working fine and the result is the same when using the real browsers.
Please check if there is any misunderstanding from my side.

Commit: https://github.com/HtmlUnit/htmlunit/commit/a3f91aea7b7f697bf8631301d14a49a083cbd93d

**Comment by rbri** [comment]
A fix similar to your PR is on the way. Check on twitter if a new snapshot build is available
