### ISSUE TITLE
How do I close all logs?

### ISSUE THREAD

**Issue by tea-blog** [HtmlUnit/htmlunit#400]
How do I close all logs?:(
All this.:(
![image](https://user-images.githubusercontent.com/68322136/140467199-7267c2e0-a7f1-4abc-b571-b33e0f01f5d4.png)

**Comment by tea-blog** [comment]
I tried to download the source code and annotate all the LOG logs, but I failed to package it into a jar.
![image](https://user-images.githubusercontent.com/68322136/140468517-78ade137-5282-447e-9ae0-f6f44e084034.png)
![image](https://user-images.githubusercontent.com/68322136/140467793-6c7d73a1-8b6c-406a-8dc1-39071de61221.png)
![image](https://user-images.githubusercontent.com/68322136/140468054-4e4386e2-d407-4ad8-b4fb-317bd512ae08.png)

**Comment by rbri** [comment]
Please have a lock at https://htmlunit.sourceforge.io/logging.html.

**Comment by rbri** [comment]
Have you solved that? Can i close this issue?

**Comment by rbri** [comment]
Will close this, feel free to open a new one if you need more support regarding this.

**Comment by tea-blog** [comment]
sorry, i have not been informed of this answer... 
I haven't solved it yet. 
I have added restrictions according to the document, but a print log will appear. 
I open a new to u,need ur help...
