### ISSUE TITLE
How to reduce CPU occupancy？

### ISSUE THREAD

**Issue by tea-blog** [HtmlUnit/htmlunit#404]
The jar package started on Linux has a very high CPU share when calling this HtmlUnit utility class. Is there any way to reduce it?
:(

![image](https://user-images.githubusercontent.com/68322136/140853694-f7f982d0-b441-4572-8872-080283c36735.png)

**Comment by rbri** [comment]
Please provide more details - e.g. what utility you call

**Comment by tea-blog** [comment]
Sorry.
I wrote a recursive method to access more pages using htmlunit to get more business content.
When there is a request, the CPU share is suddenly very high, and then it gradually stabilizes.
Are there any methods and suggestions for improvement?（Please）
Thank Q!
```java
         public void doPagesReptileBFs(String nowHtml, int deep) {
		if (deep > 10)return;
		urlMap.put(nowHtml, "right");
		List<String> htmlList = new ArrayList<>();
		HtmlPage page = null;
		try {
			page = webClient.getPage(nowHtml);
		} catch (IOException e) {
			e.printStackTrace();
		}
		if (page == null || page.getWebResponse().getStatusCode() != 200)return;

		DomNodeList<DomElement> domList = page.getElementsByTagName("a");
		if (domList == null || domList.getLength() == 0)return;
		for (DomElement dom : domList) {
			// URL processing...
			if(urlMap.get(URL) != null)continue;
			doPagesReptileBFs(URL, deep+1);
		}
	}
```

![image](https://user-images.githubusercontent.com/68322136/141227454-44d37194-6fb4-4eb3-ae6a-2d56a1005ce9.png)

**Comment by rbri** [comment]
First comment:
waitForBackgroundJavascript is not an setting, this call really waits - because you have not opened an url the call is useless.

**Comment by rbri** [comment]
Not sure what kind of cpu you are using but you program  runs without any pause. Because there is a main thread and at least one javascript thread i think two cpu's are more or less complete busy.

Depending on the pages you might consider
* disabling javascript support
* intercept the analytics stuff and remove it

But in general HtmlUnit tires to process your program as fast as possible - this implies to us the available cpu resources.

**Comment by tea-blog** [comment]
Ok, thank you!!! : )

**Comment by rbri** [comment]
Your welcome, will close this. Feel free to open a new one if you need more
