### ISSUE TITLE
Links to issues and pulls on htmlunit webpage broken

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#405]
Seems the links in your changelog on https://htmlunit.sourceforge.io/changes-report.html#a2.55.0 are missing the /issues and /pull path in them.

Not critical, just noticed it while browsing the changelog so wanted to let you know.

For example, this leads nowhere https://github.com/HtmlUnit/htmlunit/403

**Comment by rbri** [comment]
Fixed, many thanks
