### ISSUE TITLE
How do I close all logs? （二）

### ISSUE THREAD

**Issue by tea-blog** [HtmlUnit/htmlunit#406]
How do I close all logs? :(
All this. :(
I have added restrictions according to [the document(https://htmlunit.sourceforge.io/logging.html)](https://htmlunit.sourceforge.io/logging.html), but a print log will appear. :(
![image](https://user-images.githubusercontent.com/68322136/142195294-f850cd95-ccc1-49b3-8b43-75f2e0cad259.png)

**Comment by tea-blog** [comment]
This is what I did. :(
![image](https://user-images.githubusercontent.com/68322136/142195775-f75295eb-5528-4cd2-8140-0a5f1c167a41.png)

**Comment by rbri** [comment]
The main trick is commons-logging. HtmlUnit never writes to the log by itself, all logging calls are handed over to commons-logging. You can configure commons-logging itself to ignore all these calls.

But depending on your classpath commons-logging will forward the log messages to e.g. log4j or slf4j. And there you can also configure the log output.

**Comment by tea-blog** [comment]
All right... Thank you! The data obtained from this page is empty. What should i do?  :(
[https://www.iconfont.cn](https://www.iconfont.cn)

**Comment by qurikuduo** [comment]
> 

U should check your program's log to ensure where the problem is. May be u were baned by the website.
