### ISSUE TITLE
HTMLUnit loads wrong locale file for Javascript Datepicker

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#413]
Executing a jquery datepicker loads the wrong script from i18n resource folder. Instead of executing the default script (en_US), HTMLUnit executes the last file of i18n resource folder.

Datepicker is implemented link in : https://jqueryui.com/datepicker/#localization

**Comment by rbri** [comment]
Any chance to get more details or a demo page/folder and a short main method that shows your problem?

**Comment by Deadc00l** [comment]
After consulting with our developers, it seems that the problem is indeed on our side. The I18n files are faulty. 
Sorry for that :)

**Comment by rbri** [comment]
Great and thanks for the feedback
