### ISSUE TITLE
How to change the value of the Accept-Language?

### ISSUE THREAD

**Issue by tea-blog** [HtmlUnit/htmlunit#415]
this... :(
![image](https://user-images.githubusercontent.com/68322136/145329906-932f2696-0bd3-4aea-9494-62ce7776fd6f.png)

**Comment by rbri** [comment]
Have updated the docu at https://htmlunit.sourceforge.io/details.html a bit. Hope the sample at the top answers this question.

**Comment by tea-blog** [comment]
Thank you so much! 👍 ：）
