### ISSUE TITLE
HtmlPage.asText gone missing

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#417]
Hey @rbri 

I've just upgraded from `2.52.0` to `2.55.0` and apparently `HtmlPage.asText()` (or DomNode or where it's been living before) has gone missing. But there's no such change listed in the changelog. Is something wrong with my version (snapshot repo) or is it just not in the docs?

What's the new way to grab the text - `getVisibleText()`?
/edit: I see there's also `getTextContent()`

**Comment by rbri** [comment]
Hi and welcome back, hope your are happy and healthy :-)

From the release notes:
**Release 2.55.0 – November 14, 2021**
Deprecated method DomNode.asText() removed.

**Release 2.48.0 – March 20, 2021**
DomNode#asNormalizedText() added to provide a more meaningful and stable normalization. DomNode#asText() is now deprecated.

**From the javadoc of DomNode#getVisibleText()**
Returns a textual representation of this element in the same way as the selenium/WebDriver WebElement#getText() property does.
see https://w3c.github.io/webdriver/#get-element-text and https://w3c.github.io/webdriver/#dfn-bot-dom-getvisibletext Note: this is different from asText

getTextContent is from w3c Node and produces a usual too stupid repesentation.

To make the long story short use asNormalizedText() and report any problems suggestions (also for the javadoc).

**Comment by black-snow** [comment]
I'm fine, thanks!
As usually a very quick and thorough answer! I swapped to `asNormalizedText` in all the places and it looks good so far.

As for the release notes - apparently I've been too stupid to actually click the link in the table to reach https://htmlunit.sourceforge.io/changes-report.html#a2.55.0 :D

Did you automate the [github release notes](https://github.com/HtmlUnit/htmlunit/releases)? Perhaps we should add a link to the full release notes there.

Danke nochmal und hab' eine super Woche!
RB ;)

/edit: Another hint: Have you thought about going semVer with HtmlUnit? I'd probably have investigated more if it was a 2.x -> 3.x
