### ISSUE TITLE
isDisabled() returns true, while JS is set to disabled

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#418]
Hello,
I have an issue with the display of elements in case javascript is set to disabled:
com.gargoylesoftware.htmlunit.html.HtmlElement.isDisplayed()

Example html
```html
<div id="div" style="display:none;">
    <span id="test">
        Some Text
    </span>
</div>
```

Expected result of span with id "test" is false (because of  style="display:none;")
HtmlUnit returns true.

@rbri, could you please take a look at this?

Thanks and greetings

**Comment by Deadc00l** [comment]
I created this ticket some time ago and wanted to inquire about the status. In the following commit, the handling of isDisplayed() for disabled JavaScript was removed. Is there a reason, why in this case the return value is "true"?

https://github.com/HtmlUnit/htmlunit/commit/9b1404a11433cb4f2190248dfae253c2aa4184af#diff-a45bfb570046b36053d3e212141aecae4a4244fbc0c4750c7cd230be4f62c15aR742

**Comment by rbri** [comment]
Sorry this got lost...
I'm on vacation for some time, will give you a more detailed answer in two weeks. And will try to finally fix this.

**Comment by Deadc00l** [comment]
Hello @rbri,
were you able to find out anything regarding to the issue?

**Comment by rbri** [comment]
this got lost on my desk - sorry....

**Comment by rbri** [comment]
@dennisduysak sorry for the loooooooooong wait

but i think i have it working now. Will test a bit more and then release that stuff.

**Comment by rbri** [comment]
@dennisduysak just made a new snapshot build available - you can try if you like

**Comment by Deadc00l** [comment]
works now, thank you :)

**Comment by rbri** [comment]
@dennisduysak sorry for the long delay
