### ISSUE TITLE
HtmlImage.click(x,y) doesn't work

### ISSUE THREAD

**Issue by SHENXIAOTIAN1** [HtmlUnit/htmlunit#419]
Hello @rbri

I want to click on some coordinates on the picture. 
But the result is not the same as the provided coordinates.It is always at the point (2, 2).

Thanks

**Comment by rbri** [comment]
Hi,
what version do you use and how do you get the point(2,2). PointerEvent or something else?

**Comment by SHENXIAOTIAN1** [comment]
> Hi, what version do you use and how do you get the point(2,2). PointerEvent or something else?

My version is 2.56.0.
I used HtmlPage.asXml() to get the returned page.

**Comment by rbri** [comment]
Can you please provide some more details
* is there an imagemap associated with the image?
* is this image part of an anchor?
* how does the js code detect the point?

**Comment by SHENXIAOTIAN1** [comment]
> 



> Can you please provide some more details
> 
> * is there an imagemap associated with the image?
> * is this image part of an anchor?
> * how does the js code detect the point?


This is a captcha image.
`<img id="clickTipCaptcha" src="/login-web/api/captcha/clicktip/shlogin/get?modelId=&amp;t=1639493851150" draggable="false" data-reactid=".0.0.2.0.0.0.1.0.1.0.2.0.0.0.0">`


I need to click on some coordinates on the picture to complete the verification.
I think it uses PointerEvent to record point.

**Comment by rbri** [comment]
Have done a first hack to forward the information to the click event.
Please check with the latest snapshot build.

**Comment by rbri** [comment]
@SHENXIAOTIAN1 does it work for you?

**Comment by SHENXIAOTIAN1** [comment]
> @神晓天1对你有用吗？

no,I tried other ways.

**Comment by rbri** [comment]
Ok, will close this, thanks
