### ISSUE TITLE
Cannot login to a website using HtmlUnit 2.35.0

### ISSUE THREAD

**Issue by chenbbin** [HtmlUnit/htmlunit#42]
I want to login to https://www.rjs.com/member/user.html#login using HtmlUnit but failed, I still get the previous page after calling login button.click.

My code is as below.

package rjsHTMLUnit;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.HttpMethod;
import com.gargoylesoftware.htmlunit.NicelyResynchronizingAjaxController;
import com.gargoylesoftware.htmlunit.Page;
import com.gargoylesoftware.htmlunit.SilentCssErrorHandler;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.WebRequest;
import com.gargoylesoftware.htmlunit.html.HtmlButton;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.HtmlInput;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import com.gargoylesoftware.htmlunit.html.HtmlPasswordInput;
import com.gargoylesoftware.htmlunit.util.NameValuePair;

public class Test {

	 private static String TARGET_URL = "https://www.rjs.com/member/user.html#login";

		 public static void main(String[] args) throws FailingHttpStatusCodeException, MalformedURLException, IOException
		 {
			 WebClient webClient = new WebClient(BrowserVersion.CHROME);
			 webClient.setCssErrorHandler(new SilentCssErrorHandler()); 
			 webClient.getOptions().setUseInsecureSSL(true);
			 webClient.setAjaxController(new NicelyResynchronizingAjaxController());
			 webClient.getOptions().setJavaScriptEnabled(true);
			 webClient.getOptions().setCssEnabled(false);
			 webClient.getOptions().setTimeout(50000);
			 webClient.getOptions().setThrowExceptionOnScriptError(false);
			 webClient.getOptions().setRedirectEnabled(true); 
			 webClient.getCookieManager().setCookiesEnabled(true); 
			 HtmlPage page = webClient.getPage(TARGET_URL);
			 webClient.waitForBackgroundJavaScript(10000);
			 System.out.println(page.asXml());
			 HtmlInput heUsername = (HtmlInput)page.getHtmlElementById("login_username");
			 HtmlPasswordInput hePassword = (HtmlPasswordInput)page.getHtmlElementById("login_pwd");
			 HtmlButton heLogin = (HtmlButton)(page.getFirstByXPath("//button[@class='login-btn']"));
			 heUsername.setValueAttribute("18601246140");
			 hePassword.setValueAttribute("passw0rd");
			 HtmlPage page2 = heLogin.click();
			 webClient.waitForBackgroundJavaScript(10000);
			 System.out.println(page2.asXml());
			 webClient.close();
	}
}

**Comment by rbri** [comment]
For me this code seems to work (at least with the latest snapshot)

        String uri = "https://www.rjs.com/member/user.html#login";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_60)) {
            HtmlPage page = webClient.getPage(uri);
            webClient.waitForBackgroundJavaScript(10000);

            HtmlInput heUsername = (HtmlInput) page.getHtmlElementById("login_username");
            HtmlPasswordInput hePassword = (HtmlPasswordInput) page.getHtmlElementById("login_pwd");
            HtmlButton heLogin = (HtmlButton) page.getFirstByXPath("//button[@class='login-btn']");
            heUsername.type("18601246140");
            hePassword.type("passw0rd");

            heLogin.click();
            webClient.waitForBackgroundJavaScript(10000);

            page = (HtmlPage) webClient.getCurrentWindow().getEnclosedPage();
            System.out.println("----------------");
            System.out.println(page.asXml());
        }


The resulting output contains 

    <a href="/member/index.html" class="rjs-nav-accountl">我的账户</a>

and i can see the same after the login in the browser.

Please give me a sign if it works for you also - i have no idea of Chinese; i can't check it myself.

**Comment by rbri** [comment]
see https://stackoverflow.com/questions/56204745/cannot-login-to-a-website-using-htmlunit-2-35-0/56207696?noredirect=1#comment99067810_56207696

**Comment by chenbbin** [comment]
Thank you so much, your code worked fine, I found the key is below statement, if I add it, the issue re-occurs.

webClient.setAjaxController(new NicelyResynchronizingAjaxController());

**Comment by chenbbin** [comment]
I also found if I use below statement to get the page, this page is still the login page.
page = heLogin.click();
Your statement as below can get the right page, but it introduced another issue, that is the page type is text/html and cannot get the returned json data which I can see them in XHR. Any thoughts?
page = (HtmlPage) webClient.getCurrentWindow().getEnclosedPage();

**Comment by rbri** [comment]
Sorry, this is too old, will close this. Again sorry for the missing support here.
If you still use HtmlUnit and facing problems please open a new one.
