### ISSUE TITLE
JavaScript Date instances don't seem to represent localdate

### ISSUE THREAD

**Issue by thuri** [HtmlUnit/htmlunit#423]
In browsers `new Date("2021-12-18T22:23")` seem to produce a local date time. 
So when calling `new Date("2021-12-18T22:23").toISOString()` on my local machine (situated in Timezone Europe/Berlin) the resulting string will be `2021-12-18T21:23:00.000Z` 
The browser implementation seems to calculate the UTC time from the Date instance.

![grafik](https://user-images.githubusercontent.com/1602552/146656098-e50585a6-d2f5-45c6-a41a-2cfd637ab5ce.png)

But when running this in HTMLUnit I wasn't able to get the correct UTC string. Even when setting the Timezone on the browser version.

I changed my example project https://github.com/thuri/htmlunit-jquery-selector-init that was created for #422  and added a new Test `DateStringConversionTest.java` and an new example html `dateStringConversionTest.html` where this behavior can be reproduced.

Probably i'm just missing some configuration here but I couldn't find something on the web

**Comment by rbri** [comment]
will have a look

**Comment by rbri** [comment]
Ok, looks like an issue ;-)

But i have to do some more changes to make this working, including fixes to the rhino code.
I fear this will require some time - do you need this fix already this year?

**Comment by thuri** [comment]
No I don't need this this year. Please have a nice christmas time without thinking about this.
I need this for a little side project but that's not that important

**Comment by rbri** [comment]
made a PR for Rhino
https://github.com/mozilla/rhino/pull/1132

**Comment by rbri** [comment]
This is fixed with the 2.58.0 release.
Thanks for this report.
