### ISSUE TITLE
Classpath issue when upgrading to Java 11

### ISSUE THREAD

**Issue by mauromol** [HtmlUnit/htmlunit#425]
I'm trying to upgrade my project which uses HtmlUnit from Java 8 to Java 11.

I have the following classpath problem. HtmlUnit indirectly depends on `xml-apis` and this may make the Java 11 compiler complain:

```
The package javax.xml.datatype is accessible from more than one module: <unnamed>, java.xml
```

This happens even if I'm not using the module path, but the classpath.

I see that HtmlUnit 2.56 has the following dependency:

```xml
        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
            <version>2.7.2</version>
            <exclusions>
                <exclusion>
                    <groupId>xerces</groupId>
                    <artifactId>xercesImpl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

which is fine, because it excludes `xml-apis`. However, it also depends on `neko-htmlunit`, which in turn has the following dependency:

```xml
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.12.1</version>
        </dependency>
```

with no exclusion for `xml-apis`, which is transitively required by `xercelImpl`, so `xml-apis:xml-apis:1.4.01` falls transitively into the classpath, requiring consumer applications to exclude it explicitly on their own.

Could this be fine-tuned?

**Comment by black-snow** [comment]
@mauromol so a fix would be as easy as adding another exclusion? Have you tried it + would you mind filing a PR?

**Comment by mauromol** [comment]
Sorry, I just saw today your comment of July 2022... I must have missed the corresponding GitHub notification. The solution for me was yes, to exclude xml-apis from the transitive dependencies of HtmlUnit in my consumer application.
However, I see that meanwhile htmlunit 2.x has reached version 2.70.0. On a quick look at its dependencies in Maven repo I see that they have changed a bit. Also, my consumer application has changed from December 2021 when I opened this issue, so I'm not able to test whether upgrading HtmlUnit would be enough to solve this problem, because I don't have the same dependency graph.
So, I'm closing this, if something new arises I will report back.

**Comment by mauromol** [comment]
Ok, after investigating further on this problem, which was getting somewhat disguised in my current setup, I can say that:
- I can still reproduce the problem with HtmlUnit 2.56.0
- the changes in HtmlUnit 2.70.0 (and possibly some version in between 2.56.0 and 2.70.0) dependency declarations seem to fix this problem on HtmlUnit side

In case anyone comes here, some info on the problem can be read at: https://stackoverflow.com/a/71759583/1465635
or at: https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module

**Comment by rbri** [comment]
Thanks for the feedback.
