### ISSUE TITLE
Is there anyway to clear the Cookie property in request header with HtmlUnit?

### ISSUE THREAD

**Issue by TamTam2048** [HtmlUnit/htmlunit#429]
I'm trying to access a page and there is some problem with the cookie property in request header. When I compare with the header received from another browsers (like Chrome), the cookie seems to be different. 

The cookie I got from Chrome: ADRUM_BTa= xxxx
The cookie I got from Htmlunit:  AMCVS_xxxx

The AMCVS cookie leads me to a 401 code.
Please help

**Comment by rbri** [comment]
Any chance to provide some code to let me reproduce this?
Outside of this you can access all the cookies (and manipulate) using the Cookie manager from the WebClient.

**Comment by TamTam2048** [comment]
Sorry, It was a bad question, I will close this and open a new one If I have more detail on this case

**Comment by rbri** [comment]
Thanks for the feedback - will be great if you can provide a more detailed case.
