### ISSUE TITLE
The Logic in `Cache` for `max-age` is not as expected

### ISSUE THREAD

**Issue by ashleyfrieze** [HtmlUnit/htmlunit#432]
At the moment, https://github.com/HtmlUnit/htmlunit/blob/master/src/main/java/com/gargoylesoftware/htmlunit/Cache.java#L251 has logic that dictates:

- if `max-age` or `s-maxage`
- look at the `Last-Modified` header to find when the page was changed
- do not cache if the `Last-Modified` was earlier than `now` - `DELAY`

But the _correct_ behaviour would be to cache the content in this situation in all cases, but then set an expiry on the cached version. Given HtmlUnit should be used for unit tests only, you might argue that the presence of the headers is enough to cache it perpetually. However, one could reasonably add expiry to the `Cache` class, which could be applied before returning an item.

This would be easy to fix and I could propose a PR - please feed back.

**Comment by rbri** [comment]
HtmlUnit is not for unit test only. Every difference in behavior compared to real browsers is a bug. And yes please provide an PR.

**Comment by ashleyfrieze** [comment]
@rbri - please have a quick look at #433 - it passes the tests around the cache, but I don't know if it will have any other effects. It would be good to get your feedback on the logic.

**Comment by ashleyfrieze** [comment]
@rbri  - I presume we can close this?

**Comment by rbri** [comment]
Yes will be part of the next release. Aganin thanks for your contribution.

**Comment by ashleyfrieze** [comment]
@rbri it's my pleasure
