### ISSUE TITLE
2.56.0 API doc lists each class twice

### ISSUE THREAD

**Issue by niemand0** [HtmlUnit/htmlunit#435]
1. Unzip htmlunit-2.56.0-bin.zip
2. Open index.html under apidocs folder

Every class appears twice:
![image](https://user-images.githubusercontent.com/1043792/149780174-1f6d9cd2-1ca8-4b5f-ba88-0dda8939d769.png)

**Comment by rbri** [comment]
many thanks, should be fixed in the next release
