### ISSUE TITLE
formaction, formmethod, formtarget and formenctype ignored on button without type attribute

### ISSUE THREAD

**Issue by Jaaap** [HtmlUnit/htmlunit#436]
This works as expected:
```html
<button type="submit" form="fsp-form" formaction="account/csv" formmethod="GET">CSV</button>
```
but if you omit the `[type=submit]`, then the `formaction` and the `formmethod` are ignored. DOES NOT WORK:
```html
<button form="fsp-form" formaction="account/csv" formmethod="GET">CSV</button>
```

See src/main/java/com/gargoylesoftware/htmlunit/html/HtmlForm.java:226, `type` contains the empty string there.

**Comment by rbri** [comment]
fixed; will make a new snapshot available soon (pls check on twitter)

**Comment by rbri** [comment]
Many thanks.
