### ISSUE TITLE
input[type=checkbox].isValid() ignores (live) checked state

### ISSUE THREAD

**Issue by Jaaap** [HtmlUnit/htmlunit#438]
The following snippet:
```html
<input type="checkbox" name="x" required/>
```
with
```java
HtmlCheckBoxInput cb = page.querySelector("input[type=checkbox][required]");
assertFalse(cb.isValid());
cb.click();
assertTrue(cb.isValid()); // fails because isValid() still reports false
```
fails, perhaps because `HtmlCheckBoxInput.isValueMissingValidityState()` uses `getCheckedAttribute()` instead of looking at the `isChecked()`?

**Comment by rbri** [comment]
Many thanks for the report - this seem to be huge because all other inputs are also suffering from this broken impl.
Will try to fix this during the next days and make a new snapshot available soon.

**Comment by rbri** [comment]
Implemented, will make a snapshot build available if the CI is happy with the changes (check twitter for news)

Again many thanks for your report.

**Comment by rbri** [comment]
snapshot is out - please check and report new issues ;-)

**Comment by rbri** [comment]
(and github stars are always welcome)
