### ISSUE TITLE
Feature request: Implement Fetch API using polyfill on XHR

### ISSUE THREAD

**Issue by niloc132** [HtmlUnit/htmlunit#447]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

As discussed in https://github.com/HtmlUnit/htmlunit/issues/78, there are several polyfills that allow web applications to use the Fetch API in browsers that don't support them, but the browsers that HtmlUnit can behave as most (or all?) already support fetch natively. 

One option is to implement the api directly by using a polyfill, referencing some appropriately licensed JS so that when the application calls fetch(), HtmlUnit doesn't need to actually have any specific code, just let the polyfill call XmlHttpRequest which is already supported.

This strategy could be used to populate many browser APIs that can be largely implemented using existing features. This feature (or something even simpler) implemented by a project member could also serve as an example for how outside contributors could easily help by finding and hooking up quality polyfills for other yet to be implemented features.

**Comment by rbri** [comment]
@niloc132 have done a first impl - please have a look and let us discuss this a bit

**Comment by rbri** [comment]
Released, thanks for this great suggestion

**Comment by niloc132** [comment]
Thanks! I'm sorry I haven't had time to go over it in depth, but I appreciate the work you've done to add this, both to support fetch and to give an example of how polyfills can be used to add features in the future.

**Comment by rbri** [comment]
no prob, time is always the problem - same here.
Have already added proxy support using the same pattern - thanks again
