### ISSUE TITLE
Object.getOwnPropertyDescriptor(Image.prototype, "src") returns 'undefined'

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#451]
In htmlunit, Object.getOwnPropertyDescriptor(Image.prototype, "src") returns 'undefined'.
Chrome returns {enumerable: true, configurable: true, get: ƒ, set: ƒ}

**Comment by rbri** [comment]
Will have a look....

**Comment by rbri** [comment]
Hi Rural,
made a new snapshot build available - hope this is fixed.

**Comment by RuralHunter** [comment]
Yes, this is fixed. Thanks!
