### ISSUE TITLE
How can I load local HTML files through HtmlUnit?

### ISSUE THREAD

**Issue by tea-blog** [HtmlUnit/htmlunit#453]
Hello, I'm sorry to bother you, but i can't help it, and i need some help.
How can I load local HTML files through HtmlUnit?

**Comment by rbri** [comment]
You can use a file:// url or read the file into a string and use https://htmlunit.sourceforge.io/faq.html#HowToParseHtmlString to make a page out of the string.

**Comment by tea-blog** [comment]
Wow, thank you very much. ：）

**Comment by rbri** [comment]
Your welcome (and github starts also :-))
