### ISSUE TITLE
Typo in Change Report (Januar 23, 2022) (https://htmlunit.sourceforge.io/changes-report.html)

### ISSUE THREAD

**Issue by asdf913** [HtmlUnit/htmlunit#454]
https://htmlunit.sourceforge.io/changes-report.html

Type Found `Januar 23, 2022`

The correct spelling should be `January 23, 2022`

![image](https://user-images.githubusercontent.com/2301325/156693365-88005549-b9a3-4c73-94a6-4b6fc34ea2be.png)

**Comment by rbri** [comment]
Thanks - fixed
