### ISSUE TITLE
Add 'Origin' header to same-origin non-GET requests

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#461]
Currently HtmlUnit only adds 'Origin' header for true CORS requests.

https://stackoverflow.com/questions/15512331/chrome-adding-origin-header-to-same-origin-request

Per the link above, "Chrome and Safari include an Origin header on same-origin POST/PUT/DELETE requests (same-origin GET requests will not have an Origin header)". I checked the latest version of Firefox, it also adds Origin header for non-GET requests. 

I think HtmlUnit should better add it as well.

**Comment by rbri** [comment]
Sounds reasonable - do you have some time to write an additional test for this case (maybe in HttpWebConnection3Test)

**Comment by RuralHunter** [comment]
I will try.

**Comment by RuralHunter** [comment]
I checked Edge and it also adds the Origin header. HtmlUnit actually has already added this header for form post in [HtmlForm](https://github.com/HtmlUnit/htmlunit/blob/91e4ceac6b97c10ff80c86a41b54aaef792ab527/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlForm.java#L351), though missing for Edge(It does not have FORM_SUBMISSION_HEADER_ORIGIN feature currently). So I think in HttpWebConnection3Test there is nothing much to do.  Only one line to be added once the FORM_SUBMISSION_HEADER_ORIGIN is enabled for Edge.

What still missing is for XMLHttpRequest. Should the test still be added in HttpWebConnection3Test?

**Comment by RuralHunter** [comment]
Oh sorry I was wrong. Edge do have the FORM_SUBMISSION_HEADER_ORIGIN feature. The one lacks is IE and I think it's ok(I don't have IE to test it).

**Comment by RuralHunter** [comment]
I copied the refererHeader() in XMLHttpRequestTest and updated accordingly. How about that?
```
    /**
     * Tests that the <tt>Origin</tt> header is set correctly.
     * @throws Exception if the test fails
     */
    @Test
    public void testOriginHeader() throws Exception {
        final String html = "<html><head><script>\n"
            + "function test() {\n"
            + "  req = new XMLHttpRequest();\n"
            + "  req.open('post', 'foo.xml', false);\n"
            + "  req.send('');\n"
            + "}\n"
            + "</script></head>\n"
            + "<body onload='test()'></body></html>";

        final URL urlPage2 = new URL(URL_FIRST, "foo.xml");
        getMockWebConnection().setResponse(urlPage2, "<foo/>\n", MimeType.TEXT_HTML);
        loadPage2(html);

        final WebRequest request = getMockWebConnection().getLastWebRequest();
        assertEquals(urlPage2, request.getUrl());
        assertEquals(urlPage2.getProtocol()+"://"+urlPage2.getHost()+":"+urlPage2.getPort(), request.getAdditionalHeaders().get(HttpHeader.ORIGIN));
    }
```

**Comment by rbri** [comment]
good idea, have the test running (and failing). Will provide a new snapshot soon.

**Comment by rbri** [comment]
OK think i have fixed this - lets ask the CI if i broke something

**Comment by RuralHunter** [comment]
Thanks!
