### ISSUE TITLE
Height of HtmlTable calculation is wrong

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#463]
This is the demonstration:
Test html:
```html
<html>
    <head>
        <title>table size</title>
    </head>
    <body>
        <table id="mytable>
          <tbody>
               <tr>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
                    <td>td</td>
             </tr>
          </tbody>
        </table>
    </body>
</html>
```
Test code
```java
        HtmlElement table=(HtmlElement)p.getElementById("mytable");
        HTMLElement hso=table.getScriptableObject();
        int w=hso.getOffsetWidth();
        int h=hso.getOffsetHeight();
        logger.info("{}, w={}, h={}",hso, w, h);
```
The table height returned is the heights added up from all TDs. While the actual result should be the height of one TD.
I traced the code and think the problem is [here](https://github.com/HtmlUnit/htmlunit/blob/485ba1c80f90c6b44cd363f4d9f7882e8a1208f8/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/css/ComputedCSSStyleDeclaration.java#L1451). When calculating the relative top position, htmlunit adds up all the height of it's previous siblings, which is not correct for TD.

**Comment by RuralHunter** [comment]
[One more place](https://github.com/HtmlUnit/htmlunit/blob/485ba1c80f90c6b44cd363f4d9f7882e8a1208f8/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/css/ComputedCSSStyleDeclaration.java#L1379), to calculate the height of TR, HtmlTableDataCell also need to be handled specially by adding it to the children style list. So that the height of TR is calculated from the max height of its chidren TDs.

**Comment by rbri** [comment]
sorry for being a bit late on this - should be improved now

**Comment by RuralHunter** [comment]
thanks!
