### ISSUE TITLE
WebResponse.getContentAsStreamWithBomIfApplicable() overriding is missing in WebResponseWrapper

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#471]
This causes css cache loading error. In [CssStyleSheet](https://github.com/HtmlUnit/htmlunit/blob/0b584703da623b898c15e0c0ffeead6dffacb4c5/src/main/java/com/gargoylesoftware/htmlunit/css/CssStyleSheet.java#L276), if the response is from cache, then the response is a WebResponseWrapper(extended from WebResponseWrapper) instance. Since the method getContentAsStreamWithBomIfApplicable() is not overriden in WebResponseWrapper, it actually calls the WebResponse.getContentAsStreamWithBomIfApplicable() which always returns null because it's only an empty delegator.

**Comment by rbri** [comment]
Hi @RuralHunter ,
had a first look at your problem. Sounds clear so far but i like to build a test case for this also. So far i have problems simulating your case.
Do you have any hint for this. My problem is to find a case where the

    final Object fromCache = cache.getCachedObject(request);

does not detect the css as from cache but the repsonse itself is from the case.

**Comment by RuralHunter** [comment]
ah yes, this happens when I was trying to implement a FileCache, which only caches responses but not the parsed css objects. Looks it won't trigger the problem with the builtin cache since the response is always cleaned before the css object gets cleaned.

**Comment by rbri** [comment]
Ah ok will fix it soon

**Comment by RuralHunter** [comment]
Great!
