### ISSUE TITLE
package-info.class cause "org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar" failure since 2.59.0

### ISSUE THREAD

**Issue by asdf913** [HtmlUnit/htmlunit#473]
*org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar* raise below *ERROR* message.
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project \*\*\*\*-\*\*\*\*\*\*\*-\*\*\*\*\*\*: Can not execute Findbugs: java.lang.AssertionError: Can't find ClassInfo for com\gargoylesoftware\htmlunit\package-info

![image](https://user-images.githubusercontent.com/2301325/161391308-faa68ac2-28df-48f8-86d7-31f247fc32fc.png)

**Comment by rbri** [comment]
Please switch to 2.60.0 this is (hopefully) already fixed.

**Comment by asdf913** [comment]
There are  package-info.class in htmlunit 2.60.0
![image](https://user-images.githubusercontent.com/2301325/161409297-73fb27d7-1701-4af2-b2c7-fed22d51f013.png)

**Comment by rbri** [comment]
Strange - my guess was this is related to #457.

**Comment by rbri** [comment]
From the Mavan PR https://github.com/apache/maven-compiler-plugin/pull/88

> This option is turned on by default because the generated class files are valid, so they should not cause any problem.

Can you please verify that the version 2.60.0 still causes problems with sonarsource.scanner - yes i know that the files are still available in 2.60.0 but they are now correct java files and should not harm.

**Comment by asdf913** [comment]
> From the Mavan PR [apache/maven-compiler-plugin#88](https://github.com/apache/maven-compiler-plugin/pull/88)
> 
> > This option is turned on by default because the generated class files are valid, so they should not cause any problem.
> 
> Can you please verify that the version 2.60.0 still causes problems with sonarsource.scanner - yes i know that the files are still available in 2.60.0 but they are now correct java files and should not harm.

It is verified that **sonarsource.scanner** could run property for htmlunit 2.60.0.

**Comment by rbri** [comment]
@asdf913 means i can close this?

**Comment by asdf913** [comment]
> @asdf913 means i can close this?
Yes

**Comment by rbri** [comment]
Thanks for the feedback, enjoy using HtmlUnit
