### ISSUE TITLE
Uint8Array.subarray problem

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#476]
The result of subarray of another subarray is wrong. Test code:
```javascript
            var arr = new Uint8Array([1,2,3,4,5,6,7,8,9,10]);
            var sub1 =arr.subarray(5,10);
            var sub1a=[];
            for(var i=0;i<sub1.length;i++)
                sub1a.push(sub1[i]);
            console.log('sub1='+sub1a);
            
            var sub2 =sub1.subarray(0,3);
            var sub2a=[];
            for(var i=0;i<sub2.length;i++)
                sub2a.push(sub2[i]);
            console.log('sub2='+sub2a);
```
In htmlunit, the output is:
```
sub1=6,7,8,9,10
sub2=1,2,3
```
The correct result or the result from real browser is:
```
sub1=6,7,8,9,10
sub2=6,7,8
```

**Comment by rbri** [comment]
Thanks will have a look

**Comment by rbri** [comment]
Thanks @RuralHunter, this is clearly a Rhino issue, will fix this over the weekend.
Great finding -seems to be there since the first impl in 2014 :-)

**Comment by RuralHunter** [comment]
thanks for the quick fix as always!

**Comment by rbri** [comment]
Will inform you if a new snapshot containing the fix is available
