### ISSUE TITLE
Can't type into an HtmlTimeInput?

### ISSUE THREAD

**Issue by cbartolome** [HtmlUnit/htmlunit#479]
I'm using a `sendKeys()` call in Selenium to type a time into an HTML Time input, but `HtmlTimeInput` doesn't override `doType()`, so the incoming keystrokes are ignored. (Additionally, `HtmlTimeInput` is missing from a few blocks of `instanceof` checks that decide whether to fire an `input` JS event, but first things first.)

**Comment by rbri** [comment]
Have done a look at this and some refactoring already.
But this requires a major update of the current HtmlInput implementation. Will try to make this step by step during the next days and inform about the progress.

**Comment by rbri** [comment]
Sorry for being a bit late on this :-)
But it was a major rewrite of the input value handling. Hope this will work now - but i'm still in the process of testing.
Will try to make a new Snapshot build from the webdriver during the next days and hopefully a new release soon.

**Comment by cbartolome** [comment]
No worries, thanks for the update!

**Comment by rbri** [comment]
Please check with version 3.0.0

**Comment by cbartolome** [comment]
Works great, thank you!
