### ISSUE TITLE
offsetTop is the same for all table rows

### ISSUE THREAD

**Issue by svschouw-bb** [HtmlUnit/htmlunit#48]
There has been a change since HtmlUnit 2.33 which causes the Y location (or offsetTop) of all table rows to be the same. My guess was this was related to this old [sourceforge bug #1986](https://sourceforge.net/p/htmlunit/bugs/1986/). The change was such that `ComputedCSSStyleDeclaration.getTop(...)` only considers siblings with "display: block". However, for table rows, it is "table-row". I feel like most display values are block-like.

Simple `ComputedCSSStyleDeclarationTest` test:

```java
    @Test
    @Alerts("true")
    public void offsetTopTableRows() throws Exception {
        final String html = "<html><body>\n"
            + "<table>\n"
            + "<tr id='row1'><td>row1</td></tr>\n"
            + "<tr id='row2'><td>row2</td></tr>\n"
            + "</table>\n"

            + "<script>\n"
            + "  var r1 = document.getElementById('row1');\n"
            + "  var r2 = document.getElementById('row2');\n"
            + "  alert(r2.offsetTop > r1.offsetTop);\n"
            + "</script>\n"
            + "</body></html>";
        loadPageWithAlerts2(html);
    }
```

A similar issue is with the calculation of offsetLeft, where it takes all previous siblings until the first "display: block" sibling, which should also instead search for the first block-like sibling.

**Comment by rbri** [comment]
Sounds reasonable, will have a more detailed look at this at the end of next week. You can also check on Twitter for information about the HtmlUnit progress.

**Comment by rbri** [comment]
Have changed the code to handle most display values as block.
Many thanks for the report an the test case.
Will make a new snapshot build available soon (check https://twitter.com/HtmlUnit for news)

**Comment by svschouw-bb** [comment]
Seems to work. Thanks!
