### ISSUE TITLE
com.gargoylesoftware.htmlunit.ScriptException: Window is not a function

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#482]
test code:
```javascript
var divs = document.querySelectorAll('div');
Array.from.call(window,divs);
```
Array.from.call fails with the exception as the title. The same script runs fine in browser.

**Comment by RuralHunter** [comment]
It seems throwing ScriptRuntime.typeError instead of Context.reportRuntimeError in window.constructor() fixes the problem.

**Comment by rbri** [comment]
My fix is a bit more general - again some leftover from IE6 i guess.
Lets see if the CI is happy with this - and if yes i will make a new snapshot.

**Comment by rbri** [comment]
CI is happy - next snapshot is out - many thanks

**Comment by RuralHunter** [comment]
great, thanks.
