### ISSUE TITLE
Table Row data is not scrapped properly 

### ISSUE THREAD

**Issue by kamalakannanvkp** [HtmlUnit/htmlunit#487]
Hi All,  I am trying to scrap a page that has a tracking info .

When i try to access the html contents post scrapping , the row data is not in the expected string format .

**### Error :**  As you can see from below , one of the table data is not in text/string format  when scrapped, but the same request works fine when we execute the scrapped url from browser.

<tr class="h-b-e">
   <td/>
   <td>
      2021-07-07 15:32:00
   </td>
   <td>
      **[object ProgressEvent]**
   </td>
   <td>
      LHR
   </td>
   <td>
      TG0910
   </td>
</tr>

A sample code snippet : 

```
            WebClient webClient = new WebClient(BrowserVersion.CHROME);
            webClient.waitForBackgroundJavaScript(Integer.MAX_VALUE);
            webClient.waitForBackgroundJavaScriptStartingBefore(10000);
            webClient.getOptions().setJavaScriptEnabled(true);
            webClient.getOptions().setCssEnabled(false);
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setPrintContentOnFailingStatusCode(false);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.setAjaxController(new NicelyResynchronizingAjaxController());
            HtmlPage page = webClient.getPage(urlToScrap);
            TimeUnit.SECONDS.sleep(10);
          String fullpath = String.format("//*[@id=\"pp_collapse_%s_control\"]/div/div[3]/div[2]/table",trackNumber);
          HtmlTable table = (HtmlTable) page.getByXPath(fullpath).get(0);
        for (final HtmlTableRow row : table.getRows()) {
            System.out.println("Found row");
            for (final HtmlTableCell cell : row.getCells()) {
                System.out.println("   Found cell: " + cell.asNormalizedText());
            }
        }
```

**Result:**
Found row
   Found cell: 
   Found cell: 2021-07-07 15:32:00
   Found cell: [object ProgressEvent]
   Found cell: LHR
   Found cell: TG0910

**Comment by rbri** [comment]
any chance to get the urlToScrap?

**Comment by rbri** [comment]
BTW

    webClient.waitForBackgroundJavaScript(Integer.MAX_VALUE);
    webClient.waitForBackgroundJavaScriptStartingBefore(10000);

are no options, you have to call this methods after getting a page to have any effect.

**Comment by kamalakannanvkp** [comment]
<X> is the url to scrap 
i have made changes as u suggested, but still its the same issue

**Comment by kamalakannanvkp** [comment]
Heiya , any updates (i have removed the url due to some info , let me know if you havent got it so far)

**Comment by rbri** [comment]
got it - will have a look if i can reproduce the problem

**Comment by kamalakannanvkp** [comment]
thanks , we need to use `tracking-number` to construct xpath (that too in the same format like 
**123-87654321**)
though I can scrap all messages from the site (except the **event** , which _i am more interested on_ ) .

**Comment by rbri** [comment]
Looks like i can reproduce this outside of the web page.
Will try to isolate a test case out of this and then fix it. But this requires time....

(Btw. if HtmlUnit is important for your company please consider sponsoring my work https://github.com/sponsors/rbri)

**Comment by kamalakannanvkp** [comment]
thanks, looking forward to the solution .

**Comment by rbri** [comment]
Ok, the problem here is

* the cell value is created using a var named event
* window has an readonly event property
* based on this setting var event silently fails - this is correct for most readonly properties

But event is [Replaceable] (see https://dom.spec.whatwg.org/#window-current-event) and because of this the code of the webpage works.

Will have a look what solutions are possible here.

**Comment by rbri** [comment]
Have implemented a solution, the plan is so make a release this weekend.

**Comment by kamalakannanvkp** [comment]
Thanks , that was too quick. Will I be able to test on Monday ?

Thanks,
Kamal.
07384032288/9159877743

**Comment by rbri** [comment]
I was able to reproduce your case with the provided URL and i have done the tests again after the fix and the content was completely visible.
And the plan is still to make a release the weekend.

So from my point of view you will have a release version that does the job for you on Monday (CET).

(hopefully ;-))

**Comment by kamalakannanvkp** [comment]
Amazing !  Never have I ever before loved Monday , but this time :)

Thanks,
Kamal.
07384032288/9159877743
