### ISSUE TITLE
The application freezes after webClient.getPage() is called

### ISSUE THREAD

**Issue by antongrinenko** [HtmlUnit/htmlunit#49]
Hi,

Here is a simpe code to reproduce the issue:

```
public static void main(String[] args) throws IOException {
        final WebClient webClient = new WebClient(BrowserVersion.CHROME);
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(true);
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setActiveXNative(true);
        webClient.getOptions().setAppletEnabled(false);
        webClient.getOptions().setCssEnabled(true);
        webClient.getOptions().setDoNotTrackEnabled(true);
        webClient.getOptions().setGeolocationEnabled(false);
        webClient.getOptions().setPopupBlockerEnabled(true);
        webClient.getOptions().setPrintContentOnFailingStatusCode(true);
        webClient.getOptions().setThrowExceptionOnScriptError(true);
        webClient.getOptions().setUseInsecureSSL(true);
        webClient.getCookieManager().setCookiesEnabled(true);
        webClient.getOptions().setRedirectEnabled(true);
        HtmlPage page = webClient.getPage("https://new.santehnika-online.ru/product/unitaz_podvesnoy_gustavsberg_estetic_hygienic_flush_chernyy/");
        final String pageAsText = page.asText();
        System.out.println("====>>>> page: " + pageAsText);
        webClient.close();
}
```
The application freezes at webClient.getPage(...) call. Also I see with jvisualvm that memory grows and this causes OutOfMemory exception.

![htmlunit_issue](https://user-images.githubusercontent.com/5153259/59753756-786d8c00-928d-11e9-9a9c-9c7144c9c5b2.png)

**Comment by antongrinenko** [comment]
Any updates on this?

**Comment by rbri** [comment]
Sorry Anton,
but this page works based on obfuscated js code like this

          if (!_0x54d855) {
              _0x550cc5["setCookie"](["*"], "counter", 1);
          } else {
              if (_0x54d855) {
                  _0x209bba = _0x550cc5["getCookie"](null, "counter");
              } else {
                  _0x550cc5["removeCookie"]();
              }
          }

Did some checks, and it looks like there is an endless loop related to the code above (and the surrounding loop).
But because i'm currently the only developer and i'm having a real job and a real family there is no time to analyze this any deeper. If you are able to point to the js function that works different from real browsers i will try to fix.
Will close this, sorry.

Hope HtmlUnit is useful for you in other cases.
