### ISSUE TITLE
form submit is cancelled if invalid element exists in form

### ISSUE THREAD

**Issue by jpwilhelms** [HtmlUnit/htmlunit#496]
From htmlunit 2.43.0 and newer:

If a text input field has a parameter "maxlength" and the field contains a string of longer length, the submit is cancelled (in HtmlForm.areChildrenValid()).
Firefox 103 has a different behaviour. The form is submitted there.

**Comment by rbri** [comment]
Interesting, should be easy to test and to fix.

**Comment by rbri** [comment]
Progress: working on writing tests for this right now

**Comment by rbri** [comment]
made a new snapshot build available but not all test are green
Please try and if you like have a look at the new tests cases - feedback and more testcases are welcome.

**Comment by rbri** [comment]
think this is done now - please try the latest snapshot
