### ISSUE TITLE
HtmlElement.type(Keyboard) should append the given string, even if the first character is prevented.

### ISSUE THREAD

**Issue by robertgroh** [HtmlUnit/htmlunit#5]
Hi,
I have found a regression (edge-case) in [HtmlElement.type(Keyboard)](https://github.com/HtmlUnit/htmlunit/blob/93cfad0cb1a47ba892a23e0ef2f051e992f9058c/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElement.java#L616).

If the first given Character/KeyEvent doesn't satisfy the checks in [HtmlElement.type(char, startAtEnd, lastType)](https://github.com/HtmlUnit/htmlunit/blob/93cfad0cb1a47ba892a23e0ef2f051e992f9058c/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElement.java#L512), then the remaining string will be prepended to the input fieldand NOT appended.

A test (for [HtmlElementTest.java](https://github.com/HtmlUnit/htmlunit/blob/93cfad0cb1a47ba892a23e0ef2f051e992f9058c/src/test/java/com/gargoylesoftware/htmlunit/html/HtmlElementTest.java#L898)) for this edge-case may look like this:    
```java
    /**
     * If the first typed character is prevented by preventing it's
     * KeyPress-Event, the remaining string should still be appended and NOT
     * prepended.
     * 
     * @throws Exception
     *             if an error occurs
     */
    @Test
    public void typePreventedCharacterFirst() throws Exception {
        final String html = "<html><head><script>\n"
            + "  function stopEnterKey(evt) {\n"
            + "    var evt = evt || window.event;\n"
            + "    if (evt && evt.keyCode === 13)\n"
            + "    {\n"
            + "      evt.preventDefault()\n"
            + "    }\n"
            + "  }\n"
            + "  window.document.onkeypress = stopEnterKey;\n"
            + "</script></head>\n"
            + "<body>\n"
            + "  <input id='myInput' type='text' value='Hello'>\n"
            + "</body></html>";

        final HtmlPage page = loadPage(html);
        final HtmlTextInput input = page.getHtmlElementById("myInput");
        // type prevented Character first
        input.type("\nWorld");
        assertEquals("'World' should be appended.", "HelloWorld", input
                .getValueAttribute());
    }
```

My naive fix is to remove the `i == 0` expression from  [HtmlElement.type(Keyboard) - Line#632](https://github.com/HtmlUnit/htmlunit/blob/93cfad0cb1a47ba892a23e0ef2f051e992f9058c/src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElement.java#L632).
But as I don't understand the reason for this expression in the first place, I am hesitant to provide a Pull-Request.
Maybe there is something more to the selection configuration in [DomText.doType(char, boolean, HtmlElement, boolean)](https://github.com/HtmlUnit/htmlunit/blob/120d9040184cecea08073ccacb3383848a7f9746/src/main/java/com/gargoylesoftware/htmlunit/html/DomText.java#L168)?

**Comment by rbri** [comment]
The result is the same if i remove the \n from you type call. Does the test really show your problem?

**Comment by rbri** [comment]
Seems to be a case when using WebDriver sendKeys() right?

**Comment by robertgroh** [comment]
Yes, I discovered this behavior with the current HTMLUnit-Webdriver.
I will check the test case regarding your first comment as soon as I am
back in the office tomorrow.

Thank you already for your fast reply.

**Comment by rbri** [comment]
No  more actin reqired from your side. I can reproduce the case and have a test case based on your one. Will try to fix it on the weekend.

**Comment by robertgroh** [comment]
Thanks again.

Regarding the posted test:
As you noticed I used the wrong  `type()`-Method. A correct test case has to use the following snippet instead of the type(String) method call:
```java
        // type prevented Character first
        String toAppend ="\nWorld"; 
        // create Keyboard with these characters and set it, to append them
        Keyboard keyboard = new Keyboard(/*startAtEnd=*/true);
        toAppend.chars().mapToObj(i -> (char)i).forEach(keyboard::type);

        // use the 'keyboard'-type()-Method
        input.type(keyboard);
````

**Comment by rbri** [comment]
Made a first try to fix this. Lets see what our build server thinks about this.

**Comment by rbri** [comment]
Seems to work; will make a new Snapshot build available soon (have a look at [twitter](https://twitter.com/HtmlUnit))
