### ISSUE TITLE
Getting latest snapshot jar files without Maven

### ISSUE THREAD

**Issue by sengsational** [HtmlUnit/htmlunit#500]
When I go to https://oss.sonatype.org and search HtmlUnit, I find neko-htmlunit 2.63.0-SNAPSHOT, but not the 2.65.0-SNAPSHOT that I'd apparently get if I had Maven.

**Comment by rbri** [comment]
I fear that is my fault - have just made a new snapshot build available - please check.

**Comment by sengsational** [comment]
Thanks.

Found the 2.65.0 snapshot at this path location in sonatype.org:  `Snapshots/net/sourceforge/htmlunit/htmlunit/2.65.0-SNAPSHOT`

There are a lot of files under that directory path, including the following one, which is probably the one I was looking for:
https://oss.sonatype.org/service/local/repositories/snapshots/content/net/sourceforge/htmlunit/htmlunit/2.65.0-SNAPSHOT/htmlunit-2.65.0-20220821.173518-1.jar
