### ISSUE TITLE
Allowing easier overriding of window.print() behavior?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#501]
If we want to implement our own way to handle print page requests, we need to override the Window class and inject to to whichever classes are using it.

Could this be made easier by calling the attachment handler and allowing us to define the behavior there, or implementing a print handler ?

The use case is that I would like to get the html of the page whenever print is called and save it. Custom logic is easy to implement, just need a reasonable place to insert it into. 

Or is there an easy way to inject our own Window when setting up htmlunit config?

https://github.com/HtmlUnit/htmlunit/blob/9801f67927ef755ae27599f11f007a8fcd3024c2/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Window.java#L1593-L1598

**Comment by rbri** [comment]
I think we need another handler here - will have a look later on this.

**Comment by rbri** [comment]
Have done a first impl - please have a look, suggestions are welcome.
A new snapshot build containing this is available

**Comment by skyhirider** [comment]
I've noticed that the WebWindow the print handler is working with is not immutable. When the code working with the page gets the page response with a delay the state of the page may be different from when print was called.

I think this could either be mentioned in the javadoc - that the response needs to be pulled out first and stored as a variable - or another method could be added that pulls the web response only, which would be immutable.

I've also noticed that calling print on Firefox causes the print window to open, which causes the driver to stop and wait until that window is closed. If there was a way to optionally work this way as well it would be great.

Specifically, there are pages that call print and then immediately call close, so the new tab auto closes after you print. Getting the html of such pages is complicated (thou will be a lot easier even with the current code you made) as you need to grab the html at the correct time.

Will test it a bit more, thou think these are the main things.

Here is the javascript snippet I have been testign it
```
<button id="testButton">Click me</button>
<div id="logArea"></div>
<script>
    const button = document.getElementById('testButton');
    const div = document.getElementById('logArea');
    button.addEventListener('click', e => {
        console.log('click');
        window.print();
        div.innerHTML += "closed";
        window.close();
    });
</script>

```

**Comment by rbri** [comment]
@skyhirider many thanks for the feedback - will write some test and think about your suggestions.

Maybe we can only add some configuration methods to the interface...

**Comment by skyhirider** [comment]
Thanks rbri for looking into this and glad the feedback was useful.

One option would be to implement it similar to how the attachment handler is built, two methods, one for page and one for the response. If the response returns false (default implementation) then the page handler would be triggered instead. 

Thou not sure how to block the main thread until print is handled and where to add the configuration toggle to be async or blocking, or if it even makes sense adding.

**Comment by rbri** [comment]
> I've also noticed that calling print on Firefox causes the print window to open, which causes the driver to stop and wait until that window is closed. If there was a way to optionally work this way as well it would be great.

As far as i can see this is already the case because there is only one js method working on the page at the same time (there is some locking in HtmlUnit to enforce this). And because you are in a js method working on this page the page is locked and no other js method can change the page.

**Comment by rbri** [comment]
Hava added some documentation and the event support. Also have changed the interface to be more closer to the spec.

**Comment by skyhirider** [comment]
I've tested it and it looks good now. And the print html standard documentation you linked to in the javadoc is great, have not checked if the behavior was standardized.

When will the next version be released? Asking to see how much time I have to test it.

**Comment by rbri** [comment]
Just made a new snapshot build - hope you like the latest changes.

There is no release date planned so far, i have at lease one major issue on my list - hopefully 1-2 weeks from now.

**Comment by skyhirider** [comment]
Its working fine, thanks rbri.
