### ISSUE TITLE
The url of the js file will appear "\t" causing an error

### ISSUE THREAD

**Issue by dijia478** [HtmlUnit/htmlunit#503]
When I use WebClient to request some websites and execute website js code, when requesting js files, the url of js files will have a "\t" separator, which will cause the request for js files to fail. The url of the js file in the website is out of our control, so I think this special character should be handled with "replace()" in the code.

![image](https://user-images.githubusercontent.com/30929521/193247274-45fe16ea-63f2-44e5-8364-42566c2bd2fb.png)

![image](https://user-images.githubusercontent.com/30929521/193246079-cbad87d6-afc9-4cda-92a8-1d848f07894b.png)

![image](https://user-images.githubusercontent.com/30929521/193245931-f4f79d19-daf9-4dcd-92c9-d33b8aac04f9.png)

I think maybe it can be dealt with here：

![image](https://user-images.githubusercontent.com/30929521/193247591-34d40ef1-de7f-40a1-9d5c-a11ce58c48f3.png)

**Comment by rbri** [comment]
great finding, will try to fix this soon

**Comment by rbri** [comment]
think i did it, please try the latest snapshot (comments on the code are also welcome)
