### ISSUE TITLE
[Help/Possible Bug (🐛)] Unable to get `src` attribute with HTMLUnit

### ISSUE THREAD

**Issue by therealbluepandabear** [HtmlUnit/htmlunit#504]
I am creating a video scraper and I am trying to get the `src` attribute of the video using `HTMLUnit`, this is because the element is added dynamically to the page (please be nice, I am a noob to these APIs):

```Kotlin
    val webClient = WebClient()
    webClient.options.isThrowExceptionOnFailingStatusCode = false
    webClient.options.isThrowExceptionOnScriptError = false
    webClient.options.isJavaScriptEnabled = true

    val myPage: HtmlPage? = webClient.getPage("https://rumble.com/v1m9oki-our-first-automatic-afk-farms-locals-minecraft-server-smp-ep3-live-stream.html")
    Thread.sleep(10000)
    val document: Document = Jsoup.parse(myPage!!.asXml())
    println(document)
```

The issue is, the output for the `<video>` element is the following:

```HTML
        <video muted playsinline="" hidefocus="hidefocus" style="width:100% !important;height:100% !important;display:block" preload="metadata"></video>
```

Whereas -- if you navigate to the page itself -- it should be:

```HTML
<video muted="" playsinline="" hidefocus="hidefocus" style="width:100% !important;height:100% !important;display:block" preload="metadata" poster="https://sp.rmbl.ws/s8/1/I/6/v/1/I6v1f.OvCc-small-Our-First-Automatic-AFK-Far.jpg" src="blob:https://rumble.com/91372f42-30cf-46b3-8850-805ee634e2e8"></video>
```

Some attributes are missing, which are crucial for my scraper to work. I need to have the `src` attribute or else the video cannot play with ExoPlayer.

I am not totally sure, but I was wondering whether it had to do with the fact that the `crossOrigin` attribute is `anonymous` in the JavaScript:

```HTML
<video muted playsinline hidefocus="hidefocus" style="width:100% !important;height:100% !important;display:block" preload="'+t+'"'+(a.vars.opts.cc?' crossorigin="anonymous"':"")+'>
```

I tried to play around with the different `HTMLUnit` options, as well as look online but I still haven't been able to extract the right attributes I need.

How would I be able to bypass this and get the appropriate elements that I need for the scraper using `HTMLUnit`? Is this even possible to do with `HTMLUnit`? I am completely stumped. Any help would be greatly appreciated so my scraper will work.

**Comment by rbri** [comment]
had a first look at this - again a bunch of obfuscated code - will have another look later on.
A first change is made but there is more to do to make this working.

**Comment by therealbluepandabear** [comment]
Of course sir. Thank you for answering.

I found a way to scrape the video source without a headless browser (with Jsoup) -- although I do help that this issue gets fixed as it may bother other people.

**Comment by rbri** [comment]
Have done a bunch of fixes for the media support.
Now i get

    &lt;video muted="" playsinline="" hidefocus="hidefocus" style="width:100% !important;height:100% !important;display:block" preload="metadata" src="https://sp.rmbl.ws/s8/2/I/6/v/1/I6v1f.caa.rec.mp4?u=3&amp;b=0"/>

In this is what i got in the browser
![image](https://user-images.githubusercontent.com/2544132/195986970-4fd819c3-0244-427e-9f75-da8b02f22c32.png)

**Comment by rbri** [comment]
Will close this - again thanks for the report.
