### ISSUE TITLE
java.io.NotSerializableException

### ISSUE THREAD

**Issue by gangadharkasturi** [HtmlUnit/htmlunit#512]
https://github.com/HtmlUnit/htmlunit/issues/511

**Comment by rbri** [comment]
@gangadharkasturi what is your point here?

**Comment by gangadharkasturi** [comment]
why it is giving the exception, why the page is not saving on disk as a serialized object?

**Comment by rbri** [comment]
because com.gargoylesoftware.htmlunit.javascript.NativeFunctionToStringFunction$NativeFunctionToStringFunctionChrome
is not serializable

But what is the point of opening another issue for the same problem?
Or is there a second one?

**Comment by rbri** [comment]
will close this as duplicate
