### ISSUE TITLE
New release with commons-text 1.10

### ISSUE THREAD

**Issue by Hauk** [HtmlUnit/htmlunit#514]
Hi there!

We are currently using htmlUnit in one of our components, and we were made aware of the CVE linked here: https://mvnrepository.com/artifact/net.sourceforge.htmlunit/htmlunit

The fix for this CVE is to update commons-text to 1.10 or higher, which you have added here: https://github.com/HtmlUnit/htmlunit/commit/caae7849abf1464ba58b60f70943a4c9b629f139

Is it possible you could do a release with this new commons-text version please?

Many thanks!
Eoghan

**Comment by rbri** [comment]
I have a plan to do it this weekend - cross your fingers :-).

As usual i will inform at [twitter](https://twitter.com/htmlunit) if done
