### ISSUE TITLE
 Exception when calling webClient.getPage()

### ISSUE THREAD

**Issue by gimpox** [HtmlUnit/htmlunit#517]
I'm trying to automate the login to an online service that I subscribed.
I get an exception at my first java instruction

`HtmlPage page = webClient.getPage("https://foresignal.com/en/login/index");`

that is

`Exception class=[net.sourceforge.htmlunit.corejs.javascript.EvaluatorException]
com.gargoylesoftware.htmlunit.ScriptException: missing formal parameter (https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js#6)`

the (very long) exception stacktrace ends with

`== CALLING JAVASCRIPT ==
/*!
  * Bootstrap v5.1.3 (https://getbootstrap.com/)
  * Copyright 2011-2021 The Bootstrap Authors (https://github.com/twbs/bootstrap/graphs/contributors)
  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
  */
... [omissis]
======= EXCEPTION END ========`

I'm using HtmlUnit version 2.66.0.

I have read somewhere that this happens because HtmlUnit does not support some particular operands used in Bootstrab libs. But I'm not sure about this.

**Comment by rbri** [comment]
This is because bootstrap uses the spread operator currently not supported by Rhino (https://github.com/mozilla/rhino/issues/1217).

**Comment by rbri** [comment]
If you like we can think about some transpile functionality as an enhancement for HtmlUnit....

**Comment by gimpox** [comment]
I solved by using Jsoup. I'm ok for the moment.

**Comment by rbri** [comment]
Ok, when Jsoup is enough then you can also use the WebClient and simply disable Javascript.

**Comment by rbri** [comment]
Thanks - will close this.
