### ISSUE TITLE
Misinformation of getByXPath method

### ISSUE THREAD

**Issue by TomasTokaMrazek** [HtmlUnit/htmlunit#52]
JavaDoc states: _"Evaluates the specified XPath expression **from this node**, returning the matching elements."_

That implies, that with given html 
```
<html>
<body>
    <h1>Wrong</h1>
    <div>
        <h1>Right</h1>
    </div>
<body>
</html>
```
and selected  _div_ node, in order to select child _h1_ node we need to pass xpath as **//h1**. But that's not the case, we need to select current node first with a dot selector, so correct xpath is **.//h1**. While it is proper xpath, I'd argue, that JavaDoc implies, that the node is already selected. It's specially confusing, if you print node as xml and try to validate your xpath via third party tools.

It's a bit against common sense, that selected node does not traverse from it's location. I do not expect change in the code, but more specific JavaDoc would be definitely helpful.

**Comment by rbri** [comment]
Have written as short test but i can't see you problem.

```
    /**
     * @throws Exception if the test fails
     */
    @Test
    public void getByXPathSelectedNode() throws Exception {
        final String htmlContent
            = "<html>\n"
            + "  <head>\n"
            + "    <title>my title</title>\n"
            + "  </head>"
            + "  <body>\n"
            + "    <div id='d1'>\n"
            + "      <h1 id='h1'>HtmlUnit</h1>\n"
            + "    </div>\n"
            + "</body>\n"
            + "</html>";
        final HtmlPage page = loadPage(htmlContent);

        final HtmlDivision divNode = (HtmlDivision) page.getElementById("d1");

        assertEquals(page.getElementById("h1"), divNode.getByXPath("//h1").get(0));
        assertEquals(page.getElementById("h1"), divNode.getByXPath(".//h1").get(0));
    }


Can you please check and make you problem/hint more clear.
```

**Comment by DSantiagoBC** [comment]
Please, try this test
```
    /**
     * @throws Exception if the test fails
     */
    @Test
    public void getByXPathSelectedNode() throws Exception {
        final String htmlContent
            = "<html>\n"
            + "  <head>\n"
            + "    <title>my title</title>\n"
            + "  </head>"
            + "  <body>\n"
            + "    <h1>Heading!</h1>\n"
            + "    <div id='d1'>\n"
            + "      <h1 id='h1'>HtmlUnit</h1>\n"
            + "    </div>\n"
            + "  </body>\n"
            + "</html>";
        final HtmlPage page = loadPage(htmlContent);

        final HtmlDivision divNode = (HtmlDivision) page.getElementById("d1");

        assertEquals(page.getElementById("h1"), divNode.getByXPath("//h1").get(0));
        assertEquals(page.getElementById("h1"), divNode.getByXPath(".//h1").get(0));
    }
```

**Comment by mguillem** [comment]
I disagree with the expectation of the provided test. For me the current implementation is correct. The `getByXPath` here is a bit like the `cd` command: if you perform `cd ./foo` you will move to the _foo_ subdirectory of the current dir but when you call `cd /foo`, you will move to the _foo_ subdirectory of the root, no matter where you are.

@DSantiagoBC: do you have a proposition to improve the javadoc to make it more clear for you?

**Comment by mguillem** [comment]
I disagree with the expectation of the provided test. For me the current implementation is correct. The `getByXPath` here is a bit like the `cd` command: if you perform `cd ./foo` you will move to the _foo_ subdirectory of the current dir but when you call `cd /foo`, you will move to the _foo_ subdirectory of the root, no matter where you are.

@DSantiagoBC: do you have a proposition to improve the javadoc to make it clearer for you?

**Comment by TomasTokaMrazek** [comment]
Apologies for delay, I was on vacation.

@DSantiagoBC 

```   
public void getByXPathSelectedNode() throws Exception {
        WebClient client = new WebClient();

        final String htmlContent = "<html>\n"
                + "  <head>\n"
                + "    <title>my title</title>\n"
                + "  </head>"
                + "  <body>\n"
                + "    <h1>Heading!</h1>\n"
                + "    <div id='d1'>\n"
                + "      <h1 id='h1'>HtmlUnit</h1>\n"
                + "    </div>\n"
                + "  </body>\n"
                + "</html>";

        StringWebResponse response = new StringWebResponse(htmlContent,
                new URL("http://htmlunit.sourceforge.net//test.html"));

        HtmlPage page = HTMLParser.parseHtml(response, client.getCurrentWindow());

        final HtmlDivision divNode = (HtmlDivision) page.getElementById("d1");

        log.debug("Xpath: {}", divNode.getByXPath("//h1").get(0));
        log.debug("Xpath: {}", divNode.getByXPath(".//h1").get(0));

        client.close();
    }
```

Result:
```
19:16:12.149 [main] [DEBUG] cz.jaktoviditoka.investmentportfolio.model.HtmlUnitTest - Xpath: HtmlHeading1[<h1>]
19:16:12.149 [main] [DEBUG] cz.jaktoviditoka.investmentportfolio.model.HtmlUnitTest - Xpath: HtmlHeading1[<h1 id="h1">]
```

@mguillem I don't see a single usecase, where you want to select child object from html page and call xpath traverse method, which searches the whole page including parents. Why exactly would I select some div node from HtmlPage and then call getByXPath on this div in order to search whole HtmlPage? From Java OOP standpoint, I should call the method on the original HtmlPage object. Java is not command line.

I personally think, that the dot in xpath should be implicit, not explicit. But as I said that would bring compatibility issues, so I'll settle with better docs. I literally spent hours trying to figure out, why getByXPath on child node searches whole tree. But that might be due to my WSO2 EI background, where the dot is basically never used.

**Comment by rbri** [comment]
Please have a look at the commit, hope the updated docu is a bit more clear.
Many thanks for the report and the discussion of all the details. Enjoy using HtmlUnit
