### ISSUE TITLE
Descriptor of Function.length should be configurable

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#521]
`var desc=Object.getOwnPropertyDescriptor(Function.prototype, 'length');`
In Chrome, desc.configurable is true while in htmlunit it's false.

**Comment by rbri** [comment]
Hi @RuralHunter,
fix is on the way - https://github.com/mozilla/rhino/pull/1284

Is it ok to have a new snapshot build containing this at the end of the week (~  2.12)?

**Comment by RuralHunter** [comment]
sure, thanks a lot!

**Comment by RuralHunter** [comment]
Sorry, it seems more change is needed.

```
var f=function(){};
var desc=Object.getOwnPropertyDescriptor(f, 'length');
```
and
`var desc=Object.getOwnPropertyDescriptor(alert, 'length');`

desc.configurable still gets false.

**Comment by rbri** [comment]
good point, pr is updated/fixed

**Comment by RuralHunter** [comment]
Thanks. I tested the new pr but it still didn't fix attributes for builtin functions(maybe others too):
`var desc=Object.getOwnPropertyDescriptor(alert, 'length');`
This still gets false result.

**Comment by rbri** [comment]
oh, i guess there is more to do... i have a fix already but i have to think about this to make the most generic solution

**Comment by rbri** [comment]
@RuralHunter next try is on the way

**Comment by RuralHunter** [comment]
Thanks. This time it fully works for my testing web site.

**Comment by rbri** [comment]
As always - it's a pleasure to work with you improving HtmlUnit (and sometimes Rhino).

Thanks for all your input.

**Comment by rbri** [comment]
Rhino PR is accepted, building a new snapshot is on the way.

**Comment by RuralHunter** [comment]
Great, thanks!

**Comment by rbri** [comment]
You can grab it.
