### ISSUE TITLE
Cookie with negative max age causes error

### ISSUE THREAD

**Issue by NubeBuster** [HtmlUnit/htmlunit#524]
Cloudflare sets a cookie with a max-age to see if you are a real browser or not. HTMLUnit fails on adding this cookie and therefore is detected. 

Error: 
"WARNING: Adding cookie 'cf_chl_2=; Max-Age=-99999999;' failed; reason: 'Negative 'max-age' attribute: -99999999'."

Could this be changed so that there is an option for allowing negative max age. A negative max age is for setting a cookie until the browser is closed, in practise,

**Comment by rbri** [comment]
> Could this be changed...

Every difference between real browsers and HtmlUnit is a bug - will try to fix this.
Thanks for the report.

**Comment by rbri** [comment]
Hm...

wrote a test for this

    @Test
    @Alerts("first=1")
    public void cookieMaxAge() throws Exception {
        final List<NameValuePair> responseHeader1 = new ArrayList<>();
        responseHeader1.add(new NameValuePair("Set-Cookie", "first=1;max-age=1000"));
        responseHeader1.add(new NameValuePair("Set-Cookie", "second=2;max-age=-1"));
        getMockWebConnection().setResponse(URL_FIRST, HTML_ALERT_COOKIE, 200, "OK", MimeType.TEXT_HTML,
                responseHeader1);

        loadPage2(URL_FIRST, StandardCharsets.ISO_8859_1);
        verifyTitle2(getWebDriver(), getExpectedAlerts());
    }


with

    /** HTML code with JS code <code>alert(document.cookie)</code>. */
    public static final String HTML_ALERT_COOKIE
        = HtmlPageTest.STANDARDS_MODE_PREFIX_
        + "<html><head>\n"
        + "<script>\n"
        + LOG_TITLE_FUNCTION
        + "  function test() {\n"
        // there is no fixed order, sort for stable testing
        + "    var c = document.cookie;\n"
        + "    c = c.split('; ').sort().join('; ');\n"
        + "    log(c);\n"
        + "  }\n"
        + "</script>\n"
        + "</head>\n"
        + "<body onload='test()'>\n"
        + "</body></html>";

As expected the second cookie is not there - also not visible in real browsers.

This test already works in HtmlUnit. How does cloudfare check this cookie?

**Comment by rbri** [comment]
Ok, i found (and fixed) a difference between HtmlUnit and real browsers - see the attached commit.

Will make a new snapshot available as soon as the ci has passed - will inform you.

**Comment by rbri** [comment]
@Nubebuster just made a new snapshot build - 2.68.0-SNAPSHOT - please try.

**Comment by Claudemirovsky** [comment]
> @Nubebuster just made a new snapshot build - 2.68.0-SNAPSHOT - please try.

I'm not him but I tried it and the cookie part worked without problems, although it still doesn't go through cloudflare.... but that's another problem, I think you can close this issue as solved.

**Comment by rbri** [comment]
Thanks, will close this.
@Nubebuster please open a new one if you still have problems.
