### ISSUE TITLE
Incorrect charset detected

### ISSUE THREAD

**Issue by tmoreno** [HtmlUnit/htmlunit#525]
Hi!

I have opened a page that server response has this header:

content-type: text/html;charset=ascii

But a real web browser, like chrome or firefox, detects: windows-1252

Because of that when I find elements on the web page (using querySelectorAll or getByXPath or getElementsByTagName), the value has invalid characteres.

It is possible to indicate a different charset when read the page?

Thanks!!

**Comment by rbri** [comment]
Will try to fix that - but at the moment i have problems to simulate your case for a unit test.
Do you have any chance to capture the whole server response using e.g Charles WebProxy or Fiddler?

**Comment by tmoreno** [comment]
Do you mean add Fiddler or Charles to my project?

**Comment by rbri** [comment]
sorry no.
The point is that not only the header is taken into account to determine the page. As always i like to write a test case that shows the problem before fixing it.
Maybe we can start simpler... maybe you can use the network stuff from you browser to show me the response headers and the response itself....

**Comment by tmoreno** [comment]
This is the page requested, you can use curl to download the content:

https://www.totalpadel.com/Mallas_mujer_adidas_Game_Set_Match_Oto_xF1_o/descpageWAADIT-AWFMT-ES.html

Response headers are (according to chrome):

access-control-allow-origin: *
content-encoding: gzip
content-length: 13185
content-security-policy: frame-ancestors 'self' https://*.tenniswarehouse-europe.com https://*.tennis-warehouse.com https://*.runningwarehouse.com https://*.runningwarehouse.eu https://www.runningwarehouse.de https://www.runningwarehouse.it https://www.runningwarehouse.es https://www.runningwarehouse.fr;
content-type: text/html;charset=ascii
date: Mon, 12 Dec 2022 11:16:40 GMT
server: Apache
strict-transport-security: max-age=31536000; includeSubDomains
vary: Accept-Encoding,User-Agent
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN

So, according to the server, the enconding is ascii, but if you read the content body with that encoding, wrong characteres appear (go to 1251 line, at the end appears Marr�n), but if you read the body with ISO 8859-1 the content is correct. I have open the web page with different encodings using VSCode.

I have reviewed the HtmlUnit code and I think that you are decoding the content body using the content-type header.

**Comment by rbri** [comment]
Ok will have a look and come back to you....

**Comment by rbri** [comment]
Did a second shot on this and now i was able to write a test case that reproduces your problem.
Have done a check with your sample page also - works also fine.

Will make a new snapshot available soon - have a look at https://twitter.com/htmlunit to be informed when the update is available.
