### ISSUE TITLE
HTMLUnit does not return page Object when host returns status code 204

### ISSUE THREAD

**Issue by vasucomandur** [HtmlUnit/htmlunit#527]
The page object is null when host returns status code 204.
Could not look into response headers, status code etc.

**Comment by rbri** [comment]
Hi @vasucomandur,

can you please scrible a sample code of your expectation - already had a look into the code and i'm not sure what you are like to do / expect. 204 is already handled but more or less ignored.

**Comment by vasucomandur** [comment]
Hi,

   The host is sending some information as part HTTP response for 204
status. That information is required for me
   to use it in subsequent requests.I am not able to get the status code
also since the object is not returned.

   I am copying the HTTP response header as part of 204 status code. The
X-trace info is needed for me.

:status 204
server nginx
x-trace 2B39D413C3401C20927C878788F95ED9BC55A77781000000000000000000
access-control-allow-origin https://resdex.naukri.com
access-control-allow-headers x-requested-with,
access-control-allow-methods GET, POST, PUT
access-control-allow-credentials true
date Tue, 06 Dec 2022 08:47:24 GMT
  I hope the above information helps you.

Regards
 Vasu

**Comment by rbri** [comment]
Sorry, not really - i'm more interested in the java code you like to use to get the page....

**Comment by vasucomandur** [comment]
Hi,

   I am using Clojure programming and not Java.

    I am pasting the Clojure code snippet below

  * URL Construction with payload
    url-data (str "https://lg.naukri.com/uba?data=")
     qry1-data (str
"{\"rt.start\":\"navigation\",\"t_resp\":\"268\",\"t_page\":\"2875\",\"t_done\":\"3143\",\"r\":\""
(URLEncoder/encode req-url) "\",\"r2\":\"" (URLEncoder/encode ref-url)
"\",\"t_resr\":{\"t_domloaded\":1522},\"u\":\"nmit-" (URLEncoder/encode
req-url)
"\",\"nt_dns\":\"0\",\"nt_plt\":\"628\",\"nt_render\":\"2614\",\"nt_req\":\"252\",\"nt_res\":\"5\",\"nt_tcp\":\"0\",\"appId\":112,\"tag\":\"v3-preview-nmit\",\"eventName\":\"newMonkPerformance\",\"tenantId\":"
tenant-id ",\"deviceType\":\"" device-type
"\",\"screen_res\":\"1366x768\",\"pageUID\":\"" page-uid
"\",\"nLoggerCustomObject\":{\"pageUID\":\"" page-uid
"\",\"webVitalsEnabledRoute\":\"false\",\"hostname\":\"" host-name
"\",\"companyId\":\"" comp-val "\",\"userId\":\"" user-id-val "\"}}")
  web-req (new WebRequest (new URL qry1-data) (HttpMethod/GET)) ;
WebRequest block constructed.


    *******************************Instantiating Web Client  and setting browser properties*******************
         (start-page (do
                      (enable-javascript false)
     (enable-httpexception false) ; Disable the HTTP and script exceptions
     (enable-scriptexception false) ; Disable the script exceptions
                      (.setUseInsecureSSL (.getOptions *wc*) true)
                      (.addRequestHeader *wc* "Referer" "https://resdex.naukri.com/")
            web-req)

  ************************* Reading the response from Host code *************
                page-data (with-loaded-page (.getEnclosedPage(.getCurrentWindow *wc*))
                                         *page*)
                content-type   (if (not= *page* nil)
                                          (.getContentType (.getWebResponse*page*))
                                           "exception")
                st2-data (println "THE CONTENT TYPE IS >>>>>>" content-type " PAGE OBJECT TYPE >>>>>" (type *page*) )

I am getting *page* as nil, Content-type is also nil  when Status Code is 204

  I hope the above code snippet with some comments helps you
  Looking forward to your reply

Regards
 Vasu

**Comment by rbri** [comment]
Hi @vasucomandur,

i think the handling of 204 is (more or less) correct in HtmlUnit.

> The HTTP 204 No Content success status response code indicates that the request has succeed, but that the client doesn't need to go away from its current page.
(http://man.hubwiz.com/docset/HTTP.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/HTTP/Status/204.html)

When getting a 204 response code, the page of the window is not replaced.

Is it an option for you to use WebClient.loadWebResponse(WebRequest)?

**Comment by rbri** [comment]
@vasucomandur 

> Is it an option for you to use WebClient.loadWebResponse(WebRequest)?

**Comment by vasucomandur** [comment]
Hi,

   Looks like it may work. But I need to test it. The WebRequest object,
WebClient object are not null and the
   webResponse object can be accessed in this way rather than using the
PAGE object which is NULL.

   I shall check & revert.

Regards
 Vasu

**Comment by vasucomandur** [comment]
Hi,

   It worked. Thanks for the help.

Regards
 Vasu

**Comment by rbri** [comment]
Ok, will close this - waiting for your next one ;-)
