### ISSUE TITLE
Object.keys() does not enumerate properties of window.location

### ISSUE THREAD

**Issue by atnak** [HtmlUnit/htmlunit#528]
# Problem in brief

Properties of `window.location` are not enumerated by methods such as `Object.keys()`, `Object.entries()`, `Oject.getOwnPropertyNames()` but are when `location.__proto__` is queried instead.

# Reproducing

Below code shows expected behaviour (tested in Chrome, Firefox, Edge) and that of HtmlUnit 2.66.

```html
<!DOCTYPE html>
<html>
<head>
<script>

// Expected: [href,origin,protocol,host,hostname,port,pathname,search,hash,assign,replace,reload,toString]
// HtmlUnit 2.66: []
console.log(Object.keys(location));

// Expected: []
// HtmlUnit 2.66: [search,hostname,protocol,port,origin,host,href,hash,pathname,reload,replace,toString,assign]
console.log(Object.keys(location.__proto__))

</script>
</head>
<body>
</body>
</html>
```

* FWIW, in IE it was enumerated in both cases.

# More details

This practical consequence of this issue and the site it was discovered was using code like this:

```javascript
let abc = {}
console.log(Object.assign(abc, location).href)
```

The issue is complicated by the fact this expected behaviour seems more or less specific to `window.location`. For other properties such as those under `window.screen` the way HtmlUnit behaves is the expected:

```html
<!DOCTYPE html>
<html>
<head>
<script>

// Expected: []
// HtmlUnit 2.66: []
console.log(Object.keys(screen));

// Expected: [availWidth, availHeight, width, height, colorDepth, pixelDepth, availLeft, availTop, orientation, onchange, isExtended]
// HtmlUnit 2.66: [orientation, onchange, availLeft, availWidth, pixelDepth, top, left, availTop, width, colorDepth, mozOrientation, height, availHeight]
console.log(Object.keys(screen.__proto__))

</script>
</head>
<body>
</body>
</html>
```

**Comment by rbri** [comment]
Hi @atnak,
will have a look at this. Is it ok when i do it at the end of this week?

**Comment by atnak** [comment]
@rbri Thanks, we aren't impacted by this issue since we have a local workaround and there's no urgency.  Priority wise, https://github.com/HtmlUnit/htmlunit/issues/523 is slightly higher up but refactoring that will probably be costly and we don't have a good solution for that.  There's no real urgency for either.

**Comment by rbri** [comment]
Hopefully i have fixed this - please try the new snapshot.

**Comment by duonglaiquang** [comment]
I have tested your fix with our local issue and have confirmed it works. Thank you very much ! 😄

**Comment by rbri** [comment]
Great - waiting for the next one :-)
