### ISSUE TITLE
HtmlLink spams log with unnecessary warnings

### ISSUE THREAD

**Issue by svschouw-bb** [HtmlUnit/htmlunit#53]
It seems `HtmlLink` now logs a warning whenever an unknown `<link>` tag is encountered, or when a stylesheet link is encountered whenever CSS is disabled. But to me, both cases seem perfectly OK.

First, there are a number of other `<link>` types (like favicons) for which it is reasonable that htmlunit does not support them. That doesn't mean we shouldn't use them on our pages to test.

Second, we try to turn off CSS parsing whenever possible, since it makes the tests ungodly slow. But this doesn't mean the pages won't have CSS for styling.

Suggested fix: change the "Link type 'x' not supported" log message to DEBUG or INFO.

For now, as a workaround, we will just disable HtmlLink logging.

**Comment by rbri** [comment]
Have done some work for this, you you like it - if not please reopen this.
Thanks for the report and for using HtmlInit
