### ISSUE TITLE
【enhance】Add support for css4

### ISSUE THREAD

**Issue by RussiaVk** [HtmlUnit/htmlunit#530]
htmlunit seem not support  css4:
```
	public static void main(String[] args) throws IOException {
		try (WebClient webClient = new WebClient(BrowserVersion.CHROME)) {
			webClient.getOptions().setJavaScriptEnabled(false);
			webClient.getOptions().setUseInsecureSSL(true);
			webClient.getOptions().setCssEnabled(true);
			webClient.getOptions().setThrowExceptionOnScriptError(false);
			final HtmlPage page = webClient.loadHtmlCodeIntoCurrentWindow(
					"<html><head><meta content='码云,Gitee,代码托管,git,开源,内源,开源项目托管,免费代码托管,Git代码托管,企业代码管理' name='Keywords'></head><body></body></html>");
			String tags = Optional.ofNullable(page
					.querySelector("[name='keywords' i]")).map(v -> (HtmlMeta) v)
					.map(HtmlMeta::getContentAttribute).orElseGet(() -> StringUtils.EMPTY);
			System.out.println(tags);
		} 
	}
```
throw:
`com.gargoylesoftware.css.parser.CSSException: Invalid selectors: [name='keywords' i]`

[http://www.w3.org/TR/selectors4/#attribute-case](http://www.w3.org/TR/selectors4/#attribute-case)

**Comment by rbri** [comment]
Hi @RussiaVk,
i fear you are right, do you like to create an PR for this?

**Comment by rbri** [comment]
Your journey can start here https://github.com/HtmlUnit/htmlunit-cssparser/blob/master/src/main/javacc/CSS3Parser.jj#L1270

**Comment by RussiaVk** [comment]
> Your journey can start here https://github.com/HtmlUnit/htmlunit-cssparser/blob/master/src/main/javacc/CSS3Parser.jj#L1270

Sorry,I know nothing about javacc :(

**Comment by rbri** [comment]
Ok, will do it, and inform about updates (at least on twitter https://twitter.com/htmlunit).

You can speed up this by providing stars on gitbub or sponsoring ;-)

**Comment by rbri** [comment]
Ok found some time to implement this. Will make a new snapshot build available if the ci is happy with this.
Please check twitter.

Thanks for the report and for using HtmlUnit.
