### ISSUE TITLE
RequestParameter normalization replaces KeyDataPair with NameValuePair

### ISSUE THREAD

**Issue by thuri** [HtmlUnit/htmlunit#532]
Request Parameters of type KeyDataPair are replaced by instances of type NameValuePair when WebRequest#getParameters is called.
This introduces issues with Spring Boot 3 and especially spring-test 6 where the getParameters method is called instead of getRequestParameters as it has been in spring-test 5.x

See https://github.com/HtmlUnit/htmlunit/commit/39c58d2b114bebb157be57d63416f629630eee07#r93713845

I've already a proposal how this can be fixed. Pull Request incoming :-D

**Comment by rbri** [comment]
@thuri thanks  and please have a look at my last commit - hopefully i have nothing broken.

**Comment by thuri** [comment]
@rbri  it looks like your commit doesn't include my last commit containing the private copy constructor and its usage

**Comment by thuri** [comment]
Sorry, i'm a bit confused. I looked at the commit 16a9083 that was reference here in the conversation. But that's not the commit you meant which is 42cb0628a9fd848b914458ec37d2bf458494be7e if I'm right. That one looks good to me
