### ISSUE TITLE
Support for Unpoly

### ISSUE THREAD

**Issue by barrypitman** [HtmlUnit/htmlunit#534]
I'm struggling to use HtmlUnit (via webdriver) to test my application which is using unpoly - unpoly.com. 

When you click on links, unpoly will make the request using AJAX instead of a full-page reload, and swap out the old HTML with the new. However, when I try to click on these same links using HtmlUnit, nothing happens, i.e. the original HTML remains in place. 

I'm not seeing any errors in the logs either so I don't know where to start looking. There is a demo site - https://demo.unpoly.com/ and I've attached a test case (using HtmlUnitDriver) which demonstrates the issue. 

ChromeDriver and HtmlUnitDriver without javascript both work, but HtmlUnitDriver with javascript enabled doesn't work.

[unpoly_test.zip](https://github.com/HtmlUnit/htmlunit/files/10277319/unpoly_test.zip)

Thanks for a great project!

**Comment by rbri** [comment]
ok,will have a look

**Comment by rbri** [comment]
good news, looks like the js code is loaded and at least the request for the companies is triggered.
But  the  page update does not take place. Will be a harder story to understand why....

**Comment by rbri** [comment]
have set up a local debug environment for this - first found problem is this one (https://github.com/mozilla/rhino/pull/1293)
if merged i have to fix the processing of \n in the htmlunit part of the console processing.

**Comment by rbri** [comment]
ok, next step - seems to be a problem with Object.assign - if using the polyfill (line 260) replaces the content.
Will require some time to write a test for this and than the hard part with rhino starts.

**Comment by rbri** [comment]
Looks like this solves the problem

https://github.com/mozilla/rhino/issues/780

https://github.com/mozilla/rhino/pull/1242

**Comment by rbri** [comment]
Have done a new snapshot build that should fix this. @barrypitman please try and report your findings.

**Comment by barrypitman** [comment]
@rbri thank you so much! I have tested with [2.68.0](https://mvnrepository.com/artifact/net.sourceforge.htmlunit/htmlunit/2.68.0) and its working!

**Comment by rbri** [comment]
@barrypitman great - have fun using HtmlUnit
