### ISSUE TITLE
RegExpJsToJavaConverter \u{12345} to \x{12345}

### ISSUE THREAD

**Issue by Jaaap** [HtmlUnit/htmlunit#535]
We have an HTML pattern that looks like this:
```html
<input type="text" pattern="[^\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F\uE000-\uF8FF\u{F0000}-\u{FFFFD}]*"/>
```
Observe the `\u{F0000}`, this is valid JS syntax but in java it should be `\x{F0000}`.
Is it possible to add this to the `RegExpJsToJavaConverter.convert()` method?

**Comment by rbri** [comment]
yes it is :-)

@Jaap do you like to prepare a PR or should i have a look?

**Comment by Jaaap** [comment]
Please if you could do it.

**Comment by jaap** [comment]
Wrong jaap @rbri @Jaaap

**Comment by rbri** [comment]
Yes i already had a look - its a bit more complicated because this is only handled if the regex has the u flag...

Will try to fix it soon but no promises.

**Comment by rbri** [comment]
> Wrong jaap @rbri @Jaaap

sorry

**Comment by Jaaap** [comment]
> its a bit more complicated because this is only handled if the regex has the u flag...

I read that but in an HTML pattern the u flag doesn't exist afaik but the `\u{F0000}` works nonetheless.

**Comment by rbri** [comment]
a bit related - https://github.com/mozilla/rhino/issues/958

**Comment by rbri** [comment]
> > its a bit more complicated because this is only handled if the regex has the u flag...
> 
> I read that but in an HTML pattern the u flag doesn't exist afaik but the `\u{F0000}` works nonetheless.

Ah ok, will have a look and add some tests first...

**Comment by rbri** [comment]
First simplified impl is done - lets wait for the ci and then i will make a new snapshot.
Many thanks for pointing at this.

**Comment by rbri** [comment]
snapshot is updated - please try

**Comment by rbri** [comment]
will close this - please reopen if it did not work for you

**Comment by Jaaap** [comment]
Tested 2.68.0-SNAPSHOT and it works.
Thank you!
