### ISSUE TITLE
No JavaScript issues when using WebDriverManager as a dependency

### ISSUE THREAD

**Issue by stjepanmamusa** [HtmlUnit/htmlunit#545]
# Problem
Simple code for scraping a JavaScript generated HTML with currency exchange rate as text values can be found [in this file (GitHub)](https://github.com/smamusa/exchange-rate-scraper/blob/java-concept/src/main/java/com/smamusa/Main.java). When I run the code it sometimes works, but most times it doesn't due to enormous amount of JS related bugs.

- [x] throw exception on script error set to false
- [x] javascript enabled set to true (it has to be)

## Solution 1
Wrap everything up in try catches with error suppression (more like a hackaround 😒)
## Solution 2
Add [Web Driver Manager (MVN Central)](https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager/5.3.1) to your POM.xml.

This other solution is probably not connected to anything with HtmlUnit itself, maybe it's just suppressing the output because it's using the NO-OP as default Slf4J option, so this would actually be solution 1 in the end.

## Attachments
I've provided an IntelliJ terminal screenshot (With Web Driver Manager added to POM.xml) and a .TXT file with log output of what happens when I remove it from POM.xml.

The website in question is at https://www.otpbanka.hr/tecajna-lista

**Comment by stjepanmamusa** [comment]
Actually I was very wrong, enabling insecure SSL fixed the issue, and since I don't care about failed scripts in my project I resolved this by disabling HTMLUnit logging (for packaged app)

To disabled it use this code snippet
`java.util.logging.Logger.getLogger("com.gargoylesoftware.htmlunit").setLevel(Level.OFF); java.util.logging.Logger.getLogger("org.apache.commons.httpclient").setLevel(Level.OFF);
`

Also don't forget the 🙂
`options.setThrowExceptionOnScriptError(false);`

**Comment by rbri** [comment]
Hi @smamusa,
great to hear HtmlUnit is of some use for you.

Greetings to split....
