### ISSUE TITLE
Do not set referer header when anchor has rel="noreferrer"

### ISSUE THREAD

**Issue by Jaaap** [HtmlUnit/htmlunit#546]
It appears that referer headers are sent after clicking on a link even when the anchor has the `rel="noreferrer"` attribute set (see `HtmlAnchor.java:174`).

Please add a check for the `rel` attribute of anchors (`form`s can have them too) and do not set the `referer` header when its value is `noreferrer`.

More info: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

**Comment by rbri** [comment]
hopefully simple - thanks for the report

**Comment by rbri** [comment]
@Jaaap
snapshot is updated, please test.

Had a look at forms also but the current browsers are ignoring the rel attribute.
