### ISSUE TITLE
htmlunit-cssparser dependency

### ISSUE THREAD

**Issue by jjanderson5** [HtmlUnit/htmlunit#55]
I'm would like to submit this to the 'mailing list', but I have not been able to join the mailing list. I'm working on that in a different thread.

I would like to compile HtmlUnit. I went to the 'Dependencies' page and started downloading the required jar files. When I got to the htmlunit-cssparser, I followed the link, but I could not find a jar file for this unit. Note that the link connected me to verion 1.3, not 1.4 as suggested on the dependencies page. I downloaded the source and compiled with "mvn compile" and then "mvn test". I then did a search of the directory structure, but I could not find a jar file.

Is there a 1.4.0 jar file? If so, can you fix the page link so that the jar file can be downloaded?

Any help is much appreciated.

Regards,
Jim Anderson

**Comment by rbri** [comment]
Hi Jim,
HtmlUnit uses maven as build system - no need to download the dependencies manually. Simply install maven (if not already done) and execute 'mvn compile' from the command shell.

**Comment by jjanderson5** [comment]
Thank you for the help. I've never used maven, but I will give this a shot.

Jim
