### ISSUE TITLE
Find buttons by type may return more elements than expected

### ISSUE THREAD

**Issue by jowerner** [HtmlUnit/htmlunit#555]
When finding buttons by type attribute via CSS, there is a tiny discrepancy between HtmlUnit and real browsers. For example, when we search for `button[type='submit']`, HtmlUnit will find not only submit buttons, but also buttons without a type attribute. Maybe this is because the default value for the type attribute is `submit`. BTW, does not happen when searching via XPath.

Other elements / other attributes may be affected in a similar fashion, but not sure. Tested this with input elements and `input[type='text']`, but this works as expected.

Thanks!

**Comment by jowerner** [comment]
[FindButtonsByTypeTest.java.txt](https://github.com/HtmlUnit/htmlunit/files/10862136/FindButtonsByTypeTest.java.txt)

Small test case attached as *.txt file.

**Comment by rbri** [comment]
Hi @jowerner,

fix should be simple, will do this over the weekend.

**Comment by jowerner** [comment]
Awesome, thanks a lot!

**Comment by rbri** [comment]
As always thanks, have to do some cleanup on the weekend and a new Snapshot will (hopefully) available on monday
