### ISSUE TITLE
PGP Signature INVALID - for Version 3.0

### ISSUE THREAD

**Issue by rbri** [HtmlUnit/htmlunit#563]
10:05:27 [ERROR] org.htmlunit:htmlunit:pom:3.0.0 PGP Signature INVALID
10:05:27        KeyId: 0x5E7D42F58249A287BD7384DA25A73BFC746E1035 UserIds: [Ronald Brill (wetator) <rbri@rbri.de>]

**Comment by rbri** [comment]
seems to be a problem on the ci server - disabled the step for the moment

**Comment by rbri** [comment]
problem is gone

**Comment by pzygielo** [comment]
Hi @rbri 

I tried to refresh 0x5E7D42F58249A287BD7384DA25A73BFC746E1035 from
hkp://keyserver.ubuntu.com/ and hkp://pgp.surfnet.nl, with no success.
The key I currently have in my ring expired 2023-04-10.

I failed to find KEYS or equivalent on https://htmlunit.sourceforge.io/index.html.

It seems that the key is used to sign Maven Central artifacts of htmlunit:
```
gpg: assuming signed data in 'org/htmlunit/htmlunit/4.4.0/htmlunit-4.4.0.jar'
gpg: Signature made Sun 28 Jul 2024 10:43:42 CEST
gpg:                using RSA key 5E7D42F58249A287BD7384DA25A73BFC746E1035
gpg: Good signature from "Ronald Brill (wetator) ..." [expired]
gpg: Note: This key has expired!
```

Thus I suppose its validity date was changed locally. Perhaps the key/signature was not distributed to servers.

Given that - may I ask to publish an updated key, please?
