### ISSUE TITLE
htmlunite 3.0 ajax not send cookie

### ISSUE THREAD

**Issue by yuedaxia76** [HtmlUnit/htmlunit#565]
when by jquery ajax post ,the session cookite not send,bug 2.X is ok.

    function sm2login(logInfo, callback) {
        $.ajax({
            type: "POST",
            url: getContextPath() + "/do/login/getSm2key",
            dataType: "json",
            //cache:false,
            success: function (data) {
                var pubkeyHex = data.pubkey;
                var cipherMode = 1;
       
                var u =sm2Encrypt(logInfo.loId, pubkeyHex, cipherMode);
                var p =sm2Encrypt(logInfo.pwd, pubkeyHex, cipherMode);  
               **/////this post cookie not send**
                $.post(getContextPath() + "/do/login/validateSm2", {
                    "loginId": u,
                    "password": p,
                    "serVety": logInfo.serVe,
                    "IMG_CHECK": logInfo.imgV
                }, callback );
            },
            error: function (data) {
                console.log(data);
            }
        });
    }

**Comment by rbri** [comment]
Please try with 3.1.0-SNAPSHOT hopefully this is already fixed.

**Comment by rbri** [comment]
see https://github.com/HtmlUnit/htmlunit/commit/d1200887068a33d4c7cb73bececeb9bbf4b92ec9

**Comment by yuedaxia76** [comment]
3.1.0-SNAPSHOT is ok.

**Comment by rbri** [comment]
OK, great, will make a new release soon.

thanks for the report and have fun/success using HtmlUnit.
