### ISSUE TITLE
I cant login 

### ISSUE THREAD

**Issue by webdevpls** [HtmlUnit/htmlunit#567]
i cant login on this website, about 3 days ago the login worked, today it doesn't anymore.

![image](https://user-images.githubusercontent.com/89544240/228012223-0145e080-ab74-49a1-8c78-cd91089aba8c.png)

![image](https://user-images.githubusercontent.com/89544240/228012324-32ce154a-a185-4a8a-8f77-54a7507c6e44.png)

![image](https://user-images.githubusercontent.com/89544240/228012369-ac87409e-f3f8-4dd2-b611-25a4d1dde45a.png)

**Comment by webdevpls** [comment]
i think the problem is the attribute ''login-disabled" and i cant get the form.

**Comment by rbri** [comment]
Will have a look

**Comment by duonglaiquang** [comment]
@pedrolucc11 are you using the newest version 3.0.0 ?
If so, then i think the cause is the `setValueAttribute()`. Could you try using `setValue()` or `type()` instead ?

> INCOMPATIBLE CHANGE: Value processing for input controls changed; typing now ONLY changes the value but not the value attribute. As consequence all calls to setValueAttribute(..) hve to be replaced by setValue() or type().

**Comment by webdevpls** [comment]
im using the 2.7 version, how do i update it?

Em ter., 28 de mar. de 2023 às 00:37, duonglaiquang <
***@***.***> escreveu:

**Comment by webdevpls** [comment]
how do i update my html unit? how can i see wich version that im using?
