### ISSUE TITLE
[Regression 3.0.0] Incorrect placement of synthesized '</form>'

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#570]
# Problem in brief

Regression in HtmlUnit 3.0.0 causes bad DOM tree creation when `</form>` is missing in the source and synthesized.

# Reproducing

Here is a example showing and reproducing the issue.

Input HTML:

```html
x<form name="f1">y
```

### Incorrect DOM tree created created by HtmlUnit 3.0.0:

```html
<html>
  <head/>
  <body>
    x
    <form name="f1">
    </form>
    y
  </body>
</html>
```

### DOM tree created by Chrome:

```html
<html>
  <head/>
  <body>
    x
    <form name="f1">
      y
    </form>
  </body>
</html>
```

# More details

* The issue appears to be related this following condition added in commit [`651cee1301747dd11a250bc01d36c5a6bde53598`](https://github.com/HtmlUnit/htmlunit/commit/651cee1301747dd11a250bc01d36c5a6bde53598):
https://github.com/HtmlUnit/htmlunit/blob/d813e878dac3d442a9df8cc49688d828a32c93c7/src/main/java/org/htmlunit/html/parser/neko/HtmlUnitNekoDOMBuilder.java#L560

**Comment by rbri** [comment]
will have a look at this tomorrow - but if you like to provide a test case it will help

**Comment by rbri** [comment]
ok, was able to write a test - will try to find a solution

**Comment by rbri** [comment]
fixed - no idea why i left this in ;-)
