### ISSUE TITLE
isSecureContext not recognized in JavaScript

### ISSUE THREAD

**Issue by MarkEWaite** [HtmlUnit/htmlunit#573]
@jtnord of the Jenkins project found that automated tests fail when `isSecureContext` is checked in JavaScript of a page being tested with HtmlUnit.  [JENKINS-70895](https://issues.jenkins.io/browse/JENKINS-70895) is the Jenkins issue report.

We've inserted a workaround into the problematic Jenkins code that avoids evaluating `isSecureContext` when running our automated tests.  See the workaround at:

* https://github.com/jenkinsci/jenkins/pull/7784

**Comment by rbri** [comment]
Thanks for the report, will make this function available in 3.1.0.

**Comment by rbri** [comment]
have done a first impl - please try with the current 3.1.0 snapshot

**Comment by MarkEWaite** [comment]
Sincere apologies @rbri but I won't be able to try it with the current 3.1.0 snapshot.  I had to rely on @jtnord to duplicate it in his environment.

**Comment by rbri** [comment]
3.2.0 is now available, will close this.
@MarkEWaite please open a new one if this is still a problem (or you find something new ;-))
