### ISSUE TITLE
JavaScript function hasOwnProperty() incorrectly returns false

### ISSUE THREAD

**Issue by gilles-l** [HtmlUnit/htmlunit#578]
Hi,

I have an HTML form named testForm, with a hidden input named testInput, and testing the presence of that input with testForm.hasOwnProperty("testInput") returns false when run in HtmlUnit. In browsers, it returns true.

I have tested with both HtmlUnit 2.70 and 3.0.0, and hasOwnProperty() returns false with both versions. With 3.0.0, I have the additional issue that the test 'testForm.testInput !== undefined' also returns false. It returns true in HtmlUnit 2.70.

I have attached the HTML page, as well as a Unit test showing the issues.

Thanks,
Gilles

[BugReport hasOwnProperty.zip](https://github.com/HtmlUnit/htmlunit/files/11174199/BugReport.hasOwnProperty.zip)

**Comment by rbri** [comment]
Hi @gilles-l ,
thanks for your but report.

I was able to reproduce the hasOwnProperty problem (and fixed it). But the testForm.testInput !== undefined seems to work already.

Can you please have a look at the tree test cases at the end of https://github.com/HtmlUnit/htmlunit/blob/be92531a33227de45f764e8ab5a2bc89547850c4/src/test/java/org/htmlunit/html/HtmlForm2Test.java

Maybe there is something wrong with my tests.

**Comment by rbri** [comment]
Have done a new snapshot build 3.1.0-SNAPSHOT.
(Please have a look at https://github.com/HtmlUnit/htmlunit to see how to use the snapshot)

@gilles-l please try and inform about your findings

**Comment by rbri** [comment]
please try the latest snapshot 
htmlunit3-driver 
4.8.3-SNAPSHOT

In general the htmlunit driver should (exactly) behave like the driver with the real browser in the back. Everything else is an error.

**Comment by gilles-l** [comment]
I tested using the 3.1.0 snapshot, and now the two unit tests pass. I used these jars:

htmlunit-3.1.0-20230407.172415-10.jar
htmlunit-core-js-3.1.0-20230410.142608-1.jar
htmlunit-cssparser-3.1.0-20230318.154858-1.jar
htmlunit-xpath-3.1.0-20230318.153540-1.jar
neko-htmlunit-3.1.0-20230411.154246-6.jar

So both issues have been fixed. Thanks!

Gilles

**Comment by gilles-l** [comment]
And thank you for being so fast at fixing the issues!

**Comment by rbri** [comment]
github stars are always welcome ;-)
