### ISSUE TITLE
Destructuring assignment falling with com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter] error: message=[missing : after property id]

### ISSUE THREAD

**Issue by vplemyannik** [HtmlUnit/htmlunit#581]
Hi, now i have another error related with ES6 syntax - [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

HtmlUnit could not parse such js function and falling dawn with error 
`ERROR [com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter] error: message=[missing : after property id] sourceName=[script in https://localhost:8543/auth/realms/authz-test/protocol/openid-connect/auth?response_type=code&client_id=test-public-client&redirect_uri=https%3A%2F%2Flocalhost%3A8543%2Fauth%2Frealms%2Fmaster%2Fapp%2Fauth&state=ee3af90b-fe0f-4afa-85bd-da73b5c1109a&scope=openid from (88, 9) to (101, 10)] line=[96] lineSource=[    function preventDoubleClick({ submitter }) {] lineOffset=[45]
`
```js
function preventDoubleClick({ submitter }) {
        if (submitter) {
            submitter.disabled = true;
        }
    }
```

But this syntax works correctly 
```js
function preventDoubleClick(submitEvent) {
        if (submitEvent.submitter) {
            submitEvent.submitter.disabled = true;
        }
    }
```

Do you know is this syntax supported in htmlunit3?

**Comment by rbri** [comment]
Sorry but this is another feature currently not supported by rhino/core-js.

**Comment by vplemyannik** [comment]
ok, thank you
