### ISSUE TITLE
get the list of lawyers' names

### ISSUE THREAD

**Issue by webdevpls** [HtmlUnit/htmlunit#582]
i want get the list of lawyers' names, how can i do? according to the code you yourself helped me

![image](https://user-images.githubusercontent.com/89544240/232134104-a4df8208-d02f-49f4-b673-e693934ebf9e.png)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

package org.tjpb;

import com.gargoylesoftware.htmlunit.*;
import com.gargoylesoftware.htmlunit.html.*;

import java.io.IOException;
import java.net.MalformedURLException;

public class TJPBTEST {

    private static final String url = "https://pje.tjpb.jus.br/pje2g/login.seam";

    public static void main(String[] args) throws FailingHttpStatusCodeException, MalformedURLException, IOException {

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX /* , "localhost", 8888 */)) {
            webClient.getOptions().setUseInsecureSSL(true);

            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);

            HtmlPage page = webClient.getPage(url);

            webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
            page = (HtmlPage) page.getEnclosingWindow().getEnclosedPage();

            page = login(webClient, page);

            page = navigateToConsultaProcessos(webClient, page);

            page = processConsultaProcessosFilter(webClient, page);

            HtmlInlineFrame iframe = page.getHtmlElementById("frameConsultaProcessos");
            HtmlPage filteredResultsPage = (HtmlPage) iframe.getEnclosedWindow().getEnclosedPage();

            System.out.println("-------------------------------");
            System.out.println("- filter result ---------------");
            // System.out.println(filteredResultsPage.asXml());
            // System.out.println("-------------------------------");
            System.out.println("-------------------------------");

            HtmlAnchor anchro = filteredResultsPage.getAnchorByText("0000347-03.2017.8.15.0371");

            anchro.click();
            webClient.waitForBackgroundJavaScriptStartingBefore(10_000);

            WebWindow newWin = webClient.getTopLevelWindows().get(webClient.getTopLevelWindows().size() -1);
            HtmlPage newPage = (HtmlPage) newWin.getEnclosedPage();

            System.out.println("-------------------------------");
            System.out.println("- detail ----------------------");
           // System.out.println(newPage.asXml());
            System.out.println("-------------------------------");
            System.out.println("-------------------------------");

            HtmlInlineFrame documentFrame = newPage.getHtmlElementById("frameHtml");
            HtmlPage documentPage = (HtmlPage) documentFrame.getEnclosedWindow().getEnclosedPage();

            System.out.println("-------------------------------");
            System.out.println("- documents -------------------");
            //System.out.println(documentPage.asXml());
            System.out.println("-------------------------------");
            System.out.println("-------------------------------");
        }
    }

    private static HtmlPage login(WebClient webClient, HtmlPage page) throws IOException {
        HtmlPage loginPage = page;

        boolean plainLogin = page.getElementById("login") != null;

        if (!plainLogin) {
            System.out.println("Loging form not found - search for iframe");

            HtmlInlineFrame iframe = page.getHtmlElementById("ssoFrame");
            HtmlPage iPage = (HtmlPage) iframe.getEnclosedWindow().getEnclosedPage();

            loginPage= iPage;
        }

        HtmlTextInput user = loginPage.getHtmlElementById("username");
        HtmlPasswordInput password = loginPage.getHtmlElementById("password");
        user.type("******");
        password.type("*******");

        if (plainLogin) {
            loginPage.getHtmlElementById("btnEntrar").click();
        } else {
            loginPage.getHtmlElementById("kc-login").click();
        }

        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
        page = (HtmlPage) page.getEnclosingWindow().getEnclosedPage();

        System.out.println("-------------------------------");
        System.out.println("- login done ------------------");
        // System.out.println(page.asXml());
        // System.out.println("-------------------------------");
        System.out.println("-------------------------------");

        return page;
    }

    private static HtmlPage navigateToConsultaProcessos(WebClient webClient, HtmlPage page) throws IOException {
        HtmlElement nav = page.getHtmlElementById("tabConsultaProcesso_lbl");
        nav.click();
        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
        page = (HtmlPage) page.getEnclosingWindow().getEnclosedPage();

        System.out.println("-------------------------------");
        System.out.println("- navigate done -----------");
        // System.out.println(page.asXml());
        // System.out.println("-------------------------------");
        System.out.println("-------------------------------");

        return page;
    }

    private static HtmlPage processConsultaProcessosFilter(WebClient webClient, HtmlPage page) throws IOException {
        HtmlInlineFrame iframeList = page.getHtmlElementById("frameConsultaProcessos");
        HtmlPage iListPage = (HtmlPage) iframeList.getEnclosedWindow().getEnclosedPage();

        HtmlForm filterForm = iListPage.getFormByName("fPP");

        HtmlTextInput nS = filterForm.getInputByName("fPP:numeroProcesso:numeroSequencial");
        HtmlTextInput nD = filterForm.getInputByName("fPP:numeroProcesso:numeroDigitoVerificador");
        HtmlTextInput ano = filterForm.getInputByName("fPP:numeroProcesso:Ano");
        HtmlTextInput lJ = filterForm.getInputByName("fPP:numeroProcesso:ramoJustica");
        HtmlTextInput lT = filterForm.getInputByName("fPP:numeroProcesso:respectivoTribunal");
        HtmlTextInput nO = filterForm.getInputByName("fPP:numeroProcesso:NumeroOrgaoJustica");

        nS.setValue("0000347");
        nD.setValue("03");
        ano.setValue("2017");
        lJ.setValue("8");
        lT.setValue("15");
        nO.setValue("0371");

        filterForm.getInputByValue("Pesquisar").click();

        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
        page = (HtmlPage) page.getEnclosingWindow().getEnclosedPage();

        System.out.println("-------------------------------");
        System.out.println("- filter done -------------");
         System.out.println(page.asXml());
         System.out.println("-------------------------------");
        System.out.println("-------------------------------");

        return page;
    }

}

**Comment by rbri** [comment]
See our private mail conversation....
