### ISSUE TITLE
RegExpJsToJavaConverter \p{L} Unicode property escapes

### ISSUE THREAD

**Issue by Jaaap** [HtmlUnit/htmlunit#583]
We have an HTML pattern that looks like this:
```
<input type="text" pattern="[\p{L}0-9 _'@&,?/]*"/>
```

Observe the `\p{L}`. This is a Unicode property escape for the `Letter` group.
The `RegExpJsToJavaConverter.convert()` method replaces this with `[p\{L\}0-9 _'@&,?/]*`.
Notice the missing backslash before the `p` and the added backslashed before the `{` and `}`.

Is it possible to fix this?
Also see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Unicode_property_escapes

**Comment by rbri** [comment]
Yes will try to fix that - hope you are already at version 3.1

**Comment by rbri** [comment]
Have done a fix for this - please check the latest 3.2.0-SNAPSHOT.

**Comment by Jaaap** [comment]
We're waiting for a spring update to allow our project to use the 3.x release of HtmlUnit.
I did take a look at your code and it looks good.
Can we perhaps add a test like:
```java
assertEquals("[^\\p{gc=Co}\\p{gc=Cn}]+", regExpJsToJavaConverter.convert("[^\\p{gc=Co}\\p{gc=Cn}]+"));
```

**Comment by rbri** [comment]
yes, passes also
can you provide some input that passes this and some that fails...
To add a test case similar like this


    @Test
    @Alerts("true")
    public void validationPatternUnicodePropertyEscapeLowercaseLetter() throws Exception {
        validation("\\p{Ll}*", "&#x043C&#x0439&#x0440");
    }

**Comment by rbri** [comment]
Ok found something....

**Comment by rbri** [comment]
Please have a look at my last commit.

**Comment by Jaaap** [comment]
The Cn group is currently empty (so untestable), according to https://www.fileformat.info/info/unicode/category/Cn/index.htm
The Co group has six characters: https://www.fileformat.info/info/unicode/category/Co/list.htm
```java
@Test
@Alerts("true")
public void validationPatternUnicodePropertyEscapeCategoryPrivateUse() throws Exception {
    validation("[\\p{gc=Co}]+", ""); //Not sure this will copy/paste right
    validation("[\\p{gc=Co}]+", "&#xF8FF;&#xf0000;");
}
```

**Comment by rbri** [comment]
Done, will close this. Thanks.
