### ISSUE TITLE
Cannot scrape this site

### ISSUE THREAD

**Issue by LRXYZ** [HtmlUnit/htmlunit#592]
Sample page from a site I am trying to scrape:
https://en.tutiempo.net/records/lemg/1-may-2023.html 

Much of the html is dynamically loaded with javascript, but that should work, right?

Inspecting the html-code in Chrome, I see it has hundreds of `<td>`-elements.
But the code below gives an empty list.

Anyone can see what the issue is?

I am using htmlunit-2.70.0.

```
import java.net.URL;

import com.gargoylesoftware.htmlunit.HttpMethod;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.WebRequest;
import com.gargoylesoftware.htmlunit.html.HtmlPage;

public class Test {

	public static void main(String[] args) throws Exception {
		String url = "https://en.tutiempo.net/records/lemg/1-may-2023.html";
		URL u = new URL(url);
		HttpMethod m = HttpMethod.GET;
		WebRequest request = new WebRequest(u, m);

		WebClient webClient = new WebClient();
		webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
		webClient.getOptions().setThrowExceptionOnScriptError(false);
		webClient.getOptions().setUseInsecureSSL(true);
		webClient.getOptions().setJavaScriptEnabled(true);
		webClient.getOptions().setRedirectEnabled(true);
		HtmlPage page = webClient.getPage(request);
		System.out.println("page: " + page.getElementsByTagName("td"));
		webClient.close();
	}
}

```

**Comment by rbri** [comment]
Hi @LRXYZ,

this page is a nightmare, even in real browsers i got a ton of warnings about nasty things append inside. This Ad stuff is ....

But: the problem you are facing is because of parts of the js try to open up the consent page and the cookie warning. And this code seems to use js features (spread operator) currently not supported by HtmlUnit (Rhino).

Luckily there is hope - simply disable the whole js and you get the plain page with all the info inside.

This code

    try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX /* , "localhost", 8888 */)) {
        webClient.getOptions().setUseInsecureSSL(true);
        webClient.getOptions().setThrowExceptionOnScriptError(false);
        webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);

        webClient.getOptions().setJavaScriptEnabled(false);

        HtmlPage page = webClient.getPage(url);

        System.out.println("-------------------------------");
        System.out.println(page.asNormalizedText());
        System.out.println("-------------------------------");
    }

produces

    ....
	Records	ICAO: LEMG
	Records ICAO/OACI: LEMG
	METAR record in weather station:
	Icao (OACI): LEMG
	Name weather station: Malaga / Aeropuerto
	Latitude: 36.66667
	Longitude: -4.48333
    ....
	Monday 1 May 2023
	Hour	Weather conditionWC	Tem.	Wind	Hum.	Pressure
	00:00	
	Clear
		18°	4 km/h	77%	1015 hPa
	00:30	
	Clear
		19°	Calm	73%	1015 hPa
	01:00	
	Clear
		17°	7 km/h	77%	1015 hPa
	01:30	
	Clear
		17°	7 km/h	77%	1015 hPa
	02:00	
	Clear
		17°	7 km/h	82%	1016 hPa
	02:30	
	Clear
		18°	7 km/h	88%	1015 hPa
	03:00	
	Partly Cloudy
		18°	9 km/h	88%	1015 hPa
	03:13	
	Mostly Cloudy
		19°	7 km/h	88%	1015 hPa
	03:30	
	Mostly Cloudy
		18°	6 km/h	94%	1015 hPa
	04:00	
	Mostly Cloudy
		18°	9 km/h	94%	1015 hPa
	04:30	
	Mostly Cloudy
		18°	4 km/h	100%	1015 hPa
	05:00	
	Mostly Cloudy
		18°	2 km/h	94%	1015 hPa
	05:30	
	Mostly Cloudy
		18°	2 km/h	88%	1015 hPa
	06:00	
	Mostly Cloudy
		17°	11 km/h	88%	1015 hPa
	06:30	
	Partly Cloudy
		17°	11 km/h	88%	1015 hPa
	07:00	
	Fair
		16°	11 km/h	94%	1015 hPa
	07:30	
	Fair
		16°	17 km/h	88%	1015 hPa
	08:00	
	Fair
		16°	19 km/h	88%	1015 hPa
	08:30	
	Fair
		16°	11 km/h	82%	1016 hPa
	09:00	
	Fair
		17°	11 km/h	77%	1016 hPa
	09:30	
	Fair
		19°	13 km/h	73%	1016 hPa
	10:00	
	Fair
		21°	9 km/h	64%	1016 hPa
	10:30	
	Fair
		20°	9 km/h	78%	1017 hPa
	11:00	
	Fair
		20°	11 km/h	78%	1017 hPa
	11:30	
	Fair
		20°	11 km/h	78%	1017 hPa
	12:00	
	Fair
		21°	11 km/h	73%	1017 hPa
	12:30	
	Fair
		20°	15 km/h	83%	1018 hPa
	13:00	
	Fair
		20°	15 km/h	83%	1018 hPa
	13:30	
	Fair
		21°	15 km/h	78%	1017 hPa
	14:00	
	Fair
		23°	15 km/h	65%	1017 hPa
	14:30	
	Fair
		23°	17 km/h	65%	1017 hPa
	15:00	
	Fair
		23°	17 km/h	65%	1017 hPa
	15:30	
	Fair
		23°	17 km/h	61%	1017 hPa
	16:00	
	Fair
		23°	17 km/h	61%	1017 hPa
	16:30	
	Fair
		23°	17 km/h	61%	1016 hPa
	17:00	
	Fair
		23°	17 km/h	65%	1016 hPa
	17:30	
	Fair
		22°	17 km/h	69%	1016 hPa
	18:00	
	Fair
		22°	15 km/h	73%	1016 hPa
	18:30	
	Fair
		22°	15 km/h	73%	1016 hPa
	19:00	
	Fair
		21°	17 km/h	73%	1015 hPa
	19:30	
	Fair
		21°	11 km/h	78%	1016 hPa
	20:00	
	Fair
		20°	9 km/h	83%	1016 hPa
	20:30	
	Fair
		20°	9 km/h	78%	1016 hPa
	21:00	
	Fair
		20°	9 km/h	78%	1016 hPa
	21:30	
	Clear
		19°	7 km/h	88%	1016 hPa
	22:00	
	Clear
		19°	4 km/h	88%	1016 hPa
	22:30	
	Clear
		18°	7 km/h	88%	1017 hPa
	23:00	
	Clear
		19°	2 km/h	88%	1017 hPa
	23:30	
	Clear
		18°	6 km/h	88%	1017 hPa
	« 30-4-2023 2-5-2023 »
    ....

Hope that helps

**Comment by LRXYZ** [comment]
Wow, impressively quick and to-the-point analysis!
And simple solution as well! ---  Didnt think of trying that :)

Thanks for your excellent support!  
<3

**Comment by rbri** [comment]
Your welcome, github starts also 😃

and if you use HtmlUnit in a commercial environment maybe its worth to think about sponsoring my work
https://github.com/sponsors/rbri
