### ISSUE TITLE
showModal of dialog element not supported

### ISSUE THREAD

**Issue by mawinter69** [HtmlUnit/htmlunit#598]
When I have a dialog element
```
<button id="showMyDialog">Show dialog</button>
<dialog id="mydialog">
  Hello World<br/>
  <button id="dismiss">Dismiss</button>
</dialog>
```
And I want to show this dialog in javascript with
```
showButton = document.getElementById("showMyDialog");
showButton.addEventListener("click", showMyDialog);

dismissButton = document.getElementById("dismiss");
dismissButton.addEventListener("click", closeMyDialog);


function showMyDialog() {
  mydialog = document.getElementById("mydialog");
  mydialog.showModal();
}

function closeMyDialog() {
  mydialog = document.getElementById("mydialog");
  mydialog.close();
}
```
I'm not able to test this with htmlunit as showModal is not supported

**Comment by rbri** [comment]
@mawinter69 
right now dialog tags are not really supported in HtmlUnit.

Might be some work because i have to support
* close()
* open
* returnValue
* show()
* showModal()

This might require some time - i'm currently working on some Rhino enhancements.
How important/urgent is this for you?

**Comment by mawinter69** [comment]
It's not so urgent. I can probably also do that without dialogs, though with dialogs it is much easier.

**Comment by rbri** [comment]
i guess it is related to https://github.com/jenkinsci/jenkins/pull/7938 ?

Will fix the current work and come back to you during the next week (hopefully)

**Comment by mawinter69** [comment]
yes it is. That would be awesome

**Comment by rbri** [comment]
done, a new release will be available tomorrow
