### ISSUE TITLE
Browser is not supported error with the newest version of HtmlUnit

### ISSUE THREAD

**Issue by grujicaleksandar90** [HtmlUnit/htmlunit#599]
Hello, I'm using the HtmlUnit (v.2.70.0) to get some data from the following page: https://me.sap.com/. 

When the driver goes to that URL, it first faces the login screen (which is expected), and after typing username and password and clicking on the submit button, I have noticed that the new page is not the expected one. After some investigation, I found out that I'm getting some page with the error message:

`Sadly, your browser is not supported. SAP for Me works best on: Google Chrome 45+, Mozilla Firefox 45+, Apple Safari 10+, and Microsoft Edge 13+ Other legacy browsers (like Microsoft Internet Explorer 11) are no longer supported. For more information, see here. Privacy Legal Disclosure Copyright and Trademarks Terms of Use`

It should get me to the expected page, where I need to scrap some data from the network tab.

If you need any more details, I will gladly post. 

Thanks

**Comment by rbri** [comment]
Ok, the web page does a lot of fancy things but in the end there is some js based redirecting. You have to address this in your code.

            HtmlPage page = webClient.getPage(url);
            webClient.waitForBackgroundJavaScript(10_000);

            page = (HtmlPage)page.getEnclosingWindow().getEnclosedPage();
            System.out.println(page.asXml());

This means you have to wait until the js stuff is done and then (re) get the content of the window - this is the current page you like to work with.

So far for this first step - i fear you have to do something similar after the click() also.

**Comment by grujicaleksandar90** [comment]
> 

Hmm, I've put that at the end, since that is the spot where I'm facing the issue. Here is the complete snippet:

`try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX)) {
        webClient.getOptions().setThrowExceptionOnScriptError(false);

        HtmlPage page = webClient.getPage("https://me.sap.com/systems");

        HtmlForm loginForm = (HtmlForm) page.getElementById("logOnForm");

        loginForm.getInputByName("j_username").type("my_username");

        HtmlElement userNameSubmit = (HtmlElement) page.getElementById("logOnFormSubmit");
        page = (HtmlPage) userNameSubmit.click();

        HtmlForm passForm = (HtmlForm) page.getElementById("logOnForm");

        passForm.getInputByName("j_password").type("password123");

        HtmlElement passwordSubmit = (HtmlElement) page.getElementById("logOnFormSubmit");
        
        page = (HtmlPage) passwordSubmit.click();

        webClient.waitForBackgroundJavaScript(10_000);

        HtmlPage newestPage = (HtmlPage)page.getEnclosingWindow().getEnclosedPage();

       System.out.println(newestPage.asXml());

  }  catch (Exception e){
        System.out.println("ERROR " + e);
  }`

But I'm still getting the same. Did I maybe do something wrong?

**Comment by rbri** [comment]
> But I'm still getting the same. Did I maybe do something wrong?

Yes.
You have to place the code directly after the getPage() line.

**Comment by rbri** [comment]
@grujicaleksandar90 does it help? can i close this or do you need more?

**Comment by grujicaleksandar90** [comment]
Hi, that didn't help, so I switched the project to Java and Selenium at the end, and was able to do what I needed.
You can close this one and thanks for your help.

**Comment by rbri** [comment]
Ok, thanks
