### ISSUE TITLE
Broken Link on the Website to XPath Tutorial

### ISSUE THREAD

**Issue by Treppenhouse** [HtmlUnit/htmlunit#6]
The hyperlink to the XPath tutorial on W3Schools that is presented on http://htmlunit.sourceforge.net/gettingStarted.html in the Section "XPath queries" is a dead link.

I think it was moved to: https://www.w3schools.com/xml/xpath_intro.asp

**Comment by rbri** [comment]
Thanks for the info, will be available with the next release.
