### ISSUE TITLE
Javascript strict mode enforced incorrectly

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#60]
The html page below fails in HtmlUnit but is fine with real browser. 
```
<html>
    <head>
        <title>TODO supply a title</title>
        <script>
            (function() {
                "use strict"; 
                new Function("with(this){alert('OK')}")();
            })();
        </script>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>
```
The error is "com.gargoylesoftware.htmlunit.ScriptException: SyntaxError: with statements not allowed in strict mode". The problem is that the strict mode is enforced in the code snip in Function body while it should not.
This is actually a rhino bug according to this: https://github.com/mozilla/rhino/issues/403
Not sure if it can be fixed in HtmlUnit.

**Comment by rbri** [comment]
Strict mode is one of the major pain points with Rhino - any help is welcome. If you look at the rhino commits you will notice that HtmlUnit is responsible for most of the changes during the last year. Hopefully there will be more progress in the future.

**Comment by rbri** [comment]
This is now fixed as part of the latest core-js snapshot. A new release is planned for this weekend.

**Comment by RuralHunter** [comment]
Nice!
