### ISSUE TITLE
[Regression] `HtmlForm#getInputByValue` and `HtmlForm#getInputsByValue` no longer work in 3.x.x

### ISSUE THREAD

**Issue by basil** [HtmlUnit/htmlunit#602]
The [Migrating from HtmlUnit 2.x.x to HtmlUnit 3.x.x](https://www.htmlunit.org/migration.html) documentation states:

> Replace all usages of `org.htmlunit.html.HtmlInput.getValueAttribute()` by `org.htmlunit.html.HtmlInput.getValue()`. Replace all usages of `org.htmlunit.html.HtmlInput.setValueAttribute(String)` by `org.htmlunit.html.HtmlInput.setValue(String)`.

The problem is that once you do this, `org.htmlunit.html.HtmlForm#getInputByValue` and `org.htmlunit.html.HtmlForm#getInputsByValue` stop working, since they internally use `org.htmlunit.html.DomElement#getAttributeDirect("value")` rather than `org.htmlunit.html.HtmlInput#getValue`. Observed after debugging the test failures in https://github.com/jenkinsci/jenkins/pull/8050.

Workaround:

```java
/**
 * Returns the first input in this form with the specified value.
 * @param value the value to search for
 * @return the first input in this form with the specified value
 * @throws ElementNotFoundException if this form does not contain any inputs with the specified value
 */
private static HtmlInput getInputByValue(final HtmlForm f, final String value) throws ElementNotFoundException {
    // TODO org.htmlunit.html.HtmlForm#getInputByValue is busted
    return f.getInputsByValue("").stream()
            .filter(HtmlInput.class::isInstance)
            .map(HtmlInput.class::cast)
            .filter(input -> input.getValue().equals(value))
            .findFirst()
            .orElseThrow(() -> new ElementNotFoundException("input", "value", value));
}

/**
 * Returns all the inputs in this form with the specified value.
 * @param value the value to search for
 * @return all the inputs in this form with the specified value
 */
private static List<HtmlInput> getInputsByValue(final HtmlForm f, final String value) {
    // TODO org.htmlunit.html.HtmlForm#getInputsByValue is busted
    return f.getInputsByValue("").stream()
            .filter(HtmlInput.class::isInstance)
            .map(HtmlInput.class::cast)
            .filter(input -> input.getValue().equals(value))
            .collect(Collectors.toList());
}
```

CC @rbri

**Comment by rbri** [comment]
@basil sorry for that, will try to fix it today and build a new release over the weekend

**Comment by rbri** [comment]
@basil do you like to have a snapshot build for testing?

**Comment by basil** [comment]
No need, I checked commit 62d61d65ea5916e3c846855757bacbb9419e02df and it works fine.

**Comment by rbri** [comment]
@basil great thanks

**Comment by rbri** [comment]
@basil 3.3.0 is available - hope this was the last regression :-)

**Comment by basil** [comment]
Thank you very much!
