### ISSUE TITLE
Suggestion - allow overriding temporary file location

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#605]
The default temporary folder location for all web responses that are larger than 500kb can be overridden via the system parameter "java.io.tmpdir".

If we need to only change the default for Htmlunit while keeping the temp folder unchanged, we can't do it.

A solution would be to add another webclient set option that would override this, and then use that value in the create temp file call below as an additional argument.

https://github.com/HtmlUnit/htmlunit/blob/dfb0d9c82d6e9e822cac607513d4bfb60b90fbcf/src/main/java/org/htmlunit/HttpWebConnection.java#L780

Would help a lot if you need to customize the folder. Would help with detecting and leftover files a well, as its easier to notice if you redirect the temp files to a folder dedicated to it.

**Comment by rbri** [comment]
good point will add this....

**Comment by skyhirider** [comment]
Bad copy pasted javadoc description?

https://github.com/HtmlUnit/htmlunit/blob/84f57392a35c23892139244b1dc58c1ca142a032/src/main/java/org/htmlunit/WebClientOptions.java#L117-L124

**Comment by rbri** [comment]
@skyhirider :-) working in the train is not always the best place to do this kind of things - hope this is fixed.
Feel free to have a look again and do some suggestion

**Comment by skyhirider** [comment]
@rbri Not sure I could work on the train, would be too afraid I would get consumed by work and miss my stop :D

Was just curious how you implemented the change and noticed this minor thing. 

I think the change looks good and makes sense. Thanks for implementing it!
