### ISSUE TITLE
No mention of the package rename for com.gargoylesoftware.htmlunit

### ISSUE THREAD

**Issue by MenschNestor** [HtmlUnit/htmlunit#608]
There does not seem to be any mention of the apparent rename of the `com.gargoylesoftware.htmlunit` package to `org.htmlunit` in either the release notes or the migration guide. In addition, the documentation still has references to that package, e.g. https://www.htmlunit.org/gettingStarted.html:

> The class com.gargoylesoftware.htmlunit.WebClient is the main starting point.

This is a bit confusing.

**Comment by rbri** [comment]
Good point will fix that after my vacation

**Comment by rbri** [comment]
Looks like i forgot this on many more places. Many thanks for pointing this out.

**Comment by rbri** [comment]
Have updated the migration page, all the other fixes are part of the next release.
