### ISSUE TITLE
Remove the Proxy javascript host class

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#61]
Rhiho has not implemented Proxy yet and Htmlunit has a Proxy stub. This affects some js functions which checks the availability of Proxy and behaves accordingly, such as the VUE js framework. It thinks Proxy is available and tries to use it then it fails.

**Comment by rbri** [comment]
Good (and valid) point. We still have some of this stubs around but i try to slowly fill the gaps. Hopefully there will be some time to add Proxy support to Rhino.
For now i have removed the class.
