### ISSUE TITLE
Frame content can't be loaded through js

### ISSUE THREAD

**Issue by lishuaidb** [HtmlUnit/htmlunit#612]
when the frame is not loaded by the src, by using the jquery like this
`<iframe></iframe> document.querySelector('iframe')[0] .contentDocument.write("<h1>Injected from parent frame</h1>")`

Here is my code. 

    String webUrl = "xxxx";

    try (final WebClient webClient = new WebClient(BrowserVersion.CHROME)) {
        webClient.getOptions().setCssEnabled(true);
        webClient.getOptions().setJavaScriptEnabled(true);

        final HtmlPage page = webClient.getPage(webUrl);
        webClient.waitForBackgroundJavaScript(5_000);

        System.out.println(" ---- main page start ---- ");
        System.out.println(page.asXml());
        System.out.println(" ---- main page end ---- ");
        System.out.println();

        for (FrameWindow frameWindow : page.getFrames()) {
            final HtmlPage framePage = (HtmlPage) frameWindow.getEnclosedPage();
            System.out.println(" ---- frame page start ---- ");
            System.out.println(framePage.asXml());
            System.out.println(" ---- frame page end ---- ");
        }
    }

the enclosedPage from this frameWindow is null, i wonder if there is some problem with loading content from jquery dom wirte.

**Comment by rbri** [comment]
will have a look

**Comment by rbri** [comment]
just made a unit test - but this works fine.
Can you please check if the js code is really triggered in your case.

    /**
     * @throws Exception if the test fails
     */
    @Test
    @Alerts("Injected from parent frame")
    public void writeIntoIFrameContentDocument() throws Exception {
        final String html
            = "<!DOCTYPE html>\n"
            + "<html>\n"
            + "<head>\n"
            + "  <script>\n"
            + "    function doIt() {\n"
            + "      var html = '<h1>Injected from parent frame</h1>';\n"
            + "      document.getElementById(\"tester\").contentDocument.write(html);\n"
            + "    }\n"
            + "  </script>\n"
            + "</head>\n"
            + "<body>\n"
            + "  <iframe id='tester'></iframe>\n"
            + "  <input id='myButton' type=button onclick=\"javascript:doIt()\" value='Write'>\n"
            + "</body>\n"
            + "</html>";

        getMockWebConnection().setDefaultResponse(html);
        final WebDriver driver = loadPage2(html);

        driver.findElement(By.id("myButton")).click();

        driver.switchTo().frame("tester");
        verify(() -> driver.findElement(By.tagName("body")).getText(), getExpectedAlerts()[0]);

        if (driver instanceof HtmlUnitDriver) {
            final WebClient webClient = ((HtmlUnitDriver) driver).getWebClient();

            final HtmlPage page = (HtmlPage) webClient.getCurrentWindow().getEnclosedPage();

            assertEquals(1, page.getFrames().size());

            final HtmlPage framePage = (HtmlPage) page.getFrames().get(0).getEnclosedPage();
            assertEquals("Injected from parent frame", framePage.getBody().asNormalizedText());
        }
    }

**Comment by lishuaidb** [comment]
Thank you for repling.
it's my fault, i just run the code in debug mode, so all the threads stop working at the breakpoint and the frame stops at the init state. sorry to trouble you

**Comment by rbri** [comment]
@lishuaidb great and thanks for the fast answer. Will add the testcase to the testsuite.

Have fun (and success) with HtmlUnit.
