### ISSUE TITLE
Cache: support "Cache-Control" http header

### ISSUE THREAD

**Issue by cdalexndr** [HtmlUnit/htmlunit#62]
Current impl only uses "Last-Modified" and "Expires" header values do teremine if a WebResponse is cacheable (Cache.java):
```
    protected boolean isCacheableContent(final WebResponse response) {
        if (HeaderUtils.containsNoStore(response)) {
            return false;
        }

        final Date lastModified = parseDateHeader(response, HttpHeader.LAST_MODIFIED);
        final Date expires = parseDateHeader(response, HttpHeader.EXPIRES);

        final long now = getCurrentTimestamp();

        return expires != null && (expires.getTime() - now > DELAY)
                || (expires == null && lastModified != null && now - lastModified.getTime() > DELAY);
    }
```

In case of a web response with `Expires` before current time, but also `Cache-Control=max-age=3600`, then current impl will incorrectly skip caching. According to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires): 

> If there is a Cache-Control header with the max-age or s-maxage directive in the response, the Expires header is ignored.

Also, for long running servers, is there a mechanism to clear old cached entries based on their expiry date, in the above example, the response should be removed from cache after one hour (3600s), or at least considered invalid when trying to get from cache.

**Comment by rbri** [comment]
Have hopefully done all this with the last commits. Will make a new snapshot build available later on. Please have a look.
