### ISSUE TITLE
Htmlunit in Jenkins pipeline behaviour different ?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#621]
Did you experience htmlunit (driver + selenium) behaving differently when running maven tests inside a Jenkins docker container ?

I'm wondering if there are any previously documented cases of this happening.

Cant share the code or site, but tests pass perfectly fine locally yet fail reliably on Jenkins agent. 

Thought it was the amount of resources available, but no change after increasing.

It's a JavaScript heavy site so would suspect that, but it's odd that other tests work fine.

If you or anyone else has ideas let me know, if not I will close this.

**Comment by rbri** [comment]
sorry @skyhirider - no idea and no experiences with a similar setup

**Comment by mguillem** [comment]
@skyhirider what kind of failures do you have on the agent? If don't think that the JVM version matters but perhaps the keystore if you use self signed certificates. Or a network configuration?

**Comment by rbri** [comment]
no feedback for a long time - will close this
