### ISSUE TITLE
AJAX Generated table list of files to download

### ISSUE THREAD

**Issue by alexvrv** [HtmlUnit/htmlunit#624]
I have a problem with a weird website, sadly it's not public but I could get some code out of it if it helps. On the website is a table with a list of Excel files that I need to download. The problem is that every link is a `"<a href='javascript:;'/>`. The bigger problem is that the button doesn't download the files, it first redirect to another page where the download button is. xD From here I need to return and press the button from the 2nd row in the table for the 2nd Excel file. The problem is when I return I get "class org.htmlunit.UnexpectedPage cannot be cast to class org.htmlunit.html.HtmlPage",

            HtmlPage htmlpage = webClient.getPage(url);

            htmlpage.getElementsByTagName("a").forEach(el -> {
                String text = new String(el.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();

                if (text.contains(new String("Listă angajamente".getBytes(StandardCharsets.UTF_8)))) {
                    try {
                        el.click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        HtmlPage page2 = (HtmlPage) htmlpage.getEnclosingWindow().getEnclosedPage();
                        HtmlForm form = page2.getForms().get(0);

                        form.getInputByName("dataStart").setValue("01.01.2023");
                        form.getButtonByName("").click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        page2 = (HtmlPage) page2.getEnclosingWindow().getEnclosedPage();

                        //System.out.println(page3.asXml());
                        DomNodeList<DomElement> list = page2.getElementsByTagName("a");

                        list.forEach(el2 -> {
                            String text2 = new String(el2.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                            if (text2.contains(new String("Informații complete".getBytes(StandardCharsets.UTF_8)))) {
                                try {
                                    HtmlPage page4 = el2.click(false, false, false, true, true, true, false);
                                    webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                    HtmlPage page5 = (HtmlPage) page4.getEnclosingWindow().getEnclosedPage();

                                    page5.getElementsByTagName("a").forEach(el3 -> {
                                        String text3 = new String(el3.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                        if (text3.contains("Export Excel")) {
                                            try {
                                                WebResponse resp = el3.click().getWebResponse();

                                                try (InputStream in = resp.getContentAsStream()) {
                                                    try (FileOutputStream out = new FileOutputStream("D:/Test/test.xls")) {
                                                        byte[] buffer = new byte[8 * 1024];
                                                        int bytesRead;
                                                        while ((bytesRead = in.read(buffer)) != -1) {
                                                            out.write(buffer, 0, bytesRead);
                                                        }
                                                    }
                                                }

                                                //page4.getElementsByTagName("button").forEach(el4 -> {
                                                    //String text4 = new String(el2.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                                    //if (text4.contains(new String("Înapoi".getBytes(StandardCharsets.UTF_8)))) {
                                                        //try {
                                                            //el4.click();
                                                            //webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                                        //} catch (IOException e) {
                                                           //throw new RuntimeException(e);
                                                        //}
                                                    //}
                                                //});
                                            } catch (IOException e) {
                                                throw new RuntimeException(e);
                                            }
                                        }
                                    });
                                } catch (IOException e) {
                                    throw new RuntimeException(e);
                                }
                            }
                        });
                    } catch (IOException e) {
                        e.printStackTrace();
                        throw new RuntimeException(e);
                    }
                }
            });
            webClient.close();

The table from the website looks like this (I need to press on "Informatii complete"): 
![image](https://github.com/HtmlUnit/htmlunit/assets/83940062/0969a062-ff15-4a44-8aaa-4d7324bd6867)

And this is the code behind that `<a>` (`<a href="javascript:;" id="id3a">Informații complete</a>`) xD

**Comment by rbri** [comment]
will have a look in the evening

**Comment by rbri** [comment]
download is a bit tricky - have you already had a look at https://www.htmlunit.org/filedownload-howto.html?

**Comment by alexvrv** [comment]
Yeah, download works for the first Excel.

**Comment by rbri** [comment]
then the rest is handling the different windows .... :-)

**Comment by alexvrv** [comment]
Yeah but it seems that the page doesn't change. It keeps downloading only the first Excel... :'(

**Comment by alexvrv** [comment]
I've tried something else and still I get only the first Excel... I'm lost 

            final List<WebResponse> attachments = new ArrayList<>();
            webClient.setAttachmentHandler(new AttachmentHandler() {
                @Override
                public boolean handleAttachment(final WebResponse response) {
                    attachments.add(response);
                    return true;
                }

                @Override
                public void handleAttachment(final Page page) {
                    throw new IllegalAccessError("handleAttachment(Page) called");
                }
            });

            HtmlPage htmlpage = webClient.getPage(url);

            htmlpage.getElementsByTagName("a").forEach(el -> {
                String text = new String(el.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();

                if (text.contains(new String("Listă angajamente".getBytes(StandardCharsets.UTF_8)))) {
                    try {
                        el.click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        HtmlPage page2 = (HtmlPage) htmlpage.getEnclosingWindow().getEnclosedPage();
                        HtmlForm form = page2.getForms().get(0);

                        form.getInputByName("dataStart").setValue("01.01.2023");
                        form.getButtonByName("").click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        HtmlPage page3 = (HtmlPage) page2.getEnclosingWindow().getEnclosedPage();

                        DomNodeList<DomElement> list = page3.getElementsByTagName("a");
                        ArrayList<WebWindow> windows = new ArrayList<>();

                        list.forEach(el2 -> {
                            String text2 = new String(el2.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                            if (text2.contains(new String("Informații complete".getBytes(StandardCharsets.UTF_8)))) {
                                try {
                                    windows.add(el2.click(false, false, false, true, true, true, false).getEnclosingWindow());
                                } catch (IOException e) {
                                    throw new RuntimeException(e);
                                }
                            }
                        });

                        windows.forEach(window -> {
                            HtmlPage page = (HtmlPage) window.getEnclosedPage();
                            webClient.waitForBackgroundJavaScriptStartingBefore(10_000);

                            page.getElementsByTagName("a").forEach(el3 -> {
                                String text3 = new String(el3.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                if (text3.contains("Export Excel")) {
                                    try {
                                        el3.click();
                                    } catch (IOException e) {
                                        throw new RuntimeException(e);
                                    }
                                }
                            });
                        });
                    } catch (IOException e) {
                        e.printStackTrace();
                        throw new RuntimeException(e);
                    }
                }
            });
            webClient.close();

            final int[] i = {1};
            attachments.forEach(a -> {
                try (FileOutputStream out = new FileOutputStream("D:/Test/test" + i[0] + ".xls")) {
                    InputStream in = a.getContentAsStream();
                    byte[] buffer = new byte[8 * 1024];
                    int bytesRead;
                    while ((bytesRead = in.read(buffer)) != -1) {
                        out.write(buffer, 0, bytesRead);
                    }
                    in.close();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                i[0] = (i[0] + 1);
            });

**Comment by rbri** [comment]
Hard to say what is going on .... usually using a proxy like Charles or Fiddler to understand the inner workings o the page is a good option.

**Comment by rbri** [comment]
have you places some out statements in you code to understand what is going on?

**Comment by alexvrv** [comment]
On Charles/Fiddle i don't see any requests xD and I don't really understand your second question...

**Comment by rbri** [comment]
you have to start your web client with proxy settings to see something

**Comment by rbri** [comment]
is having a online session to have a look together on this, an option for you?

**Comment by alexvrv** [comment]
Sadly no, I'm not at home ... and what host and port should I set on PROXY? localhost?

**Comment by rbri** [comment]
yes localhost and some port (for charles this 8888 if my memories are correct)
both tools are setting the proxy automatically for the browser - so you can have a look at your browser settings to find the port

**Comment by alexvrv** [comment]
>https://forexe.mfinante.gov.ro:443: Malformed reply from SOCKS server
Aug 17, 2023 2:34:25 PM org.apache.http.impl.execchain.RetryExec execute

**Comment by rbri** [comment]
OK, next try, forget the proxy for the moment and use a WebconnectionWrapper for logging, simply log and pass the parameter back

https://www.htmlunit.org/faq.html#HowToModifyRequestOrResponse

**Comment by alexvrv** [comment]
From what I see in the logs the page is accessed only once xD but why?....

**Comment by rbri** [comment]
please let us switch to email (you can find my mail in the pom)

**Comment by alexvrv** [comment]
Finally got it to work using ArrayList<HtmlPage>. Maybe this helps someone in the future.

            final WebClient webClient = new WebClient(BrowserVersion.CHROME);

            Certificate cert = ks.getCertificate(alias);

            InputStream is = new ByteArrayInputStream(cert.getEncoded());

            webClient.getOptions().setSSLClientCertificate(is, "", "Windows-MY");
            webClient.getCookieManager().setCookiesEnabled(true);
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            final List<WebResponse> attachments = new ArrayList<>();
            ArrayList<HtmlPage> pages = new ArrayList<>();

            webClient.setAttachmentHandler(new AttachmentHandler() {
                @Override
                public boolean handleAttachment(final WebResponse response) {
                    attachments.add(response);
                    return true;
                }

                @Override
                public void handleAttachment(final Page page) {
                    throw new IllegalAccessError("handleAttachment(Page) called");
                }
            });

            HtmlPage htmlpage = webClient.getPage(url);

            htmlpage.getElementsByTagName("a").forEach(el -> {
                String text = new String(el.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();

                if (text.contains(new String("Listă angajamente".getBytes(StandardCharsets.UTF_8)))) {
                    try {
                        el.click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        HtmlPage page2 = (HtmlPage) htmlpage.getEnclosingWindow().getEnclosedPage();
                        HtmlForm form = page2.getForms().get(0);

                        form.getInputByName("dataStart").setValue("01.01.2023");
                        form.getButtonByName("").click();
                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                        HtmlPage page3 = (HtmlPage) page2.getEnclosingWindow().getEnclosedPage();

                        int i = 0, j = 0;

                        HtmlTable table = (HtmlTable) page3.getElementsByTagName("table").get(2);
                        HtmlTableBody body = table.getBodies().get(0);

                        for (HtmlTableRow row : body.getRows()) {
                            if (i == 0) {
                                DomElement down = row.getCell(8).getLastElementChild().getFirstElementChild().getFirstElementChild().getNextElementSibling().getFirstElementChild();

                                down.click(false, false, false, true, true, true, false);
                                webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                pages.add((HtmlPage) page3.getEnclosingWindow().getEnclosedPage());

                                int finalI = i;
                                int finalI1 = i;
                                pages.get(i).getElementsByTagName("a").forEach(el3 -> {
                                    String text3 = new String(el3.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                    if (text3.contains("Export Excel") && !pages.get(finalI).getUrl().toString().contains("contracte")) {
                                        try {
                                            el3.click();

                                            pages.get(finalI).getElementsByTagName("button").forEach(el4 -> {
                                                String text4 = new String(el4.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                                if (text4.contains(new String("Înapoi".getBytes(StandardCharsets.UTF_8)))) {
                                                    try {
                                                        el4.click();
                                                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                                        pages.add((HtmlPage) pages.get(finalI1).getEnclosingWindow().getEnclosedPage());
                                                    } catch (IOException e) {
                                                        throw new RuntimeException(e);
                                                    }
                                                }
                                            });
                                        } catch (IOException e) {
                                            throw new RuntimeException(e);
                                        }
                                    }
                                });

                                i = i + 1;
                                j = j + 1;
                            } else {
                                HtmlForm form1 = pages.get(i).getForms().get(0);

                                form1.getInputByName("dataStart").setValue("01.01.2023");
                                form1.getButtonByName("").click();
                                webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                pages.add((HtmlPage) pages.get(i).getEnclosingWindow().getEnclosedPage());
                                i = i + 1;

                                HtmlTable table1 = (HtmlTable) pages.get(i).getElementsByTagName("table").get(2);
                                HtmlTableBody body1 = table1.getBodies().get(0);
                                HtmlTableRow row1 = body1.getRows().get(j);

                                DomElement down = row1.getCell(8).getLastElementChild().getFirstElementChild().getFirstElementChild().getNextElementSibling().getFirstElementChild();

                                down.click(false, false, false, true, true, true, false);
                                webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                pages.add((HtmlPage) pages.get(i).getEnclosingWindow().getEnclosedPage());
                                i = i + 1;

                                int finalI = i;
                                int finalI1 = i;
                                pages.get(i).getElementsByTagName("a").forEach(el3 -> {
                                    String text3 = new String(el3.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                    if (text3.contains("Export Excel") && !pages.get(finalI).getUrl().toString().contains("contracte")) {
                                        try {
                                            el3.click();

                                            pages.get(finalI).getElementsByTagName("button").forEach(el4 -> {
                                                String text4 = new String(el4.getTextContent().getBytes(StandardCharsets.UTF_8)).trim();
                                                if (text4.contains(new String("Înapoi".getBytes(StandardCharsets.UTF_8)))) {
                                                    try {
                                                        el4.click();
                                                        webClient.waitForBackgroundJavaScriptStartingBefore(10_000);
                                                        pages.add((HtmlPage) pages.get(finalI1).getEnclosingWindow().getEnclosedPage());
                                                    } catch (IOException e) {
                                                        throw new RuntimeException(e);
                                                    }
                                                }
                                            });
                                        } catch (IOException e) {
                                            throw new RuntimeException(e);
                                        }
                                    }
                                });

                                i = i + 1;
                                j = j + 1;
                            }
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                        throw new RuntimeException(e);
                    }
                }
            });
            webClient.close();

            final int[] i = {1};
            attachments.forEach(a -> {
                try (FileOutputStream out = new FileOutputStream("D:/Test/test" + i[0] + ".xls")) {
                    InputStream in = a.getContentAsStream();
                    byte[] buffer = new byte[8 * 1024];
                    int bytesRead;
                    while ((bytesRead = in.read(buffer)) != -1) {
                        out.write(buffer, 0, bytesRead);
                    }
                    in.close();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                i[0] = (i[0] + 1);
            });
