### ISSUE TITLE
Warnings: IncorrectnessListenerImpl and DefaultCssErrorHandler

### ISSUE THREAD

**Issue by alexvrv** [HtmlUnit/htmlunit#626]
Everything works fine but I'm curious if I can somehow hide these warnings that I get.

    WARNING: Expected content type of 'application/javascript' or 'application/ecmascript' for remotely loaded JavaScript element at 'https://forexe.mfinante.gov.ro/CABWeb/wicket/resource/org.apache.wicket.extensions.yui.YuiLib/yuiloader/yuiloader-min-ver-46DDAFD8F3A8FB80745533D246937157.js', but got 'text/plain'.
    Aug 21, 2023 3:25:21 PM org.htmlunit.IncorrectnessListenerImpl notify

and

    WARNING: CSS error: 'https://forexe.mfinante.gov.ro/CABWeb/wicket/resource/org.apache.wicket.extensions.yui.YuiLib/calendar/assets/skins/sam/calendar.css' [7:1158] Error in declaration. '*' is not allowed as first char of a property.
    Aug 21, 2023 2:39:30 PM org.htmlunit.DefaultCssErrorHandler error

**Comment by rbri** [comment]
You are not the first one asking this :-D

https://www.htmlunit.org/faq.html#SilentCssErrorHandler

(and thanks for the star)

**Comment by alexvrv** [comment]
The second error (DefaultCssErrorHandler) got suppressed but the first one is still here (12 warnings for one page...)

I've tried this also: webClient.setJavaScriptErrorListener(new SilentJavaScriptErrorListener()); but I still see the warns

**Comment by rbri** [comment]
you have to set the IncorrectnessListener instead.
There is not SilentIncorrectnessListener available at the moment, but you can write your own in two lines of code id guess ;-)

**Comment by alexvrv** [comment]
webClient.setIncorrectnessListener((message, origin) -> {}); - did the trick, thank you :D
