### ISSUE TITLE
Possible memory leak or I do something wrong

### ISSUE THREAD

**Issue by alexvrv** [HtmlUnit/htmlunit#627]
After finishing the job on the page, I do webClient.close(); but in TaskManager I still see a java.exe with 200MB of RAM used... (that java.exe is created only when i do (final WebClient webClient = new WebClient(BrowserVersion.CHROME);). Is it a memory leak or I'm doing something wrong?

**Comment by rbri** [comment]
close should close the whole thing - but sometimes the interaction with the js thread might lead to such effects.
If you like you can debug into the close method and give me a hint why in your case the monster does not go away. Will try to improve the code then.

**Comment by rbri** [comment]
have deployed a new snapshot build - please try (and make sure gradle really uses the new version)
htmlunit-3.6.0-20230821.140108-2

**Comment by rbri** [comment]
any difference with the new snapshot?

**Comment by alexvrv** [comment]
How can I check if gradle took the latest SNAPSHOT? I've tried implementation("org.htmlunit:htmlunit:3.6.0-SNAPSHOT:htmlunit-3.6.0-20230821.165051-3") but it can't find the jar xD 
I left it like this:  implementation("org.htmlunit:htmlunit:3.6.0-SNAPSHOT") but I'm not sure if it takes the latest version.

**Comment by rbri** [comment]
org.htmlunit:htmlunit:3.6.0-SNAPSHOT is correct

I'm not so familiar with gradle -but in maven you have an option to force reloading of snapshot builds
and you can have a look inside the .m2 directory to see which version is really in use

**Comment by maimArt** [comment]
I struggled a lot with the memory leak caused by orphaned threads of the javascript engine.
I focused on fixing the problem for my context, so i did not dive too deep in the root cause inside htmlunit, but it must have to do with the fact that WebClient#close() closes all windows before stoping the scriptEngine. I think it gets stucked during closing the windows.

As a workaround for me the memory leak was simply fixed by closing the javascript engine before closing the webclient itself:

```
webClient.getJavaScriptEngine().shutdown();
webClient.close();
```

**Comment by rbri** [comment]
@maimArt can you please try the latest 3.6.0-SNAPSHOT snapshot - i tried to fix this (at least to improve the situation).

**Comment by maimArt** [comment]
Hey @rbri ,
thanks for your effort.
I am testing with the snapshot and will give you feedback later.

**Comment by maimArt** [comment]
Sorry, but seems like 2.6.0-SNAPSHOT does not fix this issue.

I looked a bit deeper in the code:

During instantiation of a WebClient many stuff is built and referenced by passing the instance of the webclient in other custructors which hold references to the webclient.
This could be an issue because so e.g. WebClient is holding reference to HttpWebConnection, JavaScriptEngine, CurrentWindowTracker, ... where all these instances again hold reference to the WebClient.
Could be problematic for the garbage collector to release these cyclic references.

**Comment by niloc132** [comment]
I wonder about your testing methodology here, if we can improve on it a big - Java does not always (or even often?) release memory back to the OS when it collects objects, but instead keeps that region of free memory available for when it might need it later. Can you try taking a heap dump with something like VisualVM, and use its tooling to find what GC roots actually hold transitive references to the parts of HtmlUnit that are actually being leaked?

Note also that Java does not use reference counting, so is not confused by cyclical references, something which should be easy to test and confirm.

**Comment by maimArt** [comment]
That´s exactly what i did, spent hours of monitoring the JVM with VisualVM. 
Where tons of byte-arrays that are hold by the JavaScript staff of HTMLUnit

**Comment by niloc132** [comment]
Can you share the connection from the htmlunit object to the gc root, so as to confirm what exactly is holding the object?

**Comment by maimArt** [comment]
I ll try to find some time for this in the next days

**Comment by rbri** [comment]
Have identified (and fixed) some issues already - but there is one more i have to work on.
Hope to get something out of the door for testing tomorrow evening.

@maimArt maybe you can wait for that before spending too much time on that

**Comment by maimArt** [comment]
Great, thanks again.

**Comment by rbri** [comment]
@maimArt @alexvrv just made a new snapshot build - please try (and if you like you can also have a look at the last commits)

**Comment by maimArt** [comment]
Tested with the snapshot now. 
The closing seems to work better now. Memory is released after closing the WebClient 👍

**Comment by rbri** [comment]
@maimArt thanks for the feedback. The change will be part of the next release. But this implies that a client is no longer usable after the close - i think this is fine but i have like implement some check / exceptions for users reusing a client.

**Comment by maimArt** [comment]
@rbri 
Thank you for fixing this issue and all your time you invest in this project.
So i will keep using the snapshot until a new stable version is released

**Comment by rbri** [comment]
@maimArt thanks for the support ❤️

**Comment by rbri** [comment]
@maimArt @alexvrv
OMG - i found a really really stupid bug that might be the reason for (at least parts) of the memory consumption.

  https://github.com/HtmlUnit/htmlunit/commit/7c19e26db8563917f6bf020ae3af5f04d193394d

Please, please try with the current 3.7.0-SNAPSHOT!

**Comment by rbri** [comment]
And because the 3.6.0 release is done i will close this for now.

Please open a new one if you still facing memory leaks.

**Comment by Jin9628** [comment]
I encountered a similar problem, I used version 2.70.0 and found "com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory$TimeoutContext

net.sourceforge.htmlunit.corejs.javascript.Interpreter$CallFrame

net.sourceforge.htmlunit.corejs.javascript.ConsString” takes up almost 5G of memory. Can I solve this problem by upgrading the version?

**Comment by rbri** [comment]
@Jin9628 i think there is a good chance to see some improvement when switching to the latest version.

And hopefully the switch is not that hard - see https://www.htmlunit.org/migration.html for the things to be done.
And please open a new issue if you still facing memory problem.
