### ISSUE TITLE
Some links are never added to the DOM

### ISSUE THREAD

**Issue by 942u3895hjf** [HtmlUnit/htmlunit#63]
We need to get links from web pages, added by Javascript in this case. Using HtmlUnit 2.35.0 this works well for most sites, but since recently we have trouble with a specific group of websites, sharing the same CMS.

HtmlUnit is unable to add all 'news' links on: https://www.afas.nl/nieuwsberichten/nieuws
This website since recently, assuming the site has changed, is throwing a EcmaError, not being able to read a property. Is that error also actually the real reason the links are not being added?

HtmlUnit is unable to add most some links on: https://www.werkenbijrocwestbrabant.nl/

The links are not added via AJAX, the JSON blob is already in the DOM.

**Comment by 942u3895hjf** [comment]
Tested this issue with 2.36.0. It still throws a 
`TypeError: Cannot read property "tagName" from null`

I am not sure if this is actually the root problem.

Is there maybe a workaround?

**Comment by 942u3895hjf** [comment]
Here is another example using the same CMS as other example: https://www.kuilnicos.nl/productgroep-prs?PrGr=COM02

This time there are no warnings or errors other than:
`Obsolete content type encountered: 'application/x-javascript'.`

I can read many links from this page, but not the actual products listed on this page (e.g. https://www.kuilnicos.nl/product-prs/artikel?BiId=26330) .  Different browser versions do not seem to change things.

**Comment by rbri** [comment]
Have tested this again with the lastest code base

        String webUrl = "https://www.kuilnicos.nl/productgroep-prs?PrGr=COM02";

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_68 /*, "localhost", 8888 */)) {
            webClient.getOptions().setUseInsecureSSL(true);

            HtmlPage page = webClient.getPage(webUrl);
            webClient.waitForBackgroundJavaScript(20_000);

            System.out.println(" ---- main page start ---- ");
            System.out.println(page.asXml());
            System.out.println(" ---- main page end ---- ");
            System.out.println();
        }

Looks like i always get only the first link. I fear this is because the page does some magic rendering and retrieves only some entries from the server. When scrolling down more entries are fetched. But HtmlUnit is headless -means some of the layout calculations will produce only dummy results. This might lead to this effect.

Because there is a huge amount of js code in this page, i see no chance for me to dig into all the details to figure out what is really going on here - sorry but i do all the work in my spare time.

**Comment by rbri** [comment]
At least for the first case (https://www.kuilnicos.nl/productgroep-prs?PrGr=COM02) i think all the content is now in the xml.

**Comment by rbri** [comment]
Did another try on this - some of the pages are changed in between so i had a look at https://www.afas.nl/nieuwsberichten/nieuws.

Page is based on many many js libraries - i see no chance to find the reason for this during the time i have for this project.
Sorry but i have to close this without any good solution for you.
