### ISSUE TITLE
Incorrect event.source when using postMessage

### ISSUE THREAD

**Issue by jogu** [HtmlUnit/htmlunit#633]
I'm trying to run some code in htmlunit 3.5.0 that has some iframes and uses code like this:

```
        var win = window.parent.document.getElementById("op_iframe").contentWindow;
        win.postMessage(mes, "*");
``` 

The receiving code looks like this:

```
            window.addEventListener('message', function(e) {
                if (window === e.source) {
                    // ignore browser extensions that are sending messages.
                    return;
                }

                if (typeof e.data !== 'string') {
                    return;
                }

                var result = calculateSessionStateResult(e.origin, e.data);
                e.source.postMessage(result, e.origin);
            }, false);
```

The problem is that running in htmlunit, the window === e.source check is true and hence it doesn't go on to process the message.

Running in Safari the same site works fine.

Adding some debug it seems event.source.location is the url for the page containing the receiving code.

Looking at the code here:

https://github.com/HtmlUnit/htmlunit/blob/96369779a836e3908aed9e6fa5acd3a54778c01e/src/main/java/org/htmlunit/javascript/host/Window.java#L1988

in particular:

```
    public void postMessage(final Object message, final String targetOrigin, final Object transfer) {
        final WebWindow webWindow = getWebWindow();
        final Page page = webWindow.getEnclosedPage();
        final URL currentURL = page.getUrl();

        if (!"*".equals(targetOrigin) && !"/".equals(targetOrigin)) {
<...>
        }

        final MessageEvent event = new MessageEvent();
        final String origin = currentURL.getProtocol() + "://" + currentURL.getHost() + ':' + currentURL.getPort();
        event.initMessageEvent(Event.TYPE_MESSAGE, false, false, message, origin, "", this, transfer);
        event.setParentScope(this);
        event.setPrototype(getPrototype(event.getClass()));
```

I think 'this', which is used as 'source' is the target window rather than the source window? Certainly that seems to be what I'm seeing in the debugger.

**Comment by rbri** [comment]
@jogu will have a look

**Comment by jogu** [comment]
Great, thank you! Let me know if it doesn't reproduce easily, I can try and supply a full example (unfortunately some of it is html dynamically generated by our testing system so it's a bit of a pain to unpick it into something standalone).

**Comment by rbri** [comment]
Was able to build a reproducible case.
Fix is not super simple but i will try to find a solution.

**Comment by rbri** [comment]
Please try the latest snapshot.

**Comment by jogu** [comment]
Thank you! I tried htmlunit:3.6.0-20230905.055023-5 - this definitely helps but I'm see a slightly different issue now - it's okay with:

`win.postMessage(mes, "*");`

but:

`e.source.postMessage(result, e.origin);`

doesn't seem to work.

Debugging through it looks in postMessage it's failing the target check:

```
       final WebWindow webWindow = sender.getWebWindow();
        final Page page = webWindow.getEnclosedPage();
        final URL currentURL = page.getUrl();

        if (!"*".equals(targetOrigin) && !"/".equals(targetOrigin)) {
  ```

in particular "currentURL" contains the url for the sending page, rather than the target one.

**Comment by jogu** [comment]
I was puzzled why this didn't fail the unit tests so dug a bit further to make sure it wasn't something I'd misinterpreted; I think the tests pass because here:

https://github.com/HtmlUnit/htmlunit/blob/5f0c6f4be4e0479b9a581ed902184488d01145d3/src/test/java/org/htmlunit/WebTestCase.java#L165C13-L165C13

```
   URL_FIRST = new URL("http://localhost:" + PORT + "/");
   URL_SECOND = new URL("http://localhost:" + PORT + "/second/");
```

These only differ in the URL path, which (I think correctly) isn't part of the check in postMessage, so the postMessage succeeds even though the urls are different.

**Comment by BrillBay** [comment]
@jogu 
have to do some real work for the rest of the day :-)
will work on this later - if you like you can write down some test cases i should include.... it will help if you simly list some cases and i will write the code and all the rest.

**Comment by jogu** [comment]
Thank you!

I think just one extra test case where the sending page and target page are on urls that differ in at least one of the port/host/scheme and the postMessage call uses the correct url as the target.

e.g. like one of the current positive test cases (e.g. postMessage_jsonPayload) but using URL_THIRD instead of URL_SECOND would do it. I believe it would fail with the current code and pass once the check in postMessage was changed to be comparing the target url (and would also pass against 3.5.0).

**Comment by rbri** [comment]
ok, will try to update the snapshot tomorrow

**Comment by rbri** [comment]
sorry you have to be a bit more patient, the fix requires more time to adjust the tests

**Comment by rbri** [comment]
@jogu 
snapshot refreshed - please try again

**Comment by jogu** [comment]
Thank you! I've tried it, and that part is now working correctly.

Unfortunately it's revealed another bug in the same area (let me know if you'd prefer I open a new bug for this)

in my message receiver I'm seeing that event.origin is:

https://mysite.azurewebsites.net:-1

when I'm expecting it without the `:-1`, i.e.:

https://mysite.azurewebsites.net

I think it's this line in Window.java's postMessage method:

> final String origin = senderURL.getProtocol() + "://" + senderURL.getHost() + ':' + senderURL.getPort();

**Comment by rbri** [comment]
No need for a new issue, and i think i know the root of that problem.

**Comment by rbri** [comment]
@jogu snapshot is refreshed, please try again

**Comment by rbri** [comment]
@jogu will be out for two weeks now - hope the latest snapshot does the job for you

**Comment by jogu** [comment]
Tried that and everything seems to be working now - awesome, thank you!

I presume I can close this now.

**Comment by rbri** [comment]
Great, thanks a lot for providing all the details (and for using HtmlUnit).
As usual i will inform on twitter (https://twitter.com/htmlunit) about new releases

and ⭐ 's are also always welcome...
