### ISSUE TITLE
Bad Request error when wait for JavascriptExecution

### ISSUE THREAD

**Issue by jveloper** [HtmlUnit/htmlunit#634]
I'm using a htmlunit (version 3) to scrapping a webpage.

```
HtmlPage p = webClient.getPage(URL);
HtmlElement b = p.getFirstByXPath("xpath selector1");
HtmlPage a = b.click();
a.executeJavaScript("window.scrollTo(0, 6000);");
webClient.waitForBackgroundJavaScript(2000);
```
My requirement is when open a page I have to do a click on a filtering button. The data is updated but the page is lazy loading, so I need to simulate scrolling to the bottom of the page to get more items. When a scroll is done a background request is executed by the server and retrieve more data.

I have a `WebConnectionWrapper` where catch the background request/response.

But an `400 Bad Request for URL` error appear when I add this line on my code because I need to wait for a javascript scroll execution to listening the request that response with new data.

` webClient.waitForBackgroundJavaScript(2000);`

And without this line the request is done without any problem.

What could be the problem when add a `waitForBackgroundJavaScript()` ?

**Comment by rbri** [comment]
Any chance to provide the url (maybe via private mail)

Am 5. September 2023 12:34:25 MESZ schrieb jveloper ***@***.***>:

**Comment by jveloper** [comment]
> Any chance to provide the url (maybe via private mail) Am 5. September 2023 12:34:25 MESZ schrieb jveloper ***@***.***>:
> […](#)
> I'm using a htmlunit (version 3) to scrapping a webpage. ``` HtmlPage p = webClient.getPage(URL); HtmlElement b = p.getFirstByXPath("xpath selector1"); HtmlPage a = b.click(); a.executeJavaScript("window.scrollTo(0, 6000);"); webClient.waitForBackgroundJavaScript(2000); ``` My requirement is when open a page I have to do a click on a filtering button. The data is updated but the page is lazy loading, so I need to simulate scrolling to the bottom of the page to get more items. When a scroll is done a background request is executed by the server and retrieve more data. I have a `WebConnectionWrapper` where catch the background request/response. But an `400 Bad Request for URL` error appear when I add this line on my code because I need to wait for a javascript scroll execution to listening the request that response with new data. ` webClient.waitForBackgroundJavaScript(2000);` And without this line the request is done without any problem. What could be the problem when add a `waitForBackgroundJavaScript()` ? -- Reply to this email directly or view it on GitHub: #634 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Sure ... I will send you an email.

**Comment by rbri** [comment]
@jveloper have opend the page in real browsers and also saw a lot of 400 (Bad Request) messages - check the console.
So i think this works as expected
