### ISSUE TITLE
Reflect.apply() fails on primitive thisArgument

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#641]
This is an issue and fix for `org.mozilla.javascript.NativeReflect`, the class in [htmlunit-rhino-fork](https://github.com/HtmlUnit/htmlunit-rhino-fork) that [hasn't yet reached upstream](https://github.com/mozilla/rhino/pull/1332).

# Problem in brief

Attempting to call the JS method [Reflect.apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/apply) with a [primitive value](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) for `thisArgument` throws `TypeError: Method called on incompatible object` in HtmlUnit 3.5.0.

According to [the specs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply), primitive values need to be converted to objects.

# Reproducing

Here's an example to reproduce:

```javascript!
// Expected: To output "foo"
// Actual: Throws TypeError: Method "toString" called on incompatible object (...)
console.log(Reflect.apply(String.prototype.toString, "foo", []));
```

Incidentally, calling the method directly works as expected:

```javascript!
// Outputs: "foo"
console.log(String.prototype.toString.apply("foo", []));
```

# Suggested fix

Add support to the code handling `args[1]`:

```diff
         Scriptable callable = ScriptableObject.ensureScriptable(args[0]);
 
-        if (args[1] instanceof Scriptable) {
+        if (ScriptRuntime.isPrimitive(args[1])) {
+            thisObj = cx.newObject(scope, "Object", new Object[] {args[1]});
+        } else if (args[1] instanceof Scriptable) {
             thisObj = (Scriptable) args[1];
         }
```

**Comment by rbri** [comment]
Thanks, will apply this next week.

**Comment by rbri** [comment]
core-js snapshot is updated, please try....

**Comment by rbri** [comment]
@duonglaiquang made a new core-js and also an htmlunit snapshot build - please try

**Comment by duonglaiquang** [comment]
@rbri Got it. Thanks a lot. 😄
