### ISSUE TITLE
HtmlUnit 3.6.0 unexpected deletion of `HtmlForm.getLostChildren()`

### ISSUE THREAD

**Issue by MarkEWaite** [HtmlUnit/htmlunit#647]
Thanks so much for your maintenance and care of HtmlUnit.  We use it many places in the Jenkins project.

The 3.6.0 release of HtmlUnit seems to have removed `HtmlForm.getLostChildren()` and the concept of lost children of a form in 3ce40a9f8ae78adea254d986e882e57a3cc09ff8 .  There is no entry in the release notes to warn about that removal.

The comment message on 3ce40a9f8ae78adea254d986e882e57a3cc09ff8 does not hint that the removal is intentional, but it may have been intentional and unstated.  It seems that rather than keeping a separate list of lost children, now the code assigns the owning element of the "lost child" to the form that is consuming the element.

If my understanding is correct, I think that means we can use `HtmlForm.getHtmlElementDescendants()` to replace `HtmlForm.getLostChildren()` though that seems like it will return all children, not just the lost children.

Any recommendation on the path we should take to replace our reference to `HtmlForm.getLostChildren()`?

**Comment by basil** [comment]
> Any recommendation on the path we should take to replace our reference to `HtmlForm.getLostChildren()`?

My recommendation is to remove any references to `HtmlForm#getLostChildren`, which was never a supported public API to begin with. The only reason to invoke this private API was to work around invalid HTML, which we may have had in July 2015 when our usage of `HtmlForm#getLostChildren` was introduced, but which we no longer seem to have in Jenkins core, Text Finder, or Throttle Concurrent Builds as of today.

**Comment by MarkEWaite** [comment]
> My recommendation is to remove any references to `HtmlForm#getLostChildren` ...

Thanks!  Done with https://github.com/jenkinsci/jenkins-test-harness/pull/664/commits/8203a3c5ac69a4daad8d6ca4977a7741ba6cc409 in 

* https://github.com/jenkinsci/jenkins-test-harness/pull/664

**Comment by MarkEWaite** [comment]
Closing since no action is needed from HTMLUnit

**Comment by rbri** [comment]
@MarkEWaite Thanks for pointing at that. You are right the release notes are not that detailed about this.
Will try to add some words.
