### ISSUE TITLE
commons-io:2.6 vulnerability

### ISSUE THREAD

**Issue by Sanady** [HtmlUnit/htmlunit#648]
Could you please fix dependency vulnerability on commons-io:2.6? This vulnerability is within 3.6.0 version.

**Comment by rbri** [comment]
Hi @Sanady 

HtmlUnit 3.6.0 uses commons-io 2.14.0 (https://github.com/HtmlUnit/htmlunit/blob/master/pom.xml).
Maybe you have some other lib that is the cause of this?

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.14.0</version>
        </dependency>

**Comment by rbri** [comment]
@Sanady have you found the reason? Can i close this issue?

**Comment by rbri** [comment]
Will close this - please reopen if you still have problems
