### ISSUE TITLE
Setting type for HtmlInput does not work

### ISSUE THREAD

**Issue by Deadc00l** [HtmlUnit/htmlunit#658]
Setting a type by "setType("hidden", true)" or by "setAttribute("type", "hidden")" doesn't seem to work. I was not able to found out, where the bug is. I guess somewhere between: org.htmlunit.html.HtmlInput.setType(String, boolean) line 1222 - 1228.

I have modified an unittest in "/htmlunit/src/test/java/org/htmlunit/html/HtmlPageTest.java" to reproduce this issue:
```
    /**
     * @throws Exception if the test fails
     */
    @Test
    public void formSubmit() throws Exception {
        final String htmlContent = "<html>\n"
            + "<head><title>foo</title></head>\n"
            + "<body>\n"
            + "<p>hello world</p>\n"
            + "<form id='form1' action='/formSubmit' method='PoSt'>\n"
            + "<input type='text' NAME='textInput1' value='textInput1'/>\n"
            + "</form>\n"
            + "</body></html>";
        final HtmlPage page = loadPage(htmlContent);
        final MockWebConnection webConnection = getMockConnection(page);

        final HtmlForm form = page.getHtmlElementById("form1");
        final HtmlInput textInput = form.getInputByName("textInput1");
        textInput.setValue("foo");
        textInput.setType("hidden", true);
        
        assertEquals("hidden", textInput.getType());
    }
```

**Comment by rbri** [comment]
short answer, the change of the type replaces the dom element - you have to do textInput = form.getInputByName("textInput1"); again.
Will have a look if this is really required

**Comment by rbri** [comment]
Sorry i think there is no easy way to solve this. Have renamed the method and added a return value, hope this helps.

**Comment by rbri** [comment]
3.8.0-SNAPSHOT is available

**Comment by Deadc00l** [comment]
I just tested it, and the return value solve my problem. Thanks a lot!

**Comment by rbri** [comment]
Thanks will close this.
