### ISSUE TITLE
Option to disable loading of frames

### ISSUE THREAD

**Issue by royteeuwen** [HtmlUnit/htmlunit#665]
We use HTMLUnit as a test engine to run our integration tests. 

On our test pages, we might have links to iframes (for example google tag manager). We would like to have an option to disable the loading of the content of the frames

**Comment by rbri** [comment]
@royteeuwen,
great to see HtmlUnit has some benefit for you.

Have done some documentation about content blocking some weeks ago - maybe that helps already
https://www.htmlunit.org/details.html#Content_blocking

And there is also a related FAQ entry (if i got you right)
https://www.htmlunit.org/faq.html#HowToModifyRequestOrResponse

Will have a look at your PR later today.

**Comment by rbri** [comment]
Oh there is something more - looks like you are not the first one having this wish....

You can set the FrameContentHandler of the WebClient to your own one returning false from the impl of loadFrameDocument()

**Comment by royteeuwen** [comment]
OK i can try that! 

Wouldn’t it be more clear / consistent to go for the provided option as in my PR though?

**Comment by rbri** [comment]
@royteeuwen does one of the suggestions work for you?

**Comment by royteeuwen** [comment]
@rbri  Yep, thanks!

**Comment by rbri** [comment]
Have a small sample of the FrameContentHandler included in the doc.
