### ISSUE TITLE
`java.lang.IllegalStateException`: This `PooledParser` was not returned to the pool properly

### ISSUE THREAD

**Issue by basil** [HtmlUnit/htmlunit#669]
An attempt to upgrade to 3.8.0 failed in https://github.com/jenkinsci/jenkins/pull/8710 / https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8710/ with intermittent errors of the form

```
Caused by: java.lang.IllegalStateException: This PooledParser was not returned to the pool properly
	at org.htmlunit.WebClient$PooledCSS3Parser.markInUse(WebClient.java:3050)
	at org.htmlunit.WebClient$CSS3ParserPool.get(WebClient.java:2999)
	at org.htmlunit.WebClient.getCSS3Parser(WebClient.java:2961)
	at org.htmlunit.html.DomNode.getSelectorList(DomNode.java:1869)
	at org.htmlunit.html.DomNode.querySelectorAll(DomNode.java:1838)
	at org.htmlunit.javascript.host.dom.Document.querySelectorAll(Document.java:1067)
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:222)
	... 35 more
```

introduced in #664 which cannot be reproduced locally or even consistently in CI. The failures have been observed mostly on Windows (slower infrastructure) but also occasionally on Linux. The failures often disappear when the test is run a second time. We have rolled back to 3.7.0.

**Comment by rschwietzke** [comment]
Checking the issue now.

**Comment by rschwietzke** [comment]
@basil Please give this build version a try. It highly likely fixes the problem. I only considered the global state but not the state of the pooled parser itself and its stateful and "visible" reference. Sorry about that and thanks for reporting.

**Comment by rbri** [comment]
@rschwietzke thanks for the fast reaction
@basil the ci test running right now, will build a new snapshot as soon as the ci is happy;

**Comment by rschwietzke** [comment]
@basil I think that the solution could be even smaller because the `volatile` is not really needed because we set null before the pool sees it (visibility guarantee). After we take it from the pool, we set it none-null (only the thread that got it will use it from here). The error was setting the pool reference in the parser to null after I sent it back to the pool and not before which violated the happen-before relation.

If you are willing, we could try a custom build with a smaller change when this one holds.

**Comment by rbri** [comment]
@basil 3.9.0-SNAPSHOT is available - please try

**Comment by basil** [comment]
I have run the same test against 3.9.0-SNAPSHOT and can confirm the issue is resolved in the snapshot.

**Comment by rbri** [comment]
@basil do you see a chance to make another test run with the simplified version from @rschwietzke ?

**Comment by basil** [comment]
I do not see a chance. My enthusiasm for this project decreased significantly when this project's maintainers forced me to spend hours and hours dealing with broken builds due to a renamed package.

**Comment by rbri** [comment]
@basil sorry for all the trouble you had with this broken release.
Maybe i can provide some insights...

There was a lot of things to do at my real job, not so much time (and brain ;-)) left for HtmlUnit during the last weeks.

Regarding the issue - we did some updates to provide a shared pool of a heavy resource used for css parsing. Using this pool has an significant effect on the performance of some scenarios and therefore we try to share the pooled objects as good as possible. But there was a bug - and sadly no (load) test case to proof the pool works under heavy load.

The test case is now there.

Again thanks a lot for your support and patience

  Ronald

**Comment by rbri** [comment]
Will close this as the fix forks for jenkins and we have a unit test also.

**Comment by basil** [comment]
Thank you very much!

**Comment by basil** [comment]
We have successfully upgraded to 3.9.0. Thanks again!

**Comment by rbri** [comment]
@basil thanks for the feedback
