### ISSUE TITLE
How to configure to parse the "<iframe>" tag

### ISSUE THREAD

**Issue by ly641921791** [HtmlUnit/htmlunit#67]
When I open the webpage through a browser, I can get the following for the "<iframe>" tag.

``` xml
<iframe id="iframe0201" frameborder="no" border="0" src="/xxx.shtml" onload="setIframeHeight('iframe0201');" style="height: 610px;">
    <html>...</html>
</iframe>
```

When I get the page through the code below, I can't get a page like that opened in the browser.

``` java
final WebClient webClient=new WebClient(BrowserVersion.CHROME);
webClient.getOptions().setCssEnabled(true);
webClient.getOptions().setJavaScriptEnabled(true);
webClient.getOptions().setMaxInMemory(500);
final HtmlPage page = webClient.getPage("...");
```

``` xml
<iframe id="iframe0201" frameborder="no" border="0" src="/xxx.shtml" onload="setIframeHeight('iframe0201');" style="height: 610px;">
</iframe>
```

**Comment by rbri** [comment]
your output is from page.asXml() ?

**Comment by ly641921791** [comment]
> your output is from page.asXml() ?

Here is my code. The version of htmlunit is 2.35.0

``` java
    public static void main(String[] args) throws Exception {
        
        String webUrl = "http://www.ggzy.gov.cn/information/html/a/150000/0201/201908/09/001581754506eb984dbabc5bdb36e7b43e47.shtml";

        final WebClient webClient = new WebClient(BrowserVersion.CHROME);
        webClient.getOptions().setCssEnabled(true);
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setMaxInMemory(500);

        final HtmlPage page = webClient.getPage(webUrl);
        TimeUnit.SECONDS.sleep(5);
        webClient.close();

        System.out.println(page.asXml());
    }
```

**Comment by rbri** [comment]
Frames are separate windows (see http://htmlunit.sourceforge.net/frame-howto.html).
The browsers are including the content html sometimes for convenience but in HtmlUnit you have to handle the iframe content yourself if you like to dump it. Of course HtmlUnit will handle (e.g. download and process js inside) the (i)frames like ordinary browsers.
To dump the content of the iframes also you can use this code:

        String webUrl = "http://www.ggzy.gov.cn/information/html/a/150000/0201/201908/09/001581754506eb984dbabc5bdb36e7b43e47.shtml";

        try (final WebClient webClient = new WebClient(BrowserVersion.CHROME)) {
            webClient.getOptions().setCssEnabled(true);
            webClient.getOptions().setJavaScriptEnabled(true);
            webClient.getOptions().setMaxInMemory(500);

            final HtmlPage page = webClient.getPage(webUrl);
            webClient.waitForBackgroundJavaScript(5_000);

            System.out.println(" ---- main page start ---- ");
            System.out.println(page.asXml());
            System.out.println(" ---- main page end ---- ");
            System.out.println();

            for (FrameWindow frameWindow : page.getFrames()) {
                final HtmlPage framePage = (HtmlPage) frameWindow.getEnclosedPage();
                System.out.println(" ---- frame page start ---- ");
                System.out.println(framePage.asXml());
                System.out.println(" ---- frame page end ---- ");
            }
        }

Does this solve your problem?

**Comment by ly641921791** [comment]
Thank you very much for helping me with this problem, but that code may not solve the problem.

The following code will print true on the console

``` java
    String webUrl = "http://www.ggzy.gov.cn/information/html/a/150000/0201/201908/09/001581754506eb984dbabc5bdb36e7b43e47.shtml";

    try (final WebClient webClient = new WebClient(BrowserVersion.CHROME)) {
        webClient.getOptions().setCssEnabled(true);
        webClient.getOptions().setJavaScriptEnabled(true);
        webClient.getOptions().setMaxInMemory(500);

        final HtmlPage page = webClient.getPage(webUrl);
        webClient.waitForBackgroundJavaScript(5_000);

        for (FrameWindow frameWindow : page.getFrames()) {
            final HtmlPage framePage = frameWindow.getEnclosingPage();
            System.out.println(page.asXml().equals(framePage.asXml()));
        }
    }
```

Is there a bug here? The code inside http://htmlunit.sourceforge.net/frame-howto.html also can't get the desired result. 

The following code will also print true on the console

``` java
    try (final WebClient client = new WebClient();) {
        final HtmlPage mainPage = client.getPage("http://htmlunit.sourceforge.net/apidocs/index.html");

        System.out.println(mainPage.asXml());

        System.out.println(mainPage.getFrameByName("classFrame").getEnclosingPage().asXml().equals(mainPage.asXml()));
    }
```

**Comment by rbri** [comment]
Ok will have a look again - you sample looks strange :-)

**Comment by rbri** [comment]
Sorry really stupid type - you have to use frameWindow.**getEnclosedPage()**; instead of getEnclosingPage()
Have edited my sample code to reflect this and removed the close call

**Comment by rbri** [comment]
And as always it is a good idea to use the latest snapshot....

**Comment by ly641921791** [comment]
Thank you very much, I used the wrong method, now my problem is solved.

**Comment by rbri** [comment]
You are welcome. Have fun using HtmlUnit.
