### ISSUE TITLE
Malformed reply from SOCKS server 

### ISSUE THREAD

**Issue by crazysvn** [HtmlUnit/htmlunit#675]
when using ipv6 socks proxy, below exception happens:
I/O exception (java.net.SocketException) caught when processing request to {s}->https://xxx.com:443: Malformed reply from SOCKS server

**Comment by rbri** [comment]
@crazysvn can you please add a complete stack trace

**Comment by rbri** [comment]
@crazysvn can i close this?

**Comment by crazysvn** [comment]
yes. thanks.

RBRi ***@***.***> 于2024年3月27日周三 19:23写道：

**Comment by rbri** [comment]
Thanks for the feedback...
