### ISSUE TITLE
Missing attachment on xhr download

### ISSUE THREAD

**Issue by ghost** [HtmlUnit/htmlunit#69]
I'm trying to automate some file download (using HtmlUnit) from a website that is based on liferay+struts+angular. HtmlUnit has done a fine job in navigating pages and interpreting JS so far, but when I try to download the file, it returns me the same page and not the attachment.

The download button is made as such:
```html
<button class="btn" name="filedownload" data-ng-disabled="false"
        type="button" data-ng-lick="vm.downloadFile(...things...)">
</button>
```

I've already tried with the two main techniques that I've found online: using a `CollectingAttachmentHandler` and `.getWebResponse().getContentAsStream()`, both of them give me the starting page and not the attachment.

By tracing it with the network tracer of Chrome I see that once I clicked it makes a call to 2 different endpoints, the first to trace that such file will be doenloaded and the second to download the file, the second one has a response with the correct `Content-Disposition: attachment; filename=` header, but apparently HtmlUnit is not picking it up.

Here is some snippet of the code that I've tried.
```java
CollectingAttachmentHandler attachmentHandler = new 
CollectingAttachmentHandler();
client.setAttachmentHandler(attachmentHandler);
attachmentHandler.handleAttachment(myButton.click());

// I get only one attachment, the page
List<Attachment> attachments = attachmentHandler.getCollectedAttachments();
```

```java
// In my_file I find the page
try (InputStream in = myButton.click().getWebResponse().getContentAsStream();
     OutputStream out = Files.newOutputStream(new File(""...my_file...).toPath())) {
    IOUtils.copy(in, out);
}
```

I've also debugged the `NicelyResynchronizingAjaxController` and I see the two abovementhioned calls passing, both seem to be processed correctly, but I don't get the file back; I've also tried the latest 2.36.0 SNAPSHOT which does not solve the problem.

My client is configured as follows:

```java
final WebClient client = new WebClient(BrowserVersion.CHROME);
client.setAjaxController(new NicelyResynchronizingAjaxController());
client.setCssErrorHandler(new SilentCssErrorHandler());
client.getCache().clear();
client.getCookieManager().clearCookies();
client.setJavaScriptTimeout(90000);

final WebClientOptions options = client.getOptions();
options.setCssEnabled(true);
options.setJavaScriptEnabled(true);
options.setDoNotTrackEnabled(true);
options.setDownloadImages(false);
options.setGeolocationEnabled(false);
options.setScreenWidth(1920);
options.setScreenHeight(1080);
options.setTimeout(90000);
options.setSSLClientCipherSuites(
    new String[] { "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256" });
options.setUseInsecureSSL(false);
options.setPopupBlockerEnabled(true);
options.setRedirectEnabled(true);
options.setAppletEnabled(false);
options.setThrowExceptionOnFailingStatusCode(false);
options.setThrowExceptionOnScriptError(false);
options.setPrintContentOnFailingStatusCode(true);
```

**Comment by rbri** [comment]
Hi Fabio,
without being able to debug it is not that simple to help you with this.
Will polish my crystal ball and telly what i can see ;-)

If you are sure that the call for for the download is sent out by htmlunit also then we only have to find the response (if you are not sure you can enable HttpClient wire logging or you can use a web debugging proxy like Charles or Fiddler). 

data-ng-lick="vm.downloadFile(...things...)"
This looks like the call is done by javascript. As far as i rember there is some strange async handling done by some frameworks for this kind of download. The usual problem is that a 'normal' call will replace the current window content with the result of the call. For this some download libraries opening the download call in another window and the browsers are so smart to detect the content-dispositon : attachment and do not really open a new window. HtmlUnit is a bit different here and opens a new window. And second, this js magic is usually async - the click() result is sync.

What does this mean?

Try this steps:
* call click() on the button but ignore the result
* wait for background javascript for some seconds
* check the window list for a new current window
* get the response from the content of the new window - this response might have your download as content

Hope that helps, if not give me please a sign and i will move the crystal ball into the bin

**Comment by rbri** [comment]
Second: if you like to work with the Attachment Handler...

Do this directly as part of you client setup

    CollectingAttachmentHandler attachmentHandler = new 
    CollectingAttachmentHandler();
    client.setAttachmentHandler(attachmentHandler);

Don't do this - if you have setup an attachment handler, all attachment responses are automatically collected
    attachmentHandler.handleAttachment(myButton.click());

Instead add waitForBackgroundJavascript with some seconds after the click and before you looking into your attachmentHandler.

**Comment by ghost** [comment]
Hi @rbri , thanks for the support. I'd like to share with you the page, but I can't because the page is in a private area which is not accessible from unauthorized users and it's not developed by the company I work for.

I've tried with the windows, without success, here is what I've done:
```java
// tried adding a windows listener, no changes were logged
client.addWebWindowListener(new WebWindowListener() {
    @Override
    public void webWindowOpened(WebWindowEvent event) {
        System.out.println("new window");
    }
                    
    @Override
    public void webWindowContentChanged(WebWindowEvent event) {
        System.out.println("Something happened");
    }
                    
    @Override
    public void webWindowClosed(WebWindowEvent event) {
        System.out.println("window closed");
    }
});
```

```java
// logged before and after the number of windows, nothing changed
System.out.println("There are '"+client.getWebWindows().size()+"' windows");
```

```java
/*
 * added the attachment handler to the client without doing the handleAttachment
 * thing, nothing was intectepted
 */
client.setAttachmentHandler(new CollectingAttachmentHandler());
```

I feel a bit stuck right now, if you have any other suggestion, even only for collecting data useful to you for debugging purposes (I could even organize a TeamViewer call if you wish, but it seems a bit too much to ask), just say and I'll try.

**Comment by rbri** [comment]
Ok, lets start simple.

You are sure the download is performed when using HtmlUnit. Can you verify this please with Charles or Fiddler.

**Comment by ghost** [comment]
Hi @rbri, sorry for the delay.
I've used Charles to debug the call, I can confirm that indeed the file gets downloaded, but I don't know how to get it via HtmlUnit.

The browser sends this request:
```
GET somepath HTTP/1.1
Host: somehost
Connection: Keep-Alive
Upgrade-Insecure-Requests: 1
User-Agent: the agent
Accept: application/json, text/plain, */*
Referer: some page
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Cookie: we all love cookies
X-Content-Type-Options: nosniff
x-token: a tocken
x-b2bcookie: another one
X-Frame-Options: deny
Strict-Transport-Security: max-age=16070400; includeSubDomains
Cache-Control: no-cache
X-XSS-Protection: 1; mode=block
```

And I get my 100kb attachments with this response headers:
```
HTTP/1.1 200 OK
Date: Mon, 19 Aug 2019 10:37:41 GMT
X-Powered-By: Servlet/3.0
x-token: the token sent before
x-b2bcookie: the other token
Content-Disposition: attachment; filename=myfile.zip
Content-Length: 106147
Keep-Alive: timeout=10, max=44
Content-Type: application/zip
Content-Language: en-US
Connection: keep-alive
```

**Comment by rbri** [comment]
Just to be sure the Charles debug was captured when using HtmlUnit - correct?

If yes there has to be a place where HtmlUnit does not call the Attachment handler after data retrieval. Will have another look at this.

**Comment by rbri** [comment]
Ahhhh sorry now i got your point, the attachment is downloaded via xhr - and this case is not what the attachment handler is for.

As quick solution you can try to use the WebConnectionWrapper.

Can you please tell me how the attachment is handled in the real browser.

**Comment by rbri** [comment]
Does you application something comparable to this?
https://stackoverflow.com/questions/22724070/prompt-file-download-with-xmlhttprequest

**Comment by ghost** [comment]
> Just to be sure the Charles debug was captured when using HtmlUnit - correct?
> 
> If yes there has to be a place where HtmlUnit does not call the Attachment handler after data retrieval. Will have another look at this.

Yes, of course. I've setup the proxy in the client, added the certificate in my `cacerts` and so on.

> Ahhhh sorry now i got your point, the attachment is downloaded via xhr - and this case is not what the attachment handler is for.
> 
> As quick solution you can try to use the WebConnectionWrapper.
> 
> Can you please tell me how the attachment is handled in the real browser.

I've done the following:
```java
client.setWebConnection(new WebConnectionWrapper(client) {
	@Override
	public WebResponse getResponse(WebRequest request) throws IOException {
		WebResponse response = super.getResponse(request);
		if (request.getUrl().toExternalForm().contains("download")) {
			System.out.println(request.getUrl().toExternalForm());
		}
		return response;
	}
});
```
Something strange happens, though. As I said before, there are two calls (both with the string download in the url), the first call is the one that requests the download and the second one is the one that actually downloads the file.
The first call I can see it passing through the `WebConnectionWrapper` and also through `NicelyResynchronizingAjaxController`, but the second one doesn't. :(

**Comment by ghost** [comment]
> Does you application something comparable to this?
> https://stackoverflow.com/questions/22724070/prompt-file-download-with-xmlhttprequest

The angular code in charge of sending the requests is:
```javascript
if (responseType) {
	try {
	  xhr.responseType = responseType;
	} catch (e) {
	  // WebKit added support for the json responseType value on 09/03/2013
	  // https://bugs.webkit.org/show_bug.cgi?id=73648. Versions of Safari prior to 7 are
	  // known to throw when setting the value "json" as the response type. Other older
	  // browsers implementing the responseType
	  //
	  // The json response type can be ignored if not supported, because JSON payloads are
	  // parsed on the client-side regardless.
	  if (responseType !== 'json') {
		throw e;
	  }
	}
	}
	xhr.send(isUndefined(post) ? null : post);
}
```

**Comment by ghost** [comment]
> Can you please tell me how the attachment is handled in the real browser.
I don't know about that, I'll give you some of the information that I can gather via the development tool of Chrome, feel free to ask others if you know what to look for.

This is the download timeline in which you can see the two calls, the second fails in HtmlUnit. Both are `GET` to a specific url, they have `Referrer Policy: no-referrer-when-downgrade` and have a status code of 200. 
![timeline](https://user-images.githubusercontent.com/22909364/63329995-429f5f00-c333-11e9-98f4-1371b132d244.jpg)

**CALL 1**

REQUEST:
```
GET a url HTTP/1.1
Host: a host
Connection: keep-alive
Sec-Fetch-Mode: cors
Strict-Transport-Security: max-age=16070400; includeSubDomains
X-Content-Type-Options: nosniff
x-token: a token
User-Agent: ua
x-b2bcookie: a cookie
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache
DNT: 1
Sec-Fetch-Site: same-origin
Referer: the url
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.9,en-GB;q=0.8,en;q=0.7
Cookie: a ton of cookies
```
RESPONSE:
```
HTTP/1.1 200 OK
Date: Tue, 20 Aug 2019 07:43:52 GMT
X-Powered-By: Servlet/3.0
x-token: a token
x-b2bcookie: a cookie
Content-Length: 0
Keep-Alive: timeout=10, max=99
Connection: Keep-Alive
Content-Language: en-US
```

**CALL 2**

REQUEST:
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.9,en-GB;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: a ton of cookies
DNT: 1
Host: a host
Referer: the referrer
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Strict-Transport-Security: max-age=16070400; includeSubDomains
User-Agent: ua
x-b2bcookie: another cookie
X-Content-Type-Options: nosniff
X-Frame-Options: deny
x-token: token
X-XSS-Protection: 1; mode=block
```

RESPONSE:
```
Connection: Keep-Alive
Content-Disposition: attachment; filename=myfile.zip
Content-Language: en-US
Content-Length: 105329
Content-Type: application/zip
Date: Tue, 20 Aug 2019 07:43:52 GMT
Keep-Alive: timeout=10, max=97
x-b2bcookie: another cookie
X-Powered-By: Servlet/3.0
x-token: token
```

**Comment by ghost** [comment]
Apparently there is light in the end of the tunnel.
While testing for various things I saw that `automagically®` started showing the second call from the wrapper connection.

I debugged a bit more and apparently the secret was to delay the two calls, the only way was through the wrapped connection though.

Here is what seems to work right now:
```java
client.setWebConnection(new WebConnectionWrapper(client) {
	@Override
	public WebResponse getResponse(WebRequest request) throws IOException {
		final WebResponse response = super.getResponse(request);
		if (request.getUrl().toExternalForm().contains("download")) {
                        // the first call has always an empty body, 
                        // so if it is the first I'll stall it a bit
			if (response.getContentLength() == 0)
				try {
					TimeUnit.SECONDS.sleep(5);
				} catch (InterruptedException e) {
					//nothing to do
				}
			else // if has contents is the right response, let's write it
				writeToFile(response, "test.zip");
		}
		return response;
	}
});
```

It is not what I'd judge as a stable and reliable fix, so if you have any suggestions please be free to report them. I'll then update also the stackoverflow post that I've opened and that you've spotted.

**Comment by rbri** [comment]
The first call seem to be the CORS preflight call. But i can't see any reason why you need this sleep code.
