### ISSUE TITLE
Cookie rejected

### ISSUE THREAD

**Issue by 32** [HtmlUnit/htmlunit#7]
`Dec 05, 2018 6:39:27 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Cookie rejected [sessionid="""", version:0, domain:.i.instagram.com, path:/, expiry:Wed Dec 31 19:00:00 EST 1969] Illegal 'domain' attribute ".i.instagram.com". Domain of origin: "www.instagram.com"`
Getting this error while trying to connect to instagram login page.(http://www.instagram.com/accounts/login/)

**Comment by rbri** [comment]
Can you please provide some more details; at least some code to reproduce your problem.

**Comment by rbri** [comment]
No more details, will close this.
