### ISSUE TITLE
Support shorthand and computed properties for ComputedCssStyleDeclaration

### ISSUE THREAD

**Issue by shapiroronny** [HtmlUnit/htmlunit#708]
Following the very welcomed support for Computed Styles without js (https://github.com/HtmlUnit/htmlunit/issues/131).
Is it possible to maintain support for getting CSS properties also set via shorthand and computed properties?

For example, With `ComputedCSSStyleDeclaration` the API supported simple utility getter like `getBackgroundImage` and `getComputedWidth`, these are not available fo `ComputedCssStyleDeclaration`.

**Comment by rbri** [comment]
@shapiroronny good point will have a look but i'm optimistic to get this done

**Comment by rbri** [comment]
@shapiroronny as a first step most of the getters are migrated.

Maybe you can give the latest snapshot build a try to check that i'm moving in the right direction....

**Comment by shapiroronny** [comment]
> @shapiroronny as a first step most of the getters are migrated.
> 
> Maybe you can give the latest snapshot build a try to check that i'm moving in the right direction....

Thanks for making progress on this!!
Most compilation issues have been resolved on the compilation level except we're still missing `getCalculatedWidth`, can this be migrated to `AbstractCssStyleDeclaration` as well?

I'm going to stub those out for now to make some progress on e2e tests.

For the moment we've seen one exception when setting the 'type' attribute of HtmlInput when JS is disabled.
Attached stack trace:

```
java.lang.IllegalStateException: No script object associated with the Page. class: 'org.htmlunit.html.HtmlPage' url: 'http://www.google.com/' content: 
	at org.htmlunit.html.DomNode.getScriptableObject(DomNode.java:906)
	at org.htmlunit.html.DomNode.getScriptableObject(DomNode.java:908)
	at org.htmlunit.html.HtmlInput.changeType(HtmlInput.java:1230)
	at org.htmlunit.html.HtmlInput.setAttributeNS(HtmlInput.java:637)
	at org.htmlunit.html.DomElement.setAttributeNS(DomElement.java:515)
	at org.htmlunit.html.DomElement.setAttribute(DomElement.java:502)
```

**Comment by shapiroronny** [comment]
> > @shapiroronny as a first step most of the getters are migrated.
> > Maybe you can give the latest snapshot build a try to check that i'm moving in the right direction....
> 
> Thanks for making progress on this!! Most compilation issues have been resolved on the compilation level except we're still missing `getCalculatedWidth`, can this be migrated to `AbstractCssStyleDeclaration` as well?
> 
> I'm going to stub those out for now to make some progress on e2e tests.
> 
> For the moment we've seen one exception when setting the 'type' attribute of HtmlInput when JS is disabled. Attached stack trace:
> 
> ```
> java.lang.IllegalStateException: No script object associated with the Page. class: 'org.htmlunit.html.HtmlPage' url: 'http://www.google.com/' content: 
> 	at org.htmlunit.html.DomNode.getScriptableObject(DomNode.java:906)
> 	at org.htmlunit.html.DomNode.getScriptableObject(DomNode.java:908)
> 	at org.htmlunit.html.HtmlInput.changeType(HtmlInput.java:1230)
> 	at org.htmlunit.html.HtmlInput.setAttributeNS(HtmlInput.java:637)
> 	at org.htmlunit.html.DomElement.setAttributeNS(DomElement.java:515)
> 	at org.htmlunit.html.DomElement.setAttribute(DomElement.java:502)
> ```

Submitted this [PR](https://github.com/HtmlUnit/htmlunit/pull/716) to fix exception.

**Comment by rbri** [comment]
getCalculatedWidth() is already migrated, will build a new snapshot as soon all tests are back to green and inform you

**Comment by rbri** [comment]
snapshot updated, the whole impl is now moved to the non js part.

**Comment by shapiroronny** [comment]
> snapshot updated, the whole impl is now moved to the non js part.

Thanks, looks great so far!

**Comment by rbri** [comment]
3.11.0 is release
