### ISSUE TITLE
Recommended way to override attachment trigger

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#71]
I'm setting up a robot that needs to capture and download attachments from a site that does not use the content disposition header in some cases.

https://github.com/HtmlUnit/htmlunit/blob/bef05a431e35cc81186c86855c52ac38dd6737f3/src/main/java/com/gargoylesoftware/htmlunit/WebClient.java#L521-L526

Is there a way or recommended approach how to extend this trigger without needing to override the webclient and attachment class?

I could change the loadWebResponseInto method but would have to keep track of any upstream changes and I was told there might be some issues with calling protected methods as well.

Also, apologize if this question should be brought up on stackeoverflow but it seems that I was banned for six months for having one question marked as -1. Not sure how that works over there.

**Comment by rbri** [comment]
Good/valid point. Will move the method isAttachment(WebResponse) from Attachment to the AttachmentHandler interface to give you more control.

Change is in, please check on twitter for info about a new snapshot build.

**Comment by skyhirider** [comment]
Thank you, this will be immensely helpful!

**Comment by rbri** [comment]
You are welcome
