### ISSUE TITLE
incorrect spam from obsolete mime type text/javascript.

### ISSUE THREAD

**Issue by jtnord** [HtmlUnit/htmlunit#710]
https://github.com/HtmlUnit/htmlunit/blob/cfecd3ef681508aea057807b7377777626ba6a47/src/main/java/org/htmlunit/html/HtmlPage.java#L1113C8-L1128 incorrectly reports text/javascript mimetype as obsolete.  However it is application/javascript that is now obsolete.

The official register at IANA will show this [here](https://www.iana.org/assignments/media-types/media-types.xhtml#application:~:text=javascript-,(OBSOLETED%20in%20favor%20of%20text/javascript,-)) as well as [Mozilla MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types#:~:text=.js,RFC%209239))

When running HTMLUnit I should not get incorrect warnings about mime types of the form:

```
Jan 19, 2024 11:52:23 AM org.htmlunit.IncorrectnessListenerImpl notify
WARNING: Obsolete content type encountered: 'text/javascript'
```

if HTMLUnit is hangin anything of the obsolete mime/type (application/javascript) then it should be updated to use the correct text/javascript, see https://www.rfc-editor.org/rfc/rfc9239.html#name-iana-considerations for more info.

**Comment by rbri** [comment]
@jtnord good catch, give me some seconds

**Comment by rbri** [comment]
@jtnord Please try the latest snapshot build

**Comment by jtnord** [comment]
> @jtnord Please try the latest snapshot build

I don't see any snapshot available at https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~org/ is there somewhere else I should be looking?

**Comment by rbri** [comment]
https://s01.oss.sonatype.org/content/repositories/snapshots/org/htmlunit/

see https://github.com/HtmlUnit/htmlunit - there are some info about getting the snapshot with maven/gradle

**Comment by rbri** [comment]
@jtnord can i close this?

**Comment by jtnord** [comment]
appoligies, I have not been able to get time to test this, but the code looked good.

**Comment by rbri** [comment]
Ok, thanks, will close this for now. Feel free to reopen or create a new one if you face this problem again (or something else)
