### ISSUE TITLE
404 on htmlunit.sourceforge.io/resources/js/app.js

### ISSUE THREAD

**Issue by danilograziano** [HtmlUnit/htmlunit#711]
Hi, we are experience various 404 error during the navigation

http://htmlunit.sourceforge.net/js/closejs.js
http://htmlunit.sourceforge.net/js/all_sg_new.js
http://htmlunit.sourceforge.net/js/window.js

1. Server: htmlunit.sourceforge.io
2. URL path: /resources/js/app.js
3. Error notes: NONE
4. Error type: 404
5. Request method: GET
6. Request query string: NONE
7. Time: 2024-01-19 14:36:43 UTC (1705675003)

**Comment by rbri** [comment]
@danilograziano  not sure that i got your point.

The newer homepage is at https://www.htmlunit.org/

Do you got the problems while browsing the page?

**Comment by danilograziano** [comment]
Hi when I try to use this method
page = webClient.loadHtmlCodeIntoCurrentWindow(finalRespString);

I encounter always this error: 404 on this resources:
http://htmlunit.sourceforge.net/js/closejs.js
http://htmlunit.sourceforge.net/js/all_sg_new.js
http://htmlunit.sourceforge.net/js/window.js

I'm using the library hosted on sourceforge

**Comment by rbri** [comment]
@danilograziano the 404 is correct - if you try to open the page with a real browser (or wget) you will see the url http://htmlunit.sourceforge.net/js/closejs.js points to nowhere - you get a 404.

I guess the url is part of the respString (maybe as href of an script tag). Where do you get this respString from?

**Comment by rbri** [comment]
no feedback - will close this.

@danilograziano please open a new one if you still face problems
