### ISSUE TITLE
htmlunit  When used in Android, an exception is thrown

### ISSUE THREAD

**Issue by 0501fei** [HtmlUnit/htmlunit#72]
htmlunit  When used in Android, an exception is thrown:

 No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; 
 in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; 
 or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)

The reason is that httpclient is not available in android。

**Comment by rbri** [comment]
Looks like you have the wrong version of the httpclient in your classpath.

**Comment by 0501fei** [comment]
Yes, thank you. The reason is found.

**Comment by rbri** [comment]
Thanks for the feedback

**Comment by palafix** [comment]
Hey, can you please tell what the reason is what helped you?
I have the same error but can't find what the problem is.

**Comment by DeborahAnn** [comment]
@rbri what would be the correct version of httpclient to use with htmlunit 2.36.0/2.37.0?

**Comment by Shabinder** [comment]
Getting Same Error , please tell how to fix this version issue.
