### ISSUE TITLE
htmlunit 3.0.0 all inclusive dependency uber jar misses few jetty dependencies

### ISSUE THREAD

**Issue by farahnaj** [HtmlUnit/htmlunit#726]
https://github.com/HtmlUnit/htmlunit/releases/tag/3.0.0

I am trying to build a GWT project and upgrading htmlunit to 3.0.0 to get past a few vulnerabilities. 
After some research I found that htmlunit packages a nice [dependencies jar ](https://github.com/HtmlUnit/htmlunit/releases/download/3.0.0/htmlunit-3.0.0.jar)which should work like plug and play. However I had to find dependencies on maven central after I had breakage in my tests. Mostly ClassDefNotFoundErrors. 

Jar which had to be added for htmlunit 3.0.0 to work
1 jetty-xml-9.4.51.v20230217.jar
2 jetty-webapp-9.4.51.v20230217.jar
3 jetty-servlet-9.4.51.v20230217.jar
4 jetty-server-9.4.51.v20230217.jar
5 jetty-security-9.4.51.v20230217.jar
6 slf4j-api-1.7.36.jar

**Comment by rbri** [comment]
@farahnaj sorry, but your assumtions is wrong, this is not an ueber-jar, it is simply the the same jar file you get when downloading it from maven central using maven/gradle.

If you like to download a file with all required dependencies you can use https://github.com/HtmlUnit/htmlunit/releases/download/3.11.0/htmlunit-3.11.0-bin.zip. But this is a simple zip file not an uber-jar.

And please consider using the latest version 3.11.0....

**Comment by farahnaj** [comment]
My bad I should put the correct link to bin.zip only. I was driven by the statement "htmlunit-x.xx.x-bin.zip contains everything you need including all required dependencies" from https://htmlunit.sourceforge.io/ in the installation section. But it does not have all the dependencies.

**Comment by rbri** [comment]
Ah, will have a loock

**Comment by rbri** [comment]
@farahnaj sorry but again i think the current distribution is correct.

As long as you are only use HtmlUnit in your projects, i think all the files you are need are in the zip file.

The jetty server components are only required if you like to compile/run the whole source code because they are used from the test infrastructure.

**Comment by rbri** [comment]
and btw i have done a minor update to the website - https://www.htmlunit.org/

**Comment by rbri** [comment]
@farahnaj can i close this?

**Comment by rbri** [comment]
no reaction will close this. Please open a new one if needed.
