### ISSUE TITLE
Timeline for removal of `BrowserVersion.INTERNET_EXPLORER` and `SupportedBrowser.IE`?

### ISSUE THREAD

**Issue by atnak** [HtmlUnit/htmlunit#735]
This isn't an issue per-se but a request for clarification of timeline.

So the browser support was deprecated nearly one year ago in the [March 19, 2023 release of Release 3.0.0](https://www.htmlunit.org/changes-report.html#a3.0.0).

Do we have a timeline on when actual code removal can be started? (Since maintaining features for IE is rather tedious and difficult.)

**Comment by rbri** [comment]
Good point,
for the most of the last releases i simply ignore the IE support. And i also check the number and i think it is really time to let go.

What do you think about this: Version 3.**11** is the last with IE **11** support...

**Comment by atnak** [comment]
> Version 3.**11** is the last with IE **11** support...

Lol, sounds good 👍
It's been a while since it's been deprecated and if there hasn't been any major pushback then probably no one is that much concerned.  At worst, those needing IE 11 could probably use an old jar.

**Comment by rbri** [comment]
ok, the train has left the station....

**Comment by rbri** [comment]
This seems to be the hugest refactoring i ever did on this lib. I think the next version will be 4.0.

**Comment by rbri** [comment]
The first pass is done - will build a new snapshot (4.0.0) and then work on your PR's

**Comment by rbri** [comment]
Ok, there is no way back - the next release is planned for begin of april.

Thanks for motivating me to start this - this is a huge improvement for the code base and i guess we will still find some left overs in some years.
