### ISSUE TITLE
If you filter out 404 resources

### ISSUE THREAD

**Issue by wangrunze2023** [HtmlUnit/htmlunit#741]
I visit a URL and there is a js in the source code. It is indeed 404. Except for this js, this page can be accessed correctly in Google Chrome. However, in HtmlUnit, this js 404 is always reported and the page content is not printed. How to filter out the 404 resources to keep it accessible？

**Comment by rbri** [comment]
@wangrunze2023 please try 

    webClientOptions.setThrowExceptionOnFailingStatusCode(false)

**Comment by wangrunze2023** [comment]
> @wangrunze2023 please try
> 
> ```
> webClientOptions.setThrowExceptionOnFailingStatusCode(false)
> ```


Thank you! 😄

**Comment by rbri** [comment]
@wangrunze2023 so i can close this?

**Comment by wangrunze2023** [comment]
> @wangrunze2023 so i can close this?

Okay, thank you again for helping me solve this problem immediately.

**Comment by rbri** [comment]
thanks, have fun using HtmlUnit
