### ISSUE TITLE
JavaScript support for Element scrolling

### ISSUE THREAD

**Issue by blasss** [HtmlUnit/htmlunit#742]
We are happy users of HtmlUnit and appreciate your continuous work for improving support of a wide range of standards.
To test the latest changes of our website we are missing JavaScript support for Scrolling Elements.

The following methods would be nice:
- [`scroll()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll)
- [`scrollBy()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy)
- [`scrollTo()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo)

All of these methods are supported by [current browsers](https://caniuse.com/element-scroll-methods) and would in perfect world as well emit [scroll-events](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event)

**Comment by rbri** [comment]
@blasss thanks

have done a first snapshot build for the upcoming 4.0.0-SNAPSHOT version.
Have added some empty stubs for the three methods. Please try the snapshot (and be warned the IE support is removed in this version).

Hope we can discuss a bit what kind of event support you expect here - at the moment i have no good idea what a headless browser can really do here. Maybe you can share some of your ideas/needs.

**Comment by blasss** [comment]
Basically the implementation in my mind can be along the lines of the implementation of `org.htmlunit.javascript.host.Window.scrollTo()` etc.
The implementation more or less accepts most values and delegates processing to `setScrollLeft()` and `setScrollTop()` and finally a scroll-event is fired.
The fired scroll-event doesn't require much ([Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event)) and is only needed to trigger client javascript code...

I'm not really sure from the [specification](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface) whether the `setScrollLeft()` and `setScrollTop()` should as well fire events, but may be that's another issue for another time...

Hope this gives you a impression of the requested functionality. Thanks.

**Comment by skyhirider** [comment]
I will chime in and give my opinion as I was forced to switch to Chrome due to scrolling not working as expected in HtmlUnit (as reported in https://github.com/HtmlUnit/htmlunit/issues/657).

I am scraping sites that have tables with dynamic scroll - you can see the first 50 rows and when you reach row 50 (scroll to it) the next 50 are loaded, and so on until the end is reached.

Normal browsers can of course handle it, but when triggering the scrollTo javascript method (via the js executor) I can't access the next 50 rows of data.

If there already is a way to scroll to an element (even if its HtmlUnit specific) I could use that as a workaround, as I know you are currently looking at switching the js engines. But it is a gap that is currently noticeable, and the first one I ran into after a few years that made me switch drivers as I had no other choice.

**Comment by rbri** [comment]
mad some hacking and a new snapshot build - please try

**Comment by skyhirider** [comment]
My test case is still failing but you were probably asking blasss.

**Comment by blasss** [comment]
I checked the snapshot and the basic functionality seems to be working, but my testcase is still failing.
After some debugging I found out the respective element is not considered scrollable in `ComputedCssStyleDeclaration.isScrollable(boolean, boolean)`, as this is only checking the `overflow` CSS-attribute and we are required to use `overflow-x` and `overflow-y`...

**Comment by rbri** [comment]
@blasss looks solvable - maybe tomorrow

**Comment by rbri** [comment]
@blasss snapshot updated - please try

**Comment by blasss** [comment]
Many thanks for this instant support!
I tested and basically the introduced fix for the scrollable-check is looking good.

Unfortunately the use of `overflow-x` and `overflow-y` is inverted:
`overflow-x` should be used to check vertical scrolling and `overflow-y` for horizontal scrolling.

**Comment by rbri** [comment]
@blasss can you please have a look at the new test cases i have added. Both are passing with real browsers AND the new impl. Maybe i made a mistake in  the tests?

**Comment by blasss** [comment]
@rbri no, the tests are looking good. Too me it looks like you tricked yourself by using the wrong value for the horizontal-boolean in some of the calling functions:
`getCalculatedHeight(boolean, boolean)` calculates the height to be 17px less if the element can be scrolled vertically (`isScrollable(false, true)`). If I didn't twist my brain too much the 17px should be subtracted if it can be scrolled horizontally (for horizontal scrolling the scrollbar shows up along the x-axis and therefore the height has to be reduced).
Same inverted use for scrolling-boolean is in `getCalculatedWidth(boolean, boolean)`.

I hope my explanations are somewhat understandable...

**Comment by rbri** [comment]
@blasss snapshot updated - please try

And thanks for your analysis - sometimes i'm blind

**Comment by blasss** [comment]
The updated snapshot is working as expected. From my perspective this issue is solved.
Many thanks for your continued support.
