### ISSUE TITLE
Field is always required even when "novalidate" attribute is specified

### ISSUE THREAD

**Issue by php-coder** [HtmlUnit/htmlunit#75]
I have a form where one of the fields has "required" attribute. htmlunit 2.36.0 respects this and doesn't allow me to submit a form with an empty field.

In order to validate a server side validation, I added a "novalidate" attribute to a form and I expect that htmlunit will ignore client side validation and let me submit a form with an empty required field. But htmlunit still doesn't submit a form and complains that form validation failed:
```
[INFO] Form validation faild; element 'HtmlTextInput[<input id="name" type="text" class="form-control" required="required" name="name" value="">]' was not valid. Submit cancelled.
```

It seems like a bug as I believe that htmlunit should skip "required" field validation when "novalidate" is present on a form.

**Comment by rbri** [comment]
Sorry for being that late on this simple issue.
This is now fixed in the latest snapshot build.
