### ISSUE TITLE
How to set and use Clipboard with WebClient?

### ISSUE THREAD

**Issue by chrc** [HtmlUnit/htmlunit#762]
Hi,
I can't find a simple test example with the `webClient`, a `ClipboardHandler` and the `Clipboard`, to simulate a copy/paste into an HtmlTextInput.
Can you tell me how to do this, please?
THANKS.

**Comment by rbri** [comment]
/**
     * @throws Exception if an error occurs
     */
    @Test
    public void clipboardCopy() throws Exception {
        final String html =
                "<html><head>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <form>\n"
                + "    <input type='text' id='i1' value='aswjdfue'>\n"
                + "  </form>\n"
                + "  <button id='check' onclick='test()'>Test</button>\n"
                + "</body></html>";

        final ClipboardHandler clipboardHandler = new AwtClipboardHandler();
        getWebClient().setClipboardHandler(clipboardHandler);

        clipboardHandler.setClipboardContent("");
        final HtmlPage page = loadPage(html);

        final HtmlInput input = (HtmlInput) page.getElementById("i1");

        final Keyboard kb = new Keyboard();
        kb.press(KeyboardEvent.DOM_VK_CONTROL);
        kb.type('a');
        kb.type('c');
        kb.release(KeyboardEvent.DOM_VK_CONTROL);
        input.type(kb);

        assertEquals("aswjdfue", clipboardHandler.getClipboardContent());
    }

    /**
     * @throws Exception if an error occurs
     */
    @Test
    public void clipboardPaste() throws Exception {
        final String html =
                "<html><head>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <form>\n"
                + "    <input type='text' id='i1'>\n"
                + "  </form>\n"
                + "  <button id='check' onclick='test()'>Test</button>\n"
                + "</body></html>";

        final ClipboardHandler clipboardHandler = new AwtClipboardHandler();
        getWebClient().setClipboardHandler(clipboardHandler);

        clipboardHandler.setClipboardContent("xyz");
        final HtmlPage page = loadPage(html);

        final HtmlInput input = (HtmlInput) page.getElementById("i1");

        final Keyboard kb = new Keyboard();
        kb.press(KeyboardEvent.DOM_VK_CONTROL);
        kb.type('v');
        kb.release(KeyboardEvent.DOM_VK_CONTROL);
        input.type(kb);

        assertEquals("xyz", input.getValue());
    }

**Comment by rbri** [comment]
@chrc you are right, there is some docu missing about this topic. will try to add some words later.
Have written unit test - hope that helps.

**Comment by rbri** [comment]
@chrc have updated the docu a bit - https://www.htmlunit.org/keyboard-howto.html

Can you please have a look and suggest further improvements....

**Comment by rbri** [comment]
i guess the thumbs up means this is ok... if not reopen :-D

Thanks for pointing at this

**Comment by chrc** [comment]
Thanks you @rbri 
But I get an HeadlessException error.

**Comment by chrc** [comment]
![Capture d’écran 2024-04-08 à 09 14 29](https://github.com/HtmlUnit/htmlunit/assets/88607/6b0c583b-5e13-47b3-8144-c8f3bd5afbf3)

**Comment by chrc** [comment]
@rbri WDYT?
