### ISSUE TITLE
[Replaceable] attribute is not implemented

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#787]
### Problem in brief

- Attempting to set the value of `Window.length` and couple of other properties of `Window` throws `Cannot set property [Window].X that has only a getter to value Y`.
- The cause of this appears to be because the extended attribute [``[Replaceable]``](https://webidl.spec.whatwg.org/#Replaceable) for JavaScript bindings is not implemented in HtmlUnit/Rhino.
- For example, [this page shows the properties of `Window`](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-window-object) that should have the `[Replaceable]` attribute.

### Example

```javascript=
console.log(window.length); // 0
window.length = 100;

// Expected: 100
// HtmlUnit: Cannot set property [Window].length that has only a getter to value 100
console.log(window.length);
```

### Notes

* This issue was previously posted in the comment together with three other issues in the below sf ticket (which can be closed). The three others issues have already been resolved
    * https://sourceforge.net/p/htmlunit/bugs/1956/#a90f

**Comment by rbri** [comment]
@duonglaiquang have done a first hack, looks to me like the browsers are not really following that spec - at least the tests are passing. Please have a look, if you agree i will implement the other window properties the same way.

**Comment by rbri** [comment]
finally implemented

**Comment by rbri** [comment]
@duonglaiquang a new snapshot is out

**Comment by duonglaiquang** [comment]
@rbri Thanks a lot for your fixes 😄 

I looked into the [specs](https://html.spec.whatwg.org/) and found out this attribute is only used in 2 other properties beside [Window's](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-window-object), which are
[DedicatedWorkerGlobalScope.name](https://html.spec.whatwg.org/#dedicated-workers-and-the-dedicatedworkerglobalscope-interface) and [SharedWorkerGlobalScope.name](https://html.spec.whatwg.org/#shared-workers-and-the-sharedworkerglobalscope-interface). 

But i think `HtmlUnit` 's `WorkerGlobalScope` doesn't support `name` property at the moment ?

**Comment by rbri** [comment]
> But i think HtmlUnit 's WorkerGlobalScope doesn't support name property at the moment ?

Now it does ;-)

@duonglaiquang if you like, you can have a look at the new tests - maybe there is room for improvements
