### ISSUE TITLE
Set browser timezone

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#788]
What is the recommended way to change the WebClient's timezone?

I can change the jvm's timezone by altering the system variable, but what if I only need to alter the client, or have multiple clients running in parallel, each with its own timezone.

The use case is accessing sites that set their content based on the timezone the browser advertises or even generate and download files with different timestamps inside the data depending on the timezone.

Chrome dev tools protocol supports a way of defining this (have not tested yet, but its in the dev tools protocol).

**Comment by rbri** [comment]
You can create your own BrowserVersion, set the timezone and then use it for creating your webclient.

    BrowserVersion ffBerlin = new BrowserVersion.BrowserVersionBuilder(BrowserVersion.FIREFOX)
                                                .setSystemTimezone(TimeZone.getTimeZone("Europe/Berlin"))
                                                .build();

But i fear there are not that many methods using this. Please open issues for all the places you find that are ignoring this info.

**Comment by skyhirider** [comment]
So thats how you use the builder, could you add mention of this option in your documentation?

You have a few examples on how to set an attachment handler or toggle javascript, it could be listed there as an option too.

**Comment by rbri** [comment]
@skyhirider updating the docu is always a good point.

Maybe you can have a look at https://www.htmlunit.org/webclient.html#Imitating_a_specific_browser, hopefully this is a bit better now.

**Comment by skyhirider** [comment]
Thanks for updating the docs!

It mentions us always being default. How do the other browsers do it, isn't it OS specific?

You could query the JVM to get the timezone and language.

Thou could be a breaking change if people are used to English.

**Comment by rbri** [comment]
For real browsers this is OS Specific (or depending on a setting of the TZ var for the current session.
For Chrome/Edge there is a way to change the timezone using the dev api.

As HtmlUnit is (also) for testing i think it should be possible to simulate every timezone/locale you like to test. Therefore there was the decision (long long ago) to always start with a fixed setting and allow to change that if needed.

At the moment this is something that has to be done before starting the WebClient but maybe there is no good reason for this. Will have a look - maybe we can move this to the options to make it simpler for the user to change.

**Comment by rbri** [comment]
After a bit more thinking....

I like to stay with the current way - it is not really possible to change the locale of a browser at runtime and i think it makes also no real sense to change these setting of a running HtmlUnit WebClient. I guess every test case starts with a fresh browser and does not change the locale/language during the test session.

**Comment by skyhirider** [comment]
I can see your point, what I meant was HtmlUnit taking on the timezone and local of the jvm when its initially launched, thou that would be a breaking change and not sure either if its a good idea or not.

Not being able to change it during runtime makes sense, thou if there was a use case when a quick switch was needed the whole driver would need to be re-loaded and initialized instead of a simple switch.

Thou having the driver immutable is logical.

For me personally, its enough to know this can be done and how (thank you for updating your documentation!).

Was surprised it was not with the rest of the webclient options, but works just a well with the browser settings.

**Comment by rbri** [comment]
Have added some more words, hope this is sufficient now.

Thanks for pointing at this.
