### ISSUE TITLE
Is the new attachment handler filename method working?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#789]
I am testing the new method that is supposed to work with the filename - handleAttachment(Page page, String attachmentFilename) .

When I 
- open this page https://www.ronsplace.ca/products/ronsdataedit/download
- click the download free link
the filename remains null during debug even thou the header contains "filename=RonsDataEdit_2024.05.15.1304_setup.exe"

I noticed this while looking at implementing an attachment handler that would download all attachments automatically to a temporary folder.

Are you open to adding an extra attachment handler to HtmlUnit in addition to the Collecting attachment handler? I can build one (provided the attachment handler is working correctly)

My very ugly work in progress test.

The attachment handler I am using is an empty class, but noticed the problem mentioned above while debugging.
```java
	@Test
	public void test() throws FailingHttpStatusCodeException, MalformedURLException, IOException, InterruptedException {
		System.out.println(System.getProperty("java.io.tmpdir"));
		WebClient webClient = new WebClient(BrowserVersion.FIREFOX);
		webClient.setAttachmentHandler(new DownloadingAttachmentHandler());
		HtmlPage page = webClient.getPage("https://www.ronsplace.ca/products/ronsdataedit/download");
		HtmlAnchor anchorByHref = page.getAnchorByHref("/contentproduct/data-edit/setup.exe");
		System.out.println(anchorByHref.asXml());
		anchorByHref.click();
		
		Thread.sleep(100000);
		
	}
```

**Comment by skyhirider** [comment]
The header is incorrectly parsed, filename and content disposition are in the same collection element (unless its intentional?)

![image](https://github.com/HtmlUnit/htmlunit/assets/1695005/f183184e-c898-4fe4-9f7a-2e020289523b)

**Comment by rbri** [comment]
Will have a look, and yes I'm open to add such a handler

**Comment by skyhirider** [comment]
Thanks, had another look and it seems the apache http library is incorrectly parsing the headers inside the BasicHttpResponse.

**Comment by rbri** [comment]
@skyhirider for me it looks like an error in HtmlUnit - hopefully this is now fixed. Please try with the lastes snapshot build

**Comment by skyhirider** [comment]
Thanks, I can see the filename now.

I am wondering, can you update it to support octet streams as well, like normal browsers do?

My original test was with this, but the reply was an octet stream so it was completely ignored by both the isAttachment method and then filename generation method as well.

Thou not sure how to infer the filename, I am assuming Chrome does it by parsing the url and getting the last part.

```java
HtmlPage page = webClient.getPage("https://www.ghisler.com/download.htm");
HtmlAnchor anchorByHref = page.getAnchorByHref("https://totalcommander.ch/1103/tcmd1103x32_64.exe");
```

**Comment by rbri** [comment]
will have a look....

**Comment by rbri** [comment]
> My original test was with this, but the reply was an octet stream so it was completely ignored by both the isAttachment method and then filename generation method as well.

@skyhirider  Your response only had the Content-Type: application/octet-stream header but no Content-Disposition: attachment header - Correct?

**Comment by skyhirider** [comment]
@rbri that is correct. Some files are like that.

**Comment by rbri** [comment]
@skyhirider please try the latest snapshot build

**Comment by skyhirider** [comment]
Thanks, octet stream is now recognized as an attachment by default. The attachment name is still null, but I will see if I can infer it from the url directly in the method.
