### ISSUE TITLE
Ampersand in title causes parser to fail

### ISSUE THREAD

**Issue by jeffcjohnson** [HtmlUnit/htmlunit#79]
The parser will allow an ampersand in the title tag but fails in some instances.  The following will cause it to treat all HTML that follows as plain text:

`String htmlCode = "<html><head><title>&X</title></head</html>";`

`System.out.println(page.getTitleText());`
prints `&x</title></head</html>` instead of `&x`.

The full code to reproduce:
```
import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.StringWebResponse;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HTMLParser;
import com.gargoylesoftware.htmlunit.html.HtmlPage;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

public class HtmlUnitTest {
	public static void main(String[] args) {
		String htmlCode = "<html><head><title>&x</title></head</html>";
		try (WebClient webClient = new WebClient(BrowserVersion.BEST_SUPPORTED)) {
			StringWebResponse response = new StringWebResponse(htmlCode, new URL("http://http://htmlunit.sourceforge.net//test.html"));
			HtmlPage page = HTMLParser.parseHtml(response, webClient.getCurrentWindow());
			System.out.println(page.getTitleText());
			// work with the html page
		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

```

**Comment by rbri** [comment]
Hope you can be a bit patient about this.
I like to switch away from Neko to https://about.validator.nu/htmlparser/. Hope this step will solve this problem also. There is still some work to do and i also have some business task during the next weeks,
So please be a bit patient....

**Comment by jeffcjohnson** [comment]
Hi, any movement on this?

**Comment by rbri** [comment]
Hi Jeff,
thanks for the reminder. Looks like i will not find the time to make the big move and change the parser.
Instead of this i will fix it in Neko.

**Comment by rbri** [comment]
Oh seems to be a  bigger one - parsing entity references eats up the '<' from the input stream; of cause this breaks the parser.

**Comment by rbri** [comment]
Have made a new neko-htmlunit snapshot build available... please try

**Comment by rbri** [comment]
After some sleep/thinking i made a more generic fix for this.
