### ISSUE TITLE
Go to other apps and push buttons

### ISSUE THREAD

**Issue by jidanni** [HtmlUnit/htmlunit#794]
Just like going to web pages pushing buttons according to criteria, perhaps add the ability to go to other apps on the Android system and push buttons on them too.

**Comment by rbri** [comment]
@jidanni sorry but i have no idea what you like to get here. Can you please add some more detail....

**Comment by jidanni** [comment]
OK. In https://www.reddit.com/r/AndroidQuestions/comments/1cx4hc5/a_routine_to_push_a_button/ they are giving me some apps to try. Maybe they'll do what I want.
