### ISSUE TITLE
window.atob() charset problem

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#80]
According to the doc, window.atob() and btoa() only suppports ASCII characters:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#Unicode_strings
[The current implementation in htmlunit](https://github.com/HtmlUnit/htmlunit/blob/014cfcbe9ad441a9acf378943a4069716faa609a/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/Window.java#L418) however supports UTF-8 which is not correct. It generates different results with real browsers. For example, the result of atob("M8OuwqY=").length in htmlunit is 3, while in real browsers it's 5.
htmlunit should construct the result string with charset ISO_8859_1 instead of UTF_8;

**Comment by rbri** [comment]
As usual, many thanks for this, including the test case.
Fix is on the way - will inform via twitter (https://twitter.com/HtmlUnit) if a new snapshot is out.

**Comment by RuralHunter** [comment]
I think the change should be applied in btoa() as well though it would not make any difference with the result?

**Comment by rbri** [comment]
Had the same idea but

return new String(Base64.encodeBase64(bytes), StandardCharsets.UTF_8);

but the javadoc says 
Returns: byte[] containing Base64 characters in their UTF-8 representation

So i think UTF_8 is correct here.

**Comment by RuralHunter** [comment]
ok, that's fine.
