### ISSUE TITLE
Support Fetch API

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#803]
I encountered some web sites utilizing [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), which I believe has not been implemented yet in htmlunit.

**Comment by blasss** [comment]
This is already discussed in #78 which as well provides a possible workaround.

**Comment by RuralHunter** [comment]
OK, good to know. Thanks for the info.
