### ISSUE TITLE
Add option to allow XMLHttpRequest for local files from the same directory and subdirectories

### ISSUE THREAD

**Issue by tntim96** [HtmlUnit/htmlunit#808]
HTML Unit 4.2.0 introduced a security fix:
https://htmlunit.sourceforge.io/changes-report.html#a4.2.0
"Prevent XMLHttpRequest from loading local resource for security reason."

Most browsers do this by default but allow an override. Can an override option please be added that allows for local files from the same directory and sub-directories to be loaded via XMLHttpRequest?

**Comment by rbri** [comment]
I think yes, will have a look after my vacation.

**Comment by rbri** [comment]
@tntim96 
made a new snapshot build - please try....

**Comment by tntim96** [comment]
Thanks. I'll try it out.

**Comment by tntim96** [comment]
Tested and works perfectly for my test scenarios. :+1:

**Comment by rbri** [comment]
Great, and thanks for the fast feedback.

Enjoy using HtmlUnit.
