### ISSUE TITLE
Support native-image?

### ISSUE THREAD

**Issue by xuxiaocheng0201** [HtmlUnit/htmlunit#809]
Is there a plan to support [native-image](https://www.graalvm.org/latest/reference-manual/native-image/)?

**Comment by rbri** [comment]
No real plans, but what do you expect here from a library?

**Comment by xuxiaocheng0201** [comment]
There is no other similar library, so this is the best and only.
For some reason, I hope this library can be used in C, but writing the corresponding API is too cumbersome. So I combined APIs in Java and provided several CEntryPoints that C can call.
However, I encountered reflection issues after compiling them into a shared library, so I hope you can provide support for native-images.

**Comment by xuxiaocheng0201** [comment]
May I try making [metadata](https://github.com/oracle/graalvm-reachability-metadata) and creating PR?

**Comment by rbri** [comment]
@xuxiaocheng0201 of course - verry welcome

I will create a new repo for this.... htmlunit-native ok?

**Comment by xuxiaocheng0201** [comment]
I've already forked the repo. Luckly the name is same: [htmlunit-native](https://github.com/xuxiaocheng0201/htmlunit-native)

**Comment by xuxiaocheng0201** [comment]
I've already forked the repo. Luckly the name is same: [htmlunit-native](https://github.com/xuxiaocheng0201/htmlunit-native)

**Comment by rbri** [comment]
@xuxiaocheng0201

maybe there was a bit of misunderstanding - i really like to open a new repo that only contains the stuff that builds the lib on top of the htmlunit jar files.
This is now available - https://github.com/HtmlUnit/htmlunit-native

Can you please open your PR's again that repo.

**Comment by xuxiaocheng0201** [comment]
OK. I will open this pr in that repo.

**Comment by xuxiaocheng0201** [comment]
But still some questions:
1. Which version should I synchronize with? `4.3.0` or the dev?
2. Should I include metadata files for other libraries that the project depends on? (like `commons-logging`)
3. Is there a specified directory scheme?

**Comment by xuxiaocheng0201** [comment]
But still some questions:
1. Which version should I synchronize with? `4.3.0` or the dev?
2. Should I include metadata files for other libraries that the project depends on? (like `commons-logging`)
3. Is there a specified directory scheme?
