### ISSUE TITLE
Lacking implementations and configurations for WebWorker

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#816]
### Problem in brief
- A lot of the [standard APIs that should work inside a `WebWorker`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers#web_apis_available_in_workers) do not currently.
- Additional interfaces like `WorkerLocation` and `WorkerNavigator` are also not implemented.

### Example

main.js:
```javascript
new Worker("worker.js").postMessage("");
```

worker.js:
```javascript
onmessage = function(e) {

  // Some examples APIs:    
    
  // HtmlUnit throw "org.htmlunit.corejs.javascript.EcmaError: ReferenceError: "URL" is not defined"
  new URL("http://example.com");

  // HtmlUnit throw "org.htmlunit.corejs.javascript.EcmaError: ReferenceError: "XMLHttpRequest" is not defined"
  new XMLHttpRequest();

  // HtmlUnit: undefined
  // Chrome: returns WorkerLocation for the script
  console.log(location);
}
```

**Comment by rbri** [comment]
Ok, ok this might be a bit more work and some refactoring. Maybe something for the weekend....

**Comment by rbri** [comment]
> Ok, ok this might be a bit more work and some refactoring. Maybe something for the weekend....

or some weekends ;-)

**Comment by rbri** [comment]
@duonglaiquang have made a first impl, please have a look (4.5.0-SNAPSHOT)

**Comment by duonglaiquang** [comment]
Wow! Thanks a lot for taking on this issue so quickly. That was fast 😄 
I'm really looking forward to the official version update 👍

**Comment by rbri** [comment]
@duonglaiquang there is still a long way to go - the next version is still 4 weeks ahead

**Comment by rbri** [comment]
Implemented (hopefully)
