### ISSUE TITLE
execute() called after the shutdown of the Javascript engine and therefore not processed

### ISSUE THREAD

**Issue by csware** [HtmlUnit/htmlunit#818]
I'm using HtmlUnit 4.3.0 in one of my projects and I'm getting the error `execute() called after the shutdown of the Javascript engine and therefore not processed` (origin `INFO  org.htmlunit.javascript.JavaScriptEngine`) logged to the console for every test case.

No issue with version 3.11.0, but according to my old logs the issue got introduced when I switched to 4.1.0.

The code can be found here: https://gitlab.com/mrtux/htmlunit-issue

Test class: https://gitlab.com/mrtux/htmlunit-issue/-/blob/master/src/test/java/de/tuclausthal/submissioninterface/WebClientTest.java

Example from the logs: https://gitlab.com/mrtux/htmlunit-issue/-/jobs/7352973308#L357

**Comment by rbri** [comment]
Hallo Sven,

the last releases got some major changes regarding the closing of the web client (mainly to resolve some memory issues), the message you see is part of this refactoring's. Will have a deeper look at your code....

**Comment by rbri** [comment]
@csware there was a typo i guess the call comes from callSecured() and not from execute(). 
This might happen if some js is executed after the client is already on the way to get closed. we have to stop several things and therefore maybe some others are still trying to do something.

Does you pages have some beforeunload/unload event handlers. Do you use some timers that (re)run the whole time - like polling some backend services? Or do you have websockets open?

If yes i will try to create an reproducable test case and maybe we can take care of the closing web client earlier.

**Comment by csware** [comment]
There are some pages that have a timer (interval >= 2 minutes), but not the login page and the overview page.
No websockets and no (before)unload event handlers.
The shutdown of the web client may have to block until all javascript is canceled or executed.

**Comment by rbri** [comment]
I like to create a snapshot build that logs the whole stack trace of the situation. This hopefully helps to understand the root cause of that.

@csware Is it possible for you to use such a snapshot build and send me the log file?

**Comment by rbri** [comment]
@csware found some reasons for the log output - have to think about....

**Comment by csware** [comment]
> @csware Is it possible for you to use such a snapshot build and send me the log file?

If I can easily use it, yes.

You can also fork the example repository and edit pom.xml on GitLab.

**Comment by rbri** [comment]
> You can also fork the example repository and edit pom.xml on GitLab.

At least the readme makes me fear that there is more to do than only running mvn.

**Comment by rbri** [comment]
@csware Ok, have changed the code a bit...

1. for the onbeforeunloadAccepted handling i have changed/optimized the code a bit. This event is no longer triggered, if the shutdown of the client was started and therefore the window gets closed
2. have removed the log calls.

@csware What do you think - is this ok for you?

**Comment by csware** [comment]
> > You can also fork the example repository and edit pom.xml on GitLab.
> 
> At least the readme makes me fear that there is more to do than only running mvn.

For the automatic tests everything is prepared automa(t|g)ically.

You're approach is ok for me (but why commenting code?)

**Comment by rbri** [comment]
> You're approach is ok for me (but why commenting code?)

Because i'm only 99% happy with that solution. But you are right....

**Comment by csware** [comment]
Btw. ``if(LOG.isDebugEnabled()) LOG.debug("")``` is redundant (cf. https://www.slf4j.org/faq.html#logging_performance and https://stackoverflow.com/a/963681/3906760)

**Comment by rbri** [comment]
> btw

yes i know (and sometimes forget about is). Hope that Spotbugs/PMD takes care of this.
Usually i have no log statements with only a constant string, but maybe there are some.

as always there is soooo much to do but i do it all in my spare time besides having a real >40h job.

PR's are very welcome, or maybe you can motivate your students to provide something ;-)

**Comment by rbri** [comment]
@csware 
just made a fresh snapshot build - please find the doc how to try it here https://github.com/HtmlUnit/htmlunit?tab=readme-ov-file#maven-1

**Comment by csware** [comment]
> @csware just made a fresh snapshot build - please find the doc how to try it here https://github.com/HtmlUnit/htmlunit?tab=readme-ov-file#maven-1

cf. https://gitlab.com/mrtux/htmlunit-issue/-/commit/dd1a2dd6c20e5605146f1e350baba605080c83c1 and https://gitlab.com/mrtux/htmlunit-issue/-/jobs/7374803118

The log entries are gone now.

**Comment by rbri** [comment]
@csware great, and thanks for re-testing. Next release is sheduled for the end of next week. OK?

**Comment by csware** [comment]
> Next release is sheduled for the end of next week. OK?

Perfectly fine, for me it was more a cosmetic issue.

**Comment by csware** [comment]
I'm sorry, but this issue is not fixed in 4.5.0. I don't get any warning any more.

**Comment by csware** [comment]
Sorry, wrong issue :(
