### ISSUE TITLE
(Html)Page.getBaseUrl() not returning base URL

### ISSUE THREAD

**Issue by black-snow** [HtmlUnit/htmlunit#83]
[getBaseUrl()](http://htmlunit.sourceforge.net/apidocs/com/gargoylesoftware/htmlunit/html/HtmlPage.html#getBaseURL--) does not seem to actually return the base URL anymore - in some cases at least.

The URL I loaded was something like this: `https://www.example.org/details/a_b_60327_c-15651212_1;jsessionid=7132CE8CE959709FD76D745BA600BC9A?x=y&z=zz`

But then

```java
final String pdfUrl = "/a/b/c";
System.out.println(page.getBaseURL().toString()+ pdfUrl);
```

returns `https://www.example.org/details/a_b_60327_c-15651212_1;jsessionid=7132CE8CE959709FD76D745BA600BC9A?x=y&z=zz/a/b/c`

**HtmlUnit 2.36.0**

I circumvent this by checking whether it's a relative URL or not and then using `HtmlPage.getFullyQualifiedUrl()`.

**Comment by rbri** [comment]
Sorry but i can't remember any change that might affect this. Are you sure this was different in the past (which version).

Have at least added some unit test for the method to be aware of changes in the future.

And btw. i fear handlings urls like strings is not a good idea at all.

**Comment by rbri** [comment]
Hi
just found this old one - i like to close this. Please open a new one if you still think the current behavior is not correct.

BTW: Hope you are fine....

**Comment by black-snow** [comment]
@rbri yeah thanks, throw it away - most probably obsolete.

I'm quite fine, yes. I hope the same goes for you! How are things going with HtmlUnit? Guess you could alway use some more helping hands? (Btw, does the GitHub sponsor thing go 100% straight into your pocket? Or does it work like ye good old app stores? :D)

**Comment by rbri** [comment]
> yeah thanks, throw it away - most probably obsolete.

Ok, will do.

> I hope the same goes for you!

Yes outside the usual problems when getting older :-)

> How are things going with HtmlUnit?

I think good - lot of work, some plans for version 3.0 but no time to do it as fast as i like

> Guess you could always use some more helping hands?

Of course

> Btw, does the GitHub sponsor thing go 100% straight into your pocket

Not really, but the sum i got every month is at least sufficient for the discussion with my wife if she ask what i'm doing here all the time
Maybe i think different about that after my 'Steuererklärung'

**Comment by black-snow** [comment]
@rbri glad to hear.

What do you think would be the best way to support this project with little spare time (one to a couple of hours / week)? Working on random issues? Working on something particular? Docs? "Moderation"?

**Comment by rbri** [comment]
Great question - thanks for offering some help (and by the way there is something going on in the selenium universe https://www.selenium.dev/blog/2022/test-automation-summit/)

Documentation is always a point - at the moment i try to improve the docs when answering questions (e.g. on stackoverflow) an there is no good doc to point to.
Maybe this is something you can look at - have a look at the stackoverflow questions regarding HtmlUnit and try to place answers matching the current state of the project. There is so much old stuff no longer true....

At second i think it will be of great help if you can work on special issues but most of the open ones are bigger. But i will have a look and will add some labels right now.

And finally we can have some kind of online meeting to discuss this points - if you like.
