### ISSUE TITLE
Commit 4b96c6766c15ffc66ce399e33179b851049b5839 introduces regression

### ISSUE THREAD

**Issue by csware** [HtmlUnit/htmlunit#837]
Commit 4b96c6766c15ffc66ce399e33179b851049b5839 causes Shibboleth login to fail (this is the first commit where this issue happens, identified using bisecting). Shibboleth receives a HTML post and then generates a HTML page with an onload action and/or a single submit button in a noscript block that redirects the request back to a calling web page.

Please revert that commit. Based on the commit description (and the separate commits that follow), I cannot see what problem it was trying to fix.

**Comment by rbri** [comment]
oh, this commit is part of the story to make the latest HTMX test suite working... will have a look.

**Comment by csware** [comment]
Reverting that commit (and adding `final AbstractJavaScriptEngine<?> jsEngine = page.getWebClient().getJavaScriptEngine();` again) makes it work again.

```patch
diff --git a/src/main/java/org/htmlunit/html/DomElement.java b/src/main/java/org/htmlunit/html/DomElement.java
index 6469c1bd09..3cf4bce55d 100644
--- a/src/main/java/org/htmlunit/html/DomElement.java
+++ b/src/main/java/org/htmlunit/html/DomElement.java
@@ -1116,12 +1116,19 @@ public class DomElement extends DomNamespaceNode implements Element {
             stateUpdated = true;
         }
 
-        final ScriptResult scriptResult = doClickFireClickEvent(event);
-        final boolean eventIsAborted = event.isAborted(scriptResult);
+        final AbstractJavaScriptEngine<?> jsEngine = page.getWebClient().getJavaScriptEngine();
+        jsEngine.holdPosponedActions();
+        try {
+            final ScriptResult scriptResult = doClickFireClickEvent(event);
+            final boolean eventIsAborted = event.isAborted(scriptResult);
 
-        final boolean pageAlreadyChanged = contentPage != page.getEnclosingWindow().getEnclosedPage();
-        if (!pageAlreadyChanged && !stateUpdated && !eventIsAborted) {
-            changed = doClickStateUpdate(shiftKey, ctrlKey);
+            final boolean pageAlreadyChanged = contentPage != page.getEnclosingWindow().getEnclosedPage();
+            if (!pageAlreadyChanged && !stateUpdated && !eventIsAborted) {
+                changed = doClickStateUpdate(shiftKey, ctrlKey);
+            }
+        }
+        finally {
+            jsEngine.processPostponedActions();
         }
 
         if (changed) {
```

**Comment by rbri** [comment]
@csware do you have a test page where i can debug this?

**Comment by csware** [comment]
Unfortunately not, I collected the HTML pages of the Shibboleth login process, replaced all SAML data, but I cannot reproduce the issue with that page. There also must be something else.

[Examples.zip](https://github.com/user-attachments/files/16466231/Examples.zip)
Brokenpage.htm is the output of asXML() and Brokenpage2 is the HTML content collected using Firefox.

**Comment by rbri** [comment]
thanks, that helps a bit (and matches my theory) - will try to build a test case

**Comment by rbri** [comment]
Sorry for being not that responsive during the last days - was on a workshop and will be out for two more weeks to have a holiday break. Afterwards we can work together to get this finally done.

**Comment by csware** [comment]
I've a reproducer that I can provide confidentially.

**Comment by rbri** [comment]
Cool... please send a mail...

**Comment by csware** [comment]
Sent.

**Comment by csware** [comment]
It seems as if 4.5.0 fixed the issue, however, it behaves differently here compared to 4.3.0 as the "auto"-submit is not performed.

**Comment by rbri** [comment]
Have done a fix also. Will write some test for this and hopefully do a release at the beginning of next week.

**Comment by rbri** [comment]
@csware i think this is finally fixed. Have written i test case (based on your sample) that shows the problem is gone.

Hopefully i will do a release tomorrow.
