### ISSUE TITLE
MethodTooLargeException: Method too large: com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes$Definition.<clinit>

### ISSUE THREAD

**Issue by jpmartins** [HtmlUnit/htmlunit#842]
Hello, not sure what is happening, but apparently the enum Definition in StyleAttributes has some sort of large static initialiser (cinit of Definition) that is causing JaCoCo to fail.

> ...
> Caused by: java.io.IOException: Error while instrumenting com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes$Definition with JaCoCo 0.8.10.202304240956/8ea9668.
> 	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
> 	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:111)
> 	at org.jacoco.agent.rt.internal_4a7f17c.CoverageTransformer.transform(CoverageTransformer.java:92)
> 	... 160 more
> Caused by: org.jacoco.agent.rt.internal_4a7f17c.asm.MethodTooLargeException: Method too large: com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes$Definition.< clinit> ()V
> 	at org.jacoco.agent.rt.internal_4a7f17c.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
> 	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassWriter.toByteArray(ClassWriter.java:511)
> 	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:92)
> 	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:109)	
> ...

Is it possible to review it there is something improvable for this enum or some insight on what can be going on here?

Thanks,
JP

**Comment by rbri** [comment]
@jpmartins That's a common problem with JaCoCo. The code generated by JavaCC for the css parser produces the same error. As far as i know you can exclude classes from the JaCoCo instrumentations.

But i will have a look if there is something i can do on my side....

**Comment by rbri** [comment]
@jpmartins do you use the lastest version?

**Comment by jpmartins** [comment]
> @jpmartins do you use the latest version?

Hello rbri, thank you for the fast reply. I am using it indirectly, my dependency is on serenity-cucumber:1.9.51 that is using htmlunit:2.49.1... 🫥

This is happening in CI server side only, and it takes a while to experiment with it... maybe I can add JaCoCo locally to replicate it locally and try to reduce the time to reproduce the issue...

**Comment by rbri** [comment]
I can reproduce it here - simply by running code coverage in my eclipse project. But i fear there is not so much i can do. You have to exclude it from you maven/gradle setup.

**Comment by rbri** [comment]
https://stackoverflow.com/questions/71797384/facing-jacoco-method-too-large-error-when-running

**Comment by jpmartins** [comment]
> https://stackoverflow.com/questions/71797384/facing-jacoco-method-too-large-error-when-running

Thank you. Will try that. 

Did you understand what is causing the static initializer <cinit>, maybe something related with the normal internal java enum inner workings for a large number of named constants ([>1000 in this case](https://github.com/JackieXie168/htmlunit/blob/master/htmlunit/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes.java))?

**Comment by rbri** [comment]
> Did you understand what is causing the static initializer , maybe something related with the normal internal java enum inner workings for a large number of named constants ([>1000 in this case](https://github.com/JackieXie168/htmlunit/blob/master/htmlunit/src/main/java/com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes.java))?

This is simple - there are several limitations for the byte code size for methods for java class files. JaCoCo changes your byte code - think about this as adding some method calls that increasing counters when a branch of a method is passed. These counters are later on used to check if every branch was visited.
The StyleAttributes class contains an enum named Definition; this enum is really huge (you can have a look at the source code ;-)). Now JaCoCo modifies the byte code and adds a bunch of bytes - and voila the final byte code of the method is now too large. The JVM cant load the class - and as far as i know JaCoCo uses the original (not enhanced) class. But then you have no coverage counters ...

**Comment by rbri** [comment]
@jpmartins can we close this?

**Comment by jpmartins** [comment]
> @jpmartins can we close this?

Well, I believe we can... I am still having the same error with my first attempt to exclude the 
```
<configuration>
	<excludes>
		<exclude>com/gargoylesoftware/htmlunit/javascript/host/css/**/*</exclude>
	</excludes>
</configuration>
```
Not sure exactly why... but that seems a topic for a different forum. 

Thanks for the help.

**Comment by rbri** [comment]
> Not sure exactly why... but that seems a topic for a different forum.

I'm really interested in a working solution - hopefully we can finally present the solution here https://www.htmlunit.org/faq.html#CodeCoverage

**Comment by jpmartins** [comment]
> > Not sure exactly why... but that seems a topic for a different forum.
> 
> I'm really interested in a working solution - hopefully we can finally present the solution here https://www.htmlunit.org/faq.html#CodeCoverage

Still unable to replicate issue in my local machine, testing in in a jenkins CI pipeline, with a frustrating huge feedback loop.

I am waiting on the result... I suspect my first attempt did not work because of missing executions elements of the jacoco-maven-plugin, will get back to you with the solution that fixed it.

Sorry for the long wait.

**Comment by jpmartins** [comment]
Confirmed, no more MethodTooLargeException.

```
...
<plugin>
<!--asm.MethodTooLargeException: Method too large:
	com/gargoylesoftware/htmlunit/javascript/host/css/StyleAttributes$Definition.<clinit> -->
<groupId>org.jacoco</groupId>
<artifactId>jacoco-maven-plugin</artifactId>
<version>0.8.10</version> <!-- 0.8.10 to match maven container version run on jenkins -->
<configuration>
	<excludes>
		<exclude>com/gargoylesoftware/htmlunit/**/*</exclude>
	</excludes>
</configuration>
<executions>
	<execution>
		<goals>
			<goal>prepare-agent</goal>
		</goals>
	</execution>
	<!-- attached to Maven test phase -->
	<execution>
		<id>report</id>
		<phase>test</phase>
		<goals>
			<goal>report</goal>
		</goals>
	</execution>
</executions>
</plugin>
...
```

I am actually considering trying `<exclude>**/lib/*</exclude>` [I found in stackoverflow](https://stackoverflow.com/questions/30727952/exclude-classes-of-jar-files-from-jacoco-coverage-report) next to try to se if build time goes down, since we actually do not need to test coverage our libraries...

**Comment by rbri** [comment]
have added some more words to the faq, hope that helps.

@jpmartins thanks for using HtmlUnit
