### ISSUE TITLE
Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by BenF99** [HtmlUnit/htmlunit#86]
No matter the website I attempt to "login" to, it seems I'm always I'm greeted by the following error:
```

Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for C:\Users\User\Documents\htmlunit-2.36.0\lib\xalan-2.7.2.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class org.apache.bsf.BSFManager not in module
```

For reference, here is the code I'm using:

```
try (WebClient webClient = new WebClient()) {

			HtmlPage page = (HtmlPage) webClient.getPage("***");
			HtmlForm form = page.getFormByName("form1");
			form.getInputByName("tUserName").type("Username");
			form.getInputByName("tPassword").type("Password");

			page = form.getInputByValue("Log In").click();

			System.out.println(page.asText());
		}

```

**Comment by rbri** [comment]
Looks like a classpath problem - usually with the new java module system.

**Comment by rbri** [comment]
Interpreting the thumbs up as hint this problem is gone. Please open a new issue if you have more problems.

**Comment by geheimepolizei** [comment]
I got the same error in java 11 and java 16, but in java 8 I didn't get this error and I was able to run a similar program. Try java 8.

public static void homePage() {
    try {
        final WebClient webClient = new WebClient();
        final HtmlPage page = webClient.getPage("http://htmlunit.sourceforge.net");
        System.out.println(page.asXml());
        webClient.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
