### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.http.client.CredentialsProvider

### ISSUE THREAD

**Issue by alexvrv** [HtmlUnit/htmlunit#862]
Hi,
I can't use the latest snapshot 4.5.0. I get this error: Caused by: java.lang.ClassNotFoundException: org.apache.http.client.CredentialsProvider ON final WebClient webClient = new WebClient(BrowserVersion.CHROME);

I'm building the SNAPSHOT myself (i wanna contribute with something) using: mvn package -DskipTests

I think dependencies aren't installed as they should be

If I add the dependencies in my main project it works xD but why?

**Comment by alexvrv** [comment]
Fixed it by copying all the dependencies from the zip xD

**Comment by rbri** [comment]
:-D
