### ISSUE TITLE
Enable WebRequest with ClassPathResource

### ISSUE THREAD

**Issue by gstephant** [HtmlUnit/htmlunit#88]
Currently we can provide the url of a file in the filesystem to make a request based on.

I'm in a use case where my file in packaged in the class path resources

The WebClient.loadWebResponse methods should accept jar protocol and access the packaged file.

**Comment by rbri** [comment]
Hi,

as far as i know there is no such support in real browsers for a feature like this. Because of this i do not like to support this directly.
I see two options
* the simple: load the resource yourself into a string and use this http://htmlunit.sourceforge.net/faq.html#HowToParseHtmlString to make a response out of this
* the more general one: add support to the web client to register protocol handlers for other content types

At the moment i prefer the first one - what do you think?

**Comment by gstephant** [comment]
Hi,

Thx for the answer.

I don't think there is a need for real browsers to handle such a case.
But, a packaged file, is just a file. So if there is support for files, packaged files should be supported as well. That's just my opinion.

Your first suggestion should work in my use case. But setting an url, with raw html code, does not make sense for me.
`StringWebResponse response = new StringWebResponse(htmlCode, new URL("http://http://htmlunit.sourceforge.net//test.html"));`
You know, which URL should the dev give to the method when he give the raw html ? I'm a bit confused with this idea. Maybe it is my understanding that is lacking.

My current workaround, is to put the file on my server, in place of in the class path. Not a big fan of it..

And for the general one, I tried it on my end( i cloned the repo and did a hack), it was working for my use case, but that's all. There are too many impacts behind the scene that i don't know, to provide a real commit or mindful insight. but in my opinion that should be the correct approach.

**Comment by mguillem** [comment]
@gstephant can you perhaps give some info about your use case. It sounds a bit strange to me to package an html file in a jar file to call it later with HtmlUnit.

**Comment by gstephant** [comment]
Sure I can provide you the use case.

I'm crawling a website. It is not mine. For performance, I don't use a headless browser to crawl the website, and so I'm only requesting simple http requests.

At some place there is pagination, and one parameter to be able to request the next page is calculated via a javascript function, using input parameters and browser parameters.

So evaluating the javascript is not enough, it uses browser information. 
So in order to correctly evaluate the result of the javascript function I need a light browser. 
So I have the javascript in a package file; it is linked to the version of my crawler.

**Comment by rbri** [comment]
What about subclassing WebClient and overwriting com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebRequest)

**Comment by rbri** [comment]
There is a method in WebClient to parse a page from a string (see https://htmlunit.sourceforge.io/faq.html#HowToParseHtmlString), You can read the resource into a string and then use this.

Hope that helps (even if the response is a bit late (sorry).
