### ISSUE TITLE
missing variable name

### ISSUE THREAD

**Issue by derklaro** [HtmlUnit/htmlunit#89]
Hello,

I am getting the exeception `Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: missing variable name`

but there is no missing variable, the website is up and running...

**Comment by rbri** [comment]
This is an error reported from the JavaScript engine. At first call the same site with your browser and check in the developer console if there is the same error.
And please provide more details to give me a chance to reproduce the problem.

**Comment by derklaro** [comment]
Hey, so the console shows the same error, but i can use the website normally...

**Comment by rbri** [comment]
Ok, means there is a bug in the web page.
Htmlunit tries to mimic the browser as good as possible if you use a webclient without setting any options. But there is one exception. Htmlunit was written as test tool and therefore the handling of  exceptions is different. You have to set the setThrowExceptionOnScriptError option to false to ignore is errors and proceed with the is execution like browsers do

**Comment by derklaro** [comment]
Thank you very much

**Comment by rbri** [comment]
gerne
