### ISSUE TITLE
document.all different results with browser

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#896]
In htmlunit:
```
document.all == undefined; //false
document.all === undefined; //false
```

In real browser:
```
document.all == undefined; //true
document.all === undefined; //false
```

**Comment by rbri** [comment]
OMG will try to make that

**Comment by rbri** [comment]
ok, this requires at least one rhino fix, hope i get it in soon but i have to write a test case for rhino...

**Comment by rbri** [comment]
btw nice finding - how many hours of debugging do you spend on this? ;-)

**Comment by RuralHunter** [comment]
Thanks, not much this time. :)

**Comment by rbri** [comment]
ok, there is a first snapshot that solves the problem (hopefully)

**Comment by RuralHunter** [comment]
Yes it's fixed now. Thanks for the quick help as always!
