### ISSUE TITLE
Why is WebRequest.defaultResponseContentCharset_ transient?

### ISSUE THREAD

**Issue by RuralHunter** [HtmlUnit/htmlunit#898]
I serialized a WebRespose object to file. After loading it back, I found response.getContentCharset() returns null. I tracked the problem and found it's because of transient defaultResponseContentCharset_ in WebRequest. Why is this transient? The same question maybe apply on WebRequest.charset_  too.

**Comment by rbri** [comment]
No idea, will have a look...

**Comment by rbri** [comment]
@RuralHunter this is a bug - Charsets are not serializable but i already have a custom readObject/writeObject in place. The bug here is the missing of the handling of defaultResponseContentCharset_; charset_  is handled already.,

will make a new snapshot build later.

**Comment by RuralHunter** [comment]
Cool, thanks!

**Comment by rbri** [comment]
Finding the bug and the reason is always the harder part - so kudos to you
