### ISSUE TITLE
html canvas tag support 

### ISSUE THREAD

**Issue by amalmys** [HtmlUnit/htmlunit#92]
the htmlunit is not supporting canvas tag in html.

**Comment by rbri** [comment]
The canvas tag is supported.

Can you please provide some more details and some sample code to  reproduce your problem.
And the version of HtmlUnit you are using.
Any log output?

**Comment by amalmys** [comment]
> The canvas tag is supported.
> 
> Can you please provide some more details and some sample code to reproduce your problem.
> And the version of HtmlUnit you are using.
> Any log output?
HtmlUnit maven Dependency that I'm using is 
      <dependency>
          <groupId>net.sourceforge.htmlunit</groupId>
          <artifactId>htmlunit</artifactId>
          <version>2.13</version>
      </dependency>


code that im using is 
 URL url = new File("in1.html").toURI().toURL();

            System.out.println(url);
            WebClient webClient = new WebClient(BrowserVersion.CHROME);
            HtmlPage page = webClient.getPage(url);
            page.save(new File("C:\\Users\\cs3339\\Desktop\\sample13.html"));



            OutputStream os = new FileOutputStream("C:\\Users\\cs3339\\Desktop\\latestDoc17.pdf");

            ITextRenderer renderer = new ITextRenderer();
            renderer.setDocument(page, url.toString());
            renderer.layout();
            renderer.createPDF(os);




the HTML file is 
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.fillRect(10,10,150,80);
</script>

</body>
</html>


The output pdf I'm getting is displaying the message your browser doesnt support canvas tag

**Comment by rbri** [comment]
Sorry but your version is really really old. Please use the latest version.

See http://htmlunit.sourceforge.net/changes-report.html

**Comment by amalmys** [comment]
> Sorry but your version is really really old. Please use the latest version.
> 
> See http://htmlunit.sourceforge.net/changes-report.html

 <dependency>
          <groupId>net.sourceforge.htmlunit</groupId>
          <artifactId>htmlunit</artifactId>
          <version>2.36.0</version>
      </dependency>

i even tried using this maven dependency....this is the latest one...sorry it isnt working

**Comment by rbri** [comment]
Your html looks like the text is always there. You are sure the IText renderer can handle the canvas?

**Comment by rbri** [comment]
Have a look at the test cases in https://github.com/HtmlUnit/htmlunit/tree/master/src/test/java/com/gargoylesoftware/htmlunit/javascript/host/canvas

**Comment by amalmys** [comment]
INFO: CanvasRenderingContext2D.closePath() not yet implemented im getting this log from htmlunit not from itext

**Comment by rbri** [comment]
Have added the implementation of the close method. Will inform via twitter if a new snapshot is available.

**Comment by rbri** [comment]
Have you found some time to test the new snapshot?

**Comment by rbri** [comment]
No response - will close this. Please open a new issue if you find more problems.
