### ISSUE TITLE
decodeURIComponent decode fail

### ISSUE THREAD

**Issue by cui19951005** [HtmlUnit/htmlunit#94]
NativeGlobal.decode("%c3%ae%10%43%72%c3%b4%c3%af%c2%b6%62%34",false) result:
URIError: Malformed URI sequence

chrome decodeURIComponent result:
îCrôï¶b4

**Comment by rbri** [comment]
Have added a testcase for this. Looks like everything works correct.
Please verify.

**Comment by rbri** [comment]
No feedback, will close this.
