### ISSUE TITLE
Unable to load page

### ISSUE THREAD

**Issue by nirzohar** [HtmlUnit/htmlunit#97]
Unable to load a specific page (url below), even if I increase the memory to 8G still not works. Get out pf memory or execution halt.

```
WebClient webClient = new WebClient());

// configuration
webClient.getOptions().setUseInsecureSSL(true);
webClient.getOptions().setCssEnabled(false);
webClient.getOptions().setJavaScriptEnabled(true);
webClient.getOptions().setThrowExceptionOnScriptError(false);

HtmlPage page = webClient.getPage("https://www.yl-invest.co.il/?CategoryID=186&ArticleID=418");
```

**Comment by Serkan80** [comment]
I’m having the same problem (OutOfMemoryException) and the root cause for this problem is that on my page an async script is trying to be loaded, e.g. <script async src=...>, and it just hangs here. 

I’ve “fixed” it by listening to JS scripts that are being loaded during page load, and removed this one and now it works.

**Comment by rbri** [comment]
version 3.0 has a fix for the infamous incapsula problem - this code now works

import org.htmlunit.BrowserVersion;
import org.htmlunit.WebClient;
import org.htmlunit.html.HtmlPage;

public class Test {

    public static void main(String[] args) throws Exception {

        try (final WebClient webClient = new WebClient(BrowserVersion.FIREFOX_ESR)) {
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            // webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);

            HtmlPage page = webClient.getPage("https://www.yl-invest.co.il/?CategoryID=186&ArticleID=418");

            System.out.println(page.asNormalizedText());
        }
    }
}
